Repository ArduPilot/ardupilot, pull requests merged in 2019-03, with the labels that each got.

#10674 Tools: waf: add -Werror=overloaded-virtual
  Tools/ardupilotwaf/boards.py
Labels: Tools

#10683 Tools: scripts: support auavx2.1 bootloader with board ID of 33
  Tools/scripts/uploader.py
Labels: Tools

#10693 waf: make board name case insensitive in waf configure
  Tools/ardupilotwaf/boards.py
  wscript
Labels: ChibiOS

#10690 tailsitter gain scaling with support for airspeed sensor for high-speed flight in Qmodes
  ArduPlane/tailsitter.cpp
Labels: DevCallTopic, VTOL-Plane

#10672 AP_Common: Location.cpp: force handling of all alt frames
  libraries/AP_Common/Location.cpp
Labels: DevCallTopic

#10655 AP_Notify: add OBC colour scheme
  libraries/AP_Notify/AP_Notify.cpp
  libraries/AP_Notify/RGBLed.cpp
  libraries/AP_Notify/RGBLed.h
Labels: DevCallTopic

#10728 waf: fixed case insensitive board name
  Tools/ardupilotwaf/boards.py
  wscript
Labels: BuildSystem

#10765 travis: added F7 and H7 boards to travis builds
  .travis.yml
  Tools/scripts/build_ci.sh
Labels: ChibiOS

#10769 HAL_ChibiOS: added retries to flash based storage
  libraries/AP_HAL_ChibiOS/Storage.cpp
Labels: ChibiOS

#10708 ArduPlane: add rudder to tailsitter gain scaling
  ArduPlane/tailsitter.cpp
Labels: DevCallTopic, VTOL-Plane

#10699 Plane: is_flying_vtol: if spool mode is shut down we are not flying
  ArduPlane/quadplane.cpp
Labels: DevCallTopic

#10406 AP_AHRS: apply AHRS trim in EKF_TYPE_SITL
  libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
Labels: DevCallTopic, Library

#10788 Copter: fix to acro trainer leveling mode
  ArduCopter/mode_acro.cpp
Labels: BUG, Copter, TradHeli

#10538 AP_ADSB: add accessor to fetch a vehicle from database by icao
  libraries/AP_ADSB/AP_ADSB.cpp
  libraries/AP_ADSB/AP_ADSB.h
Labels: Library

#10604 Plane: allow fwd motor to run in VTOL land hor positioning
  ArduPlane/quadplane.cpp
Labels: Plane, VTOL-Plane

#10615 Plane: use WP height for height above ground in vtol landing
  ArduPlane/altitude.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: VTOL-Plane

#10384 Plane: added TKOFF_TIMEOUT parameter
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/Plane.h
  ArduPlane/commands_logic.cpp
  ArduPlane/takeoff.cpp
Labels: Plane

#10836 AP_AHRS: fix bug in attitudes_consistent()
  libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
Labels: DevCallTopic, Library

#10818 Copter: mark vtol_state and landed_state methods as override
  ArduCopter/GCS_Mavlink.h
Labels: DevCallTopic

#10790 AP_BattMonitor: added a "battery" backend for liquid fuel flow
  libraries/AP_BattMonitor/AP_BattMonitor.cpp
  libraries/AP_BattMonitor/AP_BattMonitor.h
  libraries/AP_BattMonitor/AP_BattMonitor_FuelFlow.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_FuelFlow.h
  libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_Params.h
Labels: DevCallTopic

#10075 AP_Mount: fix SToRM32 protocol delay
  libraries/AP_Mount/AP_Mount_SToRM32.cpp
  libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
Labels: BUG, Library

#10867 Tools: pexpect python dependency used by autotest
  Tools/scripts/install-prereqs-mac.sh
Labels: DevEnv

#10868 Tools: autotest: add brake mode test
  Tools/autotest/arducopter.py
Labels: Tools

#10603 AP_Logger: simplify the message writers
  libraries/AP_Logger/LoggerMessageWriter.cpp
  libraries/AP_Logger/LoggerMessageWriter.h
Labels: DataFlash

#10872 AC_WPNav: Remove unused internals, and unneeded initializers
  libraries/AC_WPNav/AC_WPNav.h
Labels: Library

#10848 Sub: bugfix fail condition in motor test initialization
  ArduSub/motors.cpp
Labels: Sub

#10883 AP_HAL_Linux: add override to virtual methods
  libraries/AP_HAL_Linux/CAN.h
Labels: CAN, Linux

#10884 AP_Compass: remove unused field
  libraries/AP_Compass/AP_Compass_UAVCAN.h
Labels: Library

#10492 Antenna tracker: fix scan mode
  AntennaTracker/control_auto.cpp
  AntennaTracker/system.cpp
  AntennaTracker/tracking.cpp
Labels: AntennaTracker

#10920 AP_OpticalFlow: support cx-of on all boards
  libraries/AP_OpticalFlow/OpticalFlow.cpp
Labels: Library

#10925 remove collective position pre-arm check for heli
  ArduCopter/AP_Arming.cpp
Labels: BUG, TradHeli

#10927 AP_FlashStorage: fixed a corruption bug
  libraries/AP_FlashStorage/AP_FlashStorage.cpp
  libraries/AP_FlashStorage/AP_FlashStorage.h
Labels: AllVehicles, BUG, DataFlash

#10935 Copter: Tradheli- removes suppression of hover_trim_roll on auto takeoff
  ArduCopter/takeoff.cpp
Labels: TradHeli

#10869 AP_UAVCAN: fix typedef for callback methods
  libraries/AP_UAVCAN/AP_UAVCAN.h
Labels: Library

#10944 AC_AttitudeControl: bodyframe roll log target attitude bugfix
  libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
Labels: VTOL-Plane

#10945 Plane: fixed WAIT_ALTITUDE wiggle
  ArduPlane/servos.cpp
Labels: Plane

#10940 AP_TECS: prevent airspeed demand spikes causing large pitch changes
  libraries/AP_TECS/AP_TECS.cpp
Labels: Plane, WIP
