Repository ArduPilot/ardupilot, pull requests merged in 2019-06, with the labels that each got.

#11472 GCS_MAVLink: fix MAV.txp log field
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: DevCallTopic

#11442 AP_HAL: Make linux hardware define more readable
  libraries/AP_HAL/board/linux.h
Labels: DevCallTopic, Linux

#11223 Heli - replace H_LAND_COL_MIN with H_COL_MID
  libraries/AP_Motors/AP_MotorsHeli.cpp
  libraries/AP_Motors/AP_MotorsHeli.h
  libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
  libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
  libraries/AP_Motors/AP_MotorsHeli_Single.cpp
Labels: DevCallTopic, Safety, TradHeli

#11453 Copter: merge ArduCopter.cpp and Copter.cpp
  ArduCopter/ArduCopter.cpp
  ArduCopter/Copter.cpp
Labels: Copter

#11489 Create a README.md to hold logger information
  libraries/AP_Logger/LogStructure.h
  libraries/AP_Logger/README.md
Labels: WIP

#11493 Sub: Remove rangefinder support of control loops
  ArduSub/control_althold.cpp
  ArduSub/control_circle.cpp
  ArduSub/control_poshold.cpp
Labels: Sub

#11501 waf: use -j4 on build of ChibiOS core
  Tools/ardupilotwaf/chibios.py
Labels: ChibiOS

#11532 AP_Windvane: fix NMEA vehicle to earth frame error
  libraries/AP_WindVane/AP_WindVane_NMEA.cpp
Labels: GSoC, Library

#11530 AP_NavEKF2: default EK2_MAG_EF_LIM to 50
  libraries/AP_NavEKF2/AP_NavEKF2.cpp
Labels: EKF

#11539 waf: add -Werror=overflow
  Tools/ardupilotwaf/boards.py
Labels: DevCallTopic

#11520 GCS_MAVLink: correct is_streaming check and update of is-streaming mask
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: DevCallTopic

#11318 Copter: correct namespacing of Copter modes
  ArduCopter/Copter.cpp
  ArduCopter/Copter.h
  ArduCopter/GCS_Mavlink.cpp
  ArduCopter/Parameters.cpp
  ArduCopter/Parameters.h
  ArduCopter/autoyaw.cpp
  ArduCopter/mode.cpp
  ArduCopter/mode.h
  ArduCopter/mode_acro.cpp
  ArduCopter/mode_acro_heli.cpp
  ArduCopter/mode_althold.cpp
  ArduCopter/mode_auto.cpp
  ArduCopter/mode_autotune.cpp
  ArduCopter/mode_avoid_adsb.cpp
  ArduCopter/mode_brake.cpp
  ArduCopter/mode_circle.cpp
  ArduCopter/mode_drift.cpp
  ArduCopter/mode_flip.cpp
  ArduCopter/mode_flowhold.cpp
  ArduCopter/mode_follow.cpp
  ArduCopter/mode_guided.cpp
  ArduCopter/mode_guided_nogps.cpp
  ArduCopter/mode_land.cpp
  ArduCopter/mode_loiter.cpp
  ArduCopter/mode_poshold.cpp
  ArduCopter/mode_rtl.cpp
  ArduCopter/mode_smart_rtl.cpp
  ArduCopter/mode_sport.cpp
  ArduCopter/mode_stabilize.cpp
  ArduCopter/mode_stabilize_heli.cpp
  ArduCopter/mode_throw.cpp
  ArduCopter/mode_zigzag.cpp
  ArduCopter/takeoff.cpp
Labels: Copter, DevCallTopic

#9394 AP_HAL: fix RCOutput, RCOutput2 and RCInputToRCOutput examples to pre…
  libraries/AP_HAL/examples/RCInputToRCOutput/RCInputToRCOutput.cpp
  libraries/AP_HAL/examples/RCOutput/RCOutput.cpp
  libraries/AP_HAL/examples/RCOutput2/RCOutput.cpp
Labels: DevCallTopic, Library

#11559 Azure: fix builds
  .azure/autotest_template.yml
  .azure/azure-pipelines.yml
Labels: CI

#11563 AC_Avoidance: fix BendyRuler when outside polygon fence
  libraries/AC_Avoidance/AP_OABendyRuler.cpp
Labels: BUG, Rover

#11577 AC_Avoidance: Dijkstra's exits early if polygon fence disabled
  libraries/AC_Avoidance/AP_OADijkstra.cpp
  libraries/AC_Avoidance/AP_OADijkstra.h
Labels: BUG, Rover

#11560 AP_Common: Remove extra comparison from longitude_scale()
  libraries/AP_Common/Location.cpp
Labels: AllVehicles, DevCallTopic, Enhancement

#11557 AP_HAL_ChibiOS: add support for MatekF405 AIO and OSD board types
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405/hwdef.dat
Labels: ChibiOS, DevCallTopic

#11517 GCS_MAVLink: use send_to_active_channels for parameters
  libraries/GCS_MAVLink/GCS_Param.cpp
Labels: DevCallTopic

#11610 AP_AdvancedFailsafe: added docs for AFS output pins
  libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
Labels: Docs, Library

#11603 Tools: add IMU filter test tool
  Tools/FilterTestTool/BiquadFilter.py
  Tools/FilterTestTool/FilterTest.py
  Tools/FilterTestTool/Readme.md
  Tools/FilterTestTool/run_filter_test.py
Labels: Tools

#11637 Re-enable watchdog on Solo build targets
  Tools/Frame_params/Solo_Copter-3.7_BlackCube.param
  Tools/Frame_params/Solo_Copter-3.7_GreenCube.param
Labels: Solo, Tools

#11599 AP_Tuning: debounce RC input
  libraries/AP_Tuning/AP_Tuning.cpp
Labels: DevCallTopic

#11648 AC_Avoidance: fix Dijkstra's iteration through polygon fence points
  libraries/AC_Avoidance/AP_OADijkstra.cpp
Labels: BUG, Rover

#11633 Copter: stop passing gcs chan into method which wants an object
  ArduCopter/Copter.h
  ArduCopter/GCS_Mavlink.cpp
  ArduCopter/compassmot.cpp
Labels: DevCallTopic

#11635 GCS_Copter: Reset VISION_POSITION flag when visual_odom is enabled but not healthy
  ArduCopter/GCS_Copter.cpp
Labels: Copter, NeedRework

#11007 Tools: script: uploader.py: add --identify option
  Tools/scripts/uploader.py
Labels: NeedsTesting, Tools
