Repository ArduPilot/ardupilot, pull requests merged in 2019-04, with the labels that each got.

#10958 AP_TECS: fixed a bug in changes from rate-limited to non-limited airs…
  libraries/AP_TECS/AP_TECS.cpp
  libraries/AP_TECS/AP_TECS.h
Labels: BUG, Plane

#10701 SITL: Add drag simulation for Sub
  libraries/SITL/SIM_Submarine.cpp
  libraries/SITL/SIM_Submarine.h
Labels: SITL

#10954 AP_GPS: Ensure that all ublox configuration failure reasons have a description
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
  libraries/AP_GPS/AP_GPS_UBLOX.h
Labels: DevCallTopic, Library

#10817 INS: AP_InertialSensor comments for new cubes
  libraries/AP_InertialSensor/AP_InertialSensor.cpp
Labels: DevCallTopic, Library

#10973 Rover: assign notify is_autopilot_mode flag
  APMrover2/system.cpp
Labels: Library

#10963 travis: Move from Ubuntu 14.04 to 16.04
  .travis.yml
Labels: DevCallTopic

#10614 Plane: add crow flap options parameter, allows 'full house' wing
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/defines.h
  ArduPlane/servos.cpp
Labels: DevCallTopic, Plane

#10245 Plane: Refactor plane failsafe
  ArduPlane/ArduPlane.cpp
  ArduPlane/GCS_Mavlink.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/Plane.h
  ArduPlane/afs_plane.cpp
  ArduPlane/afs_plane.h
  ArduPlane/config.h
  ArduPlane/events.cpp
  ArduPlane/failsafe.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/servos.cpp
Labels: Plane

#10993 autotest: fixed precision landing test for copter
  Tools/autotest/arducopter.py
Labels: Copter, SITL

#11000 AP_Common: correct type conversion issues in _assert_storage_size
  libraries/AP_Common/AP_Common.h
Labels: Library

#11021 Tools: autobuild tracker on common boards
  Tools/scripts/build_binaries.py
Labels: AntennaTracker, Tools

#11013 Plane: Update GPS before updating current_loc
  ArduPlane/ArduPlane.cpp
Labels: Plane

#11012 AP_GPS: Refactor get_singleton() to return a pointer
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS.h
Labels: GPS, Scripting

#11028 HAL_ChibiOS: fixed fallback to microSD for storage
  libraries/AP_HAL_ChibiOS/Storage.cpp
  libraries/AP_HAL_ChibiOS/Util.cpp
  libraries/AP_HAL_ChibiOS/sdcard.cpp
  libraries/AP_HAL_ChibiOS/sdcard.h
Labels: BUG, ChibiOS

#10938 AP_RangeFinder: add driver for BlueRobotics Ping sensor
  libraries/AP_RangeFinder/AP_RangeFinder_BLPing.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_BLPing.h
  libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
  libraries/AP_RangeFinder/RangeFinder.cpp
  libraries/AP_RangeFinder/RangeFinder.h
Labels: Enhancement, Library

#11046 AP_HAL_SITL: fix ‘heap’ shadowing
  libraries/AP_HAL_SITL/Util.cpp
Labels: Library

#11003 AP_Declination: generate tables with float designator
  libraries/AP_Declination/generate/generate.py
Labels: DevCallTopic

#11023 AP_RSSI: make type enum class, remove default clause in type switch
  libraries/AP_RSSI/AP_RSSI.cpp
  libraries/AP_RSSI/AP_RSSI.h
Labels: DevCallTopic

#11014 Copter: solve always true condition on esc_calibration and factorize
  ArduCopter/Copter.h
  ArduCopter/esc_calibration.cpp
Labels: Copter, DevCallTopic

#11004 AP_InertialSensor: return floats from raw-sample-rate getters
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
Labels: BUG, DevCallTopic, Library

#11010 Tools: Remove BRD_SERIAL_NUM from parameter files
  Tools/Frame_params/Sub/bluerov2-3_5.params
  Tools/Frame_params/Sub/bluerov2-3_5_2.params
  Tools/Frame_params/Sub/bluerov2-heavy-3_5_2.params
  Tools/autotest/default_params/vee-gull 005.param
Labels: Sub

#10780 Fix AP_RangeFinder_TeraRangerI2C.cpp: gives zero values in Plane
  libraries/AP_RangeFinder/AP_RangeFinder_TeraRangerI2C.cpp
Labels: DevCallTopic, Library

#11057 AP_HAL_SITL: Correct range check on UART ports
  libraries/AP_HAL_SITL/UARTDriver.cpp
Labels: SITL

#11058 Add scripting target to CI
  Tools/scripts/build_ci.sh
Labels: Scripting

#8053 AP_RangeFinder: Delete unnecessary judgment
  libraries/AP_RangeFinder/AP_RangeFinder_analog.cpp
Labels: Library

#11091 RC_Channel: fixed typo
  libraries/RC_Channel/RC_Channel.cpp
Labels: Library

#11077 AP_Motors: add support for Hexa-H frame
  libraries/AP_Motors/AP_MotorsMatrix.cpp
Labels: Copter, Enhancement

#11063 AP_Rangefinder: Fix VL53L1X ignoring return status
  libraries/AP_RangeFinder/AP_RangeFinder_VL53L1X.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_VL53L1X.h
Labels: BUG, Enhancement, Library

#11079 HAL_ChibiOS: mark SDIO and SDMMC IO as pullup
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: ChibiOS

#11115 SITL: improve airspeed in FlightAxis for RF8
  libraries/SITL/SIM_FlightAxis.cpp
Labels: SITL

#11098 Copter: fix auto-disarm check
  ArduCopter/motors.cpp
Labels: BUG, Copter

#11113 Tools: autotest: fix os.path.join to handle a list of paths
  Tools/autotest/quadplane.py
Labels: DevCallTopic, Tools

#11142 Tools: apj_tool.py: python3 fixes
  Tools/scripts/apj_tool.py
Labels: WIP

#11145 AP_Airspeed: Fix race condition in SDP3X leading to garbage data
  libraries/AP_Airspeed/AP_Airspeed_SDP3X.cpp
Labels: BUG, Plane

#11164 Copter: Tradheli- removes suppression of hover_trim_roll on auto takeoff
  ArduCopter/takeoff.cpp
Labels: TradHeli

#11163 Rover: fix omni tri steering and lateral factors
  APMrover2/AP_MotorsUGV.cpp
Labels: BUG, Rover

#11092 Avoid casting to smaller-precision intermediate values in some AP_Math operations
  libraries/AP_Math/polygon.cpp
Labels: DevCallTopic

#11059 plane: restore thr_min behavior
  ArduPlane/Parameters.cpp
  ArduPlane/servos.cpp
Labels: BUG, DevCallTopic, Plane

#11002 AP_Rally: correct math conversion problems
  libraries/AP_Rally/AP_Rally.cpp
  libraries/AP_Rally/AP_Rally.h
Labels: DevCallTopic

#10853 AP_OSD: Switch screens basing on ARM state
  libraries/AP_OSD/AP_OSD.cpp
  libraries/AP_OSD/AP_OSD.h
Labels: OSD

#11171 Copter: replace 4 divisions with multiplications
  ArduCopter/GCS_Mavlink.cpp
  ArduCopter/mode_guided.cpp
Labels: Copter

#11120 AP_Mission: Send jump tracking info to GCS
  libraries/AP_Mission/AP_Mission.cpp
Labels: Library

#11201 Rover: increase RC timeout failsafe from 200ms to 500ms.
  APMrover2/radio.cpp
Labels: Rover

#11204 AP_OpticalFlow: Remove unused device ID tracking
  libraries/AP_OpticalFlow/AP_OpticalFlow_CXOF.cpp
  libraries/AP_OpticalFlow/AP_OpticalFlow_MAV.cpp
  libraries/AP_OpticalFlow/AP_OpticalFlow_Onboard.cpp
  libraries/AP_OpticalFlow/AP_OpticalFlow_PX4Flow.cpp
  libraries/AP_OpticalFlow/AP_OpticalFlow_Pixart.cpp
  libraries/AP_OpticalFlow/AP_OpticalFlow_SITL.cpp
  libraries/AP_OpticalFlow/OpticalFlow.h
Labels: Enhancement

#11208 tracker: initialise battery
  AntennaTracker/system.cpp
Labels: AntennaTracker, BUG

#11213 HAL CHIBIOS: Make Solo's older cube a child of fmuv3 instead of CubeBlack
  libraries/AP_HAL_ChibiOS/hwdef/CubeBlack-solo/README.md
  libraries/AP_HAL_ChibiOS/hwdef/CubeSolo/README.md
  libraries/AP_HAL_ChibiOS/hwdef/CubeSolo/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/CubeSolo/hwdef.dat
Labels: ChibiOS, Solo

#11215 Change auto build script from CubeBlack-solo to CubeSolo.
  Tools/scripts/build_binaries.py
Labels: BuildSystem, Solo

#11110 plane: reinstate tailsitter roll limit
  ArduPlane/mode_qstabilize.cpp
Labels: BUG, DevCallTopic, VTOL-Plane

#10443 Copter: make PosHold state member variables; remove some redundant na…
  ArduCopter/mode.h
  ArduCopter/mode_poshold.cpp
Labels: DevCallTopic
