Repository ArduPilot/ardupilot, pull requests merged in 2019-10, with the labels that each got.

#12471 autotest: allow --moddebug to sim_vehicle.py
  Tools/autotest/sim_vehicle.py
Labels: SITL

#12467 AP_Logger: fixed LOG_FILE_DSRMROT with delayed log stop
  libraries/AP_Logger/AP_Logger_File.cpp
  libraries/AP_Logger/AP_Logger_File.h
Labels: Logging

#12473 Copter: add pre-arm check of PILOT_SPEED_UP param
  ArduCopter/AP_Arming.cpp
Labels: Copter, Enhancement, Safety

#12479 AP_Follow: hide params not used by Rover
  libraries/AP_Follow/AP_Follow.cpp
Labels: Library, Rover

#12445 HAL_ChibiOS: removed wait on CAN peripheral in H7
  libraries/AP_HAL_ChibiOS/CANFDIface.cpp
Labels: BUG, CAN, ChibiOS, NeedsTesting

#12500 AP_BLHeli: Change descriptions in SERVO_BLH_PORT param to actual AP port
  libraries/AP_BLHeli/AP_BLHeli.cpp
Labels: Library

#12480 Plane: Resore old default behaviour for throttle curves
  ArduPlane/quadplane.cpp
Labels: NeedsTesting, VTOL-Plane

#12380 Rover: implement steering trim save in armed/manual mode only
  APMrover2/RC_Channel.cpp
  libraries/RC_Channel/RC_Channel.cpp
Labels: Rover

#12504 AP_Motors: Change to description(NFC)
  libraries/AP_Motors/AP_MotorsMulticopter.cpp
Labels: DevCallTopic

#12461 Remove argument location from QuadPlane::control_auto(), not used
  ArduPlane/mode_auto.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: DevCallTopic

#12426 AP_NMEA_Output: skip sending sentences if no space on UART
  libraries/AP_NMEA_Output/AP_NMEA_Output.cpp
  libraries/AP_NMEA_Output/AP_NMEA_Output.h
Labels: DevCallTopic, Library

#12519 AP_Logger: Fix logging of current on non primary instances
  libraries/AP_Logger/LogFile.cpp
Labels: BUG, Logging

#12546 AP_HAL_ChibiOS/hwdef: update KakuteF4 readme
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF4/README.md
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF4/kakutef4_bot.jpg
Labels: Library

#12182 ArduCopter: allow logging of both IMU and IMU_RAW
  ArduCopter/Copter.cpp
Labels: Copter

#12524 AP_Scripting: Fix generation of uint32_t arguments
  libraries/AP_Scripting/generator/description/bindings.desc
  libraries/AP_Scripting/generator/src/main.c
  libraries/AP_Scripting/lua_generated_bindings.cpp
Labels: BUG, DevCallTopic, Scripting

#12553 AP_RangeFinder: Add TF03-180
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake.h
  libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
  libraries/AP_RangeFinder/RangeFinder.cpp
  libraries/AP_RangeFinder/RangeFinder.h
Labels: Library

#12525 AP_GPS: fixed UAVCAN GPS status when disconnected
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS_UAVCAN.cpp
  libraries/AP_GPS/AP_GPS_UAVCAN.h
Labels: CAN, GPS

#12521 AP_Vehicle: add singleton
  libraries/AP_Vehicle/AP_Vehicle.cpp
  libraries/AP_Vehicle/AP_Vehicle.h
Labels: Enhancement

#12564 Add QACRO to flight mode list since now in beta
  ArduPlane/Parameters.cpp
Labels: Plane, VTOL-Plane

#12571 ardupilotwaf: -Werror=delete-non-virtual-dtor is a C++ flag not a C flag
  Tools/ardupilotwaf/boards.py
Labels: BuildSystem

#12572 AP_Scripting: Fix up uint32_t manipulation, fix AP_Notify binding
  libraries/AP_Scripting/examples/easter-egg.lua
  libraries/AP_Scripting/generator/description/bindings.desc
  libraries/AP_Scripting/lua_boxed_numerics.cpp
  libraries/AP_Scripting/lua_generated_bindings.cpp
Labels: BUG, Scripting

#12582 AP_Mission: add sanity check that 16-bit commands aren't stored_in_lo…
  libraries/AP_Mission/AP_Mission.cpp
Labels: DevCallTopic

#12377 AP_NavEKF3: added EK3_MAG_EF_LIM parameter
  libraries/AP_NavEKF3/AP_NavEKF3.cpp
  libraries/AP_NavEKF3/AP_NavEKF3.h
  libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.h
Labels: EKF

#12606 SITL: morse simulator should generate packets from same vehicle sysid
  libraries/SITL/SIM_Morse.cpp
Labels: SITL

#12626 AP_Compass: LEARN param default to 0 for all vehicles
  libraries/AP_Compass/AP_Compass.cpp
Labels: AllVehicles

#12639 AP_GPS: fixed GPS to UART mapping
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS.h
Labels: GPS

#12640 Copter: multicopter ATC_RAT_RLL/PIT_FILT copied to FLTD and FLTT
  ArduCopter/Parameters.cpp
Labels: BUG, Copter

#12659 AP_TECS: added TECS_LAND_PMIN for min pitch in flare
  libraries/AP_TECS/AP_TECS.cpp
  libraries/AP_TECS/AP_TECS.h
Labels: Plane

#12667 SITL Plane: fix RCn_OPTION mode initialization
  ArduPlane/RC_Channel.cpp
Labels: SITL

#12558 AP_GPS: Don't defeat the GCS message interval code
  libraries/AP_GPS/AP_GPS.cpp
Labels: AllVehicles, GPS

#12615 HAL_ChibiOS: lower speed of mpu9250
  libraries/AP_HAL_ChibiOS/hwdef/fmuv3/hwdef.dat
Labels: ChibiOS

#12532 AP_Frsky_Telem: replaced the passthrough scheduler with a WFQ one with rate limiting
  libraries/AP_Frsky_Telem/AP_Frsky_Telem.cpp
  libraries/AP_Frsky_Telem/AP_Frsky_Telem.h
Labels: AllVehicles, DevCallTopic, Library

#12678 HAL_ChibiOS: fixed build of sparky2
  libraries/AP_HAL_ChibiOS/hwdef/sparky2/hwdef.dat
Labels: ChibiOS

#12685 Fixed MatekF765 PWM 5 and 6
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: BUG, ChibiOS

#12687 Copter: fix PSC_ACCZ_FILT to _FLTE param conversion
  ArduCopter/Parameters.cpp
Labels: BUG, Copter

#12541 AP_Motors: switched tricopter to use rc_write_angle()
  libraries/AP_Motors/AP_MotorsTri.cpp
  libraries/AP_Motors/AP_MotorsTri.h
Labels: Copter

#12665 GCS_MAVLink: mission item support more mav frames
  libraries/GCS_MAVLink/MissionItemProtocol_Fence.cpp
Labels: Copter, Enhancement, Library, Rover

#12697 Motor loss detection bug where wrong motor is found
  libraries/AP_Motors/AP_MotorsMatrix.cpp
Labels: BUG, Copter

#12696 AP_Motors: Add full yaw range calculation back
  libraries/AP_Motors/AP_MotorsMatrix.cpp
Labels: BUG, Copter

#12677 AP_BLHeli: fixed critical errors caused by BLHeli code
  libraries/AP_BLHeli/AP_BLHeli.cpp
Labels: ChibiOS
