Repository ArduPilot/ardupilot, pull requests merged in 2020-01, with the labels that each got.

#13151 autotest: correct sub output on test failure
  Tools/autotest/ardusub.py
Labels: Sub, Tools

#13153 Plane:fix typo in ARSPD_FBW_MAX param description
  ArduPlane/Parameters.cpp
Labels: Plane

#13149 Copter: Change the version patch number
  ArduCopter/version.h
Labels: Copter

#13187 AP_Scripting: Forward declare lua_new_uint32_t
  libraries/AP_Scripting/lua_boxed_numerics.cpp
Labels: Scripting

#13156 Copter: remove unneeded set_range calls on RC Aux channels
  ArduCopter/radio.cpp
Labels: Copter, DevCallTopic

#13148 AP_AHRS_NavEKF: inform all running EKFs that takeoff or touchdown is …
  libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
Labels: DevCallTopic

#13198 Use battery instance number for logging
  libraries/AP_Logger/AP_Logger.h
  libraries/AP_Logger/LogFile.cpp
  libraries/AP_Logger/LogStructure.h
Labels: Logging

#13189 Copter: fix tradheli RSC RC passthrough mode
  ArduCopter/Copter.h
  ArduCopter/RC_Channel.cpp
  ArduCopter/RC_Channel.h
  ArduCopter/heli.cpp
Labels: BUG, TradHeli

#13226 Tools: Updating solo's parameters
  Tools/Frame_params/Solo_Copter-4.param
  Tools/Frame_params/Solo_Copter-4_GreenCube.param
Labels: Solo, Tools

#13254 AC_InputManager: tradheli-Fix parameter metadata errors
  libraries/AC_InputManager/AC_InputManager_Heli.cpp
Labels: BUG, TradHeli

#13178 AP_Logger: fix locking issues, log wrapping and status messages
  libraries/AP_Logger/AP_Logger_Block.cpp
  libraries/AP_Logger/AP_Logger_Block.h
Labels: DevCallTopic

#13245 GCS_MAVLink: consolidate places we snprintf statustexts
  libraries/GCS_MAVLink/GCS.cpp
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/GCS_Common.cpp
  libraries/GCS_MAVLink/GCS_Dummy.h
Labels: DevCallTopic

#13143 Copter: Changed autorotation fltmode name to clarify for heli
  ArduCopter/Parameters.cpp
Labels: DevCallTopic

#13045 Remove default cases within AP_AHRS_NavEKF methods
  libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
  libraries/AP_AHRS/AP_AHRS_NavEKF.h
Labels: DevCallTopic

#13271 AP_Rangefinder: Fix bad subgroup pointer for drivers
  libraries/AP_RangeFinder/AP_RangeFinder.cpp
Labels: BUG, Library

#13265 Travis: Combine jobs, flake8 has been moved to semaphore
  .travis.yml
Labels: CI

#13273 AP_Param: Fix failing to invalidate the cached parameter count
  libraries/AP_Param/AP_Param.h
Labels: AllVehicles, BUG

#13280 AP_Logger: regain some logging IDs
  libraries/AP_Logger/LogStructure.h
Labels: Logging

#13290 AP_Logger: remove non-error init messages
  libraries/AP_Logger/AP_Logger.cpp
Labels: Logging

#13284 AP_Logger: add a semaphore to protect creation of new log formats
  libraries/AP_Logger/AP_Logger.cpp
  libraries/AP_Logger/AP_Logger.h
Labels: BUG, Logging

#13303 AP_Scripting: Send lua errors to the console before status_text
  libraries/AP_Scripting/lua_scripts.cpp
Labels: Scripting

#13287 AP_Filesystem: fixed set_mtime semaphore
  libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp
Labels: BUG, ChibiOS

#13286 AP_UAVCAN: protect UAVCAN DNA server with semaphore
  libraries/AP_UAVCAN/AP_UAVCAN_DNA_Server.cpp
  libraries/AP_UAVCAN/AP_UAVCAN_DNA_Server.h
Labels: BUG, CAN

#13275 HAL_ChibiOS: fixed ZubaxGNSS board ID
  libraries/AP_HAL_ChibiOS/hwdef/ZubaxGNSS/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/ZubaxGNSS/hwdef.dat
Labels: ChibiOS

#13278 AP_Avoidance: fixed generated param docs
  libraries/AP_Avoidance/AP_Avoidance.cpp
Labels: Docs

#13227 Tools: Updating solo's parameters (Copter 4)
  Tools/Frame_params/Solo_Copter-4.param
  Tools/Frame_params/Solo_Copter-4_GreenCube.param
Labels: Solo

#13325 HAL_Linux: support inverted 115200 protocols
  libraries/AP_HAL_Linux/RCInput_RCProtocol.cpp
  libraries/AP_HAL_Linux/RCInput_RCProtocol.h
Labels: Linux

#13336 AP_HAL_ChibiOS: remove unused AnalogIn fields
  libraries/AP_HAL_ChibiOS/AnalogIn.h
Labels: DevCallTopic

#13283 AP_Scripting: update plane-wind-fs battery RTL failsafe example
  libraries/AP_Scripting/examples/plane-wind-fs.lua
Labels: DevCallTopic, Scripting

#13327 AP_HAL_SITL: check result code of pthread_attr_init
  libraries/AP_HAL_SITL/Scheduler.cpp
Labels: DevCallTopic

#13329 Tradheli: Correct filter param descriptions in AC_AttitudeControl library
  libraries/AC_AttitudeControl/AC_AttitudeControl_Heli.cpp
Labels: TradHeli

#13345 AC_AutoTune: fix backup of yaw acceleration
  libraries/AC_AutoTune/AC_AutoTune.cpp
Labels: BUG, Copter

#13339 AP_RCProtocol: fport downlink: fixed CRC and added missing PACKED attribute
  libraries/AP_RCProtocol/AP_RCProtocol_FPort.cpp
Labels: Driver

#13346 Add intelhex install to pre-req install to allow hex files build
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: Tools

#13351 Copter: Swap circle radius stick input direction
  ArduCopter/mode_circle.cpp
Labels: Copter

#13342 AP_GPS: fixed yaw error when one GPS has zero position
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
Labels: BUG, GPS

#13318 HAL_ChibiOS: use cortex m7 instructions on F7/H7
  libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32F745xx.py
  libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32F767xx.py
  libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32F777xx.py
  libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32H743xx.py
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: ChibiOS

#13352 AP_Terrain: Avoid update() IO operations when not enabled
  libraries/AP_Terrain/AP_Terrain.cpp
Labels: DevCallTopic

#13388 Tools: chibios.py remove duplicate fread from wraplist
  Tools/ardupilotwaf/chibios.py
Labels: Tools

#13382 AP_Camera: send mavlink camera feedback message even if no logger
  libraries/AP_Camera/AP_Camera.cpp
Labels: DevCallTopic

#13376 AP_RangeFinder: TeraRanger a to close reading is not the minimum distance
  libraries/AP_RangeFinder/AP_RangeFinder_TeraRangerI2C.cpp
Labels: BUG, DevCallTopic, Driver

#13398 AP_Hott_Telem: avoid 1-byte overwrite in prearm check string
  libraries/AP_Hott_Telem/AP_Hott_Telem.cpp
Labels: DevCallTopic

#13423 AC_AutoTune: fix restoring of original gains
  libraries/AC_AutoTune/AC_AutoTune.cpp
  libraries/AC_AutoTune/AC_AutoTune.h
Labels: BUG, Copter, Plane
