Repository ArduPilot/ardupilot, pull requests merged in 2020-09, with the labels that each got.

#15199 AP_SerialManager: Add missing baud rate documentation
  libraries/AP_SerialManager/AP_SerialManager.cpp
Labels: Docs, Enhancement

#14131 Add support for keeping a backup of storage for last 100 boots
  libraries/AP_HAL_ChibiOS/Storage.cpp
Labels: DevCallEU, Library

#15197 autotest: fix nmea output test
  Tools/autotest/common.py
Labels: Tools

#15155 Put back DSM VTX control and logging
  libraries/AP_RCProtocol/AP_RCProtocol_DSM.cpp
  libraries/AP_RCProtocol/AP_RCProtocol_DSM.h
  libraries/AP_RCProtocol/examples/RCProtocolTest/RCProtocolTest.cpp
Labels: AllVehicles, BUG, DevCallEU

#15164 SITL: fix when speedup is specified as a startup parameter
  libraries/SITL/SIM_Aircraft.cpp
Labels: DevCallEU, Tools

#15189 Plane: Update THR_FAILSAFE param metadata
  ArduPlane/Parameters.cpp
Labels: Plane

#15245 disable MAG orientation test
  Tools/autotest/common.py
Labels: BUG, Library

#15126 AP_HAL_ChibiOS: add USART3 as alt config on OmnibusNanoV6
  libraries/AP_HAL_ChibiOS/hwdef/OmnibusNanoV6/hwdef.dat
Labels: ChibiOS

#15237 AP_OSD_Screen.cpp: fix aviation unit vspd sym
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: OSD

#15220 Copter: remove superfluous RETURN_TARGET_ALTTYPE_ from enum class names
  ArduCopter/mode.h
  ArduCopter/mode_rtl.cpp
Labels: Copter, DevCallTopic

#15257 SRV_Channel: remove unused set_output_pwm_first method
  libraries/SRV_Channel/SRV_Channel.h
  libraries/SRV_Channel/SRV_Channel_aux.cpp
Labels: DevCallTopic

#15213 Plane: fixed hover learn in quadplanes for THR_MIN>0
  ArduPlane/quadplane.cpp
Labels: BUG, DevCallEU

#15256 AP_HAL_ChibiOS: fix kakutef7/mini motor glitch when using dshot
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7Mini/hwdef.dat
Labels: BUG, ChibiOS

#15114 Move travis forward from trusty to focal
  .travis.yml
Labels: DevEnv, Tools

#15262 AP_Winch: correct Daiwa line lengtha and speed scaling
  libraries/AP_Winch/AP_Winch_Daiwa.cpp
  libraries/AP_Winch/AP_Winch_Daiwa.h
Labels: BUG, Copter

#15251 More band aid fix for compass calibration test failing
  Tools/autotest/common.py
Labels: SITL

#15254 Tools: make non DEBUG SITL use -march=native
  Tools/ardupilotwaf/boards.py
Labels: DevEnv, Tools

#15323 AP_OSD: fix white space error preventing emit to Wiki
  libraries/AP_OSD/AP_OSD.cpp
Labels: Library

#15339 SITL: JSON: don't warn for none required sections
  libraries/SITL/SIM_JSON.cpp
Labels: BUG, DevCallTopic, SITL

#15316 AP_OSD_Param_Setting: fix copter FS_OPTIONS mnemonics
  libraries/AP_OSD/AP_OSD_ParamSetting.cpp
Labels: DevCallTopic

#15272 Copter: guided mode checks destination within fence before changing submode
  ArduCopter/mode_guided.cpp
Labels: BUG, Copter, DevCallTopic

#15270 Rover: add support for MAV_CMD_DO_REPOSITION
  Rover/GCS_Mavlink.cpp
  Rover/GCS_Mavlink.h
Labels: Enhancement, Rover, WikiNeeded

#15276 Copter: poshold wind effect comp limited to 2/3rds of angle max
  ArduCopter/mode_poshold.cpp
Labels: BUG, Copter

#15352 AR_AttitudeControl: update param desc increment and range
  libraries/APM_Control/AR_AttitudeControl.cpp
Labels: Enhancement, Rover

#15299 Keep trying to initialize RunCam after boot
  libraries/AP_Camera/AP_RunCam.cpp
  libraries/AP_Camera/AP_RunCam.h
Labels: AllVehicles, BUG, DevCallEU, Driver

#15304 Clean up OSD parameter vehicle defaults and compilation
  libraries/AP_OSD/AP_OSD.cpp
  libraries/AP_OSD/AP_OSD.h
  libraries/AP_OSD/AP_OSD_ParamScreen.cpp
  libraries/AP_OSD/AP_OSD_ParamSetting.cpp
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: AllVehicles, DevCallEU

#15302 Stop logs safely in the block logger and asynchronously where possible
  libraries/AP_Logger/AP_Logger_Backend.cpp
  libraries/AP_Logger/AP_Logger_Backend.h
  libraries/AP_Logger/AP_Logger_Block.cpp
  libraries/AP_Logger/AP_Logger_Block.h
Labels: AllVehicles, Logging

#15350 AP_ChibOS: add UART7_RX to OMNIBUSF7V2
  libraries/AP_HAL_ChibiOS/hwdef/OMNIBUSF7V2/hwdef.dat
Labels: ChibiOS

#15040 AP_HAL_Linux: RCInput_UDP: accept up to 16 channels
  libraries/AP_HAL_Linux/RCInput_UDP.cpp
  libraries/AP_HAL_Linux/RCInput_UDP.h
  libraries/AP_HAL_Linux/RCInput_UDP_Protocol.h
Labels: Plane

#15363 Tools: add boogie-board-boat frame params
  Tools/Frame_params/boogie-board-boat.param
Labels: Rover, Tools

#15369 AP_ADSB: set Sagetech for 2MB only
  libraries/AP_ADSB/AP_ADSB.cpp
Labels: AllVehicles

#15366 AP_HAL_ChbiOS: ALT config to enable UART3 in place of I2C
  libraries/AP_HAL_ChibiOS/hwdef/OMNIBUSF7V2/hwdef.dat
Labels: ChibiOS, DevCallTopic

#15398 AP_ChibiOS: fix configuration number in OmnibusF7V2 hwdef
  libraries/AP_HAL_ChibiOS/hwdef/OMNIBUSF7V2/hwdef.dat
Labels: Library

#15342 Plane: Add missing Q_OPTIONS metadata for all options
  ArduPlane/quadplane.cpp
Labels: Plane

#15427 AP_RCProtocol: fix fport rssi scale
  libraries/AP_RCProtocol/AP_RCProtocol_FPort.cpp
Labels: DevCallTopic

#15445 Rover: calc_steering_from_turn_rate remove unused arguments
  Rover/mode.cpp
  Rover/mode.h
Labels: Rover

#15429 AP_GPS_UBLOX: fix type
  libraries/AP_GPS/AP_GPS_UBLOX.h
Labels: DevCallTopic, GPS

#15450 AP_NavEKF3: shorten buffer size send_text message length
  libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
Labels: EKF

#15433 Plane: fixed bug in RC_Channel::has_valid_input
  ArduPlane/RC_Channel.cpp
Labels: BUG, DevCallTopic

#15324 AP_Compass: add set_dev_id when initialising HIL
  libraries/AP_Compass/AP_Compass_HIL.cpp
Labels: DevCallEU, Library

#15444 AP_WindVane: report apparent wind with named float
  libraries/AP_WindVane/AP_WindVane.cpp
Labels: DevCallEU, Rover

#15286 AC_Circle: add Circle options
  libraries/AC_WPNav/AC_Circle.cpp
  libraries/AC_WPNav/AC_Circle.h
Labels: DevCallEU, WikiNeeded

#15154 Plane: tailsitters in Qassist inherit motor state
  ArduPlane/mode.cpp
  ArduPlane/mode.h
Labels: DevCallEU, VTOL-Plane

#15471 Copter: correct acro expo calculation
  ArduCopter/mode_acro.cpp
Labels: BUG, Copter

#15472 AP_HAL_ChibiOS: disable CANFilter on H7 boards temporarily
  libraries/AP_HAL_ChibiOS/CANFDIface.cpp
Labels: CAN, ChibiOS

#15424 Copter: Add AUTO_OPTIONS and support arming and throttle bypass
  ArduCopter/Parameters.cpp
  ArduCopter/Parameters.h
  ArduCopter/mode.h
  ArduCopter/mode_auto.cpp
Labels: Copter, Enhancement, WikiNeeded
