Repository ArduPilot/ardupilot, pull requests merged in 2021-07, with the labels that each got.

#17912 AP_Logger: fixed log creation on forced arm
  libraries/AP_Logger/AP_Logger_File.cpp
Labels: BUG, Logging

#17881 Tools: install-preresq-ubuntu: add check for DO_AP_STM_ENV before add…
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: DevCallEU, Tools

#17374 AP_Soaring: Vario filter cleanup
  libraries/AP_Soaring/AP_Soaring.cpp
  libraries/AP_Soaring/AP_Soaring.h
  libraries/AP_Soaring/Variometer.cpp
  libraries/AP_Soaring/Variometer.h
Labels: MergeOnCIPass

#17914 Copter: Correct yaw expo range limit
  ArduCopter/mode.cpp
Labels: BUG, Copter

#17917 HAL_ChibiOS: always send zero DShot when disarmed
  libraries/AP_HAL_ChibiOS/RCOutput.cpp
Labels: ChibiOS

#17909 Re-enable display on 1Mb boards
  libraries/AP_Notify/Display.h
Labels: AllVehicles

#17911 Add test that we get a log if arming is forced
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17632 AC_PrecLand: NFC: Refactor PrecLand EKF code
  libraries/AC_PrecLand/PosVelEKF.cpp
  libraries/AC_PrecLand/PosVelEKF.h
Labels: Copter, Enhancement, GSoC

#17934 APM_Control: adjust fixed wing filter defaults
  libraries/APM_Control/AP_AutoTune.cpp
  libraries/APM_Control/AP_AutoTune.h
  libraries/APM_Control/AP_PitchController.h
  libraries/APM_Control/AP_RollController.h
Labels: Plane

#17521 Add FF tuning items for Quadplane TX tuning
  ArduPlane/tuning.cpp
  ArduPlane/tuning.h
Labels: DevCallTopic, Plane

#17929 Re-enable LEDs on MatekF405-bdshot
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-bdshot/hwdef.dat
Labels: AllVehicles, BUG, ChibiOS, DevCallTopic

#17918 AP_Landing: enable deepstall landing to be compiled out of the code
  libraries/AP_Landing/AP_Landing.cpp
  libraries/AP_Landing/AP_Landing.h
  libraries/AP_Landing/AP_Landing_Deepstall.cpp
  libraries/AP_Landing/AP_Landing_Deepstall.h
Labels: MergeOnCIPass

#17894 AP_Frsky_Telem: added an airspeed OPTIONS flag to frame 0x5005
  libraries/AP_Frsky_Telem/AP_Frsky_Backend.h
  libraries/AP_Frsky_Telem/AP_Frsky_Parameters.cpp
  libraries/AP_Frsky_Telem/AP_Frsky_Parameters.h
  libraries/AP_Frsky_Telem/AP_Frsky_SPort.h
  libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
Labels: Library, MergeOnCIPass

#17942 autotest: create SITL debug binaries by default
  Tools/autotest/autotest.py
Labels: DevCallEU

#17916 HAL_ChibiOS: run storage writes at 1kHz not 100Hz
  libraries/AP_HAL_ChibiOS/Scheduler.cpp
Labels: ChibiOS, DevCallEU

#17939 Plane: do not run any prearm checks if we are armed or arming is not required
  ArduPlane/AP_Arming.cpp
Labels: BUG

#17822 AP_UAVCAN: add BatteryInfoAux dsdl message
  libraries/AP_UAVCAN/dsdl/ardupilot/equipment/power/20004.BatteryInfoAux.uavcan
Labels: AP_Periph, MergeOnCIPass

#17961 autotest: show output from Replay run
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#17958 Sub: use scheduler.get_loop_period_s() instead of MAIN_LOOP_SECONDS
  ArduSub/Sub.cpp
  ArduSub/config.h
Labels: Sub

#17975 autotest: added --udp option to sim_vehicle.py
  Tools/autotest/sim_vehicle.py
Labels: SITL

#17982 Correct firmware string length for CRSF
  libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
Labels: AllVehicles, BUG

#17768 Tools: autotest: add IRLock SITL test
  Tools/autotest/arducopter.py
Labels: Tools

#17947 ArduCopter: mark get_wp() const
  ArduCopter/mode.h
  ArduCopter/mode_auto.cpp
  ArduCopter/mode_follow.cpp
  ArduCopter/mode_guided.cpp
  ArduCopter/mode_rtl.cpp
  ArduCopter/mode_smart_rtl.cpp
Labels: Copter

#17906 Tools: Force Cygwin environment install to use GCC 7.4
  Tools/environment_install/install-prereqs-windows-andAPMSource.ps1
  Tools/environment_install/install-prereqs-windows.ps1
Labels: DevCallEU, Tools

#18006 Copter: reset land_repo_active flag in RTL mode
  ArduCopter/mode_rtl.cpp
Labels: MergeOnCIPass

#18023 HAL_ChibiOS: use DNA for node allocation on Matek GPS
  libraries/AP_HAL_ChibiOS/hwdef/f303-MatekGPS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/f405-MatekGPS/hwdef.dat
Labels: AP_Periph

#18031 autotest: fixed tuning of tilthvec quadplane model
  Tools/autotest/default_params/quadplane-tilthvec.parm
Labels: SITL

#18037 autotest: added --replay option to autotest
  Tools/autotest/autotest.py
  Tools/autotest/common.py
Labels: CI, EKF, MergeOnCIPass

#18035 AP_Vehicle: explicitly number ModeReason enumeration values
  libraries/AP_Vehicle/ModeReason.h
Labels: MergeOnCIPass

#18047 AP_BattMonitor: make NeoDesign obey SMBUS_ENABLE
  libraries/AP_BattMonitor/AP_BattMonitor.cpp
Labels: DevCallTopic, Library

#18025 AP_BattMonitor: smbus remove unused returns on reads
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus.h
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Rotoye.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Rotoye.h
Labels: DevCallTopic, Library

#18040 AP_BattMonitor: add Navigator to pins metadata
  libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
Labels: Docs, Sub

#18021 Plane: Allow yaw at zero throttle in VTOL descents
  ArduPlane/quadplane.cpp
Labels: DevCallTopic, Plane

#18062 AP_AHRS: remove accessors only used internally
  libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
  libraries/AP_AHRS/AP_AHRS_NavEKF.h
Labels: MergeOnCIPass

#18066 AP_AHRS: remove unused _gps_delay variable
  libraries/AP_AHRS/AP_AHRS.h
Labels: DevCallEU

#18048 Copter: Fix guided yaw bug.
  ArduCopter/GCS_Mavlink.cpp
  ArduCopter/autoyaw.cpp
Labels: Copter

#18041 AP_LeakDetector: update leak pin for navigator r3 in metadata
  libraries/AP_LeakDetector/AP_LeakDetector.cpp
Labels: Docs, MergeOnCIPass, Sub

#18055 autotest: add new Copter yaw tests
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#18080 autotest: drain pexpects in set_parameters loop
  Tools/autotest/common.py
Labels: MergeOnCIPass

#18030 Ensure correct rotation through telemetry ESCs
  libraries/AP_BLHeli/AP_BLHeli.cpp
Labels: AllVehicles, BUG, DevCallEU

#18017 Replay: added --accuracy option
  Tools/Replay/check_replay.py
Labels: DevCallEU, EKF

#18024 AP_Airspeed: fixed display of ARSPD_DEVID when ARSPD2_TYPE=0
  libraries/AP_Airspeed/AP_Airspeed.cpp
Labels: DevCallEU, Plane

#18081 AC_WPNav: remove unused variable following https://github.com/ArduPil…
  libraries/AC_WPNav/AC_WPNav.h
Labels: Copter, MergeOnCIPass

#17986 AP_Parachute: added CHUTE_OPTIONS
  libraries/AP_Parachute/AP_Parachute.cpp
  libraries/AP_Parachute/AP_Parachute.h
Labels: ExtremeProject, WikiNeeded

#18020 SITL: added SIM2 message
  libraries/SITL/SIM_Aircraft.cpp
Labels: EKF, MergeOnCIPass, SITL

#18073 AP_Scripting: add AP_InertialSensor binding
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: Reviewed, Scripting

#18090 Copter: 4.1.0-beta6 release notes
  ArduCopter/ReleaseNotes.txt
Labels: Copter

#18091 Rover: 4.1.0-beta6 release notes
  Rover/release-notes.txt
Labels: Rover

#18106 AP_Periph: fixed msp gps yaw
  Tools/AP_Periph/msp.cpp
Labels: AP_Periph, BUG, GPS

#18121 SRV_Channel: added doc of SERVOn_FUNCTION=-1 for GPIO
  libraries/SRV_Channel/SRV_Channel.cpp
Labels: Docs, MergeOnCIPass

#18117 Tools: Add Qiotek f103 periph to build list
  Tools/scripts/build_binaries.py
Labels: MergeOnCIPass

#18110 Plane: improve description of Q_TRIM_PITCH
  ArduPlane/quadplane.cpp
Labels: Plane

#18096 AP_Periph: fix dna wait blink
  Tools/AP_Periph/can.cpp
Labels: AP_Periph, DevCallEU

#18133 AP_HAL_Chibios: Change RC in to RCINT to free a DMA channel
  libraries/AP_HAL_ChibiOS/hwdef/QioTekZealotF427/hwdef.dat
Labels: ChibiOS, DevCallEU, DevCallTopic

#12540 AP_Motors: added new MOT_PWM_TYPE=8 for PWM range
  libraries/AP_Motors/AP_MotorsMulticopter.cpp
  libraries/AP_Motors/AP_Motors_Class.cpp
  libraries/AP_Motors/AP_Motors_Class.h
Labels: Copter

#18083 AP_Scripting: add change alt frame method to location userdata
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: DevCallEU, Scripting

#18097 Tools/ardupilotwaf: make skipped summary warning red
  Tools/ardupilotwaf/build_summary.py
Labels: DevCallEU

#18116 APM_Control: remove outdated tuning guide
  libraries/APM_Control/TuningGuide.txt
Labels: DevCallEU

#18154 AP_GPS: added arming check for yaw available on ublox RTK rover
  libraries/AP_GPS/AP_GPS.cpp
Labels: GPS

#18153 autotest: stop uploading artifacts to autotest server
  Tools/autotest/common.py
Labels: MergeOnCIPass

#18162 AC_Avoidance: handle upward proximity enable and disable
  libraries/AC_Avoidance/AC_Avoid.cpp
Labels: Copter, MergeOnCIPass

#18161 Tools: Add tmux support to run_in_terminal_window.sh
  Tools/autotest/run_in_terminal_window.sh
Labels: MergeOnCIPass

#18159 .github: fix issue with another actions kernel release missing modules
  .github/workflows/test_sitl_periph.yml
Labels: DevEnv

#18156 ArduCopter: guided auto_yaw_angle_rate timeout
  ArduCopter/mode_guided.cpp
Labels: BUG, Copter
