Repository ArduPilot/ardupilot, pull requests merged in 2021-06, with the labels that each got.

#17578 autotest: add test to catch bug with opticalflow if no rangefinder
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#14749 AP_OSD: add rangefinder panel
  libraries/AP_OSD/AP_OSD.h
  libraries/AP_OSD/AP_OSD_Screen.cpp
  libraries/AP_OSD/fonts/bfstyle.mcm
  libraries/AP_OSD/fonts/bfstyle.png
  libraries/AP_OSD/fonts/bold.mcm
  libraries/AP_OSD/fonts/bold.png
  libraries/AP_OSD/fonts/clarity.mcm
  libraries/AP_OSD/fonts/clarity.png
  libraries/AP_OSD/fonts/clarity_medium.mcm
  libraries/AP_OSD/fonts/clarity_medium.png
  libraries/AP_OSD/fonts/digital.mcm
  libraries/AP_OSD/fonts/digital.png
  libraries/AP_OSD/fonts/font0.bin
  libraries/AP_OSD/fonts/font1.bin
  libraries/AP_OSD/fonts/font2.bin
  libraries/AP_OSD/fonts/font3.bin
  libraries/AP_OSD/fonts/font4.bin
Labels: MergeOnCIPass, OSD

#17611 SRV_Channel: add motor 1 - 4 to Rover function description, used on Omni frame type.
  libraries/SRV_Channel/SRV_Channel.cpp
Labels: Rover

#17615 HAL_ChibiOS: empty dma.txt on first fetch
  libraries/AP_HAL_ChibiOS/shared_dma.cpp
Labels: ChibiOS

#17574 Copter: these two errors are too common to be called "emergency"
  ArduCopter/crash_check.cpp
Labels: Copter, MergeOnCIPass

#17618 autotest: check fence upload/download when creating from locs
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17616 AP_HAL: fixed build on boards with no PWM
  libraries/AP_HAL/board/chibios.h
Labels: DevCallEU

#17607 AP_BoardConfig: minor change to BRD_IMU_TARGTEMP param desc
  libraries/AP_BoardConfig/AP_BoardConfig.cpp
Labels: DevCallEU, Docs

#17634 Tools: reduce copter autotest rate yaw P and I gains
  Tools/autotest/default_params/copter-deca.parm
  Tools/autotest/default_params/copter-dodecahexa.parm
  Tools/autotest/default_params/copter-hexa.parm
  Tools/autotest/default_params/copter-octaquad.parm
  Tools/autotest/default_params/copter-y6.parm
  Tools/autotest/default_params/copter.parm
Labels: DevCallTopic, DevEnv

#17646 AP_HAL_ChibiOS: CUAV X7/Nora: use icm42688 instead of bmi088
  libraries/AP_HAL_ChibiOS/hwdef/CUAV-Nora/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CUAV-X7/hwdef.dat
Labels: MergeOnCIPass

#17362 AP_Frsky_Telem: new parameter for the default FRSky passthrough sensor ID
  libraries/AP_Frsky_Telem/AP_Frsky_Backend.h
  libraries/AP_Frsky_Telem/AP_Frsky_Parameters.cpp
  libraries/AP_Frsky_Telem/AP_Frsky_Parameters.h
  libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
  libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.h
Labels: Library, MergeOnCIPass, WikiNeeded

#17647 autotest: add trivial test for BodyFrameOdom
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#17648 AP_Math: add tests for the sqrt_controller
  libraries/AP_Math/tests/test_sqrt_controller.cpp
Labels: MergeOnCIPass

#17663 HAL_ChibiOS: fixed DMA disable on contention
  libraries/AP_HAL_ChibiOS/UARTDriver.cpp
Labels: BUG, ChibiOS

#17603 AP_NavEKF3: remove getFilterGpsStatus
  libraries/AP_NavEKF3/AP_NavEKF3.cpp
  libraries/AP_NavEKF3/AP_NavEKF3.h
  libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.h
Labels: DevCallTopic

#17639 AP_OSD_Screen: make BLH RPM fixed length
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: AllVehicles, DevCallTopic

#17665 Plane: tailsitter: increase severity level of failed transisisons
  ArduPlane/tailsitter.cpp
Labels: DevCallTopic, Plane

#17691 AP_Common: remove weird cast of location object
  libraries/AP_Common/Location.cpp
Labels: DevCallEU

#17684 AP_ESC_Telem: don't send mavlink msgs if we've never data any data
  libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
  libraries/AP_ESC_Telem/AP_ESC_Telem.h
Labels: BUG, MergeOnCIPass

#17689 Rover: THR logs X-axis accel
  Rover/Log.cpp
Labels: BUG, Logging, Rover

#17697 Copter: fix build problem when log disabled
  ArduCopter/Log.cpp
Labels: MergeOnCIPass

#17701 autotest: fly each working Helicopter frame
  Tools/autotest/arducopter.py
  Tools/autotest/arduplane.py
  Tools/autotest/common.py
  Tools/autotest/pysim/vehicleinfo.py
  Tools/autotest/quadplane.py
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#17712 autotest: add a progress message for looking for a message in a log
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17711 autotest: wait for a few seconds for arm-failure messages to appear
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17710 autotest: wipe SITL state after temperature cal test
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#17670 AP_Compass: fixed build with AP_Periph compass
  libraries/AP_Compass/AP_Compass.cpp
Labels: Compass

#17637 Support RunCam Hybrid correctly
  libraries/AP_Camera/AP_RunCam.cpp
  libraries/AP_Camera/AP_RunCam.h
Labels: AllVehicles, BUG, DevCallEU

#17636 Ensure digital motor masks are setup correctly regardless of AUTO setting
  libraries/AP_BLHeli/AP_BLHeli.cpp
Labels: AllVehicles, BUG, DevCallEU

#17609 AP_Math: make unittest closer to 100% coverage
  libraries/AP_Math/tests/test_3d_lines.cpp
  libraries/AP_Math/tests/test_geodesic_grid.cpp
  libraries/AP_Math/tests/test_math.cpp
  libraries/AP_Math/tests/test_math_double.cpp
  libraries/AP_Math/tests/test_perpendicular.cpp
  libraries/AP_Math/tests/test_vector2.cpp
  libraries/AP_Math/tests/test_vector3.cpp
Labels: Library, MergeOnCIPass

#17718 AP_VisualOdom: do not build on 1MB boards
  libraries/AP_VisualOdom/AP_VisualOdom.h
Labels: MergeOnCIPass

#17708 AP_Scheduler: corrected tick counter overflow handling, fixes #17642
  libraries/AP_Scheduler/AP_Scheduler.cpp
Labels: AllVehicles, BUG, DevCallEU

#17725 autotest: start GDB in tui mode by default
  Tools/autotest/autotest.py
  Tools/autotest/common.py
  Tools/autotest/pysim/util.py
Labels: MergeOnCIPass

#17726 autotest: retry SITL connect many times while running under GDB
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17741 AP_Navigation: make crosstrack_error_integrator pure virtual as nobod…
  libraries/AP_Navigation/AP_Navigation.h
Labels: Library

#17737 autotest: move autotest tlog files into buildlogs directory
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17729 AP_AHRS: NavEKF: make set_origin and get_origin WARN_IF_UNUSED as bas…
  libraries/AP_AHRS/AP_AHRS_NavEKF.h
Labels: Library

#17720 AP_Common: Location Vector3f constructor zero out fields
  libraries/AP_Common/Location.cpp
Labels: BUG, DevCallTopic, Library

#17749 AP_InternalError: specify size for error_t
  libraries/AP_InternalError/AP_InternalError.h
Labels: Library

#17758 Plane: reset yaw controller on entry to POSITION1
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane

#17727 AP_HAL_ChibiOS: fix infinite loop for large SPI transfers
  libraries/AP_HAL_ChibiOS/SPIDevice.cpp
Labels: DevCallTopic

#17761 Copter: 4.1.0-beta4 release notes
  ArduCopter/ReleaseNotes.txt
Labels: Copter

#17740 Rover: 4.1.0-beta4 release notes
  Rover/release-notes.txt
Labels: Rover

#17556 Plane: Add options to USE_REVERSE_THRUST to cover all flight modes
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/defines.h
  ArduPlane/reverse_thrust.cpp
Labels: DevCallTopic

#17685 GCS_MAVLink: correct decimation of SENSOR_STATUS message
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: DevCallTopic, MAVLink

#17530 AP_Scripting: add SN-GCJA5 particle sensor example
  libraries/AP_Scripting/examples/SN-GCJA5-particle-sensor.lua
Labels: DevCallTopic, Scripting

#17730 Make sure all MatekF405 bi-dir outputs get a DMA channel
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-bdshot/hwdef.dat
Labels: AllVehicles, BUG, ChibiOS, DevCallTopic

#17776 AP_Bootloader: added QioTekZealotH743 board type
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#17772 AP_HAL_ChibiOS: Restore soaring on F405-Wing board.
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing/hwdef.dat
Labels: DevCallEU

#17232 AR_WPNav: add WP_PIVOT_DELAY parameter
  libraries/AR_WPNav/AR_WPNav.cpp
  libraries/AR_WPNav/AR_WPNav.h
Labels: MergeOnCIPass

#17657 Zero ESC battery monitor consumption total before recalculating
  libraries/AP_BattMonitor/AP_BattMonitor_ESC.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_ESC.h
Labels: AllVehicles, BUG, DevCallEU

#17717 AC_Loiter: init brake_accel and fix brake timer type
  libraries/AC_WPNav/AC_Loiter.cpp
  libraries/AC_WPNav/AC_Loiter.h
Labels: BUG, Copter, MergeOnCIPass

#17765 Copter: add configurable rangefinder filter and restore default to 0.25
  ArduCopter/Parameters.cpp
  ArduCopter/Parameters.h
  ArduCopter/config.h
  ArduCopter/sensors.cpp
Labels: Copter, DevCallEU, Enhancement

#17791 autotest: let arming failure messages get spit out
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17794 AC_WPNav: move get_yaw lower in AC_WPNav.h
  libraries/AC_WPNav/AC_WPNav.h
Labels: Copter

#17797 autotest: improve diagnostics around touchdown/takeoff expected tests
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#17540 AP_Motors: correct expo parameter description and internal limits
  libraries/AP_Motors/AP_MotorsMulticopter.cpp
Labels: BUG, Copter

#17774 Logging: keep the EKF happy when creating log files
  libraries/AP_Logger/AP_Logger_File.cpp
Labels: DevCallTopic, EKF, Logging

#17818 Test common: finish unittests for 100% coverage
  Tools/scripts/run_coverage.py
  libraries/AP_Common/Location.cpp
  libraries/AP_Common/tests/test_bitmask.cpp
  libraries/AP_Common/tests/test_cpp.cpp
  libraries/AP_Common/tests/test_expandingstring.cpp
  libraries/AP_Common/tests/test_expandingstring_failure.cpp
  libraries/AP_Common/tests/test_fwversion.cpp
  libraries/AP_Common/tests/test_location.cpp
  libraries/AP_Common/tests/test_nmea_print.cpp
  libraries/AP_Common/tests/test_nmea_vaprint.cpp
  libraries/AP_Common/tests/test_tsindex.cpp
Labels: Tools

#17369 autotest: ensure reasonable yawrate on takeoff in FlyEachFrame
  Tools/autotest/arducopter.py
Labels: WIP

#17807 Plane: fixed attitude control during QPOS_AIRBRAKE
  ArduPlane/quadplane.cpp
Labels: BUG, VTOL-Plane

#17764 HAL_ChibiOS: fixed build of VRUBrain-v51
  libraries/AP_HAL_ChibiOS/hwdef/VRUBrain-v51/hwdef.dat
Labels: ChibiOS, DevCallTopic

#17777 AP_Compass: added probe method for MMC3416 compass
  libraries/AP_Compass/AP_Compass.cpp
Labels: DevCallTopic, MergeOnCIPass

#17833 autotest: revert to subprocess.check_call
  Tools/autotest/autotest.py
Labels: Tools

#17837 AC_AttitudeControl:AC_PosControl: vibration failsafe fix
  libraries/AC_AttitudeControl/AC_PosControl.cpp
  libraries/AC_AttitudeControl/AC_PosControl.h
Labels: BUG, Copter

#17844 Fixes for config_error_loop test
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17849 Tools: added name to GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#17847 .github: allow to skip previous CI jobs on PR
  .github/workflows/cygwin_build.yml
  .github/workflows/test_chibios.yml
  .github/workflows/test_coverage.yml
  .github/workflows/test_linux_sbc.yml
  .github/workflows/test_replay.yml
  .github/workflows/test_sitl_copter.yml
  .github/workflows/test_sitl_periph.yml
  .github/workflows/test_sitl_plane.yml
  .github/workflows/test_sitl_rover.yml
  .github/workflows/test_sitl_sub.yml
  .github/workflows/test_sitl_tracker.yml
  .github/workflows/test_size.yml
  .github/workflows/test_unit_tests.yml
Labels: MergeOnCIPass

#17843 autotest: emit 'attempt 1/3' when retrying set_parameter
  Tools/autotest/arducopter.py
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17845 autotest: correct placement of not-alive-after-test message
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17841 Tools: autotest of vibration failsafe
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass, Tools

#17719 AP_HAL_ChibiOS: remove bl embed in MatekF405-Wing
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: MergeOnCIPass

#17838 Copter: loiter wobble fix
  libraries/AC_AttitudeControl/AC_PosControl.cpp
Labels: BUG, Copter, MergeOnCIPass

#17850 AC_PosControl: fixup ekf reset
  libraries/AC_AttitudeControl/AC_PosControl.cpp
Labels: BUG, NeedsTesting

#17856 Copter: RNGFND_FILT param default increased from 0.25 to 0.5
  ArduCopter/Parameters.cpp
  ArduCopter/config.h
Labels: Copter, Enhancement

#17857 Tools: add copter gps_glitch_loiter_test2
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass, Tools

#17867 autotest: disable quadplane ConfigErrorLoop test
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#17882 Plane: fix bug in tilt position for QLOITER and QRTL if THR_MIN !=0
  ArduPlane/tiltrotor.cpp
Labels: 4.0 Backport, BUG, DevCallTopic, NeedsTesting, Plane

#17899 ArduCopter : added and fixed few comments
  ArduCopter/Attitude.cpp
  ArduCopter/Copter.h
Labels: MergeOnCIPass

#17889 Copter: improve check of far_from_EKF_origin
  ArduCopter/AP_Arming.cpp
  ArduCopter/commands.cpp
  ArduCopter/config.h
Labels: BUG, Copter, Enhancement

#17904 Copter: 4.1.0-beta5 release notes
  ArduCopter/ReleaseNotes.txt
Labels: Copter

#17905 Rover: 4.1.0-beta5 release notes
  Rover/release-notes.txt
Labels: Rover

#17860 Update Install Prerequisites script for macos
  .github/workflows/macos_build.yml
  Tools/environment_install/install-prereqs-mac.sh
Labels: BuildSystem, CI, DevCallEU, WikiNeeded

#17880 CI: correct bash string eq test
  .github/workflows/test_chibios.yml
  .github/workflows/test_coverage.yml
  .github/workflows/test_linux_sbc.yml
  .github/workflows/test_replay.yml
  .github/workflows/test_sitl_copter.yml
  .github/workflows/test_sitl_plane.yml
  .github/workflows/test_sitl_rover.yml
  .github/workflows/test_sitl_sub.yml
  .github/workflows/test_sitl_tracker.yml
  .github/workflows/test_unit_tests.yml
Labels: DevCallEU

#17839 AP_HAL_ChibiOS: update clock config for FDCAN and External Flash
  libraries/AP_HAL_ChibiOS/hwdef/STM32CubeConf/H7-16MHz/H7-16MHz.ioc
  libraries/AP_HAL_ChibiOS/hwdef/STM32CubeConf/H7-24MHz/H7-24MHz.ioc
  libraries/AP_HAL_ChibiOS/hwdef/STM32CubeConf/H7-25MHz/H7-25MHz.ioc
  libraries/AP_HAL_ChibiOS/hwdef/STM32CubeConf/H7-8MHz/H7-8MHz.ioc
  libraries/AP_HAL_ChibiOS/hwdef/STM32CubeConf/H7-no-xtal/H7-no-xtal.ioc
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
Labels: ChibiOS, DelayMerge, DevCallEU, NeedsTesting
