Repository ArduPilot/ardupilot, pull requests merged in 2021-08, with the labels that each got.

#18185 Tools: cope with build_binaries.py being copied out
  Tools/scripts/build_binaries.py
Labels: BuildSystem

#18178 Plane: don't allow motortest if motors not allocated
  ArduPlane/motor_test.cpp
Labels: DevCallTopic

#18176 Move AOA and SSA state to be private in frontend
  libraries/AP_AHRS/AP_AHRS.h
  libraries/AP_AHRS/AP_AHRS_Backend.h
Labels: DevCallTopic

#18179 GCS_MAVLink: cope with MAV_CMD_ACCELCAL_VEHICLE_POS outside accelcal
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: DevCallTopic

#18184 waf: add files from ROMFS_custom to ROMFS
  Tools/ardupilotwaf/boards.py
Labels: DevCallTopic, Scripting, WikiNeeded

#18188 AP_RCTelemetry: warn if Passthru miss-configured
  libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
Labels: DevCallTopic

#18181 Remove tri yaw servo from motor mask
  libraries/AP_Motors/AP_MotorsTri.cpp
Labels: BUG, Copter

#18190 AC_AttitudeControl: Support thrust to weight of 10:1
  libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp
Labels: Copter

#18189 Copter: remove ekf check debug logging
  ArduCopter/ekf_check.cpp
Labels: Copter

#18142 AP_Scripting: avoid a error in lua with gcc 10.2 on STM32 with -Werror
  libraries/AP_Scripting/lua/src/lstring.c
Labels: MergeOnCIPass

#18039 AP_NavEKF3: add 'vertical position' to pre_arm_check description
  libraries/AP_NavEKF/AP_NavEKF_Source.cpp
Labels: Docs, EKF

#18141 Plane: fix ADSB stall speed units.
  ArduPlane/ArduPlane.cpp
Labels: BUG, Plane

#18216 .github: remove issue notifier
  .github/workflows/issue_notifier.yml
Labels: DevEnv

#18212 Guided: Add terrain following initialization.
  ArduCopter/mode_guided.cpp
Labels: BUG, Copter, MergeOnCIPass

#18209 Copter: notify buzzer on every flight mode change
  ArduCopter/Copter.h
  ArduCopter/RC_Channel.cpp
  ArduCopter/mode.cpp
  ArduCopter/system.cpp
Labels: Copter

#18224 AP_Periph: fixed float16 conversions for scalars
  Tools/AP_Periph/can.cpp
Labels: AP_Periph, BUG, CAN

#18226 Tools: break out boards list
  Tools/scripts/board_list.py
  Tools/scripts/build_binaries.py
Labels: BuildSystem

#18139 .github: swith to GCC10 for chibios build
  .github/workflows/test_chibios.yml
Labels: CI, MergeOnCIPass

#18194 AP_OSD: Add Link Quality icon
  libraries/AP_OSD/AP_OSD_Screen.cpp
  libraries/AP_OSD/fonts/bfstyle.mcm
  libraries/AP_OSD/fonts/bfstyle.png
  libraries/AP_OSD/fonts/bold.mcm
  libraries/AP_OSD/fonts/bold.png
  libraries/AP_OSD/fonts/clarity.mcm
  libraries/AP_OSD/fonts/clarity.png
  libraries/AP_OSD/fonts/clarity_medium.mcm
  libraries/AP_OSD/fonts/clarity_medium.png
  libraries/AP_OSD/fonts/digital.mcm
  libraries/AP_OSD/fonts/digital.png
  libraries/AP_OSD/fonts/font0.bin
  libraries/AP_OSD/fonts/font1.bin
  libraries/AP_OSD/fonts/font2.bin
  libraries/AP_OSD/fonts/font3.bin
  libraries/AP_OSD/fonts/font4.bin
Labels: OSD

#18239 Tools: correct author name formatting
  Tools/gittools/git-subsystems-split
Labels: Tools

#18158 SITL: Change Morse Ackermann model param
  libraries/SITL/examples/Morse/rover.parm
Labels: BUG, Rover, SITL, MergeOnCIPass

#18246 AP_OSD: add option to convert to miles at 5280ft vs 10000ft
  libraries/AP_OSD/AP_OSD.cpp
  libraries/AP_OSD/AP_OSD.h
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: OSD

#18248 AP_Scripting: make LUA memory panic more helpful
  libraries/AP_Scripting/lua/src/lstring.c
Labels: Scripting

#18264 AP_NavEKF3: fixed output LLH to account for IMU offset
  libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp
Labels: BUG, EKF

#18262 Tools: added name to GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#18253 AP_HAL_ChibiOS: add Icm42605 as a backup to replace icm20649
  libraries/AP_HAL_ChibiOS/hwdef/QioTekZealotF427/hwdef.dat
Labels: ChibiOS

#18232 AP_Airspeed: check for baro baro data in SDP3X
  libraries/AP_Airspeed/AP_Airspeed_SDP3X.cpp
Labels: BUG, AP_Periph, WikiNeeded

#18265 AP_HAL_ChibiOS: fix invalid use of FDCAN2_IT0_IRQn enum for ifdef
  libraries/AP_HAL_ChibiOS/CANFDIface.cpp
Labels: BUG, CAN, NeedsTesting

#17835 AP_Scripting: added has_valid_input binding
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: Scripting

#18019 AP_LeakDetector: enable for Pixhawk4
  libraries/AP_LeakDetector/AP_LeakDetector.cpp
Labels: Sub

#18219 Probe for compasses on FlywooF745
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF745/hwdef.dat
Labels: BUG, AllVehicles, ChibiOS

#18225 AP_NavEKF3: skip GSF reset count check if source actively changed
  libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.h
Labels: BUG, EKF, DevCallTopic

#18227 Plane: notify buzzer on every mode change
  ArduPlane/Plane.h
  ArduPlane/RC_Channel.cpp
  ArduPlane/system.cpp
Labels: Plane, DevCallTopic

#18261 Plane: added option to log PIDs at full rate
  ArduPlane/ArduPlane.cpp
  ArduPlane/Log.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/Plane.h
  ArduPlane/defines.h
Labels: Plane, DevCallTopic

#18269 waf: avoid problem with custom build server
  Tools/ardupilotwaf/ap_library.py
Labels: BuildSystem

#18270 AP_Periph: fix checking compass available before init
  Tools/AP_Periph/AP_Periph.cpp
Labels: BUG, AP_Periph

#18278 AP_Beacon: fix comparison order to prevent using wrong beacon_instanc…
  libraries/AP_Beacon/AP_Beacon.cpp
Labels: BUG, MergeOnCIPass

#18280 autotest: add test for FRSkyD battery
  Tools/autotest/common.py
Labels: MergeOnCIPass

#18144 [AP_OSD] Add option to disable Crosshair on OSD horizon element
  libraries/AP_OSD/AP_OSD.cpp
  libraries/AP_OSD/AP_OSD.h
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: OSD, DevCallEU

#18282 AP_AHRS: move takeoff/touchdown flags to frontend
  libraries/AP_AHRS/AP_AHRS.cpp
  libraries/AP_AHRS/AP_AHRS.h
  libraries/AP_AHRS/AP_AHRS_Backend.cpp
  libraries/AP_AHRS/AP_AHRS_Backend.h
  libraries/AP_AHRS/AP_AHRS_DCM.cpp
Labels: DevCallEU

#18290 AP_Torqeedo: send motor speed cmd at 50hz
  libraries/AP_Torqeedo/AP_Torqeedo.cpp
Labels: Enhancement, Rover

#18287 AP_Logger: fix MAVLink logger random failure on SITL
  libraries/AP_Logger/AP_Logger_MAVLink.cpp
Labels: BUG, SITL, Logging, MAVLink

#18289 AP_OSD: check for nullptr before using it
  libraries/AP_OSD/AP_OSD_ParamScreen.cpp
Labels: BUG, OSD

#18296 AP_BattMonitor: fix mppt sequence bug
  libraries/AP_BattMonitor/AP_BattMonitor_MPPT_PacketDigital.cpp
Labels: BUG

#18197 autotest: add option to hard-reset after every test
  Tools/autotest/autotest.py
  Tools/autotest/common.py
Labels: MergeOnCIPass

#18231 AP_Scripting: Add mission selection applet
  libraries/AP_Scripting/applets/MissionSelector.lua
  libraries/AP_Scripting/applets/MissionSelector.md
Labels: Scripting, WikiNeeded

#18314 Tools: added name to GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#18279 AP_OSD: fixes bug introduced by #16477
  libraries/AP_OSD/AP_OSD.cpp
Labels: BUG, DevCallTopic, OSD

#18321 HAL_SITL: fix use of variable before checking nullprt
  libraries/AP_HAL_SITL/SITL_State.cpp
Labels: BUG, SITL

#18050 Plane: don't output throttle in when safe
  ArduPlane/radio.cpp
Labels: BUG, Safety

#18346 AP_NavEKF3: added EK3_PRIMARY parameter
  libraries/AP_NavEKF3/AP_NavEKF3.cpp
  libraries/AP_NavEKF3/AP_NavEKF3.h
Labels: EKF

#18235 AP_HAL_ChibiOS: Pixhawk4 blue and red LEDs swapped
  libraries/AP_HAL_ChibiOS/hwdef/Pixhawk4/hwdef.dat
Labels: BUG, ChibiOS

#18238 Plane: actually fail to enter mode, don't just put the mode back and return true
  ArduPlane/mode_qacro.cpp
  ArduPlane/mode_qstabilize.cpp
  ArduPlane/system.cpp
Labels: BUG, Plane, DevCallTopic

#18256 Copter: flowhold: use correct angle max
  ArduCopter/mode_flowhold.cpp
Labels: DevCallTopic

#18347 Plane: fixed EKF fly-forward flag for tailsitters
  ArduPlane/ArduPlane.cpp
Labels: BUG, VTOL-Plane, DevCallTopic, DevCallEU

#18306 Add turtle mode docs
  libraries/RC_Channel/RC_Channel.cpp
Labels: MergeOnCIPass

#18370 .gitignore: ignore history directory from vscode extension
  .gitignore
Labels: MergeOnCIPass

#18366 autotest: add battery_charge_state ok & low tests
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#18354 AP_Scripting add quadplane in_assisted_flight binding
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: Scripting, DevCallEU

#18334 Copter: always check GPS in super simple modes
  ArduCopter/AP_Arming.cpp
Labels: Copter, DevCallEU

#18315 AP_Button: add debounce on PWM input
  libraries/AP_Button/AP_Button.cpp
  libraries/AP_Button/AP_Button.h
Labels: DevCallEU

#18360 AP_Math: correct descriptions of quaternion functions
  libraries/AP_Math/quaternion.cpp
  libraries/AP_Math/quaternion.h
Labels: MergeOnCIPass

#18345 GCS_MAVLink: add support for MAV_CMD_EKF_SOURCE_SET
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: Enhancement, EKF, AllVehicles, MergeOnCIPass

#18361 Invert SBUS on RC serial connections on F4
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF4/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MambaF405v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-i2c/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini/hwdef.dat
Labels: BUG, AllVehicles, ChibiOS, WikiNeeded, MergeOnCIPass

#18392 AP_RCTelemetry: fixed CRSF build dependency issue
  libraries/AP_RCTelemetry/AP_CRSF_Telem.h
Labels: BuildSystem, MergeOnCIPass

#18391 Add Grand Canyon to locations
  Tools/autotest/locations.txt
Labels: MergeOnCIPass

#18403 Fix macos build in CI
  Tools/environment_install/install-prereqs-mac.sh
Labels: MergeOnCIPass

#18406 AC_PosControl: init_z_controller_stopping_point: remove duplicate set…
  libraries/AC_AttitudeControl/AC_PosControl.cpp
Labels: MergeOnCIPass

#18313 AP_Terrain: added a TERRAIN_MARGIN parameter
  libraries/AP_Terrain/AP_Terrain.cpp
  libraries/AP_Terrain/AP_Terrain.h
  libraries/AP_Terrain/tools/create_terrain.py
Labels: AllVehicles, DevCallTopic

#18414 Readme: remove Kancir that isn't maintainer
  README.md
Labels: BUG, Enhancement, Safety, Reviewed, Top Contribution, DevCallTopic, DevCallEU, InternalError, MergeOnCIPass

#18399 APM_Control: remove unused variables
  libraries/APM_Control/AP_PitchController.h
  libraries/APM_Control/AP_RollController.h
Labels: DevCallTopic

#18362 AP_Arming: remove redundant checks_to_perform check
  libraries/AP_Arming/AP_Arming.cpp
Labels: DevCallTopic

#18416 HAL_ChibiOS: switch to minimum scheduling delta of 10us
  libraries/AP_HAL_ChibiOS/Scheduler.cpp
  libraries/AP_HAL_ChibiOS/hwdef/common/chconf.h
Labels: BUG, DevCallTopic, ChibiOS

#15826 Tradheli: Fix guided mode spoolup and takeoff
  ArduCopter/mode.cpp
  ArduCopter/mode.h
  ArduCopter/mode_auto.cpp
  ArduCopter/mode_brake.cpp
  ArduCopter/mode_circle.cpp
  ArduCopter/mode_follow.cpp
  ArduCopter/mode_guided.cpp
  ArduCopter/mode_land.cpp
  ArduCopter/mode_rtl.cpp
  ArduCopter/system.cpp
  ArduCopter/takeoff.cpp
Labels: TradHeli

#18412 SITL: correct SIM_FETtecOneWire consume function
  libraries/SITL/SIM_FETtecOneWireESC.cpp
Labels: MergeOnCIPass

#18389 AP_Compass: fail calibration unless at least 1 compass to cal
  libraries/AP_Compass/AP_Compass.h
  libraries/AP_Compass/AP_Compass_Calibration.cpp
Labels: DevCallTopic

#18401 AP_SerialManager: reserve Id 41 for CoDev serially-attached ESCs
  libraries/AP_SerialManager/AP_SerialManager.h
Labels: DevCallTopic

#18413 Plane: Quadplane: add Q_OPTION to only allow arming in Qmodes and auto.
  ArduPlane/AP_Arming.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: VTOL-Plane, DevCallTopic

#18425 AP_CANManager: correct metadata for values
  libraries/AP_CANManager/AP_CANIfaceParams.cpp
Labels: Library

#18426 AC_Loiter: update ANG_MAX param description
  libraries/AC_WPNav/AC_Loiter.cpp
Labels: MergeOnCIPass

#18308 ArduPlane: add thr position trigger to ThrLandCtrl Q_OPTION
  ArduPlane/config.h
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: Plane, WikiNeeded, MergeOnCIPass

#18365 SITL: add unit tests for SIM_MS5611
  libraries/SITL/tests/test_sim_ms5611.cpp
  libraries/SITL/tests/wscript
Labels: SITL

#18402 RC_Channel: rename visodom_calibrate to visodom_align
  libraries/RC_Channel/RC_Channel.cpp
  libraries/RC_Channel/RC_Channel.h
Labels: DevCallEU

#18393 AP_FETtecOneWire: README.md clarity improvements (NFC)
  libraries/AP_FETtecOneWire/README.md
Labels: AllVehicles, Docs

#18372 Copter: Change the parameter description
  ArduCopter/Parameters.cpp
Labels: DevCallEU

#18432 Constrain airspeed sensor data according to WIND_MAX
  libraries/AP_AHRS/AP_AHRS.cpp
Labels: DevCallEU

#18433 AP_AHRS: make home-relative functions AHRS-frontend only
  libraries/AP_AHRS/AP_AHRS.cpp
  libraries/AP_AHRS/AP_AHRS.h
  libraries/AP_AHRS/AP_AHRS_Backend.h
  libraries/AP_AHRS/AP_AHRS_DCM.cpp
  libraries/AP_AHRS/AP_AHRS_DCM.h
  libraries/AP_AHRS/AP_AHRS_Logging.cpp
Labels: DevCallEU

#18429 AP_AHRS: constrain airspeed sensor airspeed using WIND_MAX
  libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
Labels: DevCallEU

#18444 Plane: tailsitter: remove pilot prop-hanging teaching params and code.
  ArduPlane/quadplane.cpp
  ArduPlane/tailsitter.cpp
  ArduPlane/tailsitter.h
Labels: VTOL-Plane, DevCallEU

#18397 AP_Logger: Use actual MAVLink constant
  libraries/AP_Logger/AP_Logger_MAVLink.cpp
Labels: Logging, MergeOnCIPass

#17375 AP_Soaring: Initialize estimate to the current filtered measurement.
  libraries/AP_Soaring/AP_Soaring.cpp
  libraries/AP_Soaring/AP_Soaring.h
Labels: DevCallEU

#18448 AP_WindVane: remove empty contructors
  libraries/AP_WindVane/AP_WindVane_Airspeed.cpp
  libraries/AP_WindVane/AP_WindVane_Airspeed.h
  libraries/AP_WindVane/AP_WindVane_Home.cpp
  libraries/AP_WindVane/AP_WindVane_Home.h
  libraries/AP_WindVane/AP_WindVane_NMEA.cpp
  libraries/AP_WindVane/AP_WindVane_NMEA.h
  libraries/AP_WindVane/AP_WindVane_RPM.cpp
  libraries/AP_WindVane/AP_WindVane_RPM.h
  libraries/AP_WindVane/AP_WindVane_SITL.cpp
  libraries/AP_WindVane/AP_WindVane_SITL.h
Labels: MergeOnCIPass

#18443 Tools: autotest: enable tailsitter for tailsitter test
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#18309 Libraries: removed dead code from RC_Channel
  libraries/RC_Channel/RC_Channel.cpp
Labels: MergeOnCIPass

#18499 SITL: SIM_Sailboat: remove use of AHRS
  libraries/SITL/SIM_Sailboat.cpp
Labels: Sailboat

#18517 Increase CRSF frame timeout to account for scheduling delays
  libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp
  libraries/AP_RCProtocol/AP_RCProtocol_CRSF.h
Labels: BUG, AllVehicles

#18052 AP_Logger: specify frames on PSC fields
  libraries/AP_Logger/LogStructure.h
Labels: Logging, DevCallTopic

#18333 AP_Arming: check all GPS's for fix and health
  libraries/AP_Arming/AP_Arming.cpp
Labels: DevCallTopic

#18421 AP_Terrain: make TERRAIN_MARGIN a float
  libraries/AP_Terrain/AP_Terrain.cpp
  libraries/AP_Terrain/AP_Terrain.h
Labels: Library, DevCallTopic

#18134 Plane: Add TRIM_PITCH_CD FLIGHT_OPTIONS bits for GCS and OSD
  ArduPlane/ArduPlane.cpp
  ArduPlane/GCS_Mavlink.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/defines.h
Labels: DevCallTopic, WikiNeeded

#18461 Copter: auto RTL: don't switch modes if already in auto
  ArduCopter/mode_auto.cpp
Labels: BUG, Copter, DevCallTopic

#18487 Plane: quadplane: set `last_pidz_init_ms`
  ArduPlane/quadplane.cpp
Labels: BUG, VTOL-Plane, DevCallTopic

#18506 AP_InertialSensor: fixed locking issue in delta accumulation
  libraries/AP_InertialSensor/AP_InertialSensor.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
Labels: BUG, DevCallTopic

#18507 HAL_ChibiOS: use more USB buffers on higher end F7 chips
  libraries/AP_HAL_ChibiOS/hwdef/common/halconf.h
Labels: ChibiOS

#17977 AP_UAVCAN: cleanup comments in BatteryInfoAux dsdl message
  libraries/AP_UAVCAN/dsdl/ardupilot/equipment/power/20004.BatteryInfoAux.uavcan
Labels: DevCallTopic

#18343 AP_BoardConfig: make sure heater is left off if disabled
  libraries/AP_BoardConfig/IMU_heater.cpp
Labels: DevCallTopic, DevCallEU

#18384 plane: quadplane: tailsitter: run FW transition check and assist immediately
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, DevCallTopic

#18509 AP_Motors: use add_motors to save flash
  libraries/AP_Motors/AP_MotorsMatrix.cpp
  libraries/AP_Motors/AP_MotorsMatrix.h
Labels: Copter
