Repository ArduPilot/ardupilot, pull requests merged in 2021-12, with the labels that each got.

#19403 AP_Math: update_pos_vel_accel methods accept limit as const reference
  libraries/AP_Math/control.cpp
  libraries/AP_Math/control.h
Labels: Enhancement, Copter

#14350 AP_Scripting: added an example of OOP programming
  libraries/AP_Scripting/examples/OOP_example.lua
Labels: NeedRework, Scripting, MergeOnCIPass

#19406 hwdef: enable UART7 on Swan-K1
  libraries/AP_HAL_ChibiOS/hwdef/Swan-K1/hwdef.dat
Labels: DevCallEU, hwdef

#19402 Process CRSF crc per-byte
  libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp
  libraries/AP_RCProtocol/AP_RCProtocol_CRSF.h
Labels: Enhancement, AllVehicles, DevCallEU

#19408 Plane: fixed use before init bug in VTOL land
  ArduPlane/commands_logic.cpp
Labels: BUG, VTOL-Plane, MergeOnCIPass

#19412 AP_Compass: add new line after old param metadata
  libraries/AP_Compass/AP_Compass.cpp
Labels: MergeOnCIPass

#19410 hwdef: updated KakuteH7 battery scale defaults
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7/hwdef.dat
Labels: hwdef

#19162 AP_Proximity: Add Cygbot D1 Driver
  libraries/AP_Proximity/AP_Proximity.cpp
  libraries/AP_Proximity/AP_Proximity.h
  libraries/AP_Proximity/AP_Proximity_Cygbot_D1.cpp
  libraries/AP_Proximity/AP_Proximity_Cygbot_D1.h
Labels: Library, WikiNeeded

#19422 Plane: fixed reset of steering locked course
  ArduPlane/Attitude.cpp
  ArduPlane/Plane.h
  ArduPlane/mode.cpp
Labels: BUG, Plane

#19420 AP_RangeFinder: fixed support for multiple Benewake_CAN CAN lidars
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake_CAN.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake_CAN.h
Labels: BUG, CAN

#19425 Plane: reset VTOL takeoff if not armed
  ArduPlane/commands.cpp
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane

#19383 Tradheli: fix bug for auto missions using continue after land
  libraries/AP_Motors/AP_MotorsHeli.cpp
  libraries/AP_Motors/AP_MotorsHeli.h
  libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
  libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
  libraries/AP_Motors/AP_MotorsHeli_RSC.cpp
  libraries/AP_Motors/AP_MotorsHeli_RSC.h
  libraries/AP_Motors/AP_MotorsHeli_Single.cpp
Labels: BUG, TradHeli, NeedsTesting

#19430 AP_Torqeedo: provide human-readable version of master error code
  libraries/AP_Torqeedo/AP_Torqeedo.cpp
  libraries/AP_Torqeedo/AP_Torqeedo.h
Labels: Enhancement, Rover, MergeOnCIPass

#19439 AP_UAVCAN: use soft armed state for DroneCAN ARMING_STATUS
  libraries/AP_UAVCAN/AP_UAVCAN.cpp
Labels: BUG, CAN, AP_Periph

#19445 AP_HAL_SITL: remove unused _home_str member
  libraries/AP_HAL_SITL/SITL_State.cpp
  libraries/AP_HAL_SITL/SITL_State.h
Labels: SITL

#19426 Plane: check for VTOL takeoff in AUTO
  ArduPlane/AP_Arming.cpp
Labels: VTOL-Plane, WikiNeeded

#19478 Plane: fix divide by zero in transition time
  ArduPlane/quadplane.cpp
Labels: DevCallTopic

#19483 DevEnv: Add AP VSCode extension to recommendations
  .vscode/extensions.json
Labels: DevEnv, MergeOnCIPass

#19247 AP_L1_Control: Simplify the decision process by initializing the stack variables
  libraries/AP_L1_Control/AP_L1_Control.cpp
Labels: MergeOnCIPass

#19475 Copter: Guided Mavlink Target Input loosen force_set restriction only for acceleration commands
  ArduCopter/GCS_Mavlink.cpp
Labels: Copter

#19482 AP_BattMonitor: use SOC 127 as an invalid SOC flag
  libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp
Labels: DevCallTopic

#19488 AP_Compass: avoid loaded-value checks in case of HAL_USE_EMPTY_STORAGE
  libraries/AP_Compass/AP_Compass.cpp
Labels: DevCallTopic

#19503 AP_Vehicle: declare get_control_output only if scripting is enabled
  libraries/AP_Vehicle/AP_Vehicle.h
Labels: DevCallTopic

#19370 hwdef: fix CubeOrange-periph-heavy build
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-periph-heavy/hwdef.dat
Labels: BuildSystem, ChibiOS, MergeOnCIPass

#19502 GCS_MAVLink: Don't start with MAVLink1 messages on a MAVLink2 connection
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#19524 SRV_Channel: validate function number before array access
  libraries/SRV_Channel/SRV_Channel.h
  libraries/SRV_Channel/SRV_Channel_aux.cpp
  libraries/SRV_Channel/SRV_Channels.cpp
Labels: BUG, MergeOnCIPass

#19266 AP_Frsky_Telem: added frame 0x500D for waypoint data
  libraries/AP_Frsky_Telem/AP_Frsky_SPort.cpp
  libraries/AP_Frsky_Telem/AP_Frsky_SPort.h
  libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
  libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.h
Labels: DevCallEU

#19515 AP_Math: create double versions of is_zero, is_positive and is_negative
  libraries/AP_Math/AP_Math.h
Labels: DevCallEU

#19520 AP_Compass: fix compilation issue with declaring var after goto
  libraries/AP_Compass/AP_Compass_RM3100.cpp
Labels: MergeOnCIPass

#19522 Tools: pretty_diff_size, show total flash cost
  Tools/scripts/pretty_diff_size.py
Labels: Tools, DevCallEU

#19543 AP_ADSB: add link to UCP protocol in the UCP driver
  libraries/AP_ADSB/AP_ADSB_uAvionix_UCP.cpp
Labels: Docs

#19560 HAL_ChibiOS: set SWD pins pulled up and low by default
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: MergeOnCIPass

#19561 AP_InertialSensor: correct logging of inertial-sensor reg-change logging
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
Labels: MergeOnCIPass

#19542 AP_HAL_ChibiOS: remove stray 'No Crash Detected' diagnostic
  libraries/AP_HAL_ChibiOS/Util.cpp
Labels: DevCallTopic

#19418 AP_PiccoloCAN: Fix temperature logging bug
  libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp
Labels: DevCallTopic

#19529 AP_NavEKF3 - add missing covariance row reset
  libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
Labels: BUG, EKF

#19528 AP_Scripting: add MiniCheetah CAN motor driver example
  libraries/AP_Scripting/examples/CAN_MiniCheetah_drive.lua
Labels: DevCallTopic, Scripting

#19463 Plane: tailsitter: add gains to scale control surface vs motors
  ArduPlane/tailsitter.cpp
  ArduPlane/tailsitter.h
Labels: VTOL-Plane, DevCallTopic, WikiNeeded, DevCallEU

#19558 AP_BoardConfig: disable STLink debug pins by default (4.0 version)
  libraries/AP_BoardConfig/AP_BoardConfig.cpp
  libraries/AP_BoardConfig/AP_BoardConfig.h
  libraries/AP_BoardConfig/board_drivers.cpp
Labels: ChibiOS

#19559 AP_BoardConfig: disable STLink debug pins by default
  libraries/AP_BoardConfig/AP_BoardConfig.cpp
  libraries/AP_BoardConfig/AP_BoardConfig.h
  libraries/AP_BoardConfig/board_drivers.cpp
Labels: DevCallTopic, ChibiOS, WikiNeeded

#19579 AP_SmartAudio: fix a bug that would starve the lower priority thread
  libraries/AP_VideoTX/AP_SmartAudio.cpp
Labels: BUG, MergeOnCIPass

#19585 AP_SerialManager: fixed AP_Periph GPS
  libraries/AP_SerialManager/AP_SerialManager.cpp
Labels: BUG, AP_Periph

#19534 Tools: fix size reporting errors due to crash_log inclusion in BSS
  Tools/ardupilotwaf/build_summary.py
  Tools/scripts/pretty_diff_size.py
Labels: Tools

#18126 AP_Baro: KellerLD: clean up reading of calibration data
  libraries/AP_Baro/AP_Baro_KellerLD.cpp
  libraries/AP_Baro/AP_Baro_KellerLD.h
Labels: Sub, DevCallEU

#19591 Copter: Constrain vertical speed in loiter_to_alt_run
  ArduCopter/mode_auto.cpp
Labels: BUG, Copter, 4.0 Backport

#19449 AP_NMEA_Output: remove pointless intermediate res variables
  libraries/AP_NMEA_Output/AP_NMEA_Output.cpp
Labels: MergeOnCIPass

#19326 Plane: add Q_OPTION to force fw trans on fail instead of QLAND
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
  ArduPlane/transition.h
Labels: VTOL-Plane, WikiNeeded, MergeOnCIPass

#19603 Redefine DMA priority PH4-mini
  libraries/AP_HAL_ChibiOS/hwdef/PH4-mini/hwdef.dat
Labels: MergeOnCIPass

#19595 hwdef: enable telem3 (SERIAL5) TX on Pix32v5
  libraries/AP_HAL_ChibiOS/hwdef/Pix32v5/hwdef.dat
Labels: DevCallTopic, hwdef

#19611 Tools: fix Build_Summary when more than one targert
  Tools/ardupilotwaf/build_summary.py
Labels: BUG, BuildSystem

#19610 Plane: fixed stick mixing and throttle nudge in QRTL approach
  ArduPlane/Attitude.cpp
  ArduPlane/mode.h
  ArduPlane/mode_qrtl.cpp
Labels: VTOL-Plane, MergeOnCIPass

#19571 AP_Compass: added register checking for AK09916 mode
  libraries/AP_Compass/AP_Compass_AK09916.cpp
  libraries/AP_Compass/AP_Compass_AK09916.h
Labels: MergeOnCIPass, Compass

#19547 AP_Periph: fixed temperature reporting
  Tools/AP_Periph/can.cpp
Labels: AP_Periph, DevCallEU

#19617 AP_BattMonitor: fixed a segv with BATT_MONITOR=14
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_SUI.cpp
Labels: BUG

#19513 AP_InertialSensor: added support for more ADIS IMUs
  libraries/AP_InertialSensor/AP_InertialSensor_ADIS1647x.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_ADIS1647x.h
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
Labels: DevCallEU

#19626 Plane: add a low pass filter to speed scaler
  ArduPlane/Attitude.cpp
  ArduPlane/Plane.h
  ArduPlane/sensors.cpp
Labels: BUG, VTOL-Plane, DevCallEU

#19627 AP_Motors: fixed PWM_TYPE range for quadplanes
  libraries/AP_Motors/AP_Motors_Class.cpp
Labels: BUG, VTOL-Plane, DevCallEU

#19624 Tools: added missing periph builds
  Tools/scripts/board_list.py
Labels: AP_Periph

#19640 Plane: quadplane: remove unused loiter initial pitch variable
  ArduPlane/mode_qloiter.cpp
  ArduPlane/quadplane.h
Labels: VTOL-Plane
