Repository ArduPilot/ardupilot, pull requests merged in 2021-02, with the labels that each got.

#16477 AP_OSD: changed OSD screen switching logic
  libraries/AP_OSD/AP_OSD.cpp
Labels: OSD

#16389 Autotest: check for empty message before trying to use it
  Tools/autotest/common.py
Labels: DevCallEU, Tools

#16260 AP_HAL:examples:Printf: Improvements in the Printf example
  libraries/AP_HAL/examples/Printf/Printf.cpp
Labels: Docs, Library

#16488 Copter: make terrain failure strings human-readable
  ArduCopter/AP_Arming.cpp
Labels: DevCallEU

#16489 AP_Logger: correct spelling in metadata
  libraries/AP_Logger/LogStructure.h
Labels: DevCallEU

#16361 AP_HAL_ChibiOS: add f405-MatekGPS & MatekF405-CAN hwdef
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-CAN/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-CAN/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-CAN/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/f405-MatekGPS/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/f405-MatekGPS/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/f405-MatekGPS/hwdef.dat
Labels: DevCallEU

#16161 AP_HAL_ChibiOS: add MatekH743-periph hwdef
  libraries/AP_HAL_ChibiOS/hwdef/MatekH743-periph/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekH743-periph/hwdef.dat
Labels: DevCallEU

#16446 Use buffered writes for CRSF telemetry
  libraries/AP_RCProtocol/AP_RCProtocol.cpp
  libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp
Labels: AllVehicles, BUG, DevCallEU

#16466 Plane: instantly switch from RTL to QRTL if within radius
  ArduPlane/mode.h
  ArduPlane/mode_rtl.cpp
Labels: BUG, DevCallEU, VTOL-Plane

#16480 AP_Compass: Added support for internal i2c bus to VRBrain-v51
  libraries/AP_Compass/AP_Compass.cpp
Labels: ChibiOS, DevCallEU, Library

#16490 AP_BattMonitor: Limit the scope of possible corruption if the NeoDesigns gets a bad cell count
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_NeoDesign.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_NeoDesign.h
Labels: AllVehicles, BUG, DevCallEU, Library

#16485 Sub: remove unused prev_control_mode_reason
  ArduSub/Sub.h
  ArduSub/flight_mode.cpp
Labels: DevCallEU

#16484 Plane: store previous_mode_reason only as a local
  ArduPlane/Plane.h
  ArduPlane/system.cpp
Labels: DevCallEU

#14591 AP_Mission: Reflecting the result of the process
  libraries/AP_Mission/AP_Mission_Commands.cpp
Labels: Library, NeedAnswer, NeedsTesting

#16463 make get_control_mode_reason available to lua scripting
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: DevCallEU

#16511 Tools: default param file to ease using copter SITL with vicon
  Tools/autotest/default_params/copter-vicon.parm
Labels: DevEnv

#16501 HAL_ChibiOS: don't start rout ticks till after full system init
  libraries/AP_HAL_ChibiOS/Scheduler.cpp
Labels: BUG, ChibiOS

#13522 AP_RangeFinder: Delete some description of I2C function address.
  libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
Labels: Docs, Library

#16520 Filter: fixed reset of filters to first value
  libraries/Filter/LowPassFilter2p.cpp
  libraries/Filter/LowPassFilter2p.h
  libraries/Filter/examples/LowPassFilter2p/LowPassFilter2p.cpp
Labels: BUG

#16518 Tools: param files to ease SITL setup of GPS-for-yaw
  Tools/autotest/default_params/copter-gps-for-yaw-nmea.parm
  Tools/autotest/default_params/copter-gps-for-yaw.parm
Labels: DevEnv

#16530 Copter:PreArm Battery low voltage message repeated two times fix
  ArduCopter/AP_Arming.cpp
Labels: BUG, Copter, DevCallTopic

#16547 HAL_ChibiOS: added Durandal pinout details
  libraries/AP_HAL_ChibiOS/hwdef/Durandal/Durandal-back.png
  libraries/AP_HAL_ChibiOS/hwdef/Durandal/Durandal-front.png
  libraries/AP_HAL_ChibiOS/hwdef/Durandal/Durandal-left.png
  libraries/AP_HAL_ChibiOS/hwdef/Durandal/Durandal-right.png
  libraries/AP_HAL_ChibiOS/hwdef/Durandal/Durandal-top.png
  libraries/AP_HAL_ChibiOS/hwdef/Durandal/README.md
Labels: ChibiOS, WikiNeeded

#16529 Plane: Constrain roll until TKOFF_ROTATE_SPD is reached
  ArduPlane/takeoff.cpp
Labels: DevCallTopic

#16553 CI: added upload of failed tests to artifacts
  .github/workflows/test_replay.yml
  .github/workflows/test_sitl_copter.yml
  .github/workflows/test_sitl_plane.yml
  .github/workflows/test_sitl_rover.yml
  .github/workflows/test_sitl_sub.yml
  .github/workflows/test_sitl_tracker.yml
  .github/workflows/test_unit_tests.yml
Labels: CI, DevCallTopic

#16549 Scripting: simple relay example
  libraries/AP_Scripting/examples/relay_control.lua
Labels: DevCallTopic, Scripting

#16430 AP_NavEKF3: fix using_external_yaw when using external nav
  libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
Labels: BUG, DevCallTopic, EKF

#16544 .github: run test in privilege container to allow PTRACE
  .github/workflows/test_sitl_copter.yml
  .github/workflows/test_sitl_plane.yml
  .github/workflows/test_sitl_rover.yml
  .github/workflows/test_sitl_sub.yml
  .github/workflows/test_sitl_tracker.yml
Labels: DevEnv

#16563 AP_Scripting: add fault tolerant hex MotorsMatrix example
  libraries/AP_Scripting/examples/MotorMatrix_fault_tolerant_hex.lua
Labels: DevCallEU, Scripting

#16583 AC_PosControl: const local vars and remove todo
  libraries/AC_AttitudeControl/AC_PosControl.cpp
Labels: Copter, DevCallEU

#16570 BeastH7 has DPS310 baro
  libraries/AP_HAL_ChibiOS/hwdef/BeastH7/hwdef.dat
Labels: AllVehicles, BUG, DevCallEU

#16581 AC_AttitudeControl: remove feed-forward from run_quat
  libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
  libraries/AC_AttitudeControl/AC_AttitudeControl.h
Labels: Copter, DevCallEU, VTOL-Plane

#16516 AP_VisualOdom: fix T265 criteria for aligning to AHRS
  libraries/AP_VisualOdom/AP_VisualOdom_IntelT265.cpp
Labels: BUG, Copter, DevCallEU

#16599 AP_Periph: Remove debug printf
  Tools/AP_Periph/can.cpp
Labels: AP_Periph

#16611 HAL_ChibiOS: fixed handling of invalid channel for LED write
  libraries/AP_HAL_ChibiOS/RCOutput.cpp
Labels: ChibiOS

#16618 AP_MSP: removed date/time from MSP
  libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
Labels: OSD

#16546 Vagrant: augment bash when working in a git repository
  Tools/vagrant/bashrc_git
  Tools/vagrant/initvagrant-trusty64.sh
  Tools/vagrant/initvagrant.sh
Labels: NeedsTesting

#16590 HAL_ChibiOS: prevent hw flow control from hogging a DMA channel
  libraries/AP_HAL_ChibiOS/UARTDriver.cpp
  libraries/AP_HAL_ChibiOS/UARTDriver.h
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: ChibiOS

#16623 Copter: correct documentation of use of DO_CHANGE_SPEED parameter
  ArduCopter/GCS_Mavlink.cpp
Labels: DevCallTopic, WikiNeeded

#16626 Copter: ensure send_position_target_global_int alt always absolute
  ArduCopter/GCS_Mavlink.cpp
Labels: DevCallTopic

#16621 AP_RPM: don't present RPM2_PIN parameter if RPM_MAX_INSTANCES <=1
  libraries/AP_RPM/AP_RPM.cpp
Labels: DevCallTopic

#16540 AP_Baro: added MS5611 baro compensation for -15 to -40C
  libraries/AP_Baro/AP_Baro_MS5611.cpp
Labels: AllVehicles, DevCallTopic

#16523 Copter: run the "point yaw to ROI" controller at full rate (400Hz) in…
  ArduCopter/autoyaw.cpp
  ArduCopter/mode.h
Labels: Copter, DevCallTopic, Enhancement

#13457 GCS_MAVLink: don't lie about bad AHRS
  libraries/GCS_MAVLink/GCS.cpp
Labels: DevCallTopic

#16609 gitignore: add scripting repl
  .gitignore
Labels: DevCallEU

#15549 AP_HAL_ChibiOS: ensure UART driver fully supports 2-stop bits
  libraries/AP_HAL_ChibiOS/UARTDriver.cpp
  libraries/AP_HAL_ChibiOS/UARTDriver.h
Labels: BUG, ChibiOS, DevCallEU

#16652 AC_PID: AC_PI_2D format changes
  libraries/AC_PID/AC_PI_2D.h
Labels: Copter

#16644 AP_Scripting: use helper for not supported error saving 1K of flash
  libraries/AP_Scripting/generator/src/main.c
Labels: Scripting

#16680 HAL_ChibiOS: increase H7 serial buffer sizes
  libraries/AP_HAL_ChibiOS/hwdef/common/halconf.h
Labels: ChibiOS

#16683 Plane: use ahrs.groundspeed() instead of gps call
  ArduPlane/Attitude.cpp
Labels: Plane

#16694 Rebuild iomcu firmware
  Tools/IO_Firmware/iofirmware_highpolh.bin
  Tools/IO_Firmware/iofirmware_lowpolh.bin
Labels: AllVehicles, BUG, ChibiOS

#16700 AP_Motors: fixup octaquad CW_X motor directions
  libraries/AP_Motors/AP_MotorsMatrix.cpp
Labels: BUG, Copter

#16704 Tools: revert IO firmware
  Tools/IO_Firmware/iofirmware_highpolh.bin
  Tools/IO_Firmware/iofirmware_lowpolh.bin
Labels: ChibiOS

#16684 AP_Scripting: added pcall example
  libraries/AP_Scripting/examples/protected_call.lua
Labels: Scripting

#16695 AC_Fence: emit a FENCE_STATUS message if we newly-breach the fences
  libraries/AC_Fence/AC_Fence.cpp
  libraries/AC_Fence/AC_Fence.h
Labels: DevCallTopic

#16720 Oneshot on IOMCU
  libraries/AP_HAL_ChibiOS/RCOutput.cpp
Labels: AllVehicles, BUG, ChibiOS

#16712 AP_Notify: Change division to multiplication
  libraries/AP_Notify/MMLPlayer.cpp
Labels: DevCallEU

#16727 HAL_ChibiOS: fixed a race and null ptr deref in dshot
  libraries/AP_HAL_ChibiOS/RCOutput.cpp
Labels: BUG, ChibiOS

#16728 Copter: correct metadata for do_change_speed cmd
  ArduCopter/GCS_Mavlink.cpp
Labels: Copter

#16726 HAL_ChibiOS: fixed build of f3 boards without PWM out
  libraries/AP_HAL_ChibiOS/Scheduler.cpp
Labels: AP_Periph, DevCallEU

#16714 GCS_MAVlink: return identical seq in MISSION_CURRENT if possible after set
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: DevCallEU

#16737 AP_Scripting: allow scripting startup with no sdcard
  libraries/AP_Scripting/AP_Scripting.cpp
Labels: BUG, Scripting

#16740 waf: need to crc the padded bootloaders before embedding
  Tools/ardupilotwaf/embed.py
Labels: BUG

#16761 Plane: fixed the pitch control in transition for tilt rotors
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane

#16756 Plane: Quadplane disable forward motor assist in Q modes if rangefind…
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane
