Repository ArduPilot/ardupilot, pull requests merged in 2021-04, with the labels that each got.

#17070 AP_Motors: Constrain get_throttle_hover value with allowed range
  libraries/AP_Motors/AP_MotorsHeli.h
  libraries/AP_Motors/AP_MotorsMulticopter.h
Labels: Copter, DevCallTopic, Safety, TradHeli

#17084 autotest: fix make_safe_filename for Valgrind
  Tools/autotest/pysim/util.py
Labels: MergeOnCIPass

#17085 autotest: increase time permitted for Copte rto turn east
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#17087 autotest: fix mavproxy switch test
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#17086 autotest: correct rc-values-good debug
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17091 Tidy up beastF7 DMA channels
  libraries/AP_HAL_ChibiOS/hwdef/BeastF7/hwdef.dat
Labels: AllVehicles, BUG, ChibiOS, MergeOnCIPass

#14241 autotest: add test for copter position reset
  Tools/autotest/arducopter.py
Labels: NeedAnswer, Tools

#17100 HAL_ChibiOS: fixed ADC error on revXY STM32H7 boards
  libraries/AP_HAL_ChibiOS/AnalogIn.cpp
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
Labels: BUG, ChibiOS

#16648 HAL_ChibiOS: fixed default MSP port for f405-MatekGPS
  libraries/AP_HAL_ChibiOS/hwdef/f405-MatekGPS/hwdef.dat
Labels: AP_Periph

#16906 AP_Proximity: Check for stray faces and add new param for filter cut off freq
  libraries/AP_Proximity/AP_Proximity.cpp
  libraries/AP_Proximity/AP_Proximity.h
  libraries/AP_Proximity/AP_Proximity_Backend.cpp
  libraries/AP_Proximity/AP_Proximity_Backend.h
  libraries/AP_Proximity/AP_Proximity_Boundary_3D.cpp
  libraries/AP_Proximity/AP_Proximity_Boundary_3D.h
Labels: BUG, Driver, Enhancement

#17103 autotest: correct compilation of Replay in autotest suite
  Tools/autotest/autotest.py
  Tools/autotest/pysim/util.py
Labels: MergeOnCIPass

#16405 Copter: move brake state into a structure
  ArduCopter/mode.h
  ArduCopter/mode_poshold.cpp
Labels: Copter

#14265 GCS_MAVLink: make servicing statustext more efficient
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: DevCallTopic

#15607 Navigator led
  libraries/AP_Notify/AP_Notify.cpp
  libraries/AP_Notify/NavigatorLED.cpp
  libraries/AP_Notify/NavigatorLED.h
Labels: DevCallTopic, NeedsTesting, RFC

#16506 ArduCopter: add WoW to Copter landing check
  ArduCopter/land_detector.cpp
Labels: Copter

#17034 AP_Logger: make log file erase async
  libraries/AP_Logger/AP_Logger_File.cpp
  libraries/AP_Logger/AP_Logger_File.h
Labels: DevCallTopic, Logging

#17050 AP_RangeFinder: TeraRangerI2C redefining the output distance logic with OutOfRange cases
  libraries/AP_RangeFinder/AP_RangeFinder_TeraRangerI2C.cpp
Labels: BUG, DevCallTopic, Library

#17052 AP_Notify: UAVCAN_RGB_LED: don't init if no UAVCAN backends
  libraries/AP_Notify/UAVCAN_RGB_LED.cpp
Labels: CAN, DevCallTopic, Enhancement, Library

#17072 SITL: Examples: JSON: MATLAB: add legacy Simulink files for 2018b
  libraries/SITL/examples/JSON/MATLAB/MATLAB 2018b Legacy/AP_Conector.slx
  libraries/SITL/examples/JSON/MATLAB/MATLAB 2018b Legacy/Rover.slx
  libraries/SITL/examples/JSON/MATLAB/MATLAB 2018b Legacy/readme.md
Labels: DevCallTopic

#17107 KakuteF7 bdshot configuration
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7-bdshot/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7-bdshot/hwdef.dat
Labels: AllVehicles, ChibiOS, DevCallTopic

#17031 Plane: Push the TECS to climb in all circumstances
  ArduPlane/ArduPlane.cpp
Labels: BUG, MergeOnCIPass, Plane

#17114 HAL_ChibiOS: fixed DMA sent calculation on UART DMA timeout
  libraries/AP_HAL_ChibiOS/UARTDriver.cpp
Labels: BUG, ChibiOS

#16976 AP_Compass: add memsic MMC5883 driver
  libraries/AP_Compass/AP_Compass.cpp
  libraries/AP_Compass/AP_Compass.h
  libraries/AP_Compass/AP_Compass_Backend.h
  libraries/AP_Compass/AP_Compass_MMC5xx3.cpp
  libraries/AP_Compass/AP_Compass_MMC5xx3.h
Labels: MergeOnCIPass

#16958 AP_HAL_ChibiOS: RCOuput: LED setup re-work
  libraries/AP_HAL_ChibiOS/RCOutput.cpp
  libraries/AP_HAL_ChibiOS/RCOutput.h
Labels: DevCallEU

#17079 Optimize BeastH7 compilation
  libraries/AP_HAL_ChibiOS/hwdef/BeastF7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/BeastH7/hwdef.dat
Labels: AllVehicles, BUG, ChibiOS, DevCallEU

#17109 revo-mini variant with external I2C and respective bdshot
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-i2c-bdshot/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-i2c-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-i2c/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-i2c/hwdef.dat
Labels: AllVehicles, ChibiOS, DevCallEU

#17099 Plane: Quadplane: remove outdated Z controller reset
  ArduPlane/quadplane.cpp
Labels: DevCallEU, VTOL-Plane

#17106 Bi-directional dshot for revo-mini
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-bdshot/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-bdshot/hwdef.dat
Labels: AllVehicles, ChibiOS

#14604 HAL_ChibiOS: add fair scheduling for UARTs
  libraries/AP_HAL_ChibiOS/UARTDriver.cpp
  libraries/AP_HAL_ChibiOS/UARTDriver.h
Labels: ChibiOS

#17119 AP_Scripting: correct rotations in fault tolerant hex example
  libraries/AP_Scripting/examples/MotorMatrix_fault_tolerant_hex.lua
Labels: Scripting

#17122 AC_WPNav: remove unassigned _track_desired
  libraries/AC_WPNav/AC_WPNav.cpp
  libraries/AC_WPNav/AC_WPNav.h
Labels: BUG, Copter

#17124 Rover: 4.1.0-beta1 release notes and version update
  Rover/release-notes.txt
Labels: Rover

#17141 Tools: test mission from Leonards S-curve talk
  Tools/autotest/Generic_Missions/CMAC-copter-navtest.txt
Labels: Copter

#17142 Copter: loiter-turns fix
  ArduCopter/mode_auto.cpp
Labels: BUG, Copter

#17143 autotest: accept Copter/Plane/Sub for sim_vehicle.py
  Tools/autotest/sim_vehicle.py
Labels: MergeOnCIPass

#12430 AP_OSD: improve BLHRPM item readability
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: DevCallTopic, MergeOnCIPass, OSD

#17028 AP_Scripting: add position light example
  libraries/AP_Scripting/examples/LED_poslight.lua
Labels: AllVehicles, DevCallTopic, Scripting

#17130 HAL_ChibiOS: move to single OSD font on some boards
  libraries/AP_HAL_ChibiOS/hwdef/BeastF7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF745/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
Labels: ChibiOS, DevCallTopic

#17118 Plane: tailsitter: transition to and from inverted flight
  ArduPlane/quadplane.cpp
  ArduPlane/tailsitter.cpp
Labels: DevCallTopic, VTOL-Plane

#17154 AC_Precland: remove unused _timestamp_us
  libraries/AC_PrecLand/AC_PrecLand_Companion.cpp
  libraries/AC_PrecLand/AC_PrecLand_Companion.h
Labels: MergeOnCIPass

#17120 AP_OSD: add icon for terrain alt panel and font editor
  libraries/AP_OSD/AP_OSD_Screen.cpp
  libraries/AP_OSD/fonts/MAX7456Charwizard.jar
  libraries/AP_OSD/fonts/README.md
  libraries/AP_OSD/fonts/bfstyle.mcm
  libraries/AP_OSD/fonts/bfstyle.png
  libraries/AP_OSD/fonts/bold.mcm
  libraries/AP_OSD/fonts/bold.png
  libraries/AP_OSD/fonts/clarity.mcm
  libraries/AP_OSD/fonts/clarity.png
  libraries/AP_OSD/fonts/clarity_medium.mcm
  libraries/AP_OSD/fonts/clarity_medium.png
  libraries/AP_OSD/fonts/digital.mcm
  libraries/AP_OSD/fonts/digital.png
  libraries/AP_OSD/fonts/font0.bin
  libraries/AP_OSD/fonts/font1.bin
  libraries/AP_OSD/fonts/font2.bin
  libraries/AP_OSD/fonts/font3.bin
  libraries/AP_OSD/fonts/font4.bin
Labels: AllVehicles, MergeOnCIPass

#17160 Copter: remove unused AP_IRLock include
  ArduCopter/Copter.h
Labels: Copter, MergeOnCIPass

#17171 AP_ExternalAHRS: remove message when EAHRS_TYPE is None
  libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
Labels: DevCallEU

#17168 AP_Filesystem: fixed a read past EOF bug in @PARAM
  libraries/AP_Filesystem/AP_Filesystem_Param.cpp
  libraries/AP_Filesystem/AP_Filesystem_Param.h
Labels: BUG, DevCallEU

#17172 Clean up AC_PrecLand enumerations
  libraries/AC_PrecLand/AC_PrecLand.cpp
  libraries/AC_PrecLand/AC_PrecLand.h
Labels: DevCallEU

#17159 Copter: 4.1.0-beta1 release notes
  ArduCopter/ReleaseNotes.txt
Labels: Copter

#17125 Plane: added FLIGHT_OPTIONS bit to enable yaw control in ACRO mode
  ArduPlane/Attitude.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/defines.h
Labels: Plane, WikiNeeded

#17151 AP_Scripting: add terrain warning example
  libraries/AP_Scripting/examples/terrain_warning.lua
Labels: Scripting

#17178 AP_Logger: raise log_io stack size
  libraries/AP_Logger/AP_Logger.cpp
Labels: BUG

#17189 AP_Periph: fixed DShot in AP_Periph
  Tools/AP_Periph/rc_out.cpp
Labels: AP_Periph, BUG

#17187 HAL_ChibiOS: check bus owner on all SPI transfers
  libraries/AP_HAL_ChibiOS/SPIDevice.cpp
Labels: ChibiOS

#17205 autotest: add a test for button change for changing modes
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17222 AC_AttitudeControl: Fix Angular velocity rotation to body frame
  libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
Labels: MergeOnCIPass

#16849 AP_Proximity: Add a temporary boundary class
  libraries/AP_Proximity/AP_Proximity_AirSimSITL.cpp
  libraries/AP_Proximity/AP_Proximity_AirSimSITL.h
  libraries/AP_Proximity/AP_Proximity_Boundary_3D.cpp
  libraries/AP_Proximity/AP_Proximity_Boundary_3D.h
  libraries/AP_Proximity/AP_Proximity_MAV.cpp
  libraries/AP_Proximity/AP_Proximity_MAV.h
Labels: Driver, Enhancement

#17068 Plane: Surpress speed scaling without AS sensor on auto takeoffs
  ArduPlane/Attitude.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/defines.h
Labels: DevCallTopic

#17185 Copter: attitude target thrust-as-thrust bit moved to GUID_OPTIONS
  ArduCopter/GCS_Mavlink.cpp
  ArduCopter/Parameters.cpp
  ArduCopter/defines.h
  ArduCopter/mode.h
  ArduCopter/mode_guided.cpp
Labels: Copter, DevCallTopic

#17226 Increase stack for smart audio thread
  libraries/AP_VideoTX/AP_SmartAudio.cpp
Labels: AllVehicles, BUG, DevCallTopic

#17202 AP_Compass: fixed the IST8308 on CubeBlack
  libraries/AP_Compass/AP_Compass.cpp
Labels: DevCallTopic

#17217 RC_Channel: correct metadata for fence enable
  libraries/RC_Channel/RC_Channel.cpp
Labels: Docs, MergeOnCIPass, Plane, Rover

#17212 Tools: param_parse: fix vehicle specific parameter with multiple fields
  Tools/autotest/param_metadata/param_parse.py
Labels: Docs, Tools

#17235 Fix build on macOS
  libraries/AP_Filesystem/posix_compat.h
Labels: BUG, DevCallEU, SITL

#17208 AC_Fence: remove alt from TYPE param desc for Rover
  libraries/AC_Fence/AC_Fence.cpp
Labels: Docs

#17238 autotest: sort logs before moving
  Tools/autotest/arducopter.py
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17240 azure: fixed SITL builds
  .azure/autotest_template.yml
  .azure/azure-pipelines.yml
Labels: BuildSystem, SITL

#17247 CI: enable cygwin build in github actions
  .github/workflows/cygwin_build.yml
  Tools/scripts/cygwin_build.sh
Labels: BuildSystem, SITL

#17251 CI: removed azure pipelines
  .azure/azure-pipelines.yml
Labels: BuildSystem, SITL

#17253 waf: removed debug code
  Tools/ardupilotwaf/toolchain.py
Labels: BUG, BuildSystem, MergeOnCIPass

#17271 Tools: added can_sitl.sh to make using SITL with real CAN devices easy
  Tools/scripts/CAN/can_sitl.sh
Labels: CAN, MergeOnCIPass, SITL

#17272 AC_Fence: Correct Rover metadata
  libraries/AC_Fence/AC_Fence.cpp
Labels: DevCallTopic

#17280 AC_WPNav: fix spline initialisation of terrain offset
  libraries/AC_WPNav/AC_WPNav.cpp
Labels: BUG, Copter

#17249 autotest: add a test for Spline missions showing terrain requirement
  Tools/autotest/ArduCopter_Tests/SplineTerrain/wp.txt
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#16757 AC_Circle: Always restore the radius from parameters
  libraries/AC_WPNav/AC_Circle.cpp
  libraries/AC_WPNav/AC_Circle.h
Labels: WikiNeeded

#17295 autotest: shorten statustext message to avoid chunking
  libraries/AC_AutoTune/AC_AutoTune.cpp
Labels: MergeOnCIPass

#17298 RC_Channel: log init_aux_function and read_aux
  libraries/RC_Channel/RC_Channel.cpp
Labels: Library

#17299 Vagrant: add hirsute and hirsute-desktop
  Vagrantfile
Labels: MergeOnCIPass

#17306 AP_Notify: correct parameter documentation
  libraries/AP_Notify/AP_Notify.cpp
Labels: MergeOnCIPass

#17309 HAL_ChibiOS: fixed LED_SAFETY attached to FMU with recent DShot updates
  libraries/AP_HAL_ChibiOS/RCOutput.cpp
Labels: BUG
