Repository ArduPilot/ardupilot, pull requests merged in 2021-03, with the labels that each got.

#16755 AP_Mount: add enable flag on _TYPE
  libraries/AP_Mount/AP_Mount.cpp
Labels: DevCallTopic, Library

#16675 Plane: Quadplane: add Q_OPTION to ignore forward flight angle limits …
  ArduPlane/mode.h
  ArduPlane/mode_qstabilize.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: DevCallTopic, VTOL-Plane

#16777 Tools: Add default parameters for Hexsoon TD-650
  Tools/Frame_params/hexsoon-td650.param
Labels: Copter, Tools

#16781 RC_Channel: use RC channel options 203 and 204 for throttle and yaw
  libraries/RC_Channel/RC_Channel.h
Labels: WikiNeeded

#16708 Remove yaw rate wrapping in guided mode.
  ArduCopter/mode_guided.cpp
Labels: 4.0 Backport, BUG, Copter, DevCallEU

#16789 AP_GPS: Remove unused enum
  libraries/AP_GPS/AP_GPS.h
Labels: GPS

#16790 QuadPlane: fix loiter to RTL instant QRTL switch
  ArduPlane/mode.h
  ArduPlane/mode_rtl.cpp
Labels: BUG, VTOL-Plane

#16785 AP_TECS: Clarify parameter descriptions.
  libraries/AP_TECS/AP_TECS.cpp
Labels: DevCallEU

#16797 autotest: correct units in new AHRS2 test
  Tools/autotest/arduplane.py
Labels: DevCallEU

#15568 AC_Fence: Use int32_t as fence points
  libraries/AC_Fence/AC_PolyFence_loader.cpp
  libraries/AC_Fence/AC_PolyFence_loader.h
Labels: DevCallEU, Enhancement

#16793 AR_AttitudeControl: reset speed filter and I term when stopped
  libraries/APM_Control/AR_AttitudeControl.cpp
Labels: BUG, Rover

#16812 AP_Motors: Battery voltage compensation maximum voltage
  libraries/AP_Motors/AP_MotorsMulticopter.cpp
Labels: AllVehicles, Enhancement

#16836 .github: Disable examples tests
  .github/workflows/test_unit_tests.yml
Labels: BUG, CI, DevCallTopic

#16826 Tools: disable QuadPlane.GyroFFT autotest
  Tools/autotest/quadplane.py
Labels: Tools

#16796 Rover: rename sent_notification to send_notification and fix double notification in Guided
  Rover/mode.h
  Rover/mode_guided.cpp
  Rover/mode_rtl.cpp
Labels: BUG, Rover

#16818 AP_OSD: Add height above terrain panel and warning
  libraries/AP_OSD/AP_OSD.cpp
  libraries/AP_OSD/AP_OSD.h
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: AllVehicles

#16767 Tools:autotest, frsky passthrough fix for long status text message test
  Tools/autotest/common.py
Labels: WIP

#16828 ArduPlane: Correct description of KFF_THR2PTCH parameter.
  ArduPlane/Parameters.cpp
Labels: Docs, Plane

#16894 AP_Notify: Add calibration indications for EKF temp and compass cal t…
  libraries/AP_Notify/RGBLed.cpp
Labels: AllVehicles, DevCallTopic

#16719 Plane: fix DO_CHANGE_SPEED airspeed to only impact AUTO and GUIDED modes
  ArduPlane/AP_Arming.cpp
  ArduPlane/Plane.h
  ArduPlane/commands_logic.cpp
  ArduPlane/mode.cpp
  ArduPlane/mode_guided.cpp
  ArduPlane/navigation.cpp
  ArduPlane/quadplane.cpp
  Tools/autotest/arduplane.py
Labels: DevCallTopic, Plane

#16888 AP_GPS: Supplementary explanation of configuration parameters (NFC)
  libraries/AP_GPS/AP_GPS.cpp
Labels: DevCallTopic, Docs

#16823 Plane: add climb-before-turn on RTL
  ArduPlane/ArduPlane.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/defines.h
  ArduPlane/mode_rtl.cpp
  Tools/autotest/ArduPlane_Tests/ClimbBeforeTurn/flaps.txt
  Tools/autotest/arduplane.py
Labels: DevCallEU, DevCallTopic, Enhancement, Plane, WikiNeeded

#16864 Copter: do-mount-control commands ignored if no mount
  ArduCopter/GCS_Mavlink.cpp
  ArduCopter/mode_auto.cpp
Labels: BUG, Copter

#16853 AP_InertialSensor: fix temperature sensor on LSM9DS0
  libraries/AP_InertialSensor/AP_InertialSensor_LSM9DS0.cpp
Labels: Library

#16900 AP_Mission: avoid potential read of uninitialised memory
  libraries/AP_Mission/AP_Mission.cpp
Labels: BUG, Library

#16862 HAL_ChibiOS: fixed build of f103-trigger fw
  libraries/AP_HAL_ChibiOS/hwdef/f103-Trigger/hwdef.dat
Labels: AP_Periph

#16924 SRV_Channel: fix servo output function documentation typo
  libraries/SRV_Channel/SRV_Channel.cpp
Labels: Docs

#16910 Tools/scripts/build_binaries.py - Add FlywooF745
  Tools/scripts/build_binaries.py
Labels: DevCallEU

#16863 Copter: constrain throttle before setting deadband
  ArduCopter/Attitude.cpp
Labels: Copter, DevCallEU

#16901 Copter: path planning fix when using terrain altitudes
  libraries/AC_WPNav/AC_WPNav_OA.cpp
  libraries/AC_WPNav/AC_WPNav_OA.h
Labels: BUG, Copter

#16893 Allow further LED channels to be allocated at the same length
  libraries/AP_HAL_ChibiOS/RCOutput.cpp
Labels: AllVehicles, BUG, ChibiOS, DevCallEU

#16892 Make sure LEDs get a DMA channel on MatekH743-bdshot
  libraries/AP_HAL_ChibiOS/hwdef/MatekH743-bdshot/hwdef.dat
Labels: AllVehicles, BUG, ChibiOS, DevCallEU

#16152 Tools: add psutil used by kill_tasks_psutil for sim_vehicle.py
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: DevCallEU, DevEnv, Tools

#16928 Tools: param_parse: validate empty description and fields
  Tools/autotest/param_metadata/param_parse.py
Labels: Tools

#16528 Tools: Handle repeated add-param-file arguments to sim_vehicle.py.
  Tools/autotest/sim_vehicle.py
Labels: MergeOnCIPass, Tools

#16410 Tools: make build installation script compatible with most Linux distros - 2
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: DevEnv, MergeOnCIPass

#16784 AP_RangeFinder: increase lightware I2C timeout to 0.2 sec
  libraries/AP_RangeFinder/AP_RangeFinder_LightWareI2C.cpp
Labels: Enhancement

#16933 .semaphore: add base semaphore.yml
  .semaphore/semaphore.yml
Labels: CI, DevCallEU

#16918 autotest: tidy set_parameters
  Tools/autotest/common.py
Labels: Tools

#16934 AP_Mission: Change the description(NFC)
  libraries/AP_Mission/AP_Mission.cpp
Labels: Docs, Library, MergeOnCIPass

#16919 autotest: fix fly_square mission
  Tools/autotest/arducopter.py
Labels: Tools

#16837 Tools: split coverage script for easier update
  Tools/scripts/run-coverage.sh
  Tools/scripts/update-coverage.sh
Labels: Tools

#16914 AP_Periph: Allow skipping the BatteryInfo model_name
  Tools/AP_Periph/can.cpp
Labels: AP_Periph, CAN

#16819 AP_Frsky_Telem: added new "capabilities" param to frame 0x5007
  libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.cpp
  libraries/AP_Frsky_Telem/AP_Frsky_SPort_Passthrough.h
Labels: Library

#16776 Docker: move to ubuntu 20.04 and correct bash-completion support
  Dockerfile
Labels: DevEnv

#16942 Tools>environment_install: install-prereqs-ubuntu
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: DevEnv, MergeOnCIPass

#16932 HAL_ChibiOS: switch boards to 32k FRAM
  libraries/AP_HAL_ChibiOS/hwdef/CubeYellow/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/fmuv5/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/mRoControlZeroClassic/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/mRoControlZeroF7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/mRoControlZeroOEMH7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/mRoX21-777/hwdef.dat
Labels: ChibiOS

#16880 Backport: AP_Proximity: Check for valid reading before pushing to OA DB
  libraries/AP_Proximity/AP_Proximity_Backend.cpp
Labels: 4.0 Backport, BUG, Library

#16960 AP_HAL_ChibiOS: release ICM20649 reserve sensor
  libraries/AP_HAL_ChibiOS/hwdef/QioTekZealotF427/hwdef.dat
Labels: MergeOnCIPass

#16954 Plane: allow max auto pitch in hand launch takeoffs
  ArduPlane/takeoff.cpp
Labels: BUG, DevCallTopic, Plane

#16966 AP_OSD: Add cell voltage and resting voltage displays
  libraries/AP_OSD/AP_OSD.cpp
  libraries/AP_OSD/AP_OSD.h
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: AllVehicles, DevCallTopic

#16841 Plane: tailsitter.input_type bugfix
  ArduPlane/mode_qstabilize.cpp
Labels: BUG, VTOL-Plane

#16865 AP_Scripting: Add proximity status binding
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: DevCallTopic

#16830 AP_OSD: Fix ground and wind speed varying length
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: DevCallTopic, OSD

#16927 Plane: Add VTOL descent rate, convert existing rate to climb rate only
  ArduPlane/qautotune.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: MergeOnCIPass, Plane, WikiNeeded

#16827 AP_NavEKF3: simplify taking of GPS measurements
  libraries/AP_NavEKF3/AP_NavEKF3_Outputs.cpp
Labels: MergeOnCIPass

#16972 autotest: wait longer for prearm failure in IE24 autotest
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#16937 Copter: change description of system id delay variable (NFC)
  ArduCopter/mode_systemid.cpp
Labels: MergeOnCIPass

#16973 AC_Fence: remove unused declaration
  libraries/AC_Fence/AC_PolyFence_loader.h
Labels: MergeOnCIPass

#16833 Plane: make TERRAIN_FOLLOW at APint32 bitmask
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/Plane.h
  ArduPlane/altitude.cpp
Labels: DevCallEU, MergeOnCIPass, Plane, WikiNeeded

#16965 Copter: Added new settings for flight mode channel
  ArduCopter/Parameters.cpp
Labels: Copter, Docs

#16964 Fix occasional problems with SPL06
  libraries/AP_Baro/AP_Baro_SPL06.cpp
Labels: MergeOnCIPass

#16986 Copter: move implementation of get_pilot_desired_yaw_rate into mode.cpp
  ArduCopter/Attitude.cpp
  ArduCopter/Copter.h
  ArduCopter/mode.cpp
  ArduCopter/mode_flowhold.cpp
Labels: MergeOnCIPass

#16750 AP_Logger: OABR correct altitude logging frame and specifier
  libraries/AP_Logger/LogFile.cpp
  libraries/AP_Logger/LogStructure.h
Labels: BUG, Library

#16989 autotest: remove useless mavproxy set heartbeat directive
  Tools/autotest/common.py
Labels: MergeOnCIPass

#16985 autotest: correct pexpect handling of supplementary programs
  Tools/autotest/common.py
Labels: MergeOnCIPass, Tools

#16990 autotest: reduce race condition in fly_square mission
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#16987 Copter: move LAND state variables to be members rather than static
  ArduCopter/mode.h
  ArduCopter/mode_land.cpp
Labels: Copter

#17014 AP_Mission: options parameter description per vehicle
  libraries/AP_Mission/AP_Mission.cpp
Labels: Library

#16975 AP_Airspeed: add support ASP5033 airspeed sensor
  libraries/AP_Airspeed/AP_Airspeed.cpp
  libraries/AP_Airspeed/AP_Airspeed.h
  libraries/AP_Airspeed/AP_Airspeed_ASP5033.cpp
  libraries/AP_Airspeed/AP_Airspeed_ASP5033.h
Labels: NeedsTesting, Plane

#16977 Plane: add option to do a VTOL approach RTL
  ArduPlane/Plane.h
  ArduPlane/commands_logic.cpp
  ArduPlane/mode_rtl.cpp
  ArduPlane/navigation.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: DevCallTopic, VTOL-Plane, WikiNeeded

#17032 HAL_ChibiOS: fixed 2nd CAN inferface on F4/F7
  libraries/AP_HAL_ChibiOS/CanIface.cpp
Labels: BUG, CAN

#17024 AP_BattMonitor: Fix nullptr deref when resetting a battery
  libraries/AP_BattMonitor/AP_BattMonitor.cpp
Labels: BUG, DevCallTopic, Library

#16971 Plane: VTOL: remove motors config error
  ArduPlane/quadplane.cpp
Labels: DevCallTopic, VTOL-Plane

#17004 waf: set NDEBUG define to avoid assert issues
  Tools/ardupilotwaf/boards.py
Labels: AllVehicles, ChibiOS, DevCallTopic

#17035 AP_Notify: Remove indirection on RGBLed of init()->hw_init()
  libraries/AP_Notify/DiscoLED.cpp
  libraries/AP_Notify/DiscoLED.h
  libraries/AP_Notify/DiscreteRGBLed.cpp
  libraries/AP_Notify/DiscreteRGBLed.h
  libraries/AP_Notify/Led_Sysfs.cpp
  libraries/AP_Notify/Led_Sysfs.h
  libraries/AP_Notify/NCP5623.cpp
  libraries/AP_Notify/NCP5623.h
  libraries/AP_Notify/PCA9685LED_I2C.cpp
  libraries/AP_Notify/PCA9685LED_I2C.h
  libraries/AP_Notify/PixRacerLED.cpp
  libraries/AP_Notify/PixRacerLED.h
  libraries/AP_Notify/RCOutputRGBLed.cpp
  libraries/AP_Notify/RCOutputRGBLed.h
  libraries/AP_Notify/RGBLed.cpp
  libraries/AP_Notify/RGBLed.h
  libraries/AP_Notify/SITL_SFML_LED.cpp
  libraries/AP_Notify/SITL_SFML_LED.h
  libraries/AP_Notify/ScriptingLED.h
  libraries/AP_Notify/SerialLED.cpp
  libraries/AP_Notify/SerialLED.h
  libraries/AP_Notify/ToshibaLED_I2C.cpp
  libraries/AP_Notify/ToshibaLED_I2C.h
  libraries/AP_Notify/UAVCAN_RGB_LED.cpp
  libraries/AP_Notify/UAVCAN_RGB_LED.h
  libraries/AP_Notify/VRBoard_LED.cpp
  libraries/AP_Notify/VRBoard_LED.h
Labels: DevCallTopic, Library

#17008 Copter: make AutoTune object private state to ModeAutoTune
  ArduCopter/Copter.h
  ArduCopter/Parameters.cpp
  ArduCopter/mode.h
  ArduCopter/mode_autotune.cpp
Labels: Copter

#17041 HAL_ChibiOS: fixed skyviper builds with BMM150
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-f412-rev1/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-journey/hwdef.dat
Labels: ChibiOS, MergeOnCIPass

#17009 Copter: factor out a mode-change-failed method
  ArduCopter/Copter.h
  ArduCopter/mode.cpp
Labels: Copter, MergeOnCIPass

#16988 AP_EFI: use enum class for protocol
  libraries/AP_EFI/AP_EFI.cpp
  libraries/AP_EFI/AP_EFI.h
Labels: MergeOnCIPass

#17054 AP_Baro: work around bad WHOAMI read on DPS310
  libraries/AP_Baro/AP_Baro_DPS280.cpp
Labels: ChibiOS

#17057 autotest: fix --map option
  Tools/autotest/common.py
Labels: MergeOnCIPass

#17056 typo
  Rover/sailboat.cpp
Labels: MergeOnCIPass

#16527 SITL: Add parsing of airspeed to SIM_JSON
  libraries/SITL/SIM_JSON.cpp
  libraries/SITL/SIM_JSON.h
  libraries/SITL/examples/JSON/readme.md
Labels: DevCallEU
