Repository ArduPilot/ardupilot, pull requests merged in 2021-11, with the labels that each got.

#19096 HAL_ChibiOS: fixed build for EMPTY uarts
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: MergeOnCIPass

#19090 AP_Logger: avoid all opens of log files in main thread
  libraries/AP_Logger/AP_Logger_File.cpp
Labels: BUG, Logging

#18935 AP_CRSF_Telem: optimize flight mode and status text frames
  libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
Labels: MergeOnCIPass

#19084 AP_Param: eedump_apparam match Param_header and sentinals to AP_Param.h
  libraries/AP_Param/tools/eedump_apparam.c
Labels: MergeOnCIPass

#19099 SITL: cope with fewer than three INS_MAX_INSTANCEs
  libraries/SITL/SITL.cpp
Labels: MergeOnCIPass

#19095 autotest: FETtec tests: give vehicle a chance to realise ESCs are dead
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#19098 SITL: make ToshibaLED simulator optional
  libraries/SITL/SIM_I2C.cpp
  libraries/SITL/SIM_ToshibaLED.cpp
  libraries/SITL/SIM_ToshibaLED.h
Labels: SITL

#18994 AP_Param: Class Conversion Function
  libraries/AP_Param/AP_Param.cpp
  libraries/AP_Param/AP_Param.h
Labels: DevCallTopic

#18959 DevEnv: Add C++ and Lua recommended extensions for VSCode
  .vscode/extensions.json
  .vscode/settings.json
Labels: DevCallTopic

#19035 AP_Beacon: have nooploop use base-class uart instance
  libraries/AP_Beacon/AP_Beacon_Nooploop.cpp
  libraries/AP_Beacon/AP_Beacon_Nooploop.h
Labels: NeedsTesting

#19109 git: changed submodule protocols to https://
  .gitmodules
Labels: CI, MergeOnCIPass

#19120 AP_Motors: remove throttle roll adjust for single motor tailsitter
  libraries/AP_Motors/AP_MotorsTailsitter.cpp
Labels: Plane, VTOL-Plane, DevCallEU

#19125 Plane: use enum class for StickMixing
  ArduPlane/Attitude.cpp
  ArduPlane/GCS_Mavlink.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/defines.h
  ArduPlane/quadplane.cpp
Labels: DevCallEU

#19069 AP_SerialManager: fix ESC telem baud rate so that it is consistent with other protocols baud forcing
  libraries/AP_SerialManager/AP_SerialManager.cpp
Labels: MergeOnCIPass

#13622 AP_AHRS: relax arming checks for inactive AHRS types
  libraries/AP_AHRS/AP_AHRS.cpp
Labels: Library, AllVehicles, MergeOnCIPass

#19143 Copter: change the default of zigzag wp delay to 0
  ArduCopter/mode_zigzag.cpp
Labels: Copter, MergeOnCIPass

#19140 autotest: fix race condition in Rover gcs mission test
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#18973 Sim vehicle single mavproxy
  Tools/autotest/sim_vehicle.py
Labels: MergeOnCIPass

#19001 GCS_MAVLink: add board ID to AUTOPILOT_VERSION mavlink msg
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#19150 Tools: DeSET mapping boat default parameters
  Tools/Frame_params/deset-mapping-boat.param
Labels: Tools

#19170 .github: install anytree along with elf_diff
  .github/workflows/test_size.yml
Labels: MergeOnCIPass

#19169 Plane: fixed a bug in POSITION1 speed thresholds (for plane 4.1)
  ArduPlane/quadplane.cpp
Labels: BUG, VTOL-Plane

#19168 Plane: fixed a bug in POSITION1 speed thresholds
  ArduPlane/quadplane.cpp
Labels: BUG, VTOL-Plane, MergeOnCIPass

#19176 Plane: default rate max to 75 for quadplane VTOL
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane

#19173 AP_Scripting: Docs: document arguments names
  libraries/AP_Scripting/docs/docs.lua
Labels: Scripting

#19177 autotest: read pexpects while waiting for sim time
  Tools/autotest/common.py
Labels: MergeOnCIPass

#19121 AP_NavEKF3: fixed switch to non-zero primary on disarm
  libraries/AP_NavEKF3/AP_NavEKF3.cpp
Labels: BUG, EKF

#19141 AP_InertialSensor: fixed comments on IMU types supported
  libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_Invensensev2.cpp
Labels: Docs

#17744 AP_GPS: Novatel enhancements
  libraries/AP_GPS/AP_GPS_NOVA.cpp
Labels: GPS, DevCallTopic

#19130 AP_Logger: tidy construction of backends
  libraries/AP_Logger/AP_Logger.cpp
  libraries/AP_Logger/AP_Logger_DataFlash.h
  libraries/AP_Logger/AP_Logger_File.cpp
  libraries/AP_Logger/AP_Logger_File.h
  libraries/AP_Logger/AP_Logger_MAVLink.h
  libraries/AP_Logger/AP_Logger_SITL.h
Labels: DevCallTopic

#19137 Plane: support send_extended_sys_state
  ArduPlane/GCS_Mavlink.cpp
  ArduPlane/GCS_Mavlink.h
  ArduPlane/quadplane.cpp
  ArduPlane/tailsitter.cpp
  ArduPlane/tailsitter.h
  ArduPlane/transition.h
Labels: VTOL-Plane

#19152 AP_GPS_UBLOX: tidy reading of uart data
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
Labels: GPS, DevCallTopic

#19178 Plane: move quadplane arming checks to own function and add angle max…
  ArduPlane/AP_Arming.cpp
  ArduPlane/AP_Arming.h
Labels: VTOL-Plane, DevCallTopic

#19179 Plane: tiltrotor: allow tilt wing as flap
  ArduPlane/tiltrotor.cpp
  ArduPlane/tiltrotor.h
Labels: VTOL-Plane, DevCallTopic, WikiNeeded

#19200 AP_Landing: Fix slope calculation.
  libraries/AP_Landing/AP_Landing_Slope.cpp
Labels: Plane

#19185 AP_RCProtocol: remove pointless 100kbaud speed change
  libraries/AP_RCProtocol/AP_RCProtocol.cpp
Labels: DevCallEU

#19145 added my locations to locations.txt
  Tools/autotest/locations.txt
Labels: MergeOnCIPass

#19196 GCS_MAVLINK: fixed build of boards with APJ_BOARD_ID>32768
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: BUG, MergeOnCIPass

#19134 AP_Compass: never override custom orientation in calibration
  libraries/AP_Compass/AP_Compass_Calibration.cpp
  libraries/AP_Compass/CompassCalibrator.cpp
  libraries/AP_Compass/CompassCalibrator.h
Labels: BUG

#19202 AP_Motors: Coax: remove servo outputs from motors mask, correct array indexing
  libraries/AP_Motors/AP_MotorsCoax.cpp
Labels: Copter

#19082 StorageManager: fix storage manager counts and merge common areas
  libraries/StorageManager/StorageManager.cpp
  libraries/StorageManager/StorageManager.h
Labels: BUG, Library, NeedsTesting

#19206 AC_AttitudeControl: adjust docs for rate max limits
  libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
Labels: Copter, MergeOnCIPass

#19211 autotest: turn drain mav off when doing early-exit for being quiet
  Tools/autotest/common.py
Labels: MergeOnCIPass

#19210 AP_FETtecOneWire: reset buf_used
  libraries/AP_FETtecOneWire/AP_FETtecOneWire.cpp
Labels: Enhancement, AllVehicles, Driver

#19073 hwdef: added alternative Durandal 20602 IMU
  libraries/AP_HAL_ChibiOS/hwdef/Durandal/hwdef.dat
Labels: NeedsTesting, hwdef

#19223 Copter: add warning that heli's stabilize init code isn't run at vehicle startup
  ArduCopter/mode_stabilize_heli.cpp
Labels: TradHeli, MergeOnCIPass

#19228 SITL: quieten MKFIFO warning in case of EEXIST
  libraries/SITL/SIM_GPS.cpp
  libraries/SITL/SIM_GPS.h
Labels: SITL

#19229 AP_HAL_SITL: quieten i2c-device-creation diagnostics
  libraries/AP_HAL_SITL/I2CDevice.cpp
Labels: SITL

#18940 AP_UAVCAN: hide -Wcast-function-type warning on GCC11
  libraries/AP_UAVCAN/AP_UAVCAN.h
Labels: CAN, MergeOnCIPass

#19217 Tools: autotest: add test for QuadPlane transition states
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#19263 AP_BattMonitor: remove old parameter conversion to allow setting BATT_MONITOR to 0
  libraries/AP_BattMonitor/AP_BattMonitor.cpp
  libraries/AP_BattMonitor/AP_BattMonitor.h
Labels: DevCallTopic

#19269 Tools: reserve board id for sierra-F405
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#19250 WEBOTS_SITL: adjust_params model
  libraries/SITL/SIM_Webots.cpp
  libraries/SITL/examples/Webots/controllers/ardupilot_SITL_QUAD/ardupilot_SITL_QUAD.c
  libraries/SITL/examples/Webots/controllers/ardupilot_SITL_QUAD/ardupilot_SITL_QUAD.h
  libraries/SITL/examples/Webots/quadPlus.parm
  libraries/SITL/examples/Webots/quadPlus2.parm
  libraries/SITL/examples/Webots/quadX.parm
  libraries/SITL/examples/Webots/quadX2.parm
  libraries/SITL/examples/Webots/worlds/pyramidMap.wbt
  libraries/SITL/examples/Webots/worlds/pyramidMap_two_quads.wbt
  libraries/SITL/examples/Webots/worlds/webots_quadPlus.wbt
  libraries/SITL/examples/Webots/worlds/webots_quadX.wbt
  libraries/SITL/examples/Webots/worlds/webots_tricopter.wbt
  libraries/SITL/examples/Webots/worlds/webots_two_quadX.wbt
Labels: MergeOnCIPass

#18820 AC_Avoid: Convert Dijkstras to A-star
  libraries/AC_Avoidance/AP_OADijkstra.cpp
  libraries/AC_Avoidance/AP_OADijkstra.h
Labels: Enhancement, Copter, Rover, Library

#19221 AP_RCProtocol: Use a data structure to hold serial configurations for auto-detection
  libraries/AP_RCProtocol/AP_RCProtocol.cpp
  libraries/AP_RCProtocol/AP_RCProtocol.h
Labels: MergeOnCIPass

#19273 Rover: fix NTUN.yaw units
  Rover/Log.cpp
Labels: BUG, Rover, Logging

#19207 Copter: surface tracking timeout fix
  ArduCopter/Copter.h
  ArduCopter/surface_tracking.cpp
Labels: BUG, Copter

#18857 AP_Camera: stash information required for camera_feedback message
  libraries/AP_Camera/AP_Camera.cpp
  libraries/AP_Camera/AP_Camera.h
Labels: DevCallEU

#19231 AP_BattMonitor: added VLT_OFFSET for analog
  libraries/AP_BattMonitor/AP_BattMonitor_Analog.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_Analog.h
Labels: DevCallEU

#19136 Plane: quadplane: limit pitch for all transitions into position control modes
  ArduPlane/mode_qloiter.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
  ArduPlane/transition.h
Labels: VTOL-Plane, WikiNeeded, DevCallEU

#19240 Plane: fix bug causing wrong thr max and slew to be used during takeoff
  ArduPlane/ArduPlane.cpp
Labels: BUG, Plane, Safety, DevCallEU

#19195 hwdef: change MatekH743 to -Os
  libraries/AP_HAL_ChibiOS/hwdef/MatekH743/hwdef.dat
Labels: hwdef

#19257 Plane: suppress spurious EKF yaw reset message
  ArduPlane/quadplane.cpp
Labels: EKF

#19246 Allow notch update to be configurable
  libraries/AP_Vehicle/AP_Vehicle.cpp
Labels: BUG, AllVehicles, MergeOnCIPass

#19191 AP_RangeFinder_LightWareSerial: handle LightWare lost signal flag output
  libraries/AP_RangeFinder/AP_RangeFinder_LightWareSerial.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_LightWareSerial.h
Labels: BUG, Enhancement, Driver

#19282 Plane: fixed chute release on low value of RC option
  ArduPlane/RC_Channel.cpp
Labels: BUG

#19281 AP_Parachute: added arming check for chute released
  libraries/AP_Parachute/AP_Parachute.cpp
Labels: BUG

#19253 AP_Notify: make the buzzer pin configurable on all boards
  libraries/AP_Notify/AP_Notify.cpp
  libraries/AP_Notify/Buzzer.cpp
Labels: WikiNeeded

#19290 AP_InertialSensor: change VIBE logging units to m/s/s
  libraries/AP_InertialSensor/LogStructure.h
Labels: Logging, MergeOnCIPass

#19159 AP_RCProtocol: add support for DJI Fast SBUS
  libraries/AP_RCProtocol/AP_RCProtocol.cpp
  libraries/AP_RCProtocol/AP_RCProtocol.h
  libraries/AP_RCProtocol/AP_RCProtocol_SBUS.cpp
  libraries/AP_RCProtocol/AP_RCProtocol_SBUS.h
  libraries/AP_RCProtocol/SoftSerial.h
  libraries/RC_Channel/RC_Channels_VarInfo.h
Labels: MergeOnCIPass

#19309 Tools: fixed cygwin build for rover
  Tools/scripts/cygwin_build.sh
Labels: Rover, CI

#19299 autotest: fix MSP_DJI test for Py2
  Tools/autotest/common.py
Labels: MergeOnCIPass

#19304 Tools: sim_vehicle supports motorboat frame
  Tools/autotest/default_params/motorboat.parm
  Tools/autotest/pysim/vehicleinfo.py
Labels: Enhancement, SITL

#19291 AP_HAL_ChibiOS: remove unused pin-related defines
  libraries/AP_HAL_ChibiOS/GPIO.cpp
Labels: DevCallTopic

#19313 Plane: quadplane: log position controller PIDs
  ArduPlane/Log.cpp
Labels: VTOL-Plane

#19293 Plane: fixed variable name
  ArduPlane/quadplane.cpp
Labels: Plane, MergeOnCIPass

#19279 RC_Channel: added parachute for plane
  libraries/RC_Channel/RC_Channel.cpp
Labels: Docs

#19332 AP_Param: simplify set_defaults_from_table error path
  libraries/AP_Param/AP_Param.cpp
Labels: DevCallTopic

#19298 AP_Mission: PLANE to refuse NAV_SPLINE_WAYPOINT missions items
  libraries/AP_Mission/AP_Mission.cpp
Labels: Plane, VTOL-Plane, DevCallTopic

#19330 AP_Boardconfig: correct va_list memory over-read error
  libraries/AP_BoardConfig/AP_BoardConfig.cpp
Labels: DevCallTopic

#19339 autotest: fetch tasks.txt twice
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#19340 AC_AttitudeControl: fixed limiting of throttle mix values
  libraries/AC_AttitudeControl/AC_AttitudeControl.h
  libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp
  libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.cpp
Labels: Copter, VTOL-Plane, DevCallEU, MergeOnCIPass

#19343 AP_Airspeed: add date for parameter conversion code
  libraries/AP_Airspeed/AP_Airspeed.cpp
Labels: Library

#19336 Plane: limiting POS1 landing target speed
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: VTOL-Plane, DevCallEU

#19347 Copter: clarify SIMPLE and SUPER_SIMPLE bitmask usage
  ArduCopter/Parameters.cpp
Labels: Docs

#19349 AP_AHRS: fixed switching airspeed sensor based on EKF3 affinity
  libraries/AP_AHRS/AP_AHRS.cpp
Labels: BUG, EKF, MergeOnCIPass

#19203 solution to TECS height rate demand spikes due to setting target altitude to soon
  ArduPlane/commands.cpp
Labels: Plane, DevCallEU

#19215 autotest: Fix rangefinder in Landing-Drift test.
  Tools/autotest/arduplane.py
Labels: Plane, CI, DevCallEU

#19355 hwdef: remove unused define NO_DATAFLASH
  libraries/AP_HAL_ChibiOS/hwdef/BirdCANdy/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CUAV_GPS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CubeBlack-periph/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-periph-heavy/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-periph/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/G4-ESC/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/H757I_EVAL/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/H757I_EVAL_intf/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Hitec-Airspeed/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/HitecMosaic/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/HolybroGPS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekH743-periph/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Nucleo-G491/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Nucleo-L476/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Nucleo-L496/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Pixracer-periph/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-L431/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/ZubaxGNSS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/f103-periph/hwdef.inc
  libraries/AP_HAL_ChibiOS/hwdef/f303-MatekGPS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/f303-periph/hwdef.inc
  libraries/AP_HAL_ChibiOS/hwdef/f405-MatekGPS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/mRo-M10095/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: DevCallEU

#19335 Plane: limited VFWD integrator to cruise throttle
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, DevCallEU

#19350 AP_AHRS: fixed switching airspeed sensor based on EKF3 (for 4.1)
  libraries/AP_AHRS/AP_AHRS_NavEKF.cpp
Labels: BUG, EKF

#19262 AP_TECS: Height Demand model limiting based on command saturation.
  libraries/AP_TECS/AP_TECS.cpp
  libraries/AP_TECS/AP_TECS.h
Labels: NeedsTesting

#19363 waf: only enable `-Wsizeof-pointer-div` for gcc v8.4 or greater
  Tools/ardupilotwaf/boards.py
Labels: BuildSystem, DevCallTopic

#19366 SITL: reduce SLV2 logger message size
  libraries/SITL/SIM_JSON_Master.cpp
Labels: MergeOnCIPass

#19357 hwdef: remove unused HAL_NO_GCS defines
  libraries/AP_HAL_ChibiOS/hwdef/Nucleo-L476/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Nucleo-L496/hwdef.dat
Labels: MergeOnCIPass

#19384 Tradheli: make bailout in SITL only enabled with AROT_ENABLE
  ArduCopter/heli.cpp
Labels: TradHeli

#19391 autotest: add --callgrind option
  Tools/autotest/autotest.py
  Tools/autotest/common.py
  Tools/autotest/pysim/util.py
Labels: DevCallTopic

#19031 AP_Rangefinder: Use default address for TFMiniPlus I2C unless specified
  libraries/AP_RangeFinder/AP_RangeFinder.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake_TFMini.h
Labels: DevCallTopic

#19387 AP_Terrain: cast result of labs to unsigned
  libraries/AP_Terrain/AP_Terrain.h
Labels: DevCallTopic

#19359 APM_Control: make 2nd reduction of P smaller
  libraries/APM_Control/AP_AutoTune.cpp
Labels: Plane, DevCallTopic

#19393 SRV_Channel: correct casting of servo function number
  libraries/SRV_Channel/SRV_Channel_aux.cpp
Labels: DevCallTopic

#19394 AP_Math: memcpy nanfs rather than iteratively setting them
  libraries/AP_Math/AP_Math.cpp
Labels: DevCallTopic

#19375 updated vagrant file to not start bionic64 desktop by default
  Vagrantfile
Labels: MergeOnCIPass
