Repository ArduPilot/ardupilot, pull requests merged in 2022-01, with the labels that each got.

#19647 Tools: SITL Copter-heli.parm remove WP_YAW_BEHAVIOR
  Tools/autotest/default_params/copter-heli.parm
Labels: TradHeli, SITL

#19653 Plane: fix stabilize mode
  ArduPlane/mode_stabilize.cpp
Labels: BUG

#19605 Blimp: remove pilot_throttle_checks()
  Blimp/AP_Arming.cpp
  Blimp/AP_Arming.h
Labels: Blimp

#19651 Tool: ardupilotwaf fix duplicate reporting from build summary
  Tools/ardupilotwaf/ardupilotwaf.py
Labels: BuildSystem

#18946 Correct division-by-zero in Copter compassmot
  ArduCopter/compassmot.cpp
Labels: DevCallTopic

#19592 Copter: Guided: When yaw is not specified use default yaw behaviour.
  ArduCopter/mode_guided.cpp
Labels: Copter, DevCallTopic

#19634 hwdef: set AP_OPTICALFLOW_ENABLED 0 for SkyViper-v2450
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
Labels: DevCallTopic

#19656 AP_GPS: drop default GPS lag to 0.1s
  libraries/AP_GPS/AP_GPS.cpp
Labels: GPS, DevCallTopic

#19652 AP_Scripting: generator: use depends for singleton strings
  libraries/AP_Scripting/generator/src/main.c
Labels: DevCallTopic, Scripting

#19654 autotest: add methods for asserting received mavlink data
  Tools/autotest/common.py
Labels: MergeOnCIPass

#19657 AP_Logger: quick fixes
  libraries/AP_Logger/AP_Logger_MAVLink.cpp
Labels: Logging

#19675 Revert "AP_GPS: drop default GPS lag to 0.1s"
  libraries/AP_GPS/AP_GPS.cpp
Labels: MergeOnCIPass

#19643 AP_HAL_ChibiOS: change defaults in hwdef for Sierra-Periph
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-F405/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-F412/defaults.parm
Labels: MergeOnCIPass, hwdef

#19669 Copter: compassmot: use is_positive for float comparison
  ArduCopter/compassmot.cpp
Labels: MergeOnCIPass

#19663 RC_Channel: fix typo
  libraries/RC_Channel/RC_Channel.cpp
Labels: Library, Docs, MergeOnCIPass

#19662 AP_Logger: fix memory leak
  libraries/AP_Logger/AP_Logger.cpp
Labels: BUG

#19671 Tools: Add css formatting and red colour
  Tools/scripts/build_sizes.py
  Tools/scripts/build_sizes/filtertable.js
  Tools/scripts/build_sizes/sorttable.js
Labels: DevCallEU

#19667 Tools: add script returning build options
  Tools/scripts/build_options.py
Labels: DevCallEU

#19678 AP_NavEKF2: don't include log structures if not enabled
  libraries/AP_NavEKF2/LogStructure.h
Labels: DevCallEU

#19686 RC_Channel: fix typo, again
  libraries/RC_Channel/RC_Channel.cpp
Labels: MergeOnCIPass

#19695 AP_OpticalFlow: remove un-needed forward AP_AHRS declaration
  libraries/AP_OpticalFlow/AP_OpticalFlow.h
Labels: MergeOnCIPass

#19685 GCS_MAVLink: make send_system_time const
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#19680 Corrected pincount values for J and K
  libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32F777xx.py
Labels: MergeOnCIPass

#19683 Tools: Auto-build blimp firmwares
  Tools/scripts/build_binaries.py
Labels: MergeOnCIPass, Blimp

#19700 hwdef: CUAV-Nora: Add servo voltage detection pin
  libraries/AP_HAL_ChibiOS/hwdef/CUAV-Nora/hwdef.dat
Labels: MergeOnCIPass

#19674 Autotest: Copter test fix for tri frame
  Tools/autotest/arducopter.py
  Tools/autotest/default_params/copter-tri.parm
Labels: MergeOnCIPass

#19711 autotest: fix rover POSITION_TARGET_LOCAL test
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#19713 Tools: use define for define rather than default...
  Tools/scripts/build_options.py
Labels: DevCallTopic, NeedsTesting

#19722 autotest: loosen position constraint on SET_POSITION_TARGET_LOCAL_NED…
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#19693 Tools: add blue and bbbmini to firmware server
  Tools/scripts/board_list.py
Labels: Tools

#19744 autotest: build-with-disabled-features.py: flake8-clean
  Tools/autotest/build-with-disabled-features.py
Labels: MergeOnCIPass

#19748 AP_Param: fix convert_class when index is 0
  libraries/AP_Param/AP_Param.cpp
Labels: BUG, MergeOnCIPass

#19530 AP_HAL_Linux: RPI-CM4 detection
  libraries/AP_HAL_Linux/Util_RPI.cpp
Labels: BUG, Linux

#19648 AC_PosControl: Clean up initialisation functions and limit initial xy accelerations based on max lean angle
  libraries/AC_AttitudeControl/AC_PosControl.cpp
  libraries/AC_AttitudeControl/AC_PosControl.h
Labels: BUG, Copter, VTOL-Plane, DevCallTopic

#19664 Plane: quadplane: add transition failure action
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: VTOL-Plane, DevCallTopic

#19690 Tools: add more categories and reorganize a bit
  Tools/scripts/build_options.py
Labels: Enhancement, BuildSystem, DevCallTopic

#19745 autotest: add test_build_options to test each entry in build_options.py
  Tools/autotest/pysim/util.py
  Tools/autotest/test_build_options.py
Labels: DevCallTopic

#19734 AP_HAL_ChibiOS: save flash on the BeastF7v2
  libraries/AP_HAL_ChibiOS/hwdef/BeastF7v2/hwdef.dat
Labels: DevCallTopic

#19679 AP_NavEKF3: remove user unintelligible GCS message
  libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
Labels: DevCallEU

#19760 AP_SerialManager: add metadata for merged new protocols
  libraries/AP_SerialManager/AP_SerialManager.cpp
Labels: Docs, MergeOnCIPass

#19755 AP_Logger: fix _RATEMAX parameter descriptions
  libraries/AP_Logger/AP_Logger.cpp
Labels: Logging, Docs

#19754 Fix UART operation on original OmnibusNanoV6
  libraries/AP_HAL_ChibiOS/hwdef/OmnibusNanoV6/hwdef.dat
Labels: BUG, AllVehicles, DevCallEU

#19737 Tools: logger metadata: emit rst description on new line
  Tools/autotest/logger_metadata/emit_rst.py
Labels: DevCallEU

#19751 ArduPlane: fix man_expo pitch & rudder params/variables
  ArduPlane/radio.cpp
Labels: BUG, Plane, DevCallEU

#19726 AP_GPS: tidy configuration of UBLOX rates
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
  libraries/AP_GPS/AP_GPS_UBLOX.h
Labels: DevCallTopic, DevCallEU

#19730 .github: add size-test targets to f103-GPS and Hitec-Airspeed
  .github/workflows/test_size.yml
Labels: MergeOnCIPass

#19752 build_options.py: remove HAL_MPPT_PACKETDIGITAL_CAN_ENABLE
  Tools/scripts/build_options.py
Labels: MergeOnCIPass

#19769 hwdef: fixed flash double reserve
  libraries/AP_HAL_ChibiOS/hwdef/BeastH7/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/BeastH7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekH743/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekH743/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/ZubaxGNSS/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/ZubaxGNSS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/mindpx-v2/hwdef.dat
Labels: BUG, MergeOnCIPass

#19767 build_options.py: correct GPS Drivers section
  Tools/scripts/build_options.py
Labels: MergeOnCIPass

#19776 board_list.py: tidy
  Tools/scripts/board_list.py
Labels: MergeOnCIPass

#19459 AP_Scripting: add example of arming check for wp index = 1 and is a takeoff
  libraries/AP_Scripting/examples/arming-check-wp1-takeoff.lua
Labels: Scripting

#19788 ArduSub: Fix build with RPM_ENABLED
  ArduSub/ArduSub.cpp
Labels: BUG, Sub

#19771 autotest : correct in typos line 8549 Receving -> Receiving
  Tools/autotest/common.py
Labels: Tools, MergeOnCIPass

#19793 Tools: added name to GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#19807 AP_Compass: add and use AP_SIM_COMPASS_ENABLED
  libraries/AP_Compass/AP_Compass.cpp
  libraries/AP_Compass/AP_Compass.h
  libraries/AP_Compass/AP_Compass_SITL.cpp
  libraries/AP_Compass/AP_Compass_SITL.h
Labels: MergeOnCIPass

#19795 AP_AHRS: create and use AP_AHRS_SIM_ENABLED
  libraries/AP_AHRS/AP_AHRS.cpp
  libraries/AP_AHRS/AP_AHRS.h
Labels: MergeOnCIPass

#19799 AP_InertialSensor: add and use AP_SIM_INS_ENABLED
  libraries/AP_InertialSensor/AP_InertialSensor.cpp
  libraries/AP_InertialSensor/AP_InertialSensor.h
  libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_SITL.h
Labels: MergeOnCIPass

#19772 AP_Hal_Linux: PCA9685: do not shutdown
  libraries/AP_HAL_Linux/RCOutput_PCA9685.cpp
Labels: BUG, Linux

#19778 AP_RangFinder: support various maxbotix serial sonar
  libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarSerialLV.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarSerialLV.h
  libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
Labels: DevCallTopic

#19780 AP_HAL_ChibiOS: disable UART stats based on GCS being enabled
  libraries/AP_HAL_ChibiOS/hwdef/Hitec-Airspeed/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: DevCallTopic

#19785 RC_Channel: make AUXF.function an instance
  libraries/RC_Channel/RC_Channel.cpp
Labels: DevCallTopic

#19812 AP_Compass: only magcal detected compasses
  libraries/AP_Compass/AP_Compass_Calibration.cpp
Labels: BUG, Compass

#19773 Plane: use EKF climb rate estimate in VFR_HUD.climb
  ArduPlane/GCS_Mavlink.cpp
Labels: Plane, MergeOnCIPass

#19840 HAL_SITL: fixed mapping of --serial ports in SITL
  libraries/AP_HAL_SITL/SITL_cmdline.cpp
Labels: BUG

#19863 AP_OpticalFlow: tighten scope on variables
  libraries/AP_OpticalFlow/AP_OpticalFlow_Pixart.cpp
Labels: MergeOnCIPass

#19834 AP_Param: Change from a direct value to a defined name
  libraries/AP_Param/AP_Param.cpp
Labels: DevCallTopic

#19862 AC_PosControl: Initialise desired accel to zero
  libraries/AC_AttitudeControl/AC_PosControl.cpp
Labels: BUG, Copter, DevCallTopic, 4.0 Backport

#19870 AP_Bootloader: fixed ID conflict
  Tools/AP_Bootloader/board_types.txt
Labels: AP_Periph

#19872 AP_BattMonitor: UAVCAN switch to CURR_MULT
  libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.h
Labels: Library

#19876 Copter: improve PILOT_SPEED_DN param description
  ArduCopter/Parameters.cpp
Labels: Copter

#19867 Tools: add quick-and-dirty EKF-status-change dump tool
  Tools/scripts/solution_status_change.py
Labels: DevCallEU

#19857 Plane: tailsitter: rate limit second half of FW transition
  ArduPlane/tailsitter.cpp
  ArduPlane/tailsitter.h
Labels: VTOL-Plane, DevCallEU

#19881 Copter: fix sanity checks for takeoff altitude
  ArduCopter/mode_auto.cpp
Labels: BUG, Copter

#19893 Tools: improve tradheli sitl default params
  Tools/autotest/default_params/copter-heli.parm
Labels: MergeOnCIPass

#19277 AIRLink: added default parameters files
  libraries/AP_HAL_ChibiOS/hwdef/AIRLink/defaults.parm
Labels: ChibiOS, MergeOnCIPass, Partner

#19890 Copter: add flight option to release gripper on thrust loss
  ArduCopter/Copter.h
  ArduCopter/Parameters.cpp
  ArduCopter/crash_check.cpp
Labels: Copter

#19861 hwdef: fixed VCC monitoring on AIRLink
  libraries/AP_HAL_ChibiOS/hwdef/AIRLink/hwdef.dat
Labels: hwdef, Partner

#19725 AP_GPS: write config blob out as chunk rather than iterating
  libraries/AP_GPS/AP_GPS.cpp
Labels: NeedsTesting

#19914 fix: Missing comma
  Tools/autotest/sim_vehicle.py
Labels: MergeOnCIPass

#19941 AP_Math: spline lateral scaler reduced to 0.5
  libraries/AP_Math/SplineCurve.cpp
Labels: Enhancement, Copter, MergeOnCIPass

#19499 AP_Proximity: Fix Cygbot D1 driver CRC
  libraries/AP_Proximity/AP_Proximity_Cygbot_D1.cpp
Labels: Enhancement, Safety

#19943 Copter: change variable type from float to int32_t
  ArduCopter/mode_auto.cpp
Labels: Copter, MergeOnCIPass
