Repository ArduPilot/ardupilot, pull requests merged in 2022-06, with the labels that each got.

#20914 GCS_MAVLink: learn routes even on private channels
  libraries/GCS_MAVLink/MAVLink_routing.cpp
Labels: BUG, MAVLink, DevCallTopic

#20885 AP_WheelEncoder: fix WheelEncoder_Quadrature timestamp.
  libraries/AP_WheelEncoder/WheelEncoder_Quadrature.cpp
Labels: BUG, Rover, DevCallTopic

#20900 AP_Motors: Resolve Issue 20894
  libraries/AP_Motors/AP_MotorsMulticopter.cpp
Labels: DevCallTopic

#20926 Tools: cope with change in cygwin build
  Tools/scripts/cygwin_build.sh
Labels: BuildSystem, MergeOnCIPass

#20696 AP_Scripting: Changed NULL to nullptr
  libraries/AP_Scripting/lua_scripts.cpp
Labels: Scripting, DevCallEU, MergeOnCIPass

#20892 Plane: Quadplane: force conversions of Q_M_PMW_* params if invalid
  ArduPlane/AP_Arming.cpp
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, DevCallEU

#20911 AP_Math: calc_lowpass_alpha_dt: remove unused constrain
  libraries/AP_Math/AP_Math.cpp
Labels: Library, DevCallEU

#20925 Check for bad frames in CRSF decoding
  libraries/AP_RCProtocol/AP_RCProtocol_CRSF.cpp
  libraries/AP_RCProtocol/AP_RCProtocol_CRSF.h
Labels: BUG, AllVehicles, DevCallEU

#20924 Properly reset MPU6000 signal path at startup
  libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_Invensense_registers.h
Labels: BUG, AllVehicles, DevCallEU

#20861 AP_Periph: added RNGFND_MAX_RATE parameter
  Tools/AP_Periph/AP_Periph.h
  Tools/AP_Periph/Parameters.cpp
  Tools/AP_Periph/Parameters.h
  Tools/AP_Periph/can.cpp
Labels: AP_Periph, DevCallEU, MergeOnCIPass

#20807 AP_HAL_ChibiOS: Add on-board baro support to iFlight BeastH7 V2 target.
  libraries/AP_HAL_ChibiOS/hwdef/BeastH7v2/README.md
  libraries/AP_HAL_ChibiOS/hwdef/BeastH7v2/hwdef.dat
Labels: DevCallTopic

#20943 AP_ESC_Telem: use send_struct mavlink function
  libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
Labels: Library

#20953 Correct UART RX stats
  libraries/AP_HAL_ChibiOS/UARTDriver.cpp
Labels: BUG, AllVehicles, DevCallTopic, ChibiOS

#20978 Tools: arduroller balance bot param update
  Tools/Frame_params/ArduRoller-balancebot.param
Labels: Rover

#20942 AP_Periph: fixed non-contiguous mask for ESC telem output
  Tools/AP_Periph/can.cpp
Labels: BUG, AP_Periph, DevCallEU

#20971 autotest: tidy hover_and_check_matched_frequency method
  Tools/autotest/arducopter.py
Labels: DevCallEU

#20984 Copter: remove param docs for ACRO_RP_P and _YAW_RP
  ArduCopter/Parameters.cpp
  ArduCopter/Parameters.h
Labels: Copter, Docs

#20944 SIM_Precland: add option to set orientation of precland device in sitl
  libraries/SITL/SIM_Precland.cpp
  libraries/SITL/SIM_Precland.h
Labels: SITL, GSoC

#20987 AP_Rangefinder: fixed scaling on PWM driver and enable SCALING parameter
  libraries/AP_RangeFinder/AP_RangeFinder_PWM.cpp
Labels: BUG

#21001 AC_AutoTune: fix tradheli bug with load gain set
  libraries/AC_AutoTune/AC_AutoTune_Heli.cpp
Labels: BUG, TradHeli, 4.2 backport

#19917 AP_Baro: tidy probing of external i2c baros
  libraries/AP_Baro/AP_Baro.cpp
  libraries/AP_Baro/AP_Baro_DPS280.h
  libraries/AP_Baro/AP_Baro_MS5611.h
Labels: DevCallTopic

#20645 Plane: Quadplane: QRTL climb to QRTL alt first if in Q mode
  ArduPlane/mode.h
  ArduPlane/mode_qrtl.cpp
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, DevCallTopic, NeedsTesting, WikiNeeded

#21000 AP_HAL_ChibiOS: Allow KakuteF7 initialization without baro
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7/hwdef.dat
Labels: DevCallTopic

#20882 AP_FETTecOneWire: Fix the recent change of NUM_SERVO_CHANNELS > 24
  libraries/AP_FETtecOneWire/AP_FETtecOneWire.cpp
  libraries/AP_FETtecOneWire/README.md
Labels: BUG, AllVehicles, Driver, MergeOnCIPass

#21020 Plane: fixed int8_t wrap with FWD_BAT_VOLT_MAX
  ArduPlane/servos.cpp
Labels: BUG, Plane, MergeOnCIPass

#21021 AP_HAL_Empty: move implementations of functions to header
  libraries/AP_HAL_Empty/Scheduler.cpp
  libraries/AP_HAL_Empty/Scheduler.h
Labels: DevCallTopic

#21024 AP_Mount: document point-at-home default mode option
  libraries/AP_Mount/AP_Mount.cpp
Labels: MergeOnCIPass

#20389 AP_Scripting: example script for lidar control
  libraries/AP_Scripting/examples/lidar_control.lua
Labels: Scripting

#21046 hwdef: remove unused NO_DATAFLASH hwdef directive
  libraries/AP_HAL_ChibiOS/hwdef/DevEBoxH7v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-F405/hwdef.dat
Labels: DevCallTopic

#21069 autotest: set Rover speedup to 30
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#21059 ArduPlane: fix Q_RTL_MODE parameter doc
  ArduPlane/quadplane.cpp
Labels: Plane, Docs, VTOL-Plane

#21081 AP_Common: correct comments on get_alt_cm and change_alt_frame
  libraries/AP_Common/Location.h
Labels: MergeOnCIPass
