Repository ArduPilot/ardupilot, pull requests merged in 2022-12, with the labels that each got.

#22305 GCS_Common: refactor try_send_mission_message
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#22329 Tools: add board ID for Sierra F1 AP
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#22330 autotest: loosen channel-value constrain in Soaring test
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#22140 AP_Camera: fixed CAM_MIN_INTERVAL
  libraries/AP_Camera/AP_Camera.cpp
  libraries/AP_Camera/AP_Camera.h
Labels: BUG

#22337 Plane: ensure we init z controller when inactive
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane

#22271 AP_TECS: Remove unused TECS_LAND_PTRIM parameter
  libraries/AP_TECS/AP_TECS.cpp
  libraries/AP_TECS/AP_TECS.h
Labels: BUG, Plane

#22350 Plane: added FAST_TASK() for key scheduler tasks
  ArduPlane/ArduPlane.cpp
Labels: Plane, VTOL-Plane

#22332 Support for MambaF405-2022B
  libraries/AP_HAL_ChibiOS/hwdef/MambaF405-2022/hwdef.dat
Labels: BUG, AllVehicles, ChibiOS, WikiNeeded, 4.3 Backport

#22333 AP_HAL_ChibiOS: correct defaults and readme for ReaperF745AIO board
  libraries/AP_HAL_ChibiOS/hwdef/ReaperF745v2/README.md
  libraries/AP_HAL_ChibiOS/hwdef/ReaperF745v2/defaults.parm
Labels: DevCallTopic

#22346 AP_Scheduler: guarantee that FAST_TASK tasks do run on every loop
  libraries/AP_Scheduler/AP_Scheduler.cpp
Labels: BUG, MergeOnCIPass

#22342 Correct dependencies for CRSF in build options
  Tools/scripts/build_options.py
Labels: MergeOnCIPass

#22381 AP_OpticalFlow: add some units to OFCA log message
  libraries/AP_OpticalFlow/AP_OpticalFlow_Calibrator.cpp
Labels: MergeOnCIPass

#21883 Plane: if RTL with VTOL active and within QRTL radius and alt then QRTL
  ArduPlane/mode.h
  ArduPlane/mode_rtl.cpp
Labels: VTOL-Plane, DevCallTopic, WikiNeeded

#22251 Copter: Reserve G2 63 for Ship Operations
  ArduCopter/Parameters.cpp
Labels: Copter

#22366 AP_Mount: Align received data to AP coordinate frame for Storm32 Serial
  libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
Labels: BUG, DevCallTopic, MergeOnCIPass

#22375 AP_RangeFinder: skip GPIO arming check on analog backend
  libraries/AP_RangeFinder/AP_RangeFinder.cpp
Labels: BUG, DevCallTopic

#22384 Applets:add SportPlaneAirshow schedule
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/Schedules/SportPlane_Airshow.txt
Labels: DevCallTopic, NeedsTesting

#22377 AP_HAL: use singleton getter for Baro in SIMState
  libraries/AP_HAL/SIMState.cpp
  libraries/AP_HAL/SIMState.h
Labels: MergeOnCIPass

#21978 Plane: GCS_Mavlink: use base class DO_SET_HOME
  ArduPlane/GCS_Mavlink.cpp
Labels: Plane, DevCallEU

#22401 AP_Logger: include PIDInfo header in place of PID header
  libraries/AP_Logger/LogFile.cpp
Labels: MergeOnCIPass

#22354 Copter: Simulink Model and init scripts for Copter-4.3
  Tools/simulink/arducopter/README.md
  Tools/simulink/arducopter/arducopter.slx
  Tools/simulink/arducopter/functions/ModeConfig.m
  Tools/simulink/arducopter/functions/demodYawAngle.m
  Tools/simulink/arducopter/functions/getMotorMixerFactors.m
  Tools/simulink/arducopter/functions/getParamVal.m
  Tools/simulink/arducopter/functions/getTimeZero.m
  Tools/simulink/arducopter/functions/plausibilizeTime.m
  Tools/simulink/arducopter/functions/resampleLog.m
  Tools/simulink/arducopter/sid_controller_validation.m
  Tools/simulink/arducopter/sid_controller_validation_cfg.m
  Tools/simulink/arducopter/sid_pre.m
  Tools/simulink/arducopter/sid_sim_init.m
  Tools/simulink/arducopter/simulink_model.PNG
Labels: MergeOnCIPass

#19381 Add option to only log on disarm when battery is connected
  libraries/AP_Logger/AP_Logger.cpp
Labels: Logging, WikiNeeded, MergeOnCIPass

#22409 AP_GPS: fix GPS_AUTO example
  libraries/AP_GPS/examples/GPS_AUTO_test/GPS_AUTO_test.cpp
Labels: MergeOnCIPass

#22410 AP_Scripting: new version of knife-edge compensation in aerobatics
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting

#22367 AP_Mount: fix Siyi A8 reporting of record on/off status
  libraries/AP_Mount/AP_Mount_Siyi.cpp
Labels: BUG

#22414 autotest: fix race condition in NeedEKFToArm
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#22396 Tools: extract_features.py: add Richenpower define
  Tools/scripts/extract_features.py
Labels: MergeOnCIPass

#22352 Lua script starts/stops video recording on arm/disarm
  libraries/AP_Scripting/applets/runcam_on_arm.lua
  libraries/AP_Scripting/applets/runcam_on_arm.md
Labels: Scripting, MergeOnCIPass

#22424 Tools: parameters: mdemit: stop hiding usable params (Sub)
  Tools/autotest/param_metadata/mdemit.py
Labels: MergeOnCIPass

#22326 Sub: consider RC_CHANNELS_OVERRIDE for pilot_input_failsafe
  ArduSub/GCS_Mavlink.cpp
Labels: Sub, MergeOnCIPass

#22427 AP_Scripting: fixed error on bad cmd in mission
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting

#22116 AIRLink: added LTE module enable pin to hwdef
  libraries/AP_HAL_ChibiOS/hwdef/AIRLink/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.c
Labels: DevCallTopic

#22430 Model: Callisto param update
  Tools/autotest/models/Callisto.param
Labels: SITL, DevCallTopic

#22376 Plane: tiltrotor: add throttle scaling for vectored yaw
  ArduPlane/tiltrotor.cpp
Labels: VTOL-Plane, DevCallTopic

#22380 Plane: move adjust_altitude_target functionality to per mode functions
  ArduPlane/altitude.cpp
  ArduPlane/mode.h
  ArduPlane/mode_loiter.cpp
  ArduPlane/mode_qrtl.cpp
Labels: Plane

#22444 Model: Callisto param update Yaw D
  Tools/autotest/models/Callisto.param
Labels: DevCallTopic, MergeOnCIPass

#22416 AP_Airspeed: Periph: remove usage of hidden params and remove tube order
  libraries/AP_Airspeed/AP_Airspeed.cpp
  libraries/AP_Airspeed/AP_Airspeed.h
  libraries/AP_Airspeed/AP_Airspeed_Backend.cpp
  libraries/AP_Airspeed/AP_Airspeed_Backend.h
  libraries/AP_Airspeed/AP_Airspeed_Health.cpp
Labels: AP_Periph

#22425 autotest: removed deprecated distutils
  Tools/autotest/autotest.py
Labels: DevCallTopic, CI

#22437 AP_WindVane: add Arduino script and readme to allow conection to Bluetooth wind-vane
  libraries/AP_WindVane/Tools/Bluetooth NMEA receiver/BLE_Scanner.jpg
  libraries/AP_WindVane/Tools/Bluetooth NMEA receiver/Bluetooth NMEA receiver.ino
  libraries/AP_WindVane/Tools/Bluetooth NMEA receiver/Bluetooth NMEA receiver.md
  libraries/AP_WindVane/Tools/Bluetooth NMEA receiver/Mission_Planner_Quick.PNG
  libraries/AP_WindVane/Tools/Bluetooth NMEA receiver/XIAO_connection_diagram.png
Labels: WikiNeeded, Sailboat

#22449 hwdef: go to minimal GPS for MatekF405-CAN
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-CAN/hwdef.dat
Labels: MergeOnCIPass, hwdef

#22386 AP_TemperatureSensor: fix param count change when loading drivers
  libraries/AP_TemperatureSensor/AP_TemperatureSensor.cpp
Labels: BUG

#22442 AP_Mount: servo driver loses unnecessary closest_limits method
  libraries/AP_Mount/AP_Mount_Servo.cpp
  libraries/AP_Mount/AP_Mount_Servo.h
Labels: BUG, Driver, DevCallEU

#22441 Tools: correct autotest copter-gimbal .parm
  Tools/autotest/default_params/copter-gimbal.parm
Labels: BUG, DevEnv

#22464 autotest: use epsilon when testing for zero variance in EK3_RNG_USE_HGT
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#22456 AP_Scripting: changed airshow rolling circle
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/Schedules/AirShow.txt
Labels: Scripting, MergeOnCIPass

#22461 Improve collective to yaw compensation for traditional helicopters
  libraries/AP_Motors/AP_MotorsHeli_Single.cpp
  libraries/AP_Motors/AP_MotorsHeli_Single.h
Labels: Enhancement, TradHeli, WikiNeeded, MergeOnCIPass

#22439 AP_DAL: call start_frame for all backends
  libraries/AP_DAL/AP_DAL_RangeFinder.cpp
Labels: MergeOnCIPass

#22458 Copter: Simulink Model and init scripts
  Tools/simulink/arducopter/README.md
  Tools/simulink/arducopter/arducopter.slx
  Tools/simulink/arducopter/functions/ModeConfig.m
  Tools/simulink/arducopter/functions/demodYawAngle.m
  Tools/simulink/arducopter/functions/getMotorMixerFactors.m
  Tools/simulink/arducopter/functions/getParamVal.m
  Tools/simulink/arducopter/functions/getTimeZero.m
  Tools/simulink/arducopter/functions/plausibilizeTime.m
  Tools/simulink/arducopter/functions/resampleLog.m
  Tools/simulink/arducopter/sid_controller_validation.m
  Tools/simulink/arducopter/sid_controller_validation_cfg.m
  Tools/simulink/arducopter/sid_pre.m
  Tools/simulink/arducopter/sid_sim_init.m
  Tools/simulink/arducopter/simulink_model.PNG
Labels: Enhancement, Copter, Reviewed, Top Contribution, DevCallTopic, DevCallEU, MergeOnCIPass

#22475 Tools: add --no-merge-base option to size_compare_branches.py
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#22446 Copter: Use wp_start() in do_nav_wp()
  ArduCopter/mode.h
  ArduCopter/mode_auto.cpp
Labels: Copter

#22495 github: macosx: remove github-installed Python symlinks in /usr/local/bin
  Tools/environment_install/install-prereqs-mac.sh
Labels: MergeOnCIPass

#22418 AP_HAL_Linux: Raspberry 64OS Address fix
  libraries/AP_HAL_Linux/RCInput_RPI.cpp
  libraries/AP_HAL_Linux/RCInput_RPI.h
Labels: BUG, DevEnv, Linux

#22472 Plane: move mode update_target_altitude to correct files
  ArduPlane/altitude.cpp
  ArduPlane/mode.cpp
  ArduPlane/mode_guided.cpp
Labels: Plane

#22492 Plane: Quadplane: remove RTL navigate incorrect comment and unneeded…
  ArduPlane/mode_rtl.cpp
Labels: VTOL-Plane, DevCallTopic

#22501 Fix race condition in Copter TakeoffCheck test
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#22493 Add rate controlled aerobatics applet
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/README.md
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua
Labels: Scripting, MergeOnCIPass

#22506 AC_PosControl: Include FF in _pid_vel_xy integrator initialisation
  libraries/AC_AttitudeControl/AC_PosControl.cpp
Labels: BUG, TradHeli, Safety, VTOL-Plane, DevCallTopic, DevCallEU, 4.3 Backport

#22494 Optimize LPF and fifo update on BMI088
  libraries/AP_InertialSensor/AP_InertialSensor_BMI088.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_BMI088.h
Labels: BUG, AllVehicles, DevCallEU

#22500 AP_Scripting: don't start aerobatics until we have a vel estimate
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting

#22508 AP_Scripting: fixed derry turn in aerobatics
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/Schedules/F4CScaleExample.txt
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting

#22519 ArduPlane:test new flight options formats
  ArduPlane/Parameters.cpp
Labels: MergeOnCIPass

#22528 AP_FETtecOneWire: change comments to not use @param
  libraries/AP_FETtecOneWire/AP_FETtecOneWire.cpp
Labels: MergeOnCIPass

#22525 autotest: test_build_options.py: correct invocation of test_enable_fe…
  Tools/autotest/test_build_options.py
Labels: MergeOnCIPass

#22445 Copter: Fix Auto Takeoff when complete_alt_cm is current altitude
  ArduCopter/mode.h
  ArduCopter/takeoff.cpp
Labels: BUG, Copter

#22527 AC_WPNav: remove _wp_accel_cmss.set_and_save_ifchanged
  libraries/AC_WPNav/AC_WPNav.cpp
  libraries/AC_WPNav/AC_WPNav.h
Labels: BUG, Copter, VTOL-Plane, 4.3 Backport

#22537 AP_Scripting:fix format error in readme file
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/README.md
Labels: DevCallTopic

#22485 Copter: set param default for user parameters
  ArduCopter/UserParameters.cpp
  ArduCopter/UserParameters.h
Labels: BUG, Copter, MergeOnCIPass
