Repository ArduPilot/ardupilot, pull requests merged in 2022-07, with the labels that each got.

#20656 AP_Scripting: add examples
  libraries/AP_Scripting/examples/rover-MinFixType.lua
  libraries/AP_Scripting/examples/rover-SaveTurns.lua
Labels: Scripting, MergeOnCIPass

#21091 SITL/SIM_RF_MAVLink: fix incomplete initializer clauses
  libraries/SITL/SIM_RF_MAVLink.cpp
Labels: MergeOnCIPass

#21074 Plane: fixed misspellings of 'transition'
  ArduPlane/mode_qacro.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/tailsitter.cpp
  ArduPlane/tailsitter.h
  ArduPlane/tiltrotor.cpp
  ArduPlane/transition.h
Labels: Plane

#21088 AP_TECS: Unify coding style for if statements
  libraries/AP_TECS/AP_TECS.cpp
Labels: Plane

#21104 Plane: fixed combination of passby and acceptance dist WP
  ArduPlane/commands_logic.cpp
Labels: BUG, Plane

#20889 AP_InertialSensor: remove voiding of parameter
  libraries/AP_InertialSensor/AP_InertialSensor_Invensensev2.cpp
Labels: DevCallTopic

#21051 hwdef: remove redundant 'define HAL_MINIMIZE_FEATURES 0'
  libraries/AP_HAL_ChibiOS/hwdef/BirdCANdy/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CUAV_GPS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/FreeflyRTK/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/G4-ESC/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/HerePro/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Hitec-Airspeed/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/HitecMosaic/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/HolybroG4_GPS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/HolybroGPS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekL431/hwdef.inc
  libraries/AP_HAL_ChibiOS/hwdef/Nucleo-G491/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Nucleo-L476/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-F405/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-F412/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-F9P/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-L431/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/ZubaxGNSS/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/ZubaxGNSS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/f103-periph/hwdef.inc
  libraries/AP_HAL_ChibiOS/hwdef/f303-MatekGPS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/f303-periph/hwdef.inc
  libraries/AP_HAL_ChibiOS/hwdef/f405-MatekGPS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/mRo-M10095/hwdef.dat
Labels: DevCallTopic, DevCallEU

#21072 AP_Scripting: Generator: fix docs generator aliasing
  libraries/AP_Scripting/generator/src/main.c
Labels: DevCallTopic, Scripting

#21112 hwdef: added telem3 on Pixhawk6X
  libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6X/hwdef.dat
Labels: DevCallTopic, hwdef

#21113 HAL_ChibiOS: hwdef: add new hardware MFE-PixSurveyA1
  Tools/AP_Bootloader/board_types.txt
  libraries/AP_HAL_ChibiOS/hwdef/PixSurveyA1/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/PixSurveyA1/hwdef.dat
Labels: WikiNeeded

#21124 Plane: don't failsafe when in RTL_AUTOLAND landing sequence
  ArduPlane/events.cpp
Labels: Plane

#21126 AP_Scripting: fixed SimOnHardware build
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: BuildSystem, MergeOnCIPass

#21085 autotest: build Heli in parallel to Copter
  .github/workflows/test_sitl_copter.yml
Labels: CI, MergeOnCIPass

#20840 GCS_MAVLink: improved battery cell monitoring
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: CAN, MergeOnCIPass

#21082 AP_Rally: tidy calculation of nearest rally/home
  libraries/AP_Rally/AP_Rally.cpp
  libraries/AP_Rally/AP_Rally.h
Labels: Library, MergeOnCIPass

#21147 Correct gcs_out_of_space_to_send methodname
  libraries/GCS_MAVLink/GCS.cpp
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/GCS_MAVLink.cpp
Labels: DevCallTopic

#21151 Tools: rstemit.py: Change Range to be clearer meaning
  Tools/autotest/param_metadata/rstemit.py
Labels: Docs

#20420 Tools: build_bootloaders.py should invoke bin2hex.py with the same Python interpreter as its own
  Tools/scripts/build_bootloaders.py
Labels: BuildSystem, DevCallEU

#21107 Plane: add yaw input shaping command model
  ArduPlane/mode_qacro.cpp
  ArduPlane/mode_qloiter.cpp
  ArduPlane/mode_qrtl.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
  ArduPlane/tailsitter.cpp
Labels: VTOL-Plane, DevCallEU

#21019 AP_RangeFinder: reduce verbiage when detecting serial rangefinders
  libraries/AP_RangeFinder/AP_RangeFinder.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_BLPing.h
  libraries/AP_RangeFinder/AP_RangeFinder_Backend_Serial.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_Backend_Serial.h
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake_TF02.h
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake_TF03.h
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake_TFMini.h
  libraries/AP_RangeFinder/AP_RangeFinder_GYUS42v2.h
  libraries/AP_RangeFinder/AP_RangeFinder_Lanbao.h
  libraries/AP_RangeFinder/AP_RangeFinder_LeddarOne.h
  libraries/AP_RangeFinder/AP_RangeFinder_LeddarVu8.h
  libraries/AP_RangeFinder/AP_RangeFinder_LightWareSerial.h
  libraries/AP_RangeFinder/AP_RangeFinder_MAVLink.h
  libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarSerialLV.h
  libraries/AP_RangeFinder/AP_RangeFinder_NMEA.h
  libraries/AP_RangeFinder/AP_RangeFinder_USD1_Serial.h
  libraries/AP_RangeFinder/AP_RangeFinder_Wasp.h
Labels: NeedsTesting

#21168 AP_RangeFinder: support Benewake H30 radar
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake_CAN.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake_CAN.h
Labels: WikiNeeded, DevCallEU

#21064 Plane: fixed check for fixed wing approach QRTL start
  ArduPlane/commands_logic.cpp
Labels: BUG, VTOL-Plane, MergeOnCIPass

#21195 AP_BoardConfig: use HAL_GCS_ENABLED in place of periph/example check
  libraries/AP_BoardConfig/AP_BoardConfig.cpp
Labels: AP_Periph

#21194 AP_RAMTRON: reduce scope for WITH_SEMAPHORE
  libraries/AP_RAMTRON/AP_RAMTRON.cpp
Labels: DevCallTopic

#21201 Copter: Append WHITE SPACE to the else statement
  ArduCopter/mode_rtl.cpp
Labels: MergeOnCIPass

#21174 AP_GPS: move defaulting of AP_GPS_UBLOX_ENABLED to AP_GPS_config
  libraries/AP_GPS/AP_GPS_UBLOX.h
  libraries/AP_GPS/AP_GPS_config.h
Labels: DevCallTopic

#21179 AP_InertialSensor: remove un-needed methods
  libraries/AP_InertialSensor/AP_InertialSensor.h
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
  libraries/AP_InertialSensor/AP_InertialSensor_Logging.cpp
Labels: DevCallTopic

#21205 Plane: log ATT on non quadplanes
  ArduPlane/Log.cpp
Labels: Plane, DevCallTopic

#21215 AP_HAL_ChibiOS: add BDShot for Holybro PH4-mini
  libraries/AP_HAL_ChibiOS/hwdef/PH4-mini-bdshot/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/PH4-mini-bdshot/hwdef.dat
Labels: DevCallTopic

#21221 AP_ICEngine: fixed RPM filter rate and plane.G_Dt
  libraries/AP_ICEngine/AP_ICEngine.cpp
Labels: BUG, MergeOnCIPass

#21182 Plane: VTOL approach threshold use path proportion rather than radius
  ArduPlane/commands_logic.cpp
Labels: BUG, VTOL-Plane, DevCallEU

#21228 Plane: tailsitter: dont check if flying its always true in vtol transtion
  ArduPlane/tailsitter.cpp
Labels: VTOL-Plane, DevCallEU

#21227 AP_Scripting: examples: Aerobatics: Corrects arg1/arg2
  libraries/AP_Scripting/examples/Aerobatics/Missions/plane_aerobatics.lua
Labels: Scripting

#21236 Plane: check G_Dt to catch startup errors
  ArduPlane/ArduPlane.cpp
Labels: MergeOnCIPass

#21230 AP_RangeFinder: add prearm for analogue/pwm pin conflicts
  libraries/AP_RangeFinder/AP_RangeFinder.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_Backend.h
Labels: MergeOnCIPass

#21237 AP_AHRS: body_to_earth is unused and bugged
  libraries/AP_AHRS/AP_AHRS.h
Labels: BUG, MergeOnCIPass

#19979 Tools: Enable uploader.py and waf --upload to work on WSL2
  Tools/ardupilotwaf/chibios.py
  Tools/scripts/uploader.py
Labels: DevEnv, MergeOnCIPass, 4.2 backport, 4.1 Backport

#21232 autotest: make search of dflog for required messages faster
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21218 AP_GPS: Do not drop reassembly buffer for injected packets when a dupllicate fragment is received
  libraries/AP_GPS/AP_GPS.cpp
Labels: GPS, MergeOnCIPass

#21248 Enable OSD parameter menus on KakuteH7
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7/hwdef.dat
Labels: BUG, AllVehicles, DevCallTopic, ChibiOS, 4.2 Issue, 4.2 backport

#21259 autotest: increase time allowed for mission download
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21275 AP_SerialManager: correct bug in find_baudrate() function
  libraries/AP_SerialManager/AP_SerialManager.cpp
Labels: MergeOnCIPass

#21251 AP_Landing: change LAND_ABORT_THR param docs to match code and wiki of 90%
  libraries/AP_Landing/AP_Landing.cpp
Labels: Plane, Docs

#21027 AP_Control: change autotune I determination for Roll axis
  libraries/APM_Control/AP_AutoTune.cpp
Labels: DevCallTopic

#21129 Copter: Payload Place fix take-off
  ArduCopter/mode.h
  ArduCopter/mode_auto.cpp
Labels: Copter, DevCallTopic, MergeOnCIPass

#21253 autotest: add --extra_hwdef option to test_build_options.py
  Tools/autotest/test_build_options.py
Labels: MergeOnCIPass

#21257 GCS_MAVLink: ensure payload space for ACK before sending
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#21239 add skip-string-normalization to black config
  pyproject.toml
Labels: MergeOnCIPass

#21266 autotest: remove report of pull failure
  Tools/scripts/build_autotest.sh
Labels: DevCallEU

#21285 Tools: add script to extract features supported by a firmware
  Tools/scripts/extract_features.py
Labels: MergeOnCIPass

#21296 Copter: Fix Payload Place Bug
  ArduCopter/mode_auto.cpp
Labels: BUG, Copter, DevCallTopic

#21298 autotest: augment PayLoadPlaceMission test to check drop distance
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass
