Repository ArduPilot/ardupilot, pull requests merged in 2022-03, with the labels that each got.

#20165 External flash binaries should be published like internal flash binaries
  Tools/ardupilotwaf/chibios.py
Labels: BUG, DevCallTopic

#20197 AP_NavEKF3: fixed constrain indexing bug
  libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
Labels: BUG, EKF, MergeOnCIPass

#20200 Tools: switch compiler for new releases to 10.2
  Tools/scripts/build_binaries.py
Labels: BuildSystem, MergeOnCIPass

#20175 AP_Scripting: added example for orbit follow
  libraries/AP_Scripting/examples/orbit_follow.lua
Labels: Scripting, DevCallEU

#20205 SRV_Channel: Changing servo functions are now reboot required
  libraries/SRV_Channel/SRV_Channel.cpp
Labels: Docs

#20207 hwdef: fixed buzzer on CUAV_GPS peripheral
  libraries/AP_HAL_ChibiOS/hwdef/CUAV_GPS/hwdef.dat
Labels: BUG, AP_Periph

#20177 AP_Follow: support the FOLLOW_TARGET mavlink message
  libraries/AP_Follow/AP_Follow.cpp
Labels: MAVLink, WikiNeeded

#20212 AP_Follow: zreo velocities if not provided
  libraries/AP_Follow/AP_Follow.cpp
Labels: MergeOnCIPass

#20214 AR_AttitudeControl: use _desired_speed instead of desired_speed for t…
  libraries/APM_Control/AR_AttitudeControl.cpp
Labels: BUG, Rover, MergeOnCIPass

#20195 AP_Compass: Fix compass priority instance message to make sense to users
  libraries/AP_Compass/AP_Compass.cpp
Labels: Enhancement, DevCallTopic, Compass

#20206 Rover: loiter: sailboats don't try and sail directly into the wind
  Rover/mode_loiter.cpp
Labels: Rover, DevCallTopic, Sailboat

#20232 Plane: don't prevent stick mixing in none RC failsafe
  ArduPlane/Attitude.cpp
Labels: Plane

#20236 AP_RangeFinder: add AP_RANGEFINDER_LEDDARVU8_ENABLED
  libraries/AP_RangeFinder/AP_RangeFinder_LeddarVu8.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_LeddarVu8.h
Labels: DevCallTopic

#20237 HAL_ChibiOS: fixed min/max inversion in MCU voltage logging
  libraries/AP_HAL_ChibiOS/AnalogIn.cpp
Labels: BUG, ChibiOS

#20203 Plane: added Q_LAND_ALTCHG parameter
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: VTOL-Plane, DevCallEU, MergeOnCIPass

#20226 README: Fix broken links to CI tests
  README.md
Labels: CI

#20186 CPUInfo: add DSP
  Tools/CPUInfo/CPUInfo.cpp
  Tools/CPUInfo/Makefile
Labels: Tools, MergeOnCIPass

#20187 AP_Scripting: Change to no message notification in DISARMED state
  libraries/AP_Scripting/examples/copter-fast-descent.lua
Labels: MergeOnCIPass

#20194 Tools: util.py: fix comment for reltopdir()
  Tools/autotest/pysim/util.py
Labels: SITL, Docs, MergeOnCIPass

#18600 AP_Airspeed: improve description of ARSPD_TUBE_ORDR
  libraries/AP_Airspeed/AP_Airspeed.cpp
Labels: MergeOnCIPass

#20152 Tools: add AntennaTracker to builds list
  Tools/scripts/build_sizes/build_sizes.py
Labels: BuildSystem, MergeOnCIPass

#20211 SITL: Change build errors
  libraries/SITL/SIM_Buzzer.h
Labels: MergeOnCIPass

#20260 AC_AttitudeControl: WeatherVane: defualt to 0 gain on plane and early return
  libraries/AC_AttitudeControl/AC_WeatherVane.cpp
Labels: VTOL-Plane, DevCallEU

#20255 Plane: tailsitter: keep attitude controll throttle level upto date for smoother controller handover
  ArduPlane/tailsitter.cpp
Labels: VTOL-Plane, DevCallEU

#20247 Always choose high for dshot prescaler calculation
  libraries/AP_HAL/RCOutput.cpp
  libraries/AP_HAL/tests/test_prescaler.cpp
Labels: BUG, ChibiOS, DevCallEU

#20256 Plane: never stick mix without valid RC input
  ArduPlane/Attitude.cpp
Labels: Plane, DevCallEU

#20268 Plane: protect against short stop_distance
  ArduPlane/quadplane.cpp
Labels: BUG, VTOL-Plane

#20276 Tools: board_list.py: build Sub binaries
  Tools/scripts/board_list.py
Labels: MergeOnCIPass

#20282 autotest: board_list.py: correct autobuild target name for Tracker
  Tools/scripts/board_list.py
Labels: MergeOnCIPass

#20274 Tools: build_options.py: make and assert it flake8-clean
  Tools/scripts/build_options.py
Labels: MergeOnCIPass

#20293 AP_HAL_ChibiOS: correct #ifndef nesting in periph defaults
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: DevCallTopic

#18191 HAL_ChibiOS: add MatekF405-STD S7 PWM output
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-STD/hwdef.dat
Labels: ChibiOS, WikiNeeded

#20298 AP_CANManager: correct parameter metadata error
  libraries/AP_CANManager/AP_CANIfaceParams.cpp
Labels: BUG, Library, DevCallTopic, CAN

#20033 GubeGreen: Add OREOLED support for Solo
  libraries/AP_HAL_ChibiOS/hwdef/CubeGreen-solo/hwdef.dat
Labels: MergeOnCIPass

#20283 AP_HAL_ChibiOS: CUAVv5: use icm42688p instead of icm20602
  libraries/AP_HAL_ChibiOS/hwdef/CUAVv5/hwdef.dat
Labels: MergeOnCIPass

#20254 Ensure indexing into declination tables is always correct
  libraries/AP_Declination/AP_Declination.cpp
  libraries/AP_Declination/AP_Declination.h
  libraries/AP_Declination/tables.cpp
Labels: BUG, AllVehicles, DevCallTopic

#20267 AP_OSD: make OSD rssi scale match link quality (0-100)
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: DevCallTopic

#20231 AP_FlashIface: Fixed could be used unintialized
  libraries/AP_FlashIface/AP_FlashIface_JEDEC.cpp
Labels: Library, MergeOnCIPass

#20309 Tools: test_build_options.py: add bin mappings for all vehicles
  Tools/autotest/test_build_options.py
Labels: MergeOnCIPass

#20312 Plane: added an arming check for Q_ASSIST_SPEED
  ArduPlane/AP_Arming.cpp
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, DevCallEU

#20310 Rover: balance bot stands in acro with no position estimate
  Rover/mode_acro.cpp
Labels: BUG, Rover

#20275 Plane: Display Fence Breach message in GCS
  ArduPlane/fence.cpp
Labels: DevCallEU

#20313 Tracker: fix sim_vehicle.py with --tracker option
  AntennaTracker/system.cpp
Labels: DevCallEU

#20155 Allow H7 480Mhz clock speed to be configured in hwdef
  libraries/AP_HAL_ChibiOS/hwdef/SPRacingH7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
  libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32H750xx.py
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: ChibiOS, MergeOnCIPass

#19920 Plane: adjust throttle mix for auto landing
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, NeedsTesting

#20330 Tools: correct antennatracker name in size_compare_branches.py
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#20308 Plane: correct compilation when airspeed disabled
  ArduPlane/GCS_Mavlink.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/Plane.h
  ArduPlane/is_flying.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/servos.cpp
Labels: Plane, NeedsTesting, MergeOnCIPass

#19958 AP_GPS: prevent switching to a dead GPS
  libraries/AP_GPS/AP_GPS.cpp
Labels: GPS, DevCallTopic

#20041 Plane: remove persistent guided_WP_loc state
  ArduPlane/ArduPlane.cpp
  ArduPlane/GCS_Mavlink.cpp
  ArduPlane/Plane.h
  ArduPlane/avoidance_adsb.cpp
  ArduPlane/avoidance_adsb.h
  ArduPlane/commands.cpp
  ArduPlane/fence.cpp
  ArduPlane/mode_LoiterAltQLand.cpp
  ArduPlane/mode_guided.cpp
Labels: DevCallTopic

#20241 AP_Scripting: added set_override method for scripting
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/examples/RC_override.lua
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: DevCallTopic, Scripting

#20355 Plane: when shutting down motors force outputs to minimum
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, DevCallEU

#20294 AP_HAL_ChibiOS: ensure that common ram is selected for bootloader/app for STM32H7 periph
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: AP_Periph, DevCallEU

#20295 AP_GPS: only use PPS time when there is atleast 2D Fix
  libraries/AP_GPS/GPS_Backend.cpp
Labels: GPS, DevCallEU

#20357 AP_BattMonitor: fixed battery remaining of sum battery
  libraries/AP_BattMonitor/AP_BattMonitor_Analog.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_Backend.h
  libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_LTC2946.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp
Labels: BUG, MergeOnCIPass

#20360 Plane: prevent rapid RTL/AUTO switching on fence breach
  ArduPlane/fence.cpp
Labels: BUG, Plane

#20345 Plane: added RTL_AUTOLAND=3
  ArduPlane/AP_Arming.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/defines.h
  ArduPlane/events.cpp
  ArduPlane/mode_rtl.cpp
Labels: Plane, VTOL-Plane, WikiNeeded

#20359 autotest: add test for landing speed
  Tools/autotest/arducopter.py
  Tools/autotest/common.py
Labels: MergeOnCIPass

#20363 Plane: fixed yaw on the ground when rudder disarming in AUTO
  ArduPlane/fence.cpp
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, MergeOnCIPass

#20349 AP_HAL_ChibiOS: reversible DShot fix
  libraries/AP_HAL_ChibiOS/RCOutput.cpp
Labels: BUG, Rover, MergeOnCIPass

#20365 Copter: Clarify calculations in get_pilot_desired_lean_angles
  ArduCopter/mode.cpp
  ArduCopter/mode.h
Labels: Copter

#20322 HAL_ChibiOS: prevent conflicting RC input
  libraries/AP_HAL_ChibiOS/RCInput.cpp
  libraries/AP_HAL_ChibiOS/RCInput.h
Labels: BUG

#19813 AP_HAL:RPI read cpu by revision
  libraries/AP_HAL_Linux/Util_RPI.cpp
  libraries/AP_HAL_Linux/Util_RPI.h
Labels: Linux

#20306 AP_Scripting: copter fast descent gets improved slowdown
  libraries/AP_Scripting/examples/copter-fast-descent.lua
Labels: BUG, Enhancement, Copter, Scripting

#20378 autotest: correct diagnostic message symlink->link
  Tools/autotest/common.py
Labels: MergeOnCIPass

#20377 autotest: print mag cal progress messages when testing mag cal
  Tools/autotest/common.py
Labels: MergeOnCIPass

#20381 Blimp: remove duplicated and unused params
  Blimp/Parameters.cpp
  Blimp/Parameters.h
Labels: DevCallTopic, Blimp

#20388 AP_Param: fixed param class conversion code
  libraries/AP_Param/AP_Param.cpp
Labels: BUG, DevCallTopic

#20391 HWDEF: add SLCAN OTG port, correct defaults.param errors
  libraries/AP_HAL_ChibiOS/hwdef/QioTekZealotH743/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/QioTekZealotH743/hwdef.dat
Labels: AllVehicles, DevCallTopic

#20346 AP_Math: add specialisation for sq(float)
  libraries/AP_Math/AP_Math.h
  libraries/AP_Math/tests/test_math.cpp
Labels: MergeOnCIPass

#20370 Plane: handle AIRBRAKE RC option
  ArduPlane/RC_Channel.cpp
Labels: Plane

#20228 AP_HAL_ChibiOS: fix ms5611 probe for NucleoH743
  libraries/AP_HAL_ChibiOS/hwdef/NucleoH743/hwdef.dat
Labels: ChibiOS, hwdef
