Repository ArduPilot/ardupilot, pull requests merged in 2022-08, with the labels that each got.

#21276 NavEKF3: Option to disable logging of EKF log messages
  libraries/AP_NavEKF3/AP_NavEKF3.cpp
  libraries/AP_NavEKF3/AP_NavEKF3.h
  libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp
Labels: DevCallTopic, WikiNeeded

#21286 Guided Mode support MAV_CMD_DO_CHANGE_SPEED
  ArduCopter/GCS_Mavlink.cpp
  ArduCopter/mode.h
  ArduCopter/mode_auto.cpp
  ArduCopter/mode_guided.cpp
Labels: BUG, Copter, MergeOnCIPass

#21301 Plane: fix attitude logging logic and rates
  ArduPlane/ArduPlane.cpp
  ArduPlane/Log.cpp
  ArduPlane/Plane.h
Labels: WikiNeeded

#21305 Plane: change CURRENT to BATT_MON in log bitmask metadata
  ArduPlane/Parameters.cpp
Labels: DevCallTopic

#21202 AP_EFI: prevent flood of Lutan serial port
  libraries/AP_EFI/AP_EFI_Serial_Lutan.cpp
Labels: Plane

#21297 AP_RangeFinder: default orientation to NONE for AP_Periph
  libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
Labels: AP_Periph

#21211 HAL_ChibiOS: hwdef: add README.md for PixSurveyA1
  libraries/AP_HAL_ChibiOS/hwdef/PixSurveyA1/README.md
Labels: MergeOnCIPass

#21328 Tools: build_ci.sh: correct quoting of space-containing value
  Tools/scripts/build_ci.sh
Labels: MergeOnCIPass

#21317 Plane: improve target airspeed in landing approach
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, MergeOnCIPass

#20419 hwdef: KakuteH7 bluetooth switch
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7/hwdef.dat
Labels: ChibiOS, WikiNeeded, MergeOnCIPass

#21308 Fix bootloader flash storage
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: BUG, NeedsTesting, DevCallEU, 4.2 backport

#21338 AP_Arming: use prearm-display-timeout in milliseconds instead of counter
  libraries/AP_Arming/AP_Arming.cpp
  libraries/AP_Arming/AP_Arming.h
Labels: DevCallEU

#21322 Tools: FilterTool: add support for PIDs and other updates.
  Tools/autotest/web-firmware/Tools/FilterTool/filters.js
  Tools/autotest/web-firmware/Tools/FilterTool/index.html
Labels: DevCallEU

#21226 AP_NavEKF3: add GPS vAcc threshold that decides when to use the GPS as an altitude source
  libraries/AP_NavEKF3/AP_NavEKF3.cpp
  libraries/AP_NavEKF3/AP_NavEKF3.h
  libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_VehicleStatus.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.h
Labels: EKF, DevCallEU

#21352 autotest: allow more time for angle test to retrieve correct angle
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#21283 Change logging to be designated as streaming
  libraries/AP_Landing/AP_Landing_Slope.cpp
Labels: MergeOnCIPass

#21262 Tools: web-filter save use comma instead of =
  Tools/autotest/web-firmware/Tools/FilterTool/filters.js
Labels: MergeOnCIPass

#21133 SITL: set z component of precland device position separately
  libraries/SITL/SIM_Precland.cpp
Labels: MergeOnCIPass

#21358 autotest: correct assert_prearm_failure to not try to arm vehicle
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21378 Tools: added name to GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#21307 autotest: add test for WP_YAW_BEHAVIOUR 0
  Tools/autotest/arducopter.py
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21287 autotest: allow a test to override speedup
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21304 Tools: FilterTool: add support for query strings
  Tools/autotest/web-firmware/Tools/FilterTool/filters.js
  Tools/autotest/web-firmware/Tools/FilterTool/index.html
Labels: DevCallTopic

#21339 AP_Arming: display 'Arm: ' instead of 'PreArm: ' for arming failures
  libraries/AP_Arming/AP_Arming.cpp
  libraries/AP_Arming/AP_Arming.h
Labels: DevCallTopic

#21349 Copter: move motors check to be must-run prearm
  ArduCopter/AP_Arming.cpp
Labels: DevCallTopic

#21361 Copter: fix take-off velocity limits
  libraries/AP_Math/control.cpp
  libraries/AP_Math/control.h
Labels: BUG, Copter, VTOL-Plane

#21356 Plane: Quadplane: allow servo auto trim for motors only tailsitter asist
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
  ArduPlane/servos.cpp
Labels: VTOL-Plane

#21373 Add back in bdshot targets for KakuteF7 and CubeYellow
  Tools/scripts/board_list.py
Labels: BUG, AllVehicles, DevCallTopic

#21362 Plane: Quadplane: add option_is_set helper for Q_OPTIONS
  ArduPlane/AP_Arming.cpp
  ArduPlane/GCS_Mavlink.cpp
  ArduPlane/altitude.cpp
  ArduPlane/commands_logic.cpp
  ArduPlane/events.cpp
  ArduPlane/mode_qloiter.cpp
  ArduPlane/mode_qstabilize.cpp
  ArduPlane/navigation.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
  ArduPlane/servos.cpp
  ArduPlane/system.cpp
  ArduPlane/tailsitter.cpp
  ArduPlane/tiltrotor.cpp
Labels: VTOL-Plane, MergeOnCIPass

#21334 SITL: fix var naming for precland device center
  libraries/SITL/SIM_Aircraft.cpp
  libraries/SITL/SIM_Precland.cpp
  libraries/SITL/SIM_Precland.h
Labels: MergeOnCIPass

#21299 hwdef: support moving baseline GPS yaw on MatekL431-Periph
  libraries/AP_HAL_ChibiOS/hwdef/MatekL431-Periph/hwdef.dat
Labels: AP_Periph

#21180 hwdef: support moving baseline yaw with Holybro G4 CAN GPS
  libraries/AP_HAL_ChibiOS/hwdef/HolybroG4_GPS/hwdef.dat
Labels: AP_Periph

#21340 Tools: rebuilt bootloaders
  Tools/bootloaders/BeastH7_bl.bin
  Tools/bootloaders/BeastH7_bl.hex
  Tools/bootloaders/HitecMosaic_bl.elf
  Tools/bootloaders/HolybroG4_GPS_bl.elf
  Tools/bootloaders/KakuteH7Mini_bl.bin
  Tools/bootloaders/KakuteH7Mini_bl.hex
  Tools/bootloaders/KakuteH7_bl.bin
  Tools/bootloaders/KakuteH7_bl.elf
  Tools/bootloaders/KakuteH7_bl.hex
  Tools/bootloaders/MatekH743_bl.bin
  Tools/bootloaders/MatekH743_bl.hex
  Tools/bootloaders/Nucleo-G491_bl.bin
  Tools/bootloaders/Nucleo-G491_bl.elf
  Tools/bootloaders/Nucleo-G491_bl.hex
  Tools/bootloaders/SkystarsH7HD_bl.bin
  Tools/bootloaders/SkystarsH7HD_bl.hex
  Tools/bootloaders/ZubaxGNSS_bl.bin
  Tools/bootloaders/ZubaxGNSS_bl.elf
  Tools/bootloaders/ZubaxGNSS_bl.hex
  Tools/bootloaders/f303-MatekGPS_bl.elf
  Tools/bootloaders/luminousbee5_bl.bin
  Tools/bootloaders/luminousbee5_bl.elf
  Tools/bootloaders/luminousbee5_bl.hex
  Tools/bootloaders/mRo-M10095_bl.elf
Labels: MergeOnCIPass

#21385 Tools: remove MAV_POWER_STATUS_ from bit descriptions
  Tools/scripts/powr_change.py
Labels: MergeOnCIPass

#21359 AP_HAL_SITL: correct bind-value SIM_RC_FAIL handling
  libraries/AP_HAL_SITL/SITL_State.cpp
Labels: DevCallEU

#21394 Tools: extract_features.py: allow for regular expressions for features
  Tools/scripts/extract_features.py
Labels: MergeOnCIPass

#21388 AP_Math: add dignostic message for SCurve internal error
  libraries/AP_Math/SCurve.cpp
Labels: MergeOnCIPass

#21397 build_binaries.py: print not-found-on-boardlist message
  Tools/scripts/build_binaries.py
Labels: MergeOnCIPass

#21400 AP_OpenDroneID: correct compilation under gcc 7.5.0
  libraries/AP_OpenDroneID/AP_OpenDroneID.cpp
Labels: MergeOnCIPass

#21398 autotest: tidy resetting of parameters after battery failsafe test
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#21405 AP_DroneID: add missing element to constructor
  libraries/AP_OpenDroneID/AP_OpenDroneID.cpp
Labels: MergeOnCIPass, OpenDroneID

#18999 autotest: add tests for mavlink disarm
  Tools/autotest/arduplane.py
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#21412 autotest: tidy angle test
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#21413 Tools: size_compare_branches: allow compilation with --extra-hwdef
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#21429 build_ci.sh: change back to original directory after running profile
  Tools/scripts/build_ci.sh
Labels: MergeOnCIPass

#21426 autotest: be generous with mission upload timeouts
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21430 AP_Common: correct gtests
  libraries/AP_Common/tests/test_cpp.cpp
Labels: DevCallTopic

#21414 autotest: add test for quadplane booting in auto
  Tools/autotest/ArduPlane_Tests/BootInAUTO/mission.txt
  Tools/autotest/common.py
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#21419 FilterTool: graph split and phase wrap option
  Tools/autotest/web-firmware/Tools/FilterTool/filters.js
  Tools/autotest/web-firmware/Tools/FilterTool/index.html
Labels: DevCallTopic

#21447 ArduPlane: remove unused limit_length calculation in overshoot
  ArduPlane/quadplane.cpp
Labels: Plane, VTOL-Plane

#21443 waf: ensure we don't apply app desc step on BL
  Tools/ardupilotwaf/chibios.py
Labels: MergeOnCIPass

#21457 autotest: pop extra contexts post-test to clean up message hooks
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21460 autotest: clear context before looking for GPS type
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21461 autotest: force-disarm quadplane after ICEngine test
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#21454 SRV_Channel: Change the minimum value of minimum PWM for servo output(NFC)
  libraries/SRV_Channel/SRV_Channel.cpp
Labels: MergeOnCIPass

#21332 autotest: retain elf files on build server
  Tools/scripts/build_binaries.py
Labels: DevCallEU

#21437 Tools: include blimp in manifest
  Tools/scripts/generate_manifest.py
Labels: DevCallTopic, DevCallEU

#21433 AP_HAL_ChibiOS: remove unused HAL_RCIN_PULSE_PPM_ONLY define
  libraries/AP_HAL_ChibiOS/hwdef/iomcu/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/iomcu_f103_8MHz/hwdef.dat
Labels: DevCallTopic, DevCallEU

#21423 Fix omnibusf4pro-bdshot compilation; hwdef: remove ICEngine support from many boards
  libraries/AP_HAL_ChibiOS/hwdef/BeastF7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/BeastF7v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF745/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF4Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-TE/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/ReaperF745v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VRBrain-v51/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VRUBrain-v51/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-sd/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
Labels: DevCallTopic, DevCallEU

#21424 Rover: return true straight away in prearm checks if armed
  Rover/AP_Arming.cpp
Labels: DevCallTopic, DevCallEU

#21434 autotest: switch sim_vehicle to EKF3
  Tools/autotest/default_params/quadplane.parm
Labels: SITL, VTOL-Plane, MergeOnCIPass

#21436 Tools: build_autotest.sh: sync submodules from new master not old
  Tools/scripts/build_autotest.sh
Labels: MergeOnCIPass

#21477 AP_Scripting: unint32: remove integer range check
  libraries/AP_Scripting/lua_boxed_numerics.cpp
Labels: Scripting

#21484 autotest: correct Rover DriveMission test
  Tools/autotest/common.py
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#21480 autotest: stop vehicle running into terrain in MAV_CMD_NAV_LOITER_TURNS
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#21486 autotest: let heading settle before testing WP_YAW_BEHAVIOR=0
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#21481 AP_Module: correct ModuleTest example for lack of GCS object
  libraries/AP_Module/examples/ModuleTest/ModuleTest.cpp
Labels: MergeOnCIPass

#21489 Copter: auto takeoff may trigger terrain failsafe
  ArduCopter/takeoff.cpp
Labels: BUG, Copter

#21500 autotest: terminate FTP session after transfering files
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21501 autotest: allow more time for Rover to go to smartrtl intermediate point
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#21491 Rover: include fix in mode.h
  Rover/Rover.h
  Rover/mode.cpp
  Rover/mode.h
  Rover/mode_acro.cpp
  Rover/mode_auto.cpp
  Rover/mode_follow.cpp
  Rover/mode_guided.cpp
  Rover/mode_hold.cpp
  Rover/mode_loiter.cpp
  Rover/mode_manual.cpp
  Rover/mode_rtl.cpp
  Rover/mode_simple.cpp
  Rover/mode_smart_rtl.cpp
  Rover/mode_steering.cpp
Labels: Rover

#21503 build_binaries.py: write fwversion out even if directory exists
  Tools/scripts/build_binaries.py
Labels: NeedsTesting

#21289 Plane: Quadplane: add option to refuse change to FW mode at low altitude
  libraries/AP_Scripting/applets/QuadPlane_Low_Alt_FW_mode_prevention.lua
  libraries/AP_Scripting/applets/QuadPlane_Low_Alt_FW_mode_prevention.md
Labels: VTOL-Plane, Scripting, WikiNeeded

#21482 Tools: SITL copter param file for wind speed estimation
  Tools/autotest/default_params/copter-wind-estimates.parm
Labels: Copter, SITL

#21514 autotest: make pysim/util.py AP_FLAKE8_CLEAN
  Tools/autotest/pysim/util.py
Labels: MergeOnCIPass

#21511 autotest: use assert_receive_message
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21525 autotest: wait for logging to be good in replay GPS test
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#21498 Bdshot version of MatekF405-Wing
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing-bdshot/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing-bdshot/hwdef.dat
Labels: AllVehicles, Driver, DevCallEU

#21524 Pixhawk 1M bdshot
  Tools/scripts/board_list.py
Labels: BUG, DevCallEU

#21516 Avoid undefined floating point exceptions on macOS when using implicit casts
  libraries/AP_Declination/AP_Declination.cpp
Labels: BUG

#21527 AP_Mount: fix SITL crash when user sets mode to GPS_POINT with all zero lat,lon,alt
  libraries/AP_Mount/AP_Mount_Backend.cpp
Labels: BUG, DevCallEU

#21517 AP_OpticalFlow: allow use of OpticalFlow on SimOnHardWare
  libraries/AP_OpticalFlow/AP_OpticalFlow.cpp
  libraries/AP_OpticalFlow/AP_OpticalFlow.h
  libraries/AP_OpticalFlow/AP_OpticalFlow_Backend.h
  libraries/AP_OpticalFlow/AP_OpticalFlow_SITL.cpp
  libraries/AP_OpticalFlow/AP_OpticalFlow_SITL.h
Labels: DevCallEU

#21518 Tools: check_replay.py: add --ignore-field option
  Tools/Replay/check_replay.py
Labels: DevCallEU

#21537 Tools: fixed sim_vehicle.py with -n
  Tools/autotest/sim_vehicle.py
Labels: SITL, DevCallTopic

#21542 Tools: add dronecan to install scripts
  Tools/environment_install/install-prereqs-arch.sh
  Tools/environment_install/install-prereqs-mac.sh
  Tools/environment_install/install-prereqs-ubuntu.sh
  Tools/environment_install/install-prereqs-windows-andAPMSource.ps1
  Tools/environment_install/install-prereqs-windows.ps1
Labels: DevEnv

#21552 AP_SerialManager: generalize EFI serial protocol name
  libraries/AP_SerialManager/AP_SerialManager.cpp
Labels: MergeOnCIPass

#21549 autotest: remove global variable
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21550 autotest: disable SpeedToFly McReady tests
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#21548 autotest: do not wait for ACK from reboot command
  Tools/autotest/common.py
Labels: MergeOnCIPass

#20692 AP_BattMonitor: move read_block up to SMBus base class
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus.h
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Generic.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Generic.h
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_SUI.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_SUI.h
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Solo.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Solo.h
Labels: Library, DevCallTopic, NeedsTesting

#21546 AP_Mount: allow users to disable yaw on 3-axis gimbals
  libraries/AP_Mount/AP_Mount_Alexmos.cpp
  libraries/AP_Mount/AP_Mount_Backend.h
  libraries/AP_Mount/AP_Mount_Gremsy.h
  libraries/AP_Mount/AP_Mount_SToRM32.cpp
  libraries/AP_Mount/AP_Mount_SToRM32.h
  libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
  libraries/AP_Mount/AP_Mount_SToRM32_serial.h
  libraries/AP_Mount/AP_Mount_Servo.cpp
Labels: BUG, Enhancement, Driver

#21551 Copter: Arming: check EKF height variance
  ArduCopter/AP_Arming.cpp
  ArduCopter/Parameters.cpp
Labels: Copter, DevCallTopic

#21557 HWDEF: correct default params file and readme for SPR H7
  libraries/AP_HAL_ChibiOS/hwdef/SPRacingH7/README.md
  libraries/AP_HAL_ChibiOS/hwdef/SPRacingH7/defaults.parm
Labels: DevCallTopic

#21570 AP_RPM: added AP_Generator support
  libraries/AP_RPM/AP_RPM.cpp
  libraries/AP_RPM/AP_RPM.h
  libraries/AP_RPM/AP_RPM_Params.cpp
  libraries/AP_RPM/RPM_Generator.cpp
  libraries/AP_RPM/RPM_Generator.h
Labels: NeedsTesting

#21573 Copter: display throttle below failsafe only when display_failure set
  ArduCopter/AP_Arming.cpp
Labels: BUG, Copter, MergeOnCIPass

#21567 Copter: fix auto mode is_taking_off
  ArduCopter/mode_auto.cpp
Labels: BUG, Copter

#21347 SRV_Channel: Passthrough mapped RC channels
  libraries/SRV_Channel/SRV_Channel.cpp
  libraries/SRV_Channel/SRV_Channel.h
  libraries/SRV_Channel/SRV_Channel_aux.cpp
Labels: WikiNeeded, DevCallEU

#21543 Tools: make hirsute and impish support EOL for env install and vagrant.
  Tools/environment_install/install-prereqs-ubuntu.sh
  Vagrantfile
Labels: DevEnv, DevCallEU

#20958 fix: baro same driver multi-definition issues:20887
  libraries/AP_Baro/AP_Baro.cpp
  libraries/AP_Baro/AP_Baro.h
  libraries/AP_Baro/AP_Baro_BMP085.cpp
Labels: BUG, Library
