Repository ArduPilot/ardupilot, pull requests merged in 2022-09, with the labels that each got.

#21553 Copter: Payload Place: Improve touchdown test
  ArduCopter/mode_auto.cpp
Labels: BUG, Enhancement, Copter, Safety

#21608 Copter: PosHold: remove unnecessary loiter_nav->update
  ArduCopter/mode_poshold.cpp
Labels: Copter, MergeOnCIPass

#21607 SITL: fix simulated RC failure while receiving RC overrides
  libraries/AP_HAL_SITL/SITL_State.cpp
Labels: MergeOnCIPass

#21623 autotest: explicltly close filehandle with streamrate contents
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#21631 Tools: fix readme error for signing script
  Tools/scripts/signing/README.md
Labels: BUG

#21632 Plane: correct extened range airspeed scailing limits
  ArduPlane/Attitude.cpp
Labels: Plane, NeedsTesting

#21611 AP_GPS: remove incorrect build option on GPS_DRV_OPTIONS param
  libraries/AP_GPS/AP_GPS.cpp
Labels: BUG, DevCallTopic

#21638 Plane: add min airspeed arming check and constrain for speed scailing
  ArduPlane/AP_Arming.cpp
  ArduPlane/Attitude.cpp
  ArduPlane/defines.h
Labels: Plane, DevCallTopic

#21591 CI: Build with all/no options enabled
  Tools/scripts/build_ci.sh
Labels: DevCallTopic

#21639 Copter: fix do-mount-control yaw scaling
  ArduCopter/GCS_Mavlink.cpp
Labels: BUG, Copter

#21619 Tools: fix build option for MSP Optical Flow sensor and cleanup
  Tools/scripts/build_options.py
Labels: DevCallTopic

#21640 AP_Rangefinder: fixed out of range issue with benewake uart lidars
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake.cpp
Labels: BUG

#21644 Tools: Add ROS and Ardupilot-ros environment install script
  Tools/environment_install/install-ROS-ubuntu.sh
Labels: DevEnv, Tools, MergeOnCIPass

#18398 AP_Logger: Be stricter on MAVLink ack handling
  libraries/AP_Logger/AP_Logger_MAVLink.cpp
Labels: Logging, DevCallTopic

#21583 GCS_MAVLink: Check for mission space before sending items
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/MissionItemProtocol.cpp
  libraries/GCS_MAVLink/MissionItemProtocol_Waypoints.cpp
Labels: BUG, MAVLink, DevCallTopic

#21670 Tools: install_ROS_ubuntu points at ArduPilot repo
  Tools/environment_install/install-ROS-ubuntu.sh
Labels: DevEnv, Tools

#21668 Tools: remove vestiges of travis autotest hooks
  Tools/autotest/arducopter.py
  Tools/autotest/autotest.py
  Tools/scripts/build_ci.sh
Labels: MergeOnCIPass

#21672 Rover: fix overshoot beyond stopping dist in dock mode
  Rover/mode_dock.cpp
Labels: MergeOnCIPass

#21669 autotest: move log_name method for balancebot to within class
  Tools/autotest/balancebot.py
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21656 Tools: generate_manifest.py: allow generation of features.json file
  Tools/scripts/build_binaries.py
  Tools/scripts/generate_manifest.py
Labels: MergeOnCIPass

#21679 autotest: check context for expected esc-rpm statustext
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#21682 autotest: use reflection to collect test details
  Tools/autotest/antennatracker.py
  Tools/autotest/arducopter.py
  Tools/autotest/arduplane.py
  Tools/autotest/ardusub.py
  Tools/autotest/balancebot.py
  Tools/autotest/common.py
  Tools/autotest/helicopter.py
  Tools/autotest/quadplane.py
  Tools/autotest/rover.py
  Tools/autotest/sailboat.py
Labels: MergeOnCIPass

#21258 autotest: test landed state of copter during takeoff in auto mode
  Tools/autotest/ArduCopter_Tests/MAVLandedStateTakeoff/copter_mission.txt
  Tools/autotest/arducopter.py
  Tools/autotest/common.py
  Tools/autotest/quadplane.py
Labels: Copter, CI, MergeOnCIPass

#21683 hwdef: fixed FlyingmoonF427 servo rail voltage
  libraries/AP_HAL_ChibiOS/hwdef/FlyingMoonF427/hwdef.dat
Labels: MergeOnCIPass

#21621 hwdef: Hitec-Airspeed: disable UART to save flash
  libraries/AP_HAL_ChibiOS/hwdef/Hitec-Airspeed/hwdef.dat
Labels: NeedsTesting

#21249 Tools: Check if version exist before installing it
  Tools/environment_install/install-prereqs-mac.sh
Labels: DevEnv, MergeOnCIPass

#21692 autotest: ensure MAVProxy arm attempt times out
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21693 autotest: correct running of single test
  Tools/autotest/autotest.py
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21694 autotest: remove syntax test for test lambdas
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21696 autotest: remove disabled LogUpload test
  Tools/autotest/arducopter.py
  Tools/autotest/arduplane.py
  Tools/autotest/ardusub.py
  Tools/autotest/balancebot.py
  Tools/autotest/common.py
  Tools/autotest/helicopter.py
  Tools/autotest/quadplane.py
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#21687 AC_Fence: always clear breaches
  libraries/AC_Fence/AC_Fence.cpp
Labels: DevCallTopic

#21703 autotest: correct type-check
  Tools/autotest/autotest.py
Labels: MergeOnCIPass

#20590 autotest: Fix watch_altitude_maintained for Copter
  Tools/autotest/arducopter.py
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21654 AP_Arming: Expose ARMING_OPTIONS to all vehicles
  libraries/AP_Arming/AP_Arming.cpp
Labels: Library, AllVehicles, DevCallTopic

#21664 GCS_MAVLink: add warnings if older messages used
  libraries/GCS_MAVLink/GCS_Common.cpp
  libraries/GCS_MAVLink/MissionItemProtocol.cpp
  libraries/GCS_MAVLink/MissionItemProtocol.h
Labels: MAVLink, DevCallTopic

#21667 autotest: fail if no steps supplied and not autotest server
  Tools/autotest/autotest.py
Labels: DevCallTopic

#21648 AP_Scripting: enforce skip check on correct types update description to match
  libraries/AP_Scripting/generator/description/bindings.desc
  libraries/AP_Scripting/generator/src/main.c
Labels: Scripting, MergeOnCIPass

#21709 SITL: fixed tailsitter airspeed in RF9
  libraries/SITL/SIM_FlightAxis.cpp
Labels: SITL, MergeOnCIPass

#19981 Plane: remove logging of CMDI
  ArduPlane/GCS_Mavlink.cpp
  ArduPlane/Log.cpp
  ArduPlane/Plane.h
  ArduPlane/defines.h
Labels: DevCallEU

#21717 Fix reporting of RPM from the harmonic notch
  libraries/AP_RPM/RPM_HarmonicNotch.cpp
Labels: BUG, DevCallEU, 4.2 Issue, 4.2 backport

#20997 AP_OSD: fixed serial port initialization for MSP DisplayPort protocol
  libraries/AP_OSD/AP_OSD.cpp
  libraries/AP_OSD/AP_OSD_Backend.h
  libraries/AP_OSD/AP_OSD_MSP_DisplayPort.cpp
  libraries/AP_OSD/AP_OSD_MSP_DisplayPort.h
Labels: BUG, Library, OSD, MergeOnCIPass

#21706 LIB: change PROXIMITY_GND_DETECT_THRESHOLD to param
  libraries/AP_Proximity/AP_Proximity.cpp
  libraries/AP_Proximity/AP_Proximity.h
  libraries/AP_Proximity/AP_Proximity_Utils.cpp
Labels: Enhancement, Copter, Rover, MergeOnCIPass

#21721 AP_HAL_SITL: do not return from reboot command
  libraries/AP_HAL_SITL/HAL_SITL_Class.cpp
  libraries/AP_HAL_SITL/Scheduler.cpp
  libraries/AP_HAL_SITL/Scheduler.h
Labels: MergeOnCIPass

#21688 AP_Motors: added a SPIN_MIN check
  libraries/AP_Motors/AP_MotorsMulticopter.cpp
Labels: VTOL-Plane, MergeOnCIPass

#21726 AP_Logger: Fix an error in the doc string for the MAVC message
  libraries/AP_Logger/LogStructure.h
Labels: Docs

#21598 AP_OSD: added missing parameter meta information for OSD_TYPE=5
  libraries/AP_OSD/AP_OSD.cpp
Labels: Library, OSD

#21200 SRV_Channels.cpp: small correction
  libraries/SRV_Channel/SRV_Channels.cpp
Labels: Docs

#21728 Autotest: fixes bisect-helper for python 3.10
  Tools/autotest/bisect-helper.py
Labels: MergeOnCIPass

#21661 AP_InertialSensor: Remove line breaks from PANIC strings
  libraries/AP_InertialSensor/AP_InertialSensor_BMI270.cpp
Labels: MergeOnCIPass

#21718 Tools: cygwin install script add pexpect
  Tools/environment_install/install-prereqs-windows-andAPMSource.ps1
  Tools/environment_install/install-prereqs-windows.ps1
Labels: Tools

#21660 AP_Mission: Share the method RETURN
  libraries/AP_Mission/AP_Mission_Commands.cpp
Labels: MergeOnCIPass

#21585 AP_Scripting: added example script for ship takeoff vel match
  libraries/AP_Scripting/examples/ship_vel_match.lua
Labels: VTOL-Plane, Scripting

#21742 autotest: add a drive_to_location for Rover
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#21743 autotest: correct reboot in failure case for dock mode test
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#21740 autotest: explicitly fail reboot if armed
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21034 ArduPlane: add 0 disable to FLTMODE_CH parameter doc
  ArduPlane/Parameters.cpp
Labels: Plane, Docs

#21390 AP_InertialSensor: Allow gyro counts to be returned
  libraries/AP_InertialSensor/AP_InertialSensor.h
Labels: BUG, Library

#21575 AP_BattMonitor: fix Rotoye Temperature Monitoring
  libraries/AP_BattMonitor/AP_BattMonitor_SMBus_Rotoye.cpp
Labels: Driver

#21737 AP_Mount: remove set_mode overrides to fix mode defaulting at startup
  libraries/AP_Mount/AP_Mount_Backend.h
  libraries/AP_Mount/AP_Mount_SToRM32.cpp
  libraries/AP_Mount/AP_Mount_SToRM32.h
  libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
  libraries/AP_Mount/AP_Mount_SToRM32_serial.h
  libraries/AP_Mount/AP_Mount_SoloGimbal.cpp
  libraries/AP_Mount/AP_Mount_SoloGimbal.h
Labels: BUG, Driver, NeedsTesting

#21735 SRV_Channel: adjust trim, check all channels for range limit
  libraries/SRV_Channel/SRV_Channel_aux.cpp
Labels: Plane

#21751 SITL: SIM_Rotoye update TEMP_EXT Register
  libraries/SITL/SIM_BattMonitor_SMBus_Rotoye.h
Labels: SITL, MergeOnCIPass

#21710 AIRLink: USART2 enabled in hwdef
  libraries/AP_HAL_ChibiOS/hwdef/AIRLink/hwdef.dat
Labels: MergeOnCIPass, 4.3 Backport

#19762 AP_OSD: Added new per screen PARAMs for HD OSD options
  libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
  libraries/AP_MSP/AP_MSP_Telem_Backend.h
  libraries/AP_MSP/msp.h
  libraries/AP_OSD/AP_OSD.h
  libraries/AP_OSD/AP_OSD_MSP_DisplayPort.cpp
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: Library, WikiNeeded, DevCallEU, 4.3 Backport

#21749 AP_MSP: move arming status to MSP telemetry base class
  libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
  libraries/AP_MSP/AP_MSP_Telem_Backend.h
  libraries/AP_MSP/AP_MSP_Telem_DJI.cpp
Labels: Library, AllVehicles, DevCallEU, 4.3 Backport

#21748 Make sure notches are not spuriously disabled when not using throttle notch
  libraries/AP_Vehicle/AP_Vehicle.cpp
Labels: BUG, 4.3 Backport

#21727 Disable DMA on I2C on bdshot boards to free up DMA channels
  libraries/AP_HAL_ChibiOS/hwdef/BeastF7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/BeastH7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CUAV-X7-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CUAVv5-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF745/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF745Nano/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MambaH743v4/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekH743-bdshot/hwdef.dat
Labels: BUG, DevCallEU

#21761 AP_Mission: prevent use of uninitialised stack data
  libraries/AP_Mission/AP_Mission.cpp
Labels: BUG, MergeOnCIPass

#21762 AP_Scripting: simple script for plane GUIDED follow
  libraries/AP_Scripting/examples/plane_guided_follow.lua
Labels: Plane, Scripting, MergeOnCIPass

#21764 RC_Channel: save some bytes by excluding functions
  libraries/RC_Channel/RC_Channel.cpp
Labels: MergeOnCIPass

#21763 Optimize notch filter frequency updates when the requested frequency has not changed
  libraries/Filter/NotchFilter.cpp
  libraries/Filter/NotchFilter.h
Labels: BUG, 4.3 Backport

#21770 autotest: add a method to easily install message printer
  Tools/autotest/common.py
Labels: MergeOnCIPass

#21798 AP_OSD: update HD font files to remove blank space artifacts
  libraries/AP_OSD/fonts/HDFonts/Color/font.bin
  libraries/AP_OSD/fonts/HDFonts/Color/font_hd.bin
Labels: DevCallTopic

#21744 AP_Filesystem_Param: Better estimation of filesize
  libraries/AP_Filesystem/AP_Filesystem_Param.cpp
Labels: DevCallTopic

#21769 Initialize jump-tracking in AP_Mission::init()
  libraries/AP_Mission/AP_Mission.cpp
Labels: BUG, Copter, Plane, DevCallTopic

#21783 ArduPlane: fixed roll and pitch for OSD VTOL view
  ArduPlane/ArduPlane.cpp
  ArduPlane/Plane.h
  libraries/AP_Vehicle/AP_Vehicle.cpp
  libraries/AP_Vehicle/AP_Vehicle.h
Labels: BUG, Plane, DevCallTopic, OSD

#21816 hwdef: reduced memory usage on MatekF405-CAN board
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-CAN/hwdef.dat
Labels: hwdef

#21827 AP_Vehicle: add 0x to internal error statustext
  libraries/AP_Vehicle/AP_Vehicle.cpp
Labels: MergeOnCIPass

#21829 AP_CANManager: disable SLCAN when armed
  libraries/AP_CANManager/AP_SLCANIface.cpp
Labels: CAN, WikiNeeded

#21698 Copter: use 3d vector from plnd to slow down
  ArduCopter/mode.cpp
Labels: Enhancement, Copter, NeedsTesting
