Repository ArduPilot/ardupilot, pull requests merged in 2022-04, with the labels that each got.

#20413 AP_Logger: increase stack of log_io thread by 256
  libraries/AP_Logger/AP_Logger.cpp
Labels: MergeOnCIPass

#20402 Blimp: add temporary GCS FS behavior of disarming Blimp
  Blimp/events.cpp
Labels: Blimp

#20401 Tools: add blimp as vehicle option in sim_vehicle
  Tools/autotest/sim_vehicle.py
Labels: SITL

#20394 Plane: fixed rudder control when ARMING_RUDDER != 2
  ArduPlane/quadplane.cpp
Labels: BUG, VTOL-Plane

#20429 autotest: add more convenience methods for checking received data
  Tools/autotest/common.py
Labels: MergeOnCIPass

#20418 Update: AP_Periph Hwdef Carbonix l496
  libraries/AP_HAL_ChibiOS/hwdef/CarbonixL496/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/CarbonixL496/hwdef.dat
Labels: DevCallTopic, hwdef, Partner

#20422 AP_Airspeed: correct metadata for params for non-Plane vehicles
  libraries/AP_Airspeed/AP_Airspeed.cpp
Labels: DevCallTopic

#20433 AP_Scripting: remove original aerobatics example to avoid confusion
  libraries/AP_Scripting/examples/plane_aerobatics.lua
Labels: DevCallTopic

#20404 autotest: correct extraction of fields from LogWrite messages
  Tools/autotest/common.py
Labels: MergeOnCIPass

#20339 hwdef: add hwdef for CubeOrange-SimOnHardware
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-SimOnHardWare/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-SimOnHardWare/hwdef.dat
Labels: WIP, NeedsTesting

#20459 AP_Logger: fixed @SYS file logging
  libraries/AP_Logger/AP_Logger.cpp
Labels: BUG, MergeOnCIPass

#20454 Copter: factor failsafe reporting
  ArduCopter/Copter.h
  ArduCopter/events.cpp
Labels: Copter, DevCallEU

#20395 AP_HAL_ChibiOS: CUAV-Nora: add usart3 support
  libraries/AP_HAL_ChibiOS/hwdef/CUAV-Nora/hwdef.dat
Labels: WikiNeeded

#20462 hwdef: disable GPS drivers on low flash boards
  libraries/AP_HAL_ChibiOS/hwdef/F35Lightning/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF4/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MambaF405v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/OmnibusNanoV6/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/SuccexF4/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VRUBrain-v51/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/fmuv2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/include/minimal_GPS.inc
  libraries/AP_HAL_ChibiOS/hwdef/omnibusf4v6/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/speedybeef4/hwdef.dat
Labels: GPS, BuildSystem

#20439 hwdef: fix redefinition of Solo values in CubeSolo/CubeGreen-Solo
  libraries/AP_HAL_ChibiOS/hwdef/CubeGreen-solo/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CubeSolo/hwdef.dat
Labels: DevCallEU

#20331 Slight tidy of GPS blending
  libraries/AP_GPS/AP_GPS.cpp
Labels: DevCallEU

#20425 Blimp: remove land_acel_ef_filter
  Blimp/Blimp.cpp
  Blimp/Blimp.h
Labels: DevCallEU

#20477 Tools: added script to make using a crash_dump.bin easier
  Tools/debug/gdb_crashdump.sh
Labels: ChibiOS

#20482 autotest: fixed annoying gdb pagination on reboot
  Tools/autotest/sim_vehicle.py
Labels: MergeOnCIPass

#20496 Tools: allow size-compare_branches.py on AP_Periph
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#20506 AP_Scripting: increase default heap size in SITL and on F7/H7
  libraries/AP_Scripting/AP_Scripting.cpp
Labels: Scripting

#20423 Tools: add airspeed defaults to vehicle defaults files
  Tools/autotest/default_params/blimp.parm
  Tools/autotest/default_params/copter.parm
  Tools/autotest/default_params/rover.parm
  Tools/autotest/default_params/sailboat.parm
  Tools/autotest/default_params/sub.parm
Labels: DevCallTopic, MergeOnCIPass

#20474 hwdef: minimal GPS support for Flywoo boards
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF745/hwdef.dat
Labels: DevCallTopic, WikiNeeded

#20502 Check CRSF EKF checks against failsafe defaults
  libraries/AP_RCTelemetry/AP_RCTelemetry.cpp
Labels: BUG, DevCallTopic

#20515 Tools: added QioTekAdeptF427 board ID
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#20520 hwdef: remove non-ascii character from hwdef
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-sd/hwdef.dat
Labels: MergeOnCIPass

#20503 Plane: disable pitch based weathervaning for quadplanes
  libraries/AC_AttitudeControl/AC_WeatherVane.cpp
  libraries/AC_AttitudeControl/AC_WeatherVane.h
Labels: VTOL-Plane, WikiNeeded, DevCallEU

#20524 Tools: fix cygwin build error
  Tools/scripts/cygwin_build.sh
Labels: BuildSystem, MergeOnCIPass

#20466 Copter: properly set feedforward enabled before exiting SysID
  ArduCopter/mode.h
  ArduCopter/mode_systemid.cpp
Labels: BUG, Copter, TradHeli

#20536 autotest: test_build_options.py: undef variables before setting them
  Tools/autotest/test_build_options.py
Labels: MergeOnCIPass

#20552 autotest: tidy richenpower test using new methods
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#20387 AP_HAL_ChibiOS: add support for NucleoH755 board
  libraries/AP_HAL_ChibiOS/hwdef/NucleoH755/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/NucleoH755/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/NucleoH755/hwdef.dat
Labels: hwdef

#20553 Plane: Updated highest airspeed limit when armed
  ArduPlane/Attitude.cpp
Labels: Plane

#20557 AP_Scripting: correct script restart send_text message
  libraries/AP_Scripting/AP_Scripting.cpp
Labels: Scripting, MergeOnCIPass

#20546 AP_NavEKF: GSF logging in deg from 0 to 360
  libraries/AP_NavEKF/EKFGSF_Logging.cpp
  libraries/AP_NavEKF/LogStructure.h
Labels: EKF, Logging, DevCallTopic

#20475 AP_AHRS_DCM: fix normalization reset
  libraries/AP_AHRS/AP_AHRS_DCM.cpp
Labels: DevCallTopic

#20529 SITL: JSON: add more keywords to define a vehicle
  libraries/SITL/SIM_Frame.cpp
  libraries/SITL/SIM_Frame.h
  libraries/SITL/SIM_Motor.cpp
  libraries/SITL/SIM_Motor.h
Labels: SITL, DevCallTopic

#20540 AP_Logger: must set default fd = -1
  libraries/AP_Logger/AP_Logger.h
Labels: BUG, DevCallTopic, 4.2 Issue

#20509 Plane: add Q_OPTION for RTL always on VTOL RC failsafe for ship landing
  ArduPlane/events.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: WikiNeeded, MergeOnCIPass

#20578 Tools: Update GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#20580 HAL_ChibiOS: disable fatal exceptions for DMA errors
  libraries/AP_HAL_ChibiOS/hwdef/common/mcuconf.h
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32f1_mcuconf.h
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32f3_mcuconf.h
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32f47_mcuconf.h
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32g4_mcuconf.h
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32l4_mcuconf.h
Labels: BUG, ChibiOS

#20517 AP_HAL: remove BRD_PWM_COUNT reference
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/hwdef.dat
Labels: Docs, hwdef

#20571 AP_CustomRotations: fix param referencing
  libraries/AP_CustomRotations/AP_CustomRotations.cpp
  libraries/AP_CustomRotations/AP_CustomRotations.h
Labels: BUG, DevCallEU

#20573 actions: skip periph check on gcc6
  .github/workflows/test_chibios.yml
Labels: DevEnv, DevCallEU, MergeOnCIPass

#20588 AP_Proximity_Boundary_3D:correction of miswriting
  libraries/AP_Proximity/AP_Proximity_Boundary_3D.h
Labels: BUG, MergeOnCIPass

#20591 Blimp: Update displayed version to current version
  Blimp/version.h
Labels: MergeOnCIPass

#20600 Tools: add name to Git_Test (retry)
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#20610 autotest: fix Rover syntax for Python2
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#20579 AP_RPM: avoid attach interrupt retry and spam to GCS if PIN = -1
  libraries/AP_RPM/RPM_Pin.cpp
  libraries/AP_RPM/RPM_Pin.h
Labels: BUG, DevCallTopic

#20620 AP_Rangefinder: VL53L1X Preserve new address
  libraries/AP_RangeFinder/AP_RangeFinder_VL53L1X.cpp
Labels: BUG, Library

#20634 hwdef: uncompress bootloader for HolybroG4_GPS
  libraries/AP_HAL_ChibiOS/hwdef/HolybroG4_GPS/hwdef.dat
Labels: AP_Periph, DevCallEU

#20635 Tools: fixed type of max-gap in CAN fix2 script
  Tools/scripts/CAN/fix2_gap.py
Labels: CAN, DevCallEU

#20630 iFlight Chimera 7 parameters
  Tools/Frame_params/iflight-chimera7-4.2.param
Labels: DevCallEU, 4.2 Issue

#20581 Catch and handle STM32_DMA_ISR_DMEIF in bdshot
  libraries/AP_HAL_ChibiOS/RCOutput_bdshot.cpp
Labels: BUG, ChibiOS, DevCallEU, 4.2 Issue

#20348 AP_InertialSensor: Added BMI085 support
  Tools/scripts/decode_devid.py
  libraries/AP_InertialSensor/AP_InertialSensor_BMI088.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_BMI088.h
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
Labels: NeedsTesting, DevCallEU, Partner

#20641 Rover: wscript: remove AP_L1_Control
  Rover/wscript
Labels: Rover, MergeOnCIPass

#20649 Allow high ANGLE_P gains in autotune
  libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
Labels: Enhancement, Copter

#20636 AP_Periph: mark ESC DShot channels as digital
  Tools/AP_Periph/rc_out.cpp
Labels: AP_Periph
