Repository ArduPilot/ardupilot, pull requests merged in 2022-11, with the labels that each got.

#22086 Plane: implement quaternion based ACRO mode
  ArduPlane/Attitude.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/Plane.h
  ArduPlane/mode_acro.cpp
  ArduPlane/mode_qacro.cpp
Labels: Plane, NeedsTesting, WikiNeeded

#22093 Plane: zero error on release of sticks
  ArduPlane/Attitude.cpp
  ArduPlane/Plane.h
Labels: Plane

#22107 AP_Scripting: added crossbox humpty maneuvers
  libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua
Labels: Scripting

#22126 AP_HAL: add missing include for APM_BUILD_TYPE
  libraries/AP_HAL/SIMState.cpp
Labels: MergeOnCIPass

#22132 Fix bisect helper when run in build mode
  Tools/autotest/bisect-helper.py
Labels: MergeOnCIPass

#22096 Plane: added AUTOTUNE_AXES function to normal tune
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/Plane.h
  ArduPlane/control_modes.cpp
Labels: DevCallTopic, WikiNeeded

#22142 AP_GPS: disable GPS lag checking in AP_Periph
  libraries/AP_GPS/GPS_Backend.cpp
Labels: GPS, DevCallTopic, AP_Periph

#22149 AP_Logger: need to be able to finish format messages even when there …
  libraries/AP_Logger/LoggerMessageWriter.cpp
Labels: MergeOnCIPass

#22156 AP_Scripting: allow aerobatic sequences to load from a txt file
  libraries/AP_Scripting/examples/Aerobatics/Trajectory/plane_aerobatics.lua
  libraries/AP_Scripting/examples/Aerobatics/Trajectory/trick72.txt
Labels: Scripting

#22139 AP_GPS: fixed injection of RTCM on 2 different CAN buses
  libraries/AP_GPS/AP_GPS_UAVCAN.cpp
Labels: BUG, CAN

#21601 autotest: drain self.mav while waiting on other link
  Tools/autotest/common.py
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#22162 Fix parameter caching with RunCam enablement and setup on 3-pos switch
  libraries/AP_Camera/AP_RunCam.cpp
Labels: BUG, DevCallEU, 4.3 Backport

#22171 AP_Filesystem: fixed open to return nullptr on failure
  libraries/AP_Filesystem/posix_compat.cpp
Labels: BUG, Scripting

#22167 HAL_SITL: only do the cygwin speedup hack for scripting while armed
  libraries/AP_HAL_SITL/SITL_State.cpp
  libraries/AP_HAL_SITL/Scheduler.cpp
  libraries/AP_HAL_SITL/Scheduler.h
Labels: SITL

#22151 AP_Mount: gremsy driver sends vehicle attitude at 50hz
  libraries/AP_Mount/AP_Mount_Gremsy.cpp
Labels: BUG

#22178 Rover: add MANUAL_STR_EXPO
  Rover/Parameters.cpp
  Rover/Parameters.h
  Rover/mode_manual.cpp
Labels: Enhancement, Rover, WikiNeeded

#22182 autotest: tight turns for plane-3d
  Tools/autotest/models/plane-3d.parm
Labels: Plane, SITL

#22014 AP_LeakDetector: add manual leak-pin selection to extend board compatibility
  libraries/AP_LeakDetector/AP_LeakDetector.cpp
  libraries/AP_LeakDetector/AP_LeakDetector.h
Labels: NeedsTesting

#22192 AP_Scripting: added yaw angular accel limit for aerobatics
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Plane, Scripting

#22196 AP_Scripting: minor aerobatics fixes
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting

#22106 AP_Scripting: use helpers for full range return types to save flash
  libraries/AP_Scripting/generator/description/bindings.desc
  libraries/AP_Scripting/generator/src/main.c
  libraries/AP_Scripting/lua_bindings.cpp
Labels: Scripting

#22147 AP_Mission: DO_LAND_START to consider altitude (3D distance)
  libraries/AP_Mission/AP_Mission.cpp
Labels: Enhancement, WikiNeeded

#22201 Tools: blacklist the SkystarsH7HD board,use only bd-shot version
  Tools/scripts/board_list.py
Labels: DevCallTopic

#22205 autotest: use implicit context for AutoTuneSwitch
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#22195 autotest: tighten tolerances on beacon test
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#22207 hwdef: disable notify displays on SkyViper
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
Labels: MergeOnCIPass

#22208 AP_InertialSensor: various SITL INS improvements
  libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_SITL.h
Labels: MergeOnCIPass

#22212 AP_Scripting: implement path lookahead for aerobatics
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting

#22215 AP_MotorsHeli: update H_DUAL_MODE description to include coaxial
  libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
Labels: TradHeli, MergeOnCIPass

#22214 AP_Math: make rand_vec a little more efficient
  libraries/AP_Math/AP_Math.cpp
  libraries/AP_Math/AP_Math.h
Labels: MergeOnCIPass

#22222 AP_Scripting: Fixed barrel roll arc
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: MergeOnCIPass

#22230 AP_Scripting: added AEROM_PATH_SCALE
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Plane, Scripting

#22242 AP_Scripting: added roll_sequence to simplify complex manuevers
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting

#22240 AP_Scripting: added set_orient and funny_loop
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting

#22243 AP_Scripting: update readme on plane_aerobatics
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md
Labels: DevCallTopic

#22193 AC_AutoTune: Tuned Gains not loaded during pilot testing
  libraries/AC_AutoTune/AC_AutoTune.cpp
Labels: BUG, Copter, 4.3 Backport

#22234 Retry RunCam device info maximum number of times
  libraries/AP_Camera/AP_RunCam.cpp
Labels: BUG, 4.3 Backport

#22248 AP_GPS: improve support for uBlox-M10
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
  libraries/AP_GPS/AP_GPS_UBLOX.h
Labels: GPS, MergeOnCIPass

#22233 Inform GCS that turtle mode is active
  ArduCopter/mode.h
  ArduCopter/mode_turtle.cpp
Labels: BUG, DevCallEU, 4.3 Backport

#22270 autotest: add a test for EK3_RNG_USE_HGT
  Tools/autotest/arducopter.py
Labels: DevCallEU

#22029 AP_HAL_ChibiOS: add CubeOrangePlus bdshot hwdef
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-bdshot/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-bdshot/hwdef.dat
Labels: DevCallEU, MergeOnCIPass

#22262 AP_UAVCAN: update options bitmask for PWM option
  libraries/AP_UAVCAN/AP_UAVCAN.cpp
Labels: DevCallEU

#22255 AP_Scripting: remove lua acess to ap object creation
  libraries/AP_Scripting/generator/src/main.c
Labels: Scripting, DevCallEU

#22268 Tools: allocate a board ID for AP_HW_JFB100
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#22273 AP_Scripting: allow "thr_boost: true" in text aerobatic schedules
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting

#22220 Copter: remove some unused definitions
  ArduCopter/config.h
Labels: Copter, DevCallTopic

#22127 Plane: Quadplane: correct units used in rate_bf_yaw_target
  ArduPlane/quadplane.cpp
Labels: BUG, VTOL-Plane, NeedsTesting

#22291 hwdef: correct compilation of CubeOrange bdshot variants
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-bdshot/hwdef.dat
Labels: MergeOnCIPass

#22216 Add * to the end of flight mode string in CRSF
  libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
  libraries/RC_Channel/RC_Channel.h
  libraries/RC_Channel/RC_Channels_VarInfo.h
Labels: WikiNeeded

#22254 AP_Scripting: dont check objects that are expected to be null
  libraries/AP_Scripting/lua_bindings.cpp
Labels: BUG, DevCallTopic, Scripting

#22288 Plane: Quadplane: tiltrotor: add Q_OPTION to keep motors tilted up when disarmed in FW modes
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
  ArduPlane/tiltrotor.cpp
Labels: VTOL-Plane, WikiNeeded

#22296 AP_HAL_ChibiOS:remove synth curr from bds with onbd current
  libraries/AP_HAL_ChibiOS/hwdef/F35Lightning/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-TE/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/speedybeef4/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/speedybeef4v3/hwdef.dat
Labels: DevCallTopic

#22318 AP_Landing: assign values to each of the slope approach stages
  libraries/AP_Landing/AP_Landing.h
  libraries/AP_Landing/AP_Landing_Slope.cpp
Labels: DevCallEU

#22306 AP_CANManager: add an output buffer for MAVCAN
  libraries/AP_CANManager/AP_CANManager.cpp
  libraries/AP_CANManager/AP_CANManager.h
Labels: BUG, CAN, DevCallEU

#22313 AP_Mount: fix for Siyi A8
  libraries/AP_Mount/AP_Mount_Siyi.cpp
Labels: BUG, Enhancement, DevCallEU

#22293 AP_Scripting: stall turn, part 2
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting
