Repository ArduPilot/ardupilot, pull requests merged in 2023-03, with the labels that each got.

#23041 AP_HAL_ChibiOS: replace NO_FASTBOOT with AP_FASTBOOT_ENABLED (NFC)
  Tools/AP_Bootloader/AP_Bootloader.cpp
  libraries/AP_HAL_ChibiOS/Scheduler.cpp
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.c
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32_util.h
  libraries/AP_HAL_ChibiOS/hwdef/iomcu/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/iomcu_f103_8MHz/hwdef.dat
Labels: DevCallEU

#23065 AP_RangeFinder: Allow multiple USD-D1-CAN
  libraries/AP_RangeFinder/AP_RangeFinder.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_USD1_CAN.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_USD1_CAN.h
Labels: MergeOnCIPass

#16678 Plane: Auto takeoff roll-limits to use TKOFF_LVL_ALT
  ArduPlane/mode.h
  ArduPlane/mode_takeoff.cpp
  ArduPlane/takeoff.cpp
Labels: Plane, NeedsTesting, WikiNeeded, Partner

#23080 Rover: Better wording for MIS_DONE_BEHAVE (NFC)
  Rover/Parameters.cpp
Labels: Rover, MergeOnCIPass

#23078 AP_Mount: allow gimbals other than primary to be retracted/neutralised
  libraries/AP_Mount/AP_Mount.cpp
Labels: MergeOnCIPass, 4.3 Backport

#23074 GCS_MAVLink: constrain battery % to 0-100
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MAVLink, MergeOnCIPass

#23087 Tracker: remove wrong comments
  AntennaTracker/Parameters.h
Labels: AntennaTracker, MergeOnCIPass, Non-Functional Change

#23084 AP_Winch: Fix baud rate handling in AP_Winch_Daiwa
  libraries/AP_Winch/AP_Winch_Daiwa.cpp
Labels: MergeOnCIPass

#23095 SITL: correct use of uninitialised stack data in SIM_Gimbal
  libraries/SITL/SIM_Gimbal.cpp
Labels: MergeOnCIPass

#23094 AP_GPS:make Unicore reset to rover in all cases
  libraries/AP_GPS/AP_GPS_NMEA.cpp
Labels: BUG, DevCallTopic

#23106 AP_Mount: remove redundant constructors
  libraries/AP_Mount/AP_Mount_Alexmos.h
  libraries/AP_Mount/AP_Mount_Gremsy.cpp
  libraries/AP_Mount/AP_Mount_Gremsy.h
  libraries/AP_Mount/AP_Mount_SToRM32.cpp
  libraries/AP_Mount/AP_Mount_SToRM32.h
  libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
  libraries/AP_Mount/AP_Mount_SToRM32_serial.h
Labels: MergeOnCIPass

#23121 Tools: remove defunct build-with-disabled-features.py
  Tools/autotest/build-with-disabled-features.py
Labels: MergeOnCIPass

#23112 Copter: Re-enable PID logging in SystemID mode
  ArduCopter/Copter.cpp
  ArduCopter/mode_systemid.cpp
Labels: Copter, DevCallEU

#23107 GCS_MAVLink: use GCS_MAVLINK& when routing
  libraries/GCS_MAVLink/GCS_Common.cpp
  libraries/GCS_MAVLink/MAVLink_routing.cpp
  libraries/GCS_MAVLink/MAVLink_routing.h
  libraries/GCS_MAVLink/examples/routing/routing.cpp
Labels: DevCallEU

#23110 Copter: Add Radio Failsafe Brake Mode option
  ArduCopter/Copter.h
  ArduCopter/Parameters.cpp
  ArduCopter/defines.h
  ArduCopter/events.cpp
Labels: Enhancement, Copter, Safety, MergeOnCIPass

#23127 Save some bytes in the Camera library
  libraries/AP_Camera/AP_Camera.cpp
  libraries/AP_Camera/AP_Camera.h
Labels: MergeOnCIPass

#23077 Copter: pause resume reporting
  ArduCopter/mode_auto.cpp
  Tools/autotest/arducopter.py
Labels: Enhancement, Copter, MergeOnCIPass, Partner

#23146 Tools: size_compare_branches.py: change --no-elf-diff into --elf-diff
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#23145 AP_Airspeed: save some bytes by making conversion structure static
  libraries/AP_Airspeed/AP_Airspeed.cpp
Labels: MergeOnCIPass

#23137 Tools: Adding Eggemoen flying field coords
  Tools/autotest/locations.txt
Labels: Tools, MergeOnCIPass

#23152 Tools: use gcc 10.2.1 for Sub too
  Tools/scripts/build_binaries.py
Labels: MergeOnCIPass

#23140 Update GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#23141 AP_Scripting: add some docs
  libraries/AP_Scripting/docs/docs.lua
Labels: Scripting, MergeOnCIPass

#23144 Save bytes in AP_Logger to get Pixhawk1-1M-bdshot compiling again
  libraries/AP_Logger/AP_Logger.h
  libraries/AP_Logger/LogFile.cpp
  libraries/AP_Logger/LogStructure.h
Labels: MergeOnCIPass

#23172 Tools: correct feature extraction of ICM20948
  Tools/scripts/extract_features.py
Labels: MergeOnCIPass

#21532 Tools: Bring flake8 speed improvements to pre-commit
  Tools/gittools/pre-commit.py
Labels: MergeOnCIPass

#22996 AP_Mission: Jump tags to use optimized mission search
  libraries/AP_Mission/AP_Mission.cpp
Labels: DevCallTopic, MergeOnCIPass

#23175 autotest: correct race condition in spiral test
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#23179 StorageManager: fixed startup crash
  libraries/StorageManager/StorageManager.cpp
  libraries/StorageManager/StorageManager.h
Labels: BUG, MergeOnCIPass

#23143 CI: allow test_size to work on private repos
  .github/workflows/test_size.yml
Labels: CI

#23158 Tools: add Aerofox AYK320 drone param
  Tools/Frame_params/Aerofox_AYK320.param
Labels: DevCallTopic

#23142 AP_Scripting: bump SCRIPTING_HEAP_SIZE for large RAM (>=1MB) devices
  libraries/AP_Scripting/AP_Scripting.cpp
Labels: Scripting, MergeOnCIPass

#23133 Filter: HarmonicNotch: update FREQ description to make it clear half …
  libraries/Filter/HarmonicNotchFilter.cpp
Labels: DevCallEU

#23208 Tools: add EKF3 wind estimation to build options
  Tools/scripts/build_options.py
  Tools/scripts/extract_features.py
Labels: DevCallEU

#23205 SITL: prevent a conflict with a _serialize() macro on cygwin
  libraries/SITL/picojson.h
Labels: SITL, DevCallEU

#23217 AP_EFI: use uint16_t to store offset
  libraries/AP_EFI/AP_EFI_Serial_MS.cpp
Labels: MergeOnCIPass

#23212 Tools:reserve KakuteH7-Wing board type
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#23236 hwdef: fixed polarity of VDD_5V_PERIPH_EN on several boards
  libraries/AP_HAL_ChibiOS/hwdef/CubeYellow/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/fmuv3-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/fmuv3/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/mRoX21-777/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/thepeach-k1/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/thepeach-r1/hwdef.dat
Labels: BUG, MergeOnCIPass, hwdef

#23228 HAL_ChibiOS: fix a memory corruption bug on STM32H757
  libraries/AP_HAL_ChibiOS/hwdef/common/board.c
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
Labels: BUG, ChibiOS

#23159 AP_Scripting:provide altitude loss safety abort for plane aerobatics
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: MergeOnCIPass

#23211 AP_Arming:correct ARMING_RUDDER description
  libraries/AP_Arming/AP_Arming.cpp
Labels: Docs, DevCallTopic

#23218 CubeOrangePlus-SimOnHardWare: add support
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-SimOnHardWare/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrangePlus-SimOnHardWare/hwdef.dat
Labels: SITL, MergeOnCIPass, hwdef

#23258 AP_RCProtocol: HAL_LOGGING_ENABLED in place of checking build types
  libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp
Labels: DevCallTopic

#23051 .github: add GH cache cleanup on PR close. Taken from https://docs.gi…
  .github/workflows/cache_cleanup.yml
Labels: CI

#23251 AP_NavEKF: ensure gyro biases are numbers
  libraries/AP_NavEKF/EKFGSF_yaw.cpp
Labels: BUG, 4.3 Backport

#23260 Tools: add jolnir on install script
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: DevEnv, MergeOnCIPass

#23223 Copter: Add TKOFF_TH_MAX
  ArduCopter/Parameters.cpp
  ArduCopter/Parameters.h
  ArduCopter/takeoff.cpp
Labels: Copter, WikiNeeded, MergeOnCIPass

#23250 RC_Channel:rename 173 option more appropriately
  libraries/RC_Channel/RC_Channel.cpp
Labels: Plane, Docs, MergeOnCIPass

#23229 AP_GPS: decouple status enumeration from MAVLink fix types
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS.h
Labels: MergeOnCIPass

#23273 [Backport 4.4] bootloaders: add CubeOrangePlus-bdshot bootloader
  Tools/bootloaders/CubeOrangePlus-bdshot_bl.bin
  Tools/bootloaders/CubeOrangePlus-bdshot_bl.hex
Labels: DevCallEU, MergeOnCIPass, 4.4 Backport

#23272 bootloaders: add CubeOrangePlus-bdshot bootloaders
  Tools/bootloaders/CubeOrangePlus-bdshot_bl.bin
  Tools/bootloaders/CubeOrangePlus-bdshot_bl.hex
Labels: DevCallEU

#23289 AP_DDS: Use python3 shebang
  libraries/AP_DDS/gen_config_h.py
  libraries/AP_DDS/wscript
Labels: ROS, MergeOnCIPass, For-4.5

#23276 AP_InertialSensor: increase the temperature tolerance for ICM20649 for fifo reset
  libraries/AP_InertialSensor/AP_InertialSensor_Invensensev2.cpp
Labels: MergeOnCIPass

#23245 AP_HAL_ChibiOS:improve MambaF405MINI defaults
  libraries/AP_HAL_ChibiOS/hwdef/MambaF405-2022/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/MambaF405-2022/hwdef.dat
Labels: MergeOnCIPass, hwdef

#23293 .github: replace testing of Hirsute by Jammy
  .github/workflows/test_environment.yml
Labels: CI, MergeOnCIPass

#23296 AP_Baro: LPS2XH SPI/I2C bug during setup
  libraries/AP_Baro/AP_Baro_LPS2XH.cpp
Labels: BUG, Library, MergeOnCIPass

#23317 AP_Arming: add and use a define for AP_ARMING_AUX_AUTH_ENABLED
  libraries/AP_Arming/AP_Arming.cpp
  libraries/AP_Arming/AP_Arming.h
  libraries/AP_Arming/AP_Arming_config.h
Labels: MergeOnCIPass

#23313 Copter: Remove misleading enable_motor_output method
  ArduCopter/system.cpp
Labels: MergeOnCIPass

#23337 Ensure the rcout TIM_UP DMA request source is re-instated after cancellation
  libraries/AP_HAL_ChibiOS/RCOutput.cpp
Labels: BUG, ChibiOS, MergeOnCIPass, 4.3 Backport

#23328 AP_HAL: fix CANFrame initialization in constructor
  libraries/AP_HAL/CANIface.cpp
Labels: BUG, CAN

#23327 Copter: Add an element of NAV_CONTROLLER_OUTPUT to ZIGZAG mode
  ArduCopter/mode.h
  ArduCopter/mode_zigzag.cpp
Labels: Copter, MergeOnCIPass

#23341 Tools: remove remove redundant install-apt-ci.sh
  Tools/scripts/install-apt-ci.sh
Labels: MergeOnCIPass

#23340 Tools: remove dead Tools/scripts/magfit_flashlog.py script
  Tools/scripts/magfit_flashlog.py
Labels: MergeOnCIPass

#23303 AP_DDS: Bump to using latest MicroXRCEDDSGen
  libraries/AP_DDS/Idl/NavSatFix.idl
  libraries/AP_DDS/Idl/NavSatStatus.idl
  libraries/AP_DDS/Idl/PoseStamped.idl
  libraries/AP_DDS/wscript
Labels: ROS, MergeOnCIPass, For-4.5

#23290 .pre-commit: Add xmllint for AP_DDS xml file
  .pre-commit-config.yaml
Labels: ROS, MergeOnCIPass
