Repository ArduPilot/ardupilot, pull requests merged in 2023-11, with the labels that each got.

#25412 Use RangeFinder backend defines better
  libraries/AP_RangeFinder/AP_RangeFinder.cpp
  libraries/AP_RangeFinder/AP_RangeFinder.h
  libraries/AP_RangeFinder/AP_RangeFinder_USD1_Serial.h
  libraries/AP_RangeFinder/AP_RangeFinder_config.h
Labels: DevCallEU

#25421 Autotest: improve flapping Sub test
  Tools/autotest/ardusub.py
Labels: MergeOnCIPass

#25425 AP_ADSB: create an enum class for logging
  libraries/AP_ADSB/AP_ADSB.cpp
  libraries/AP_ADSB/AP_ADSB.h
Labels: MergeOnCIPass

#25430 AP_HAL_ChibiOS: add CubeNode pinout diagram
  libraries/AP_HAL_ChibiOS/hwdef/CubePilot-CANMod/CubeNode_PinOut.pdf
Labels: Docs, MergeOnCIPass

#25438 AP_GPS: Remove GPS_TC_BLEND
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS.h
Labels: Library, MergeOnCIPass

#25426 AP_HAL_SITL: create and use ADSB sim when mxs simulator is in play
  libraries/AP_HAL_SITL/SITL_State_common.cpp
Labels: MergeOnCIPass

#25424 SITL: correct bit for enabling MXS simulation
  libraries/SITL/SITL.cpp
Labels: MergeOnCIPass

#25440 hwdef: corrected README.md file in JFB110
  libraries/AP_HAL_ChibiOS/hwdef/JFB110/README.md
Labels: MergeOnCIPass, hwdef

#25441 AP_Camera: CAMERA_FOV_STATUS includes horizontal and vertical field-of-view
  libraries/AP_Camera/AP_Camera_Backend.cpp
  libraries/AP_Camera/AP_Camera_Backend.h
  libraries/AP_Camera/AP_Camera_Params.cpp
  libraries/AP_Camera/AP_Camera_Params.h
Labels: Enhancement, Driver, MergeOnCIPass

#24552 AP_GPS: Rename GSOF packing functions
  libraries/SITL/SIM_GPS.cpp
  libraries/SITL/SIM_GPS.h
Labels: MergeOnCIPass

#25452 AP_Mount: fixed SIYI parser bug
  libraries/AP_Mount/AP_Mount_Siyi.cpp
Labels: BUG

#25437 Plane: Cruise: only lock in heading once moving forwards
  ArduPlane/mode_cruise.cpp
Labels: VTOL-Plane

#25444 AP_Scripting: add binding for GCS last seen time
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: Scripting

#25465 Tools: added Web Tools landing page
  Tools/autotest/web-firmware/index.html
Labels: Tools

#25446 AP_Scripting: add bindings for fence
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/examples/FenceBreach.lua
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: DevCallTopic, Scripting

#25431 hwdef: add YJUAV_A6SE_H743 board support
  Tools/bootloaders/YJUAV_A6SE_H743_bl.bin
  Tools/bootloaders/YJUAV_A6SE_H743_bl.hex
  libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE_H743/README.md
  libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE_H743/YJUAV_A6SE_H743-pinout.jpg
  libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE_H743/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE_H743/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE_H743/hwdef.dat
Labels: hwdef

#25456 AP_GPS: Expose COM port and Output Rate in header, Fix default COM port
  libraries/AP_GPS/AP_GPS_GSOF.cpp
  libraries/AP_GPS/AP_GPS_GSOF.h
Labels: GPS, For-4.5

#25476 AP_GPS: correct uBlox M10 configuration on minimised boards
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
Labels: DevCallEU, MergeOnCIPass

#25482 hwdef: AP_BATTERY_ESC_ENABLED needs HAL_WITH_ESC_TELEM
  libraries/AP_HAL_ChibiOS/hwdef/include/minimize_common.inc
Labels: DevCallEU

#23564 AP_BattMonitor: Addition of AD7091R5 ADC I2C Read Driver
  libraries/AP_BattMonitor/AP_BattMonitor.cpp
  libraries/AP_BattMonitor/AP_BattMonitor.h
  libraries/AP_BattMonitor/AP_BattMonitor_AD7091R5.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_AD7091R5.h
  libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_config.h
Labels: DevCallEU

#25486 AP_EFI: remove unused definitions
  libraries/AP_EFI/AP_EFI_State.h
Labels: MergeOnCIPass

#25415 hwdef:save flash on FlywooF405S-AIO
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF405S-AIO/hwdef.dat
Labels: DevCallTopic, hwdef

#25417 Sub: scale get_pilot_desired_climb_rate() deadzone and output with pilot gain
  ArduSub/Attitude.cpp
  ArduSub/Parameters.cpp
Labels: Sub

#25479 AP_GPS: Use GPS_COM_PORT param in GSOF driver
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS_GSOF.cpp
  libraries/AP_GPS/AP_GPS_GSOF.h
Labels: GPS, WikiNeeded, MergeOnCIPass

#25472 Tools: ros2: Add missing socat dependency
  Tools/ros2/ardupilot_dds_tests/package.xml
Labels: ROS, MergeOnCIPass, For-4.5

#25362 AP_Logger: correct the filling order of the struct
  libraries/AP_Logger/AP_Logger_Backend.cpp
Labels: MergeOnCIPass

#25228 AP_DDS: support automatic reconnect to micro-ROS agent
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Serial.cpp
  libraries/AP_DDS/AP_DDS_UDP.cpp
Labels: ROS, MergeOnCIPass, For-4.5

#25418 Sub: use gain-ajusted deadzone for pilot_desired_yaw_rate
  ArduSub/mode_althold.cpp
  ArduSub/mode_poshold.cpp
  ArduSub/mode_stabilize.cpp
Labels: Sub

#25151 HAL_ChibiOS: default RTS pins to PULLDOWN
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: ChibiOS, NeedsTesting

#25507 autotest: understand verbose and very_vrbose for wait_message_field_v…
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#25504 board_types.txt: reserve ID for FreeSpace PowerStack
  Tools/AP_Bootloader/board_types.txt
Labels: DevCallTopic

#25514 Copter: fix 440-beta1 release notes
  ArduCopter/ReleaseNotes.txt
Labels: Copter, Non-Functional Change

#25509 Tools:reserve ATOMRCF405NAVI_DX bd id
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#25505 AP_OpticalFlow: increase scaler param desc ranges
  libraries/AP_OpticalFlow/AP_OpticalFlow.cpp
Labels: BUG, Docs

#25515 AP_ExternalAHRS: Specify brand on all VN log messages
  libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp
Labels: Enhancement

#25536 AP_Notify: add IS31FL3195 to default LED types
  libraries/AP_Notify/AP_Notify.cpp
Labels: WikiNeeded, MergeOnCIPass

#25219 Carbonix PR - AP_BattMonitor: Add in reventech fuel level driver
  libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.h
Labels: WikiNeeded

#25538 SRV_Channel: fix RCInxScaled when input is range (instead of angle)
  libraries/SRV_Channel/SRV_Channel_aux.cpp
Labels: BUG, DevCallEU

#25512 Correct ESC mask for takeoff check
  ArduCopter/takeoff_check.cpp
Labels: BUG, DevCallEU

#25551 AP_Mount: added support for sending gimbal rates to GCS
  libraries/AP_Mount/AP_Mount_Backend.cpp
  libraries/AP_Mount/AP_Mount_Backend.h
  libraries/AP_Mount/AP_Mount_Siyi.cpp
  libraries/AP_Mount/AP_Mount_Siyi.h
Labels: Enhancement, Driver, Gimbal

#25537 AP_Notify: document IS31FL3195 LED type for LED_TYPES parameter
  libraries/AP_Notify/AP_Notify.cpp
Labels: MergeOnCIPass

#25558 AP_DroneCAN: cope with null stats (for SLCAN interface)
  libraries/AP_DroneCAN/AP_Canard_iface.cpp
Labels: CAN, MergeOnCIPass

#25547 AP_RangeFinder: Move to a process that uses maximum value acquisition
  libraries/AP_RangeFinder/AP_RangeFinder_JRE_Serial.cpp
Labels: Library, MergeOnCIPass

#25519 AP_Scripting: added more params to revert script
  libraries/AP_Scripting/applets/revert_param.lua
Labels: Scripting

#25534 SITL: add code to add, remove or corrupt bytes in SITL::SerialDevice …
  libraries/SITL/SIM_SerialDevice.cpp
  libraries/SITL/SIM_SerialDevice.h
  libraries/SITL/SIM_config.h
Labels: SITL

#25539 AP_Mount: validate modes before setting them
  libraries/AP_Mount/AP_Mount_Backend.cpp
  libraries/AP_Mount/AP_Mount_Backend.h
Labels: MergeOnCIPass

#25564 AP_DroneCAN: don't update hobbywing ESC table while armed
  libraries/AP_DroneCAN/AP_DroneCAN.cpp
Labels: CAN, MergeOnCIPass

#25510 AP_Baro: Returns directly calculated values
  libraries/AP_Baro/AP_Baro.cpp
Labels: Library, MergeOnCIPass

#25568 Docker: Added oportunity to set build flags (some envs) via docker bu…
  Dockerfile
Labels: DevEnv, MergeOnCIPass

#25565 SITL: set sitl point for GPS backends in constructor
  libraries/SITL/SIM_GPS.cpp
Labels: MergeOnCIPass

#25578 AP_Networking: fixed buffer size handling
  libraries/AP_Networking/AP_Networking.h
  libraries/AP_Networking/AP_Networking_Config.h
  libraries/AP_Networking/AP_Networking_port.cpp
Labels: Networking

#25573 Enable serial LEDs on ARK_CANNODE
  libraries/AP_HAL_ChibiOS/hwdef/ARK_CANNODE/hwdef.dat
Labels: BUG, DevCallTopic

#25584 AP_BattMonitor:remove unused param from analog fuel level
  libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_FuelLevel_Analog.h
Labels: DevCallTopic

#25583 AP_DDS: increase the timeout when creating participants and entities
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: ROS, MergeOnCIPass

#25585 AP_Compass: fix C++ One Definition Rule violations
  libraries/AP_Compass/AP_Compass_AK09916.cpp
  libraries/AP_Compass/AP_Compass_AK09916.h
  libraries/AP_Compass/AP_Compass_AK8963.cpp
  libraries/AP_Compass/AP_Compass_AK8963.h
  libraries/AP_Compass/AP_Compass_LSM9DS1.cpp
  libraries/AP_Compass/AP_Compass_LSM9DS1.h
Labels: MergeOnCIPass

#25559 SITL: Bump up read rate on SITL
  libraries/SITL/SIM_GPS.cpp
  libraries/SITL/SIM_GPS.h
Labels: MergeOnCIPass

#25550 AP_RangeFinder Add signal_quality_pct to range finder state
  libraries/AP_RangeFinder/AP_RangeFinder.cpp
  libraries/AP_RangeFinder/AP_RangeFinder.h
  libraries/AP_RangeFinder/AP_RangeFinder_BLPing.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_BLPing.h
  libraries/AP_RangeFinder/AP_RangeFinder_Backend.h
  libraries/AP_RangeFinder/AP_RangeFinder_Backend_Serial.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_Backend_Serial.h
  libraries/AP_RangeFinder/AP_RangeFinder_JRE_Serial.h
  libraries/AP_RangeFinder/AP_RangeFinder_LightWareSerial.h
  libraries/AP_RangeFinder/AP_RangeFinder_MAVLink.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_MAVLink.h
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: Library, MergeOnCIPass

#25563 AP_HAL_ChibiOS: base HAL_USE_SPI on devices not buses
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: DevCallEU

#25561 Copter: fix USER_PARAMS_ENABLED includes
  ArduCopter/Copter.h
  ArduCopter/Parameters.cpp
  ArduCopter/Parameters.h
  ArduCopter/UserParameters.cpp
  ArduCopter/config.h
  ArduCopter/toy_mode.h
Labels: Copter, DevCallEU

#25081 AP_Scripting: change some _INFO msgs to _CRITICAL
  libraries/AP_Scripting/AP_Scripting.cpp
  libraries/AP_Scripting/lua_scripts.cpp
Labels: Scripting, MergeOnCIPass

#25615 AP_Stats: initialise parameter defaults
  libraries/AP_Stats/AP_Stats.cpp
Labels: MergeOnCIPass

#25594 AP_DDS: Add instructions for running HW test
  libraries/AP_DDS/README.md
Labels: Docs, ROS, MergeOnCIPass, Non-Functional Change

#25619 Tools: autotest: Fix exception in junit printing for double to str conversion during failed test
  Tools/autotest/vehicle_test_suite.py
Labels: BUG, CI, MergeOnCIPass

#25612 hwdef: ark rtk gps safety led fix
  libraries/AP_HAL_ChibiOS/hwdef/ARK_RTK_GPS/hwdef.dat
Labels: MergeOnCIPass, hwdef

#25602 hwdef: correct ARK_CANNODE compilation
  libraries/AP_HAL_ChibiOS/hwdef/ARK_CANNODE/hwdef.dat
Labels: hwdef

#25609 .git-blame-ignore-revs: Ignore black format change
  .git-blame-ignore-revs
Labels: ROS, DevCallTopic, Experiment

#25499 AP_Arming: Reduce response time when checks go from true to false
  libraries/AP_Arming/AP_Arming.cpp
  libraries/AP_Arming/AP_Arming.h
Labels: Library, MergeOnCIPass

#25593 AP_Networking: Allow Broadcast
  libraries/AP_HAL/utility/Socket.cpp
Labels: MergeOnCIPass, Networking

#25639 Rover: Extra pre-arm checks on outputs
  libraries/AR_Motors/AP_MotorsUGV.cpp
Labels: Rover

#25626 AP_BattMonitor: fixed battery percentage with aux info
  libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp
Labels: BUG

#25645 Tools: sort serial ports for uploader
  Tools/scripts/uploader.py
Labels: DevCallTopic

#25601 AP_GPS: Support integrated headings from SBF
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS.h
  libraries/AP_GPS/AP_GPS_SBF.cpp
  libraries/AP_GPS/AP_GPS_SBF.h
Labels: Enhancement, GPS, Driver, WikiNeeded

#25608 AP_Param: check dynamic param tables are available before adding a param
  libraries/AP_Param/AP_Param.cpp
Labels: BUG, DevCallTopic

#25628 AP_ExternalAHRS: Clarify public interface design intent
  libraries/AP_ExternalAHRS/AP_ExternalAHRS_backend.h
Labels: EKF, Docs, Non-Functional Change

#25525 AP_GPS: Increase robustness of GSOF configuration with ACK/NACK handling and retry logic
  libraries/AP_GPS/AP_GPS_GSOF.cpp
  libraries/AP_GPS/AP_GPS_GSOF.h
Labels: Enhancement, GPS

#25591 hwdef:correct JFB110 defaults
  libraries/AP_HAL_ChibiOS/hwdef/JFB110/defaults.parm
Labels: WikiNeeded, MergeOnCIPass, hwdef

#25659 Tools: fix AP_Periph param docs generator
  Tools/autotest/param_metadata/param_parse.py
Labels: Docs, AP_Periph, MergeOnCIPass

#25658 AP_Periph: disable UART reboot check for non-debug builds
  Tools/AP_Periph/AP_Periph.h
Labels: AP_Periph

#25661 AP_RangeFinder: use boolean uartdriver read method
  libraries/AP_RangeFinder/AP_RangeFinder_BLPing.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_Benewake.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_Lanbao.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_LeddarVu8.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_LightWareSerial.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_MaxsonarSerialLV.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_NMEA.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_TeraRanger_Serial.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_USD1_Serial.cpp
  libraries/AP_RangeFinder/AP_RangeFinder_Wasp.cpp
Labels: MergeOnCIPass

#25629 AP_Scripting: simplify Rover quick tune
  libraries/AP_Scripting/applets/rover-quicktune.lua
  libraries/AP_Scripting/applets/rover-quicktune.md
Labels: Enhancement, Rover, Scripting, MergeOnCIPass

#25667 Sub: copy 4.1 parm defaults
  ArduSub/Parameters.h
  Tools/autotest/ardusub.py
Labels: Sub
