Repository ArduPilot/ardupilot, pull requests merged in 2023-12, with the labels that each got.

#25669 AP_Networking: improve startup wait
  libraries/AP_Networking/AP_Networking.cpp
  libraries/AP_Networking/AP_Networking.h
  libraries/AP_Networking/AP_Networking_port.cpp
  libraries/AP_Networking/AP_Networking_tests.cpp
Labels: MergeOnCIPass, Networking

#25683 AP_Networking: fixed docs for network port types
  libraries/AP_Networking/AP_Networking_port.cpp
Labels: MergeOnCIPass, Networking

#25673 SITL: add missing includes
  libraries/SITL/SIM_GPS_MSP.cpp
  libraries/SITL/SIM_GPS_NMEA.cpp
  libraries/SITL/SIM_GPS_Trimble.cpp
Labels: MergeOnCIPass

#25680 Copter: Fix AP_MISSION_NAV_PAYLOAD_PLACE_ENABLED
  ArduCopter/mode_auto.cpp
Labels: BUG, DevCallTopic

#25416 Plane: set_servos_controlled rework
  ArduPlane/servos.cpp
Labels: Plane, DevCallTopic

#25604 AP_Motors: Heli: dual and quad: remove un-needed override methods
  libraries/AP_Motors/AP_MotorsHeli_Dual.h
  libraries/AP_Motors/AP_MotorsHeli_Quad.h
Labels: TradHeli

#25672 AP_HAL_ChibiOS: Set RADIX2HD HAL_I2C_INTERNAL_MASK
  libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/hwdef.dat
Labels: DevCallTopic

#25682 AP_HAL_ChibiOS: allow betaflight converter to run on output from "dump hardware"
  libraries/AP_HAL_ChibiOS/hwdef/scripts/convert_betaflight_unified.py
Labels: DevCallTopic

#25677 AP_HAL_ChibiOS: Set RADIX2HD HAL_I2C_INTERNAL_MASK (backport to 4.4)
  libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/hwdef.dat
Labels: DevCallTopic

#25719 ROS2 sitl package added ardupilot_msgs dependency
  Tools/ros2/ardupilot_sitl/package.xml
Labels: ROS, MergeOnCIPass

#25727 AP_Follow: correct defaulting of AP_FOLLOW_ENABLED
  libraries/AP_Follow/AP_Follow.cpp
  libraries/AP_Follow/AP_Follow_config.h
Labels: MergeOnCIPass

#25729 AR_WPNav: correct missing include
  libraries/AR_WPNav/AR_WPNav.cpp
  libraries/AR_WPNav/AR_WPNav_OA.cpp
Labels: Rover, MergeOnCIPass

#25737 AP_RTC: fixed ms value from AP_RTC::get_date_and_time_utc
  libraries/AP_RTC/AP_RTC.cpp
Labels: BUG, MergeOnCIPass, Gimbal

#25685 AP_Scripting: added readstring for uarts
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/generator/description/bindings.desc
  libraries/AP_Scripting/lua_bindings.cpp
  libraries/AP_Scripting/lua_bindings.h
Labels: Scripting, MergeOnCIPass

#25750 AP_WindVane: add and use AP_WINDVANE_*_ENABLED defines
  libraries/AP_WindVane/AP_WindVane.cpp
  libraries/AP_WindVane/AP_WindVane.h
  libraries/AP_WindVane/AP_WindVane_Airspeed.cpp
  libraries/AP_WindVane/AP_WindVane_Airspeed.h
  libraries/AP_WindVane/AP_WindVane_Analog.cpp
  libraries/AP_WindVane/AP_WindVane_Analog.h
  libraries/AP_WindVane/AP_WindVane_Backend.cpp
  libraries/AP_WindVane/AP_WindVane_Backend.h
  libraries/AP_WindVane/AP_WindVane_Home.cpp
  libraries/AP_WindVane/AP_WindVane_Home.h
  libraries/AP_WindVane/AP_WindVane_ModernDevice.cpp
  libraries/AP_WindVane/AP_WindVane_ModernDevice.h
  libraries/AP_WindVane/AP_WindVane_NMEA.cpp
  libraries/AP_WindVane/AP_WindVane_NMEA.h
  libraries/AP_WindVane/AP_WindVane_RPM.cpp
  libraries/AP_WindVane/AP_WindVane_RPM.h
  libraries/AP_WindVane/AP_WindVane_SITL.cpp
  libraries/AP_WindVane/AP_WindVane_SITL.h
  libraries/AP_WindVane/AP_WindVane_config.h
Labels: DevCallTopic

#23458 Plane: fix bug in RTL_AUTOLAND with rally points
  ArduPlane/commands_logic.cpp
Labels: BUG, Plane

#25660 Copter: Use RTL_CLIMB_MIN in cone slope.
  ArduCopter/config.h
  ArduCopter/mode_rtl.cpp
Labels: Enhancement, WikiNeeded

#25703 AP_Scripting: Add filtering of incoming CAN frames
  libraries/AP_Scripting/AP_Scripting_CANSensor.cpp
  libraries/AP_Scripting/AP_Scripting_CANSensor.h
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/examples/CAN_read.lua
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: Scripting

#25757 AP_Scripting: correct compilation when AP_RTC is compiled out
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: MergeOnCIPass

#25765 AP_SerialManager: Reserving serial protocol ID for future Vertiq IFCI implementation
  libraries/AP_SerialManager/AP_SerialManager.h
Labels: DevCallEU

#25763 GCS_MAVLink: correct compilation when compass not enabled
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: DevCallEU

#25758 Plane: Quadplane: alt and angle assist messages to warning
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, DevCallEU

#25756 AP_Scripting: fix some more of the easy luacheck warnings
  libraries/AP_Scripting/applets/runcam_on_arm.lua
  libraries/AP_Scripting/examples/OOP_example.lua
  libraries/AP_Scripting/examples/plane-doublets.lua
  libraries/AP_Scripting/examples/protected_call.lua
  libraries/AP_Scripting/examples/quadruped.lua
  libraries/AP_Scripting/examples/test_load.lua
Labels: Scripting, DevCallEU

#25761 AP_Arming: correct compilation when logging not available
  libraries/AP_Arming/AP_Arming.cpp
Labels: DevCallEU

#25686 AP_Scripting: added SCR_THD_PRIORITY
  libraries/AP_Scripting/AP_Scripting.cpp
  libraries/AP_Scripting/AP_Scripting.h
Labels: Scripting, WikiNeeded, MergeOnCIPass

#25744 AP_Scripting: update SkyPower driver to support new model
  libraries/AP_Scripting/drivers/EFI_SkyPower.lua
Labels: Scripting

#25791 AP_ExternalARHS: Don't offer IMU by default
  libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp
Labels: Enhancement, MergeOnCIPass, ExternalAHRS

#25789 AP_ExternalAHRS: Fix typos in configuration for microstrain7
  libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp
  libraries/AP_ExternalAHRS/MicroStrain_common.cpp
Labels: Docs, DevCallTopic, Non-Functional Change, ExternalAHRS

#25776 Plane: Quadplane: log tailsitter speed scaling in TSIT msg
  ArduPlane/Log.cpp
  ArduPlane/defines.h
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
  ArduPlane/tailsitter.cpp
  ArduPlane/tailsitter.h
Labels: VTOL-Plane

#25782 Plane: rework forward throttle voltage compensation into sub class and split min/max from throttle
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/Plane.h
  ArduPlane/servos.cpp
Labels: Plane, DevCallEU

#25802 HAL_ChibiOS: fixed SPI build on F1xx
  libraries/AP_HAL_ChibiOS/SPIDevice.h
Labels: AP_Periph, DevCallEU

#25803 hwdef: fixed build of CarbonixL496
  libraries/AP_HAL_ChibiOS/hwdef/CarbonixL496/hwdef.dat
Labels: MergeOnCIPass

#24693 Add option to add lua scripts to CubeRed Secondary firmware
  libraries/AP_HAL_ChibiOS/hwdef/CubeRedSecondary/hwdef.dat
Labels: MergeOnCIPass

#25635 AP_Motors:expand heli tail param metadata
  libraries/AP_Motors/AP_MotorsHeli_Single.cpp
Labels: TradHeli

#25827 HAL_ChibiOS: fixed micros and millis on boards without 1MHz clock
  libraries/AP_HAL_ChibiOS/hwdef/common/hrt.c
  libraries/AP_HAL_ChibiOS/hwdef/common/hrt.h
Labels: ChibiOS

#25835 hwdef: give a more useful error message on no bootloader
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: ChibiOS

#25837 AP_ExternalAHRS: fixed InertialLabs gyro/accel data
  libraries/AP_ExternalAHRS/AP_ExternalAHRS_InertialLabs.cpp
Labels: BUG

#25842 AP_Scripting: fixed use after free bug
  libraries/AP_Scripting/lua_scripts.cpp
Labels: BUG, Scripting, MergeOnCIPass
