Repository ArduPilot/ardupilot, pull requests merged in 2023-09, with the labels that each got.

#24829 AP_HAL_ESP32: change storage sector size to 128K
  libraries/AP_HAL_ESP32/Storage.h
  libraries/AP_HAL_ESP32/targets/esp32/partitions.csv
Labels: esp32

#24746 AP_Mount: Siyi supports set_lens and get_rangefinder_distance
  libraries/AP_Mount/AP_Mount_Siyi.cpp
  libraries/AP_Mount/AP_Mount_Siyi.h
Labels: Enhancement, Driver, DevCallTopic

#24839 AP_Periph: define external hal symbol to correct compilation
  Tools/AP_Periph/hardpoint.cpp
Labels: MergeOnCIPass

#24826 AP_Logger: fix typo in AP_Logger.h
  libraries/AP_Logger/AP_Logger.h
Labels: MergeOnCIPass

#24705 Tools : Added custom ROS-2 service definition for switching drive modes
  Tools/ros2/ardupilot_msgs/CMakeLists.txt
  Tools/ros2/ardupilot_msgs/srv/ModeSwitch.srv
Labels: ROS, MergeOnCIPass

#24634 AP_Scripting: added EFI driver for DLA EFI serial protocol
  libraries/AP_Scripting/drivers/EFI_DLA.lua
  libraries/AP_Scripting/drivers/EFI_DLA.md
Labels: Scripting, WikiNeeded

#24857 Tools: fixed ccache test for newer ccache version
  Tools/scripts/build_tests/test_ccache.py
Labels: CI, MergeOnCIPass

#24856 Plane: fixed nav_roll/nav_pitch when waiting for VTOL takeoff
  ArduPlane/quadplane.cpp
Labels: BUG, VTOL-Plane, MergeOnCIPass

#24859 Tools: blacklist iomcu dshot builds when building bootloaders
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#24847 AP_HAL: Delete commented-out processes
  libraries/AP_HAL/SIMState.cpp
Labels: MergeOnCIPass

#24848 AP_Vehicle: add missing include for accelcal
  libraries/AP_Vehicle/AP_Vehicle.h
Labels: MergeOnCIPass

#24846 AP_Logger: Align indentation with others
  libraries/AP_Logger/AP_Logger.h
Labels: MergeOnCIPass

#24835 AP_HAL_Linux: update Navigator available GPIOs
  libraries/AP_HAL_Linux/GPIO_Navigator.h
Labels: DevCallTopic

#24869 Tools: size_compare_branches.py: blacklist iomcu-f103 for bootloader …
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#24590 Update defaults.parm luminousbee5
  libraries/AP_HAL_ChibiOS/hwdef/luminousbee5/defaults.parm
Labels: MergeOnCIPass

#24833 AP_ICEngine: stop engine on parachute release
  libraries/AP_ICEngine/AP_ICEngine.cpp
Labels: Plane

#24834 AP_L1_Control: check vehicle yaw (heading) and ground track agree
  libraries/AP_L1_Control/AP_L1_Control.cpp
Labels: Plane

#24841 AP_Mount: xacti supports set lens and zoom
  libraries/AP_Mount/AP_Mount_Xacti.cpp
  libraries/AP_Mount/AP_Mount_Xacti.h
Labels: Enhancement, Driver

#24819 AP_DDS: use /tf instead of /ap/tf
  libraries/AP_DDS/README.md
  libraries/AP_DDS/dds_xrce_profile.xml
Labels: ROS, MergeOnCIPass

#24849 AP_HAL_ChibiOS: chibios_hwdef.py: canonicalise AP_PERIPH env define
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: MergeOnCIPass

#24803 gitignore: Add Python venv folder
  .gitignore
Labels: DevEnv, DevCallEU

#24734 AP_DDS: /ap/cmd_vel accepts body-frame messages
  libraries/AP_DDS/AP_DDS_ExternalControl.cpp
Labels: ROS, MergeOnCIPass, For-4.5

#23334 AP_AdvancedFailsafe: option to continue the mission even after data link is recovered
  libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
  libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
Labels: WikiNeeded, MergeOnCIPass

#24890 build_options.py: correct case of Sagetech company name
  Tools/scripts/build_options.py
Labels: MergeOnCIPass

#24876 AP_DDS: add IDL for ArmMotors and ModeSwitch services
  libraries/AP_DDS/Idl/ardupilot_msgs/srv/ArmMotors.idl
  libraries/AP_DDS/Idl/ardupilot_msgs/srv/ModeSwitch.idl
Labels: ROS, MergeOnCIPass

#24880 AP_DDS: update dds profile, eliminate need for integration service
  libraries/AP_DDS/AP_DDS_Service_Table.h
  libraries/AP_DDS/Is-Config/Arm_Motors_DDS_IS_config.yaml
  libraries/AP_DDS/README.md
  libraries/AP_DDS/dds_xrce_profile.xml
Labels: ROS, MergeOnCIPass

#24904 hwdef: Modify YJUAV_A6SE board TIME12 to TIM8
  libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE/README.md
  libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE/hwdef.dat
Labels: MergeOnCIPass

#24917 GCS_MAVLink: Fix CAMERA_SETTINGS payload size check
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#24891 AP_Math: add conversions from metres to feet
  libraries/AP_Math/definitions.h
Labels: MergeOnCIPass

#24873 Plane: use dead zone in stick mixing
  ArduPlane/Attitude.cpp
Labels: Plane, VTOL-Plane, MergeOnCIPass

#24916 AP_TECS: ensure good TECS state before running update_pitch_throttle
  libraries/AP_TECS/AP_TECS.cpp
Labels: DevCallTopic, NeedsTesting

#24928 Plane:add taildrag holdown to TAKEOFF mode
  ArduPlane/takeoff.cpp
Labels: DevCallTopic

#24926 AP_Scripting: add version requirement to plane_aerobatics
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/README.md
Labels: DevCallTopic

#24914 AP_ESC_Telem: fix fake value of SITL ESC
  libraries/AP_ESC_Telem/AP_ESC_Telem_SITL.cpp
Labels: BUG, DevEnv, MergeOnCIPass

#24908 AP_Mount: In Siyi, fix zoom percentage in CAMERA_SETTINGS
  libraries/AP_Mount/AP_Mount_Siyi.cpp
Labels: BUG, MergeOnCIPass

#24939 AP_Torqeedo: error code reporting fix
  libraries/AP_Torqeedo/AP_Torqeedo.cpp
Labels: BUG, Rover, DevCallTopic

#24895 AP_Scripting: Examples: UART log: remove spaces in log description
  libraries/AP_Scripting/examples/UART_log.lua
Labels: DevCallTopic, Scripting

#23333 AP_AdvancedFailsafe: automatically set mode to auto when datalink loss
  ArduCopter/afs_copter.cpp
  ArduCopter/afs_copter.h
  ArduPlane/afs_plane.cpp
  ArduPlane/afs_plane.h
  Rover/afs_rover.cpp
  Rover/afs_rover.h
  libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
  libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
Labels: WikiNeeded

#24842 autotest: paper over problem with EKF heading not recovering
  Tools/autotest/common.py
Labels: DevCallTopic

#24915 AP_Mount: In Siyi, add check for minimum supported firmware version
  libraries/AP_Mount/AP_Mount_Siyi.cpp
  libraries/AP_Mount/AP_Mount_Siyi.h
Labels: Driver, MergeOnCIPass

#24948 AP_Logger: log valid-input and in-rc-failsafe
  libraries/AP_Logger/AP_Logger.h
  libraries/AP_Logger/LogFile.cpp
  libraries/AP_Logger/LogStructure.h
Labels: MergeOnCIPass

#24934 AP_OSD:add Aviation style AH option
  libraries/AP_OSD/AP_OSD.cpp
  libraries/AP_OSD/AP_OSD.h
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: DevCallEU

#24952 autotest: add test for Plane MAV_CMD_DO_VTOL_TRANSITION mission item
  Tools/autotest/Generic_Missions/QuadPlaneDalbyRTL.txt
  Tools/autotest/common.py
  Tools/autotest/helicopter.py
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#24919 AP_Mount: In Siyi, fix calculation of attitude quaternion
  libraries/AP_Mount/AP_Mount_Siyi.cpp
Labels: BUG, Driver, MergeOnCIPass

#24867 Allow Precland fast descend
  ArduCopter/mode.cpp
  libraries/AC_PrecLand/AC_PrecLand.cpp
  libraries/AC_PrecLand/AC_PrecLand.h
Labels: Copter, WikiNeeded, MergeOnCIPass, Partner

#24885 Tools: Add missing runtime dependency for running ardupilot_sitl
  Tools/ros2/ardupilot_sitl/package.xml
Labels: MergeOnCIPass

#24956 autotest: loosen constrain on proximity distance message
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#24897 AP_HAL_ChibiOS: Add RADIX2HD target (4.4 backport)
  libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/README.md
  libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/pack_firmware.sh
  libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/radix_2_hd_pinout_bottom.png
  libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/radix_2_hd_pinout_top.png
Labels: DevCallEU

#24966 AP_Notify: remove unused enumeration
  libraries/AP_Notify/AP_Notify.h
  libraries/AP_Notify/OreoLED_I2C.h
Labels: DevCallEU

#24963 AP_VideoTX: Added frequency change support for Matek VTX-1G3SE. IRC Tramp protocol.
  libraries/AP_VideoTX/AP_Tramp.h
  libraries/AP_VideoTX/AP_VideoTX.cpp
  libraries/AP_VideoTX/AP_VideoTX.h
Labels: DevCallEU

#24961 AP_AdvancedFailsafe: make GCS failsafe timeout a parameter
  libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
  libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
Labels: WikiNeeded, DevCallEU

#24949 Plane: move nav_delay state to be private in ModeAuto
  ArduPlane/Plane.h
  ArduPlane/commands_logic.cpp
  ArduPlane/mode.h
Labels: DevCallEU

#24950 Copter: allow motor tests to be triggered with COMMAND_INT
  ArduCopter/GCS_Mavlink.cpp
  ArduCopter/GCS_Mavlink.h
  Tools/autotest/arducopter.py
Labels: DevCallEU

#24957 autotest: tidy and re-enable QAUTOTUNE test
  Tools/autotest/common.py
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#24967 autotest: improve STATUSTEXT handling
  Tools/autotest/common.py
Labels: MergeOnCIPass

#24945 AP_Notify: Reenable the DiscreteRGB backend
  libraries/AP_Notify/AP_Notify.cpp
  libraries/AP_Notify/AP_Notify.h
Labels: Enhancement, DevCallTopic

#24979 AP_Periph: fixed debug bitmask docs
  Tools/AP_Periph/Parameters.cpp
Labels: AP_Periph

#24990 AP_Mount: In Siyi, fix missing braces in process_packet()
  libraries/AP_Mount/AP_Mount_Siyi.cpp
Labels: BUG, MergeOnCIPass

#24982 AP_Notify: tidy use of DiscreteRGB
  libraries/AP_Notify/AP_Notify.cpp
  libraries/AP_Notify/AP_Notify.h
  libraries/AP_Notify/AP_Notify_config.h
  libraries/AP_Notify/DiscreteRGBLed.cpp
  libraries/AP_Notify/DiscreteRGBLed.h
Labels: DevCallTopic

#24793 AP_HAL_ChibiOS: change adc sampling rate stm32l4+
  libraries/AP_HAL_ChibiOS/AnalogIn.cpp
Labels: DevCallTopic

#24794 AP_HAL_ChibiOS: Increase limit for Storage pages
  libraries/AP_HAL_ChibiOS/Storage.h
Labels: DevCallTopic

#25014 autotest: loosen constraint on achieved angles
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#25015 GCS_MAVLink: correct sensors when no baros found
  libraries/GCS_MAVLink/GCS.cpp
Labels: BUG

#24980 HAL_ChibiOS: fixed CAN statistics on F4/L4/F3/F7
  libraries/AP_HAL_ChibiOS/CANIface.h
  libraries/AP_HAL_ChibiOS/CanIface.cpp
Labels: CAN

#24977 Correct hwdef of BETAFPV-F405
  libraries/AP_HAL_ChibiOS/hwdef/BETAFPV-F405/hwdef.dat
Labels: DevCallTopic

#25020 AP_SmartRTL: fix disable if second point fails to add
  libraries/AP_SmartRTL/AP_SmartRTL.cpp
Labels: DevCallTopic

#24997 AP_OSD: correct compilation when OSD compiled out
  libraries/AP_OSD/AP_OSD.cpp
Labels: DevCallTopic

#24900 AP_Periph: add AP_PERIPH_SAFETY_SWITCH_ENABLED
  Tools/AP_Periph/AP_Periph.h
  Tools/AP_Periph/can.cpp
  Tools/AP_Periph/rc_out.cpp
Labels: AP_Periph

#24913 Plane: Tailsitter: use motor I term for pitch in assist if no surfaces are setup
  ArduPlane/tailsitter.cpp
Labels: VTOL-Plane

#25003 Mamba F405 v2 fixes
  libraries/AP_HAL_ChibiOS/hwdef/MambaF405v2/hwdef.dat
Labels: BUG, WikiNeeded

#25019 AP_AHRS: make a pair of methods static on AP_AHRS_Backend
  libraries/AP_AHRS/AP_AHRS.cpp
  libraries/AP_AHRS/AP_AHRS.h
  libraries/AP_AHRS/AP_AHRS_Backend.cpp
  libraries/AP_AHRS/AP_AHRS_Backend.h
Labels: MergeOnCIPass

#25038 AP_AHRS: rename EKFType::NONE to EKFType::DCM
  libraries/AP_AHRS/AP_AHRS.cpp
  libraries/AP_AHRS/AP_AHRS.h
Labels: DevCallEU

#25002 AP_HAL: relax F4 notch constraints slightly to allow triple notch on quads
  libraries/AP_HAL/AP_HAL_Boards.h
Labels: DevCallEU

#25044 AP_AHRS: move AP_AHRS_DCM::groundspeed_vector into correct file
  libraries/AP_AHRS/AP_AHRS_Backend.cpp
  libraries/AP_AHRS/AP_AHRS_DCM.cpp
Labels: MergeOnCIPass

#25033 AP_HAL_ChibiOS: Explicitly include InternalError in Util
  libraries/AP_HAL_ChibiOS/Util.cpp
Labels: AP_Periph, MergeOnCIPass, Partner

#25046 Fix balancebot yaw reset to be kinimatically consistent
  libraries/SITL/SIM_BalanceBot.cpp
Labels: MergeOnCIPass

#25023 AP_GPS: implement the GPS_DRV_OPTION for ellisoid height in mode drivers
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS_DroneCAN.cpp
  libraries/AP_GPS/AP_GPS_ERB.cpp
  libraries/AP_GPS/AP_GPS_NMEA.cpp
  libraries/AP_GPS/AP_GPS_NOVA.cpp
  libraries/AP_GPS/AP_GPS_SBF.cpp
  libraries/AP_GPS/AP_GPS_SIRF.cpp
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
  libraries/AP_GPS/GPS_Backend.cpp
  libraries/AP_GPS/GPS_Backend.h
Labels: GPS, MergeOnCIPass

#25057 autotest: fix DO_CHANGE_SPEED test
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#25056 autotest: print command number when sending commands
  Tools/autotest/common.py
Labels: MergeOnCIPass

#25062 AP_Generator: use HAL_LOGGING_ENABLED
  libraries/AP_Generator/AP_Generator_IE_2400.cpp
  libraries/AP_Generator/AP_Generator_IE_2400.h
  libraries/AP_Generator/AP_Generator_IE_FuelCell.cpp
  libraries/AP_Generator/AP_Generator_IE_FuelCell.h
  libraries/AP_Generator/AP_Generator_RichenPower.cpp
  libraries/AP_Generator/AP_Generator_RichenPower.h
Labels: MergeOnCIPass

#25061 SITL: log achieved speedup rate
  libraries/SITL/SIM_Aircraft.cpp
  libraries/SITL/SIM_Aircraft.h
Labels: MergeOnCIPass

#25086 AP_AHRS: fill in error string when invalid backend specified
  libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
Labels: DevCallTopic

#25096 autotest: tweak test_mount_pitch win condition
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#25042 Plane:clarify CTUN.SAs message meaning
  ArduPlane/Log.cpp
Labels: DevCallTopic

#24994 AP_Generator: IE 650/800: does have fuel remaining
  libraries/AP_Generator/AP_Generator_IE_650_800.cpp
Labels: DevCallTopic

#25094 AP_Scripting: winch-test simplification
  libraries/AP_Scripting/examples/winch-test.lua
Labels: Enhancement, Scripting

#25093 AP_Winch: Options param for init state and verbose output
  libraries/AP_Winch/AP_Winch.cpp
  libraries/AP_Winch/AP_Winch.h
  libraries/AP_Winch/AP_Winch_Backend.h
  libraries/AP_Winch/AP_Winch_Daiwa.cpp
  libraries/AP_Winch/AP_Winch_Daiwa.h
Labels: Enhancement, Driver, WikiNeeded, MergeOnCIPass

#25099 AP_Baro: Fix GCS DPS310 HWID issue
  libraries/AP_Baro/AP_Baro_DPS280.cpp
  libraries/AP_Baro/AP_Baro_DPS280.h
Labels: MergeOnCIPass

#25079 Copter: Change to ternary operator
  ArduCopter/mode_zigzag.cpp
Labels: MergeOnCIPass

#24581 New Lua script example
  libraries/AP_Scripting/examples/copter_pingpong.lua
  libraries/AP_Scripting/examples/copter_pingpong.md
Labels: Scripting, MergeOnCIPass

#25109 AP_Periph: Fix bad conversion of APD ESC telemetry
  Tools/AP_Periph/esc_apd_telem.cpp
Labels: BUG, AP_Periph

#25113 SITL: add a thermal at home
  libraries/SITL/SIM_Aircraft.cpp
Labels: Plane, SITL, MergeOnCIPass

#25118 AP_GPS: add an AP_GPS_FixType header
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS_FixType.h
Labels: MergeOnCIPass

#25122 AP_Bootloader: update board id for TMotor H7
  Tools/AP_Bootloader/board_types.txt
Labels: BUG

#25129 autotest: rename get_message_rate to measure_message_rate
  Tools/autotest/common.py
Labels: MergeOnCIPass

#25133 autotest: rename PayLoadPlaceMission to PayloadPlaceMission
  Tools/autotest/ArduCopter_Tests/PayloadPlaceMission/copter_payload_place.txt
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#25131 AP_TECS: fixed descent or lack of climb bug
  libraries/AP_TECS/AP_TECS.cpp
Labels: BUG, Plane, MergeOnCIPass

#25027 GPS: lower required rate for moving baseline rover
  libraries/AP_GPS/AP_GPS.cpp
Labels: GPS

#25043 AP_Scripting: added logging to EFI_Halo6000.lua driver
  libraries/AP_Scripting/drivers/EFI_Halo6000.lua
Labels: Scripting
