Repository ArduPilot/ardupilot, pull requests merged in 2023-05, with the labels that each got.

#23624 AP_HAL: default CAN_Px_DRIVER to 0 on SITL
  libraries/AP_HAL/board/sitl.h
Labels: SITL, MergeOnCIPass

#23189 Plane: don't trigger RC failsafe until RC has been received for the first time
  ArduPlane/AP_Arming.cpp
  ArduPlane/AP_Arming.h
  ArduPlane/radio.cpp
Labels: Plane, WIP, WikiNeeded, For-4.5

#23579 Tools: sim_vehicle to only launch one 1455x UDP port
  Tools/autotest/sim_vehicle.py
Labels: DevEnv, SITL

#23609 AP_Mount: Siyi supports absolute zoom control
  libraries/AP_Mount/AP_Mount_Siyi.cpp
  libraries/AP_Mount/AP_Mount_Siyi.h
Labels: Enhancement

#23649 waf: added -g option to configure
  Tools/ardupilotwaf/boards.py
  wscript
Labels: BuildSystem

#23644 Tools: bisect-helper.py: require a failure string if doing a --build
  Tools/autotest/bisect-helper.py
Labels: MergeOnCIPass

#23665 Advanced timers are now determined automatically on L4+
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32l4+_mcuconf.h
Labels: BUG, ChibiOS

#23604 AP_Scripting: added example that slew a servo with controls
  libraries/AP_Scripting/examples/servo_slew.lua
Labels: Scripting, MergeOnCIPass

#23645 hwdef: airbotf4: minimize this board
  libraries/AP_HAL_ChibiOS/hwdef/airbotf4/hwdef.dat
Labels: DevCallEU

#23573 Tools: update ROS 2 README
  Tools/ros2/README.md
Labels: ROS, MergeOnCIPass

#23678 autotest: stop vehicle from entering RTL instantly when it enters auto
  Tools/autotest/common.py
Labels: MergeOnCIPass

#23677 autotest: add progress file for enable-in-turn
  Tools/autotest/test_build_options.py
Labels: MergeOnCIPass

#23643 Tools: remove old bufsize parameters
  Tools/autotest/bisect-helper.py
  Tools/autotest/check_autotest_speedup.py
  Tools/scripts/build_binaries.py
Labels: MergeOnCIPass

#23675 autotest: bisect-helper.py: improve py2 compatability, improve diagnostics
  Tools/autotest/bisect-helper.py
Labels: MergeOnCIPass

#23679 Tools: option to not reconfigure on each sim_vehicle.py run
  Tools/autotest/sim_vehicle.py
Labels: BuildSystem, MergeOnCIPass

#23540 AP_DDS: GeoPose Publisher
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/Idl/geographic_msgs/msg/GeoPoint.idl
  libraries/AP_DDS/Idl/geographic_msgs/msg/GeoPose.idl
  libraries/AP_DDS/Idl/geographic_msgs/msg/GeoPoseStamped.idl
  libraries/AP_DDS/README.md
  libraries/AP_DDS/dds_xrce_profile.xml
Labels: ROS, MergeOnCIPass, For-4.5

#22278 Tools: scripts: create mavlink_parse.py
  Tools/scripts/mavlink_parse.py
Labels: Enhancement, Tools, AllVehicles, Docs, MAVLink, WikiNeeded

#23693 Sub: backport mavlink_parse for docs generation
  Tools/scripts/mavlink_parse.py
Labels: 4.1 Backport

#23688 HAL_ChibiOS: fixed asserts in AnalogIn driver
  libraries/AP_HAL_ChibiOS/AnalogIn.cpp
  libraries/AP_HAL_ChibiOS/AnalogIn.h
Labels: BUG, ChibiOS

#23696 AP_Motors: Heli: get_output_mask return only motors
  libraries/AP_Motors/AP_MotorsHeli.cpp
  libraries/AP_Motors/AP_MotorsHeli.h
  libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
  libraries/AP_Motors/AP_MotorsHeli_Dual.h
  libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
  libraries/AP_Motors/AP_MotorsHeli_Quad.h
  libraries/AP_Motors/AP_MotorsHeli_RSC.cpp
  libraries/AP_Motors/AP_MotorsHeli_RSC.h
  libraries/AP_Motors/AP_MotorsHeli_Single.cpp
Labels: TradHeli

#23699 Tools: size_compare_branches.py: quieten rsync
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#23707 hwdef: correct double-definitions of DEFAULT_NTF_LED_TYPES
  libraries/AP_HAL_ChibiOS/hwdef/MatekF765-SE/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF765-Wing-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/SkystarsH7HD-bdshot/hwdef.dat
Labels: MergeOnCIPass

#23685 autotest: improve diagnostics when waiting for EKF state
  Tools/autotest/common.py
Labels: MergeOnCIPass

#22674 Tools: Add missing functions for Simulink model
  Tools/simulink/arducopter/functions/dcmFromEuler.m
  Tools/simulink/arducopter/functions/fromAxisAngle.m
  Tools/simulink/arducopter/functions/quatMult.m
  Tools/simulink/arducopter/sid_controller_validation.m
Labels: Tools

#23656 AP_Motors: test: fix for heli
  libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp
Labels: TradHeli

#23694 AP_DDS: Support single and double precision hardware
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: BUG, ROS, DevCallTopic, For-4.5

#23698 Actions: test_size: fix elf diff for vehicles
  .github/workflows/test_size.yml
Labels: DevCallTopic

#23695 SITL: fix memory leak on multi fcu json sim
  libraries/SITL/SIM_JSON_Master.cpp
Labels: BUG, SITL, DevCallEU

#23718 FoxeerH743 GA release
  libraries/AP_HAL_ChibiOS/hwdef/FoxeerH743v1/FoxeerH743_Board.JPG
  libraries/AP_HAL_ChibiOS/hwdef/FoxeerH743v1/README.md
  libraries/AP_HAL_ChibiOS/hwdef/FoxeerH743v1/hwdef.dat
Labels: BUG, ChibiOS, WikiNeeded, DevCallEU, 4.4 Backport

#23746 Tools: Web: Add FFT batch log review tool
  Tools/autotest/web-firmware/Tools/FilterReview/DecodeDevID.js
  Tools/autotest/web-firmware/Tools/FilterReview/FilterReview.js
  Tools/autotest/web-firmware/Tools/FilterReview/Readme.md
  Tools/autotest/web-firmware/Tools/FilterReview/index.html
  Tools/autotest/web-firmware/Tools/FilterReview/parser.js
Labels: MergeOnCIPass

#23743 AP_GPS: Add const and WARN_IF_UNUSED to AP_GPS_GSOF
  libraries/AP_GPS/AP_GPS.h
  libraries/AP_GPS/AP_GPS_GSOF.cpp
  libraries/AP_GPS/AP_GPS_GSOF.h
Labels: GPS, Driver, Non-Functional Change

#23756 Tools: WSL2 python.exe uploader.py stdout to be unbuffered via -u
  Tools/ardupilotwaf/chibios.py
Labels: DevEnv, MergeOnCIPass

#23747 Tools: size_compare_branches.py: add --parallel option
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#23757 Tools: add ./waf --upload-force arg to allow uploader.py to do --force
  Tools/ardupilotwaf/ardupilotwaf.py
  Tools/ardupilotwaf/chibios.py
Labels: DevEnv, AP_Periph

#23762 AP_GPS: Remove unused member variable in gsof driver
  libraries/AP_GPS/AP_GPS_GSOF.cpp
  libraries/AP_GPS/AP_GPS_GSOF.h
Labels: GPS, Driver, Non-Functional Change

#23761 AP_HAL: Add reference to sparse endian manpage
  libraries/AP_HAL/utility/sparse-endian.h
Labels: Docs, MergeOnCIPass

#23765 Tools: size_compare_branches: avoid elf_diff when not requested
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#22944 autotest: break out a dump_process_status method
  Tools/autotest/common.py
Labels: MergeOnCIPass

#23774 SITL: guard against LP5562 not being included
  libraries/SITL/SIM_I2C.cpp
Labels: MergeOnCIPass

#23770 Tools: size_compare_branches.py: add option to hide lines with no binary changes
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#23625 AP_HAL_ChibiOS: fix battery monitor params for CubeRed
  libraries/AP_HAL_ChibiOS/hwdef/CubeRedPrimary/hwdef.dat
Labels: BUG

#23768 AC_Avoidance: make _output_level AP_Enum
  libraries/AC_Avoidance/AP_OADatabase.cpp
  libraries/AC_Avoidance/AP_OADatabase.h
Labels: DevCallTopic

#23777 AP_Filesystem: remove unused header
  libraries/AP_Filesystem/AP_Filesystem_Available.h
Labels: DevCallTopic

#23755 AP_GPS: Add missing const to the rest of the headers
  libraries/AP_GPS/AP_GPS_GSOF.cpp
  libraries/AP_GPS/AP_GPS_GSOF.h
Labels: GPS, Driver, DevCallTopic, Non-Functional Change

#23779 AP_AHRS: pre-declare Location object
  libraries/AP_AHRS/AP_AHRS_Backend.h
Labels: MergeOnCIPass

#23780 SITL: add simulator for LM2755 RGBLED
  libraries/SITL/SIM_I2C.cpp
  libraries/SITL/SIM_LM2755.cpp
  libraries/SITL/SIM_LM2755.h
Labels: MergeOnCIPass

#23620 APBoardConfig: Add skip validate board
  libraries/AP_BoardConfig/AP_BoardConfig.cpp
  libraries/AP_BoardConfig/AP_BoardConfig.h
  libraries/AP_BoardConfig/board_drivers.cpp
Labels: DevCallTopic, Scripting

#23733 autotest: integrate features.json generation to build_binaries.py
  Tools/scripts/build_binaries.py
  Tools/scripts/generate_features_txt_files.py
Labels: 4.4 Backport

#23790 Load test gains for correct axis when testing yaw D
  libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
Labels: BUG, Copter, MergeOnCIPass, 4.4 Backport

#23787 Filter: correct description of filter tracking mode
  libraries/Filter/HarmonicNotchFilter.cpp
Labels: WikiNeeded, MergeOnCIPass

#23729 Use enum classes and shorten variable names in GSOF
  libraries/AP_GPS/AP_GPS_GSOF.cpp
  libraries/AP_GPS/AP_GPS_GSOF.h
Labels: GPS, Driver, DevCallEU, Non-Functional Change

#21772 AP_GPS: log fragments used/fragments discarded for RTCM injection data
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS.h
  libraries/AP_GPS/LogStructure.h
Labels: DevCallEU

#23810 Correct locking on LED thread
  libraries/AP_HAL_ChibiOS/RCOutput.cpp
Labels: BUG, AllVehicles, ChibiOS, MergeOnCIPass

#23783 Tools: use methods to determine port numbers
  Tools/autotest/common.py
  Tools/autotest/pysim/util.py
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#23739 .github: use fixed revision for docker dev containers
  .github/workflows/test_ccache.yml
  .github/workflows/test_chibios.yml
  .github/workflows/test_coverage.yml
  .github/workflows/test_linux_sbc.yml
  .github/workflows/test_replay.yml
  .github/workflows/test_scripting.yml
  .github/workflows/test_scripts.yml
  .github/workflows/test_sitl_copter.yml
  .github/workflows/test_sitl_periph.yml
  .github/workflows/test_sitl_plane.yml
  .github/workflows/test_sitl_rover.yml
  .github/workflows/test_sitl_sub.yml
  .github/workflows/test_sitl_tracker.yml
  .github/workflows/test_size.yml
  .github/workflows/test_unit_tests.yml
Labels: CI, MergeOnCIPass

#23742 AP_RCProtocol: Fix the issue of ST24 receiver not working
  libraries/AP_RCProtocol/AP_RCProtocol_ST24.cpp
Labels: MergeOnCIPass

#23801 Fix early exit from loiter to alt and loiter to time when using large WP_LOITER_NAV values
  ArduPlane/Plane.h
  ArduPlane/mode_loiter.cpp
  ArduPlane/navigation.cpp
Labels: Plane

#23826 AP_GPS: More const for gsofmsgreq
  libraries/AP_GPS/AP_GPS_GSOF.h
Labels: GPS, MergeOnCIPass, Non-Functional Change

#23817 AP_Notify: bump up max number of simulated notify devices
  libraries/AP_Notify/AP_Notify.cpp
Labels: MergeOnCIPass

#23680 Tools: logger_metadata: add emit_md
  .gitignore
  Tools/autotest/logger_metadata/emit_md.py
  Tools/autotest/logger_metadata/parse.py
Labels: MergeOnCIPass

#23728 Mode takeoff step by step
  ArduPlane/mode_takeoff.cpp
Labels: DevCallTopic

#23818 AP_BattMonitor: allow max amps to be configured on INS2XX
  libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_INA2xx.h
Labels: DevCallTopic, WikiNeeded

#23834 AP_GPS: Update GSOF docs with newer links
  libraries/AP_GPS/AP_GPS_GSOF.cpp
  libraries/AP_GPS/AP_GPS_GSOF.h
Labels: GPS, Docs

#23835 Enforce max of 10 GSOF outputs per the manual via static_assert
  libraries/AP_GPS/AP_GPS_GSOF.cpp
Labels: GPS, Non-Functional Change

#23832 Copter: Add GCS Failsafe Brake option
  ArduCopter/Parameters.cpp
  ArduCopter/defines.h
  ArduCopter/events.cpp
Labels: Copter, Safety, MergeOnCIPass

#23852 AP_HAL_ChibiOS: disable watchdog only for non periph bootloaders
  libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: DevCallTopic, AP_Periph

#23657 Plane: Quadplane: move modes fully to run function
  ArduPlane/Attitude.cpp
  ArduPlane/mode_qacro.cpp
  ArduPlane/mode_qautotune.cpp
  ArduPlane/mode_qhover.cpp
  ArduPlane/mode_qloiter.cpp
  ArduPlane/mode_qrtl.cpp
  ArduPlane/mode_qstabilize.cpp
Labels: VTOL-Plane

#23731 .editorconfig: Update for more standards aware editors
  .editorconfig
Labels: DevEnv

#23821 AP_Motors: example: add ability to dump all matrix motor layouts in JSON format
  libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp
Labels: DevCallTopic

#23829 AP_Logger: make SCR name field instance
  libraries/AP_Logger/LogStructure.h
Labels: Enhancement, DevCallTopic

#23726 AP_ICEngine: fixed a bug engine control when running (4.3 backport)
  libraries/AP_ICEngine/AP_ICEngine.cpp
Labels: BUG, Plane, 4.3 Backport

#23858 Tools: support beta-4.3 tags for doing new beta releases
  Tools/scripts/build_binaries.py
  Tools/scripts/generate_manifest.py
Labels: BuildSystem

#23807 Improve stability of EKF3 covariance calculation
  libraries/AP_NavEKF3/AP_NavEKF3.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
Labels: BUG, EKF, 4.4 Backport

#23789 Backport of AP_HAL_ChibiOS: FoxeerH743 GA release
  libraries/AP_HAL_ChibiOS/hwdef/FoxeerH743v1/FoxeerH743_Board.JPG
  libraries/AP_HAL_ChibiOS/hwdef/FoxeerH743v1/README.md
  libraries/AP_HAL_ChibiOS/hwdef/FoxeerH743v1/hwdef.dat
Labels: 4.4 Backport

#23862 AP_Filesystem: enable posix compat functions if romfs compiled in
  libraries/AP_Filesystem/posix_compat.cpp
Labels: MergeOnCIPass

#23885 Tools: added beta-4.3 to build list
  Tools/scripts/build_sizes/build_sizes.py
Labels: BuildSystem

#23868 AP_DDS: Add UDP instructions to README
  libraries/AP_DDS/README.md
Labels: Docs, ROS, For-4.5

#23883 Reduce IMU SPI low speed on Matek H743 to 1Mhz to avoid chip initialization issues
  libraries/AP_HAL_ChibiOS/hwdef/MatekH743/hwdef.dat
Labels: BUG, 4.4 Backport

#23884 Tools: AP_Periph: Reduce the priority of outgoing ADS-B messages
  Tools/AP_Periph/can.cpp
Labels: Enhancement, AP_Periph, MergeOnCIPass

#23895 AP_BoardConfig: fixed documentation of safety options
  libraries/AP_BoardConfig/AP_BoardConfig.cpp
Labels: BUG, WikiNeeded

#23881 Tools: continue on coverage test failure
  Tools/scripts/run_coverage.py
Labels: CI

#23898 waf: also run Tools/gittools/submodule-sync.sh at distclean
  wscript
Labels: DevEnv

#23888 HAL_ChibiOS: fixed USB pass-thru for 2nd USB endpoint
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: BUG, ChibiOS, WikiNeeded

#23899 AP_GPS: add clarifying comment on _configure_config_set method
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
Labels: GPS, Non-Functional Change

#23910 github: remove elf_diff from checks we run
  .github/workflows/test_size.yml
Labels: DevCallTopic

#23828 AP_GPS: Remove gsof zero initialization
  libraries/AP_GPS/AP_GPS_GSOF.h
Labels: GPS, Non-Functional Change

#23872 AP_OSD: Add missing labels for new serial protocols
  libraries/AP_OSD/AP_OSD_ParamSetting.cpp
Labels: BUG, DevCallTopic, 4.4 Backport

#23908 AP_HAL_Chibios: Update hwdef for FlywooF405S-AIO (alternative IMUs)
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF405S-AIO/hwdef.dat
Labels: DevCallTopic

#23823 autotest: add epsilon for sprayer pump speed test
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#23909 GCS_MAVLink: remove more compass cal if it is not enabled
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#23869 AP_Temperature: slow down temp driver thread
  libraries/AP_TemperatureSensor/AP_TemperatureSensor.cpp
  libraries/AP_TemperatureSensor/AP_TemperatureSensor.h
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_MAX31865.cpp
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_MCP9600.cpp
Labels: Library

#23912 AP_Scripting: mount-poi applet sends camera feedback message
  libraries/AP_Scripting/applets/mount-poi.lua
Labels: Enhancement, Scripting, MergeOnCIPass

#23857 SITL: Value Semantics for TOW calc
  libraries/SITL/SIM_GPS.cpp
Labels: SITL, GPS, Non-Functional Change

#23928 Tools: AP_Periph: fix building of hwesc telem
  Tools/AP_Periph/can.cpp
Labels: BUG, AP_Periph

#23932 waf: revert run Tools/gittools/submodule-sync.sh at distclean
  wscript
Labels: BUG, MergeOnCIPass

#23935 Remove bdshot from speedybeef4 as it doesn't work an increases flash usage
  libraries/AP_HAL_ChibiOS/hwdef/speedybeef4v3/hwdef.dat
Labels: BUG, MergeOnCIPass
