Repository ArduPilot/ardupilot, pull requests merged in 2023-02, with the labels that each got.

#22793 AP_HAL_ChibiOS: disable watchdog in hwdef.h not in-line in code
  libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: DevCallEU

#22777 Plane: remove direct roll/pitch stick mixing support
  ArduPlane/Attitude.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/defines.h
Labels: Plane, DevCallEU

#22792 Tools: Add Sierra True series periphs
  Tools/AP_Bootloader/board_types.txt
Labels: ChibiOS, DevCallEU

#22415 hwdef: SkyViper-v2450 has no SD card on the FCU, so remove intervals-…
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
Labels: ChibiOS, DevCallEU

#22798 Reserve letter y in AP_Logger for litres/second
  libraries/AP_Logger/LogStructure.h
Labels: Logging, MergeOnCIPass

#22801 GCS_MAVLink: add warning about providing full-sized buffer to send_pa…
  libraries/GCS_MAVLink/GCS.h
Labels: MergeOnCIPass

#22795 Tools:board_types.txt - reserve ids for esp32 and esp32s3 ap_periph
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass, esp32

#21870 .github: add disco to build-size checks
  .github/workflows/test_size.yml
Labels: CI, MergeOnCIPass

#21797 AP_Mission: Initialize return variables
  libraries/AP_Mission/AP_Mission.cpp
Labels: Library, MergeOnCIPass

#22808 .github: tidy setting of environment variables
  .github/workflows/test_size.yml
Labels: MergeOnCIPass

#22818 .github: remove Disco from size builds
  .github/workflows/test_size.yml
Labels: MergeOnCIPass

#22825 SITL: fixed RealFlight RPM
  libraries/SITL/SIM_FlightAxis.cpp
Labels: SITL, MergeOnCIPass

#22827 AC_PID: AC_PI: fix param defaulting
  libraries/AC_PID/AC_PI.cpp
Labels: BUG, DevCallTopic

#22797 RC_Channel: allocate channel option for loweheiser manual control
  libraries/RC_Channel/RC_Channel.cpp
  libraries/RC_Channel/RC_Channel.h
Labels: Library

#22804 Plane: stop passing speed_scaler all over the place
  ArduPlane/Attitude.cpp
  ArduPlane/Plane.h
Labels: Plane

#22805 Copter: Clarify the exclusion determination in the ENUM definition
  ArduCopter/Parameters.h
  ArduCopter/mode.h
  ArduCopter/mode_rtl.cpp
Labels: Copter, MergeOnCIPass

#22811 AP_Scripting: add bindings for E-Stop, Motor interlock and safety state
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/examples/Safety_States.lua
  libraries/AP_Scripting/generator/description/bindings.desc
  libraries/AP_Scripting/lua_bindings.cpp
  libraries/AP_Scripting/lua_bindings.h
Labels: Scripting

#22828 AP_Mission: Match variable types
  libraries/AP_Mission/AP_Mission.cpp
Labels: Library, DevCallEU

#22842 SITL: fix heli RPM for heli SITL models
  libraries/SITL/SIM_Helicopter.cpp
Labels: BUG, TradHeli, DevCallTopic

#22837 autotest: reboot after DCMFallback test
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#22821 Tools: Update pyenv for new MacOS Clang13
  Tools/environment_install/install-prereqs-mac.sh
Labels: Tools, MergeOnCIPass

#21821 AP_Terrain: Explicitly state that they are at the same latitude
  libraries/AP_Terrain/TerrainIO.cpp
Labels: Library, MergeOnCIPass

#22853 Tools: change WSL2 host IP detection method from route to ip
  Tools/autotest/sim_vehicle.py
Labels: MergeOnCIPass

#22847 Tools: add compasses to list of features extracted
  Tools/scripts/extract_features.py
Labels: DevCallEU

#22845 AP_Camera: make trigger dist a float
  libraries/AP_Camera/AP_Camera.cpp
  libraries/AP_Camera/AP_Camera.h
Labels: DevCallEU

#22714 AP_BattMonitor: support EFI "battery" backend
  libraries/AP_BattMonitor/AP_BattMonitor.cpp
  libraries/AP_BattMonitor/AP_BattMonitor.h
  libraries/AP_BattMonitor/AP_BattMonitor_EFI.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_EFI.h
  libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
Labels: WikiNeeded, MergeOnCIPass

#22859 AP_HAL_ChibiOS: exclude more code based on HAL_WITH_IO_MCU
  libraries/AP_HAL_ChibiOS/RCInput.cpp
  libraries/AP_HAL_ChibiOS/RCInput.h
Labels: MergeOnCIPass

#22866 AP_Baro: fix bug in alt error arming check
  libraries/AP_Baro/AP_Baro.cpp
Labels: BUG, DevCallTopic

#22863 AP_Bootloader: add board id for PixFlamingo L4R5 v1
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#22888 Copter: Match type to set value
  ArduCopter/ekf_check.cpp
Labels: Copter

#22880 Tools: fix show_output bug in run_program methods
  Tools/scripts/build_binaries.py
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#22889 AP_Scripting: Docs: correct update_rpm and set_rpm_scale markup
  libraries/AP_Scripting/docs/docs.lua
Labels: Scripting

#22890 AP_HAL_ChibiOS: add HAL_WITH_MCU_MONITORING define for H757
  libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32H757xx.py
Labels: ChibiOS

#22874 Probe external compasses on foxeer reaper f745
  libraries/AP_HAL_ChibiOS/hwdef/ReaperF745/hwdef.dat
Labels: BUG, DevCallTopic, 4.3 Backport

#22905 AP_Logger: add @FieldValueEnum for rangefinder status
  libraries/AP_Logger/LogStructure.h
Labels: DevCallTopic

#22843 AP_OSD:Add avg resting cell and refactor
  libraries/AP_OSD/AP_OSD.cpp
  libraries/AP_OSD/AP_OSD.h
  libraries/AP_OSD/AP_OSD_Screen.cpp
Labels: DevCallTopic, NeedsTesting, WikiNeeded

#22902 AP_Scripting: dji rs2 driver fixes
  libraries/AP_Scripting/drivers/mount-djirs2-driver.lua
Labels: BUG, Driver, Scripting, DevCallEU

#22855 Protect vtx from pitmode changes when not enabled or not armed
  libraries/AP_VideoTX/AP_VideoTX.cpp
Labels: BUG, DevCallEU

#22846 AP_Scripting: fix uint32 bitwise not
  libraries/AP_Scripting/lua_boxed_numerics.cpp
Labels: Scripting, DevCallEU

#22812 Plane: mode allows arming return string allowing quadplane mode checks tidy
  ArduPlane/AP_Arming.cpp
  ArduPlane/mode.cpp
  ArduPlane/mode.h
  ArduPlane/mode_auto.cpp
Labels: Plane, DevCallEU

#22872 Tools: build_ci: speedup git download operations
  Tools/scripts/build_ci.sh
Labels: Tools, CI, MergeOnCIPass

#22932 SITL: stop cygwin from trying to create FIFOs
  libraries/SITL/SIM_GPS.h
Labels: SITL, MergeOnCIPass

#22935 autotest: add install_example_script_context
  Tools/autotest/common.py
Labels: MergeOnCIPass

#22951 Tools/autotest: update Williams locations.txt
  Tools/autotest/locations.txt
Labels: SITL, MergeOnCIPass

#22940 AP_HAL_ChibiOS:Default CAN Term to off on ARK GPS
  libraries/AP_HAL_ChibiOS/hwdef/ARK_GPS/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/ARK_GPS/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/ARK_RTK_GPS/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/ARK_RTK_GPS/hwdef.dat
Labels: MergeOnCIPass

#22937 AP_Compass: add and use AP_COMPASS_LIS3MDL_ENABLED
  Tools/scripts/build_options.py
  libraries/AP_Compass/AP_Compass.cpp
  libraries/AP_Compass/AP_Compass.h
  libraries/AP_Compass/AP_Compass_LIS3MDL.cpp
  libraries/AP_Compass/AP_Compass_LIS3MDL.h
  libraries/AP_Compass/AP_Compass_config.h
Labels: Driver

#22953 Tradheli autotest for manual autorotation power recovery
  Tools/autotest/helicopter.py
Labels: TradHeli, MergeOnCIPass

#22963 AP_GPS: don't try and configure M10 options on non-M10 GPS
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
  libraries/AP_GPS/AP_GPS_UBLOX.h
Labels: BUG, GPS

#22961 Tools/autotest: locations.txt add Portmoak
  Tools/autotest/locations.txt
Labels: MergeOnCIPass

#22968 AP_MotorsHeli: patch for manual autorotation
  libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
  libraries/AP_Motors/AP_MotorsHeli_Quad.cpp
  libraries/AP_Motors/AP_MotorsHeli_RSC.h
  libraries/AP_Motors/AP_MotorsHeli_Single.cpp
Labels: BUG, TradHeli

#22959 Tools: size_compare_branches.py: correct elf_diff for bootloaders
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#22969 Tools: autotest for Tradheli turbine start feature
  Tools/autotest/helicopter.py
Labels: TradHeli, MergeOnCIPass

#22975 AP_TECS: protect against low airspeed in reset
  libraries/AP_TECS/AP_TECS.cpp
Labels: Plane

#22970 AP_OpenDroneID: fixed static msg timing
  libraries/AP_OpenDroneID/AP_OpenDroneID.h
Labels: OpenDroneID

#22978 Tracker: correct compilation when AP_AdvancedFailsafe is disabled
  AntennaTracker/system.cpp
Labels: MergeOnCIPass

#22980 autotest: add nasty mission tests
  Tools/autotest/helicopter.py
Labels: MergeOnCIPass

#22977 Plane: arming: modes: don't always display
  ArduPlane/AP_Arming.cpp
Labels: Plane, MergeOnCIPass

#22962 SITL: Send VCAS in Flightgear packet.
  libraries/AP_HAL_SITL/SITL_State.cpp
Labels: SITL

#22924 RC_Channel:Add mag cal switch
  libraries/RC_Channel/RC_Channel.cpp
  libraries/RC_Channel/RC_Channel.h
Labels: WikiNeeded

#22994 AP_Periph: Fix hwesc telem temp units
  Tools/AP_Periph/can.cpp
Labels: BUG, AP_Periph, DevCallEU, Partner

#22925 RC_Channel:fix code formatting
  libraries/RC_Channel/RC_Channel.cpp
Labels: Library, MergeOnCIPass

#22991 autotest: add test for flying mission twice back-to-back
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#22964 AP_BattMonitor: refactor Option param usage
  libraries/AP_BattMonitor/AP_BattMonitor.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_Params.h
  libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.h
Labels: Library, CAN

#22979 AP_Scripting: DJIRS2 gimbal driver upside down support
  libraries/AP_Scripting/drivers/mount-djirs2-driver.lua
Labels: Driver, Scripting, DevCallEU

#22876 AP_PiccoloCAN: Fix ESC voltage and current telem scaling
  libraries/AP_PiccoloCAN/AP_PiccoloCAN.cpp
Labels: CAN, DevCallEU

#22939 AP_Scripting: luacheck: check globals
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/generator/src/main.c
  libraries/AP_Scripting/tests/luacheck.lua
Labels: DevCallTopic, Scripting, DevCallEU

#23001 AP_HAL_ChibiOS: Fix half-duplex serial on L431 periph nodes
  libraries/AP_HAL_ChibiOS/UARTDriver.cpp
Labels: MergeOnCIPass, Partner

#16677 Plane: add takeoff param TKOFF_GND_PITCH
  ArduPlane/Parameters.cpp
  ArduPlane/mode.h
  ArduPlane/mode_takeoff.cpp
  ArduPlane/takeoff.cpp
Labels: Plane, WikiNeeded, Partner

#23011 AP_Scripting: fix doc warnings
  libraries/AP_Scripting/applets/RockBlock.lua
  libraries/AP_Scripting/examples/MAVLinkHL.lua
Labels: CI, Scripting, MergeOnCIPass

#23005 AP_Periph:Add SLCAN feature note
  Tools/AP_Periph/README.md
Labels: MergeOnCIPass

#23009 RC_Channel: Check when to use
  libraries/RC_Channel/RC_Channel.cpp
Labels: MergeOnCIPass

#22929 .github: add and use ccache on cygwin build
  .github/workflows/cygwin_build.yml
Labels: DevCallTopic, CI

#22989 AP_Scripting: disable PWMSource in scripts for 4.3.4
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: ReleaseAdmin

#23026 Periph: fix sending GNSS:Heading packet at correct interval
  Tools/AP_Periph/can.cpp
Labels: GPS, AP_Periph, MergeOnCIPass

#23023 Plane: re-init throttle wait on quadplane arm and disarm
  ArduPlane/RC_Channel.cpp
  ArduPlane/quadplane.cpp
Labels: BUG

#23024 Plane: constrain tilt range for vectored yaw
  ArduPlane/tiltrotor.cpp
Labels: BUG

#23028 Tools: autotest: add a test for Rover's INITIAL_MODE
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#23029 AP_HAL_ChibiOS: Do not include debug variables in bootloader build
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
  libraries/AP_HAL_ChibiOS/system.cpp
Labels: MergeOnCIPass

#23027 autotest: remove default value for paramValue in setGCSfailsafe
  Tools/autotest/common.py
Labels: MergeOnCIPass

#23037 .github: test MatekF405-CAN bootloader builds
  .github/workflows/test_size.yml
Labels: MergeOnCIPass

#22831 ChibioOS: hwdef: CUAV-X7: correct 6.6v ADC scale factor
  libraries/AP_HAL_ChibiOS/hwdef/CUAV-X7/hwdef.dat
Labels: ChibiOS

#19461 autotest: add test for transitioning with disabled airspeed sensor
  Tools/autotest/common.py
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#23060 Tools: use build_iofirmware.py in build_ci.sh
  Tools/scripts/build_ci.sh
Labels: MergeOnCIPass

#23054 AC_Attitude:add TKOFF/LAND only weathervane option
  libraries/AC_AttitudeControl/AC_WeatherVane.cpp
  libraries/AC_AttitudeControl/AC_WeatherVane.h
Labels: MergeOnCIPass
