Repository ArduPilot/ardupilot, pull requests merged in 2023-01, with the labels that each got.

#22550 Plane: QAcro name4 longer than 4
  ArduPlane/mode.h
Labels: DevCallTopic

#22547 Copter: Fix takeoff with alt drift and wp_navalt_min set
  ArduCopter/takeoff.cpp
Labels: BUG, Copter, TradHeli, DevCallTopic, 4.3 Backport

#22542 BMI270 IMU support for omnibusf4 controllers
  libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
Labels: DevCallTopic

#22480 Plane: Events: combine failsafe event prints
  ArduPlane/events.cpp
Labels: Plane

#22504 AP_Scripting: bindings: logger: support more formats
  libraries/AP_Scripting/lua_bindings.cpp
Labels: Scripting

#22521 AP_Scripting: rename TRIK to TRIKR for sport_aerobatics
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/README.md
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua
Labels: DevCallTopic

#22523 AP_Arming: only require AP_RALLY_ENABLED if MIS_ITEM_CHECK_RALLY
  libraries/AP_Arming/AP_Arming.cpp
Labels: DevCallTopic

#22553 AP_HAL_ChibiOS: minimize Mamba405-2022
  libraries/AP_HAL_ChibiOS/hwdef/MambaF405-2022/hwdef.dat
Labels: DevCallTopic

#22526 AP_SerialManager: Add 2Mbps for simulator
  libraries/AP_SerialManager/AP_SerialManager.cpp
Labels: MergeOnCIPass

#22540 MambaH743 v2 with dual ICM42688
  libraries/AP_HAL_ChibiOS/hwdef/MambaH743v4/README.md
  libraries/AP_HAL_ChibiOS/hwdef/MambaH743v4/hwdef.dat
Labels: ChibiOS, 4.3 Backport

#22479 AP_HAL_SITL: add option to create uart connection to file
  libraries/AP_HAL_SITL/UARTDriver.cpp
Labels: WikiNeeded, MergeOnCIPass

#22302 Add test that wind estimation works on each AHRS type
  Tools/autotest/arduplane.py
  Tools/autotest/common.py
Labels: MergeOnCIPass

#22560 AP_HAL: correct sitl-on-hw compilation for Helicopters
  libraries/AP_HAL/SIMState.cpp
Labels: DevCallEU

#22561 hwdef: minimize features on VRBrain-v52 and VRCore-v10
  libraries/AP_HAL_ChibiOS/hwdef/VRBrain-v52/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VRCore-v10/hwdef.dat
Labels: DevCallEU

#22569 AP_AHRS: get_relative_position_D_home: don't use home until set
  libraries/AP_AHRS/AP_AHRS.cpp
Labels: DevCallEU

#22570 autotest: simplify Plane Rangefinder test
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#22557 Tools/autotest: automate sim_vehicle in WSL2
  Tools/autotest/sim_vehicle.py
Labels: DevEnv

#22576 autotest: rover: remove pointless try/except block
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#22581 autotest: fix un-set variable problem in verify_innov
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#22586 Tools: fix wsl2 check in sim_vehicle to match uploader.py
  Tools/autotest/sim_vehicle.py
Labels: MergeOnCIPass

#22591 autotest: give WindEstimate more time to converge
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#22596 MAVLink: save flash in CHECK_PAYLOAD_SIZE()
  libraries/GCS_MAVLink/GCS.cpp
  libraries/GCS_MAVLink/GCS.h
Labels: MAVLink

#22404 AP_Landing: Change from division to multiplication
  libraries/AP_Landing/AP_Landing_Slope.cpp
Labels: Plane

#22598 Tools: Add ardupilot_gazebo install script
  Tools/environment_install/install-ROS-ubuntu.sh
Labels: Enhancement, DevEnv

#22607 Tools: fix CI error while building for macos
  Tools/environment_install/install-prereqs-mac.sh
Labels: CI

#22610 AC_AttitudeControl: fixed time wrap bug in is_active_xy()
  libraries/AC_AttitudeControl/AC_PosControl.cpp
Labels: BUG, MergeOnCIPass

#22614 waf: add -fcheck-new to g++ build
  Tools/ardupilotwaf/boards.py
Labels: BUG, DevCallTopic

#22435 Dockerfile: sim_vehicle.py can not found mavproxy.py
  Dockerfile
Labels: DevEnv, MergeOnCIPass

#22601 Plane: bugfix - RTL_AUTOLAND no longer overrides loiter direction
  ArduPlane/mode_rtl.cpp
Labels: BUG, Plane, 4.3 Backport

#22599 AP_Scripting: sport_aerobatics trick additions and fixes
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/README.md
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua
Labels: DevCallTopic

#22336 AP_Scripting: added example for generator throttle control
  libraries/AP_Scripting/examples/gen_control.lua
Labels: Scripting

#22608 Tools: Update ardupilot_gazebo install script
  Tools/environment_install/install-ROS-ubuntu.sh
Labels: MergeOnCIPass

#22611 Copter: Use filtered and corrected range finder in surface tracking
  ArduCopter/surface_tracking.cpp
Labels: BUG, Copter, DevCallTopic, 4.3 Backport

#22618 Tools: Remove legacy code from sid_pre.m
  Tools/simulink/arducopter/sid_pre.m
Labels: BUG, Copter, MergeOnCIPass

#22622 hwdef: update thepeach hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/thepeach-k1/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/thepeach-r1/hwdef-bl.dat
Labels: MergeOnCIPass

#22619 AP_Param: correct compilation when debugging enabled
  libraries/AP_Param/AP_Param.cpp
Labels: DevCallEU

#22574 Create AP_AHRS_SIM backend
  libraries/AP_AHRS/AP_AHRS.cpp
  libraries/AP_AHRS/AP_AHRS.h
  libraries/AP_AHRS/AP_AHRS_Backend.h
  libraries/AP_AHRS/AP_AHRS_DCM.cpp
  libraries/AP_AHRS/AP_AHRS_DCM.h
  libraries/AP_AHRS/AP_AHRS_SIM.cpp
  libraries/AP_AHRS/AP_AHRS_SIM.h
Labels: NeedsTesting

#22634 Tools: param_parse.py: sort SIM_ parameters into the output files
  Tools/autotest/param_metadata/param_parse.py
Labels: MergeOnCIPass

#22637 Copter: remove FS_OPTIONS parameter conversion
  ArduCopter/Copter.h
  ArduCopter/Parameters.cpp
Labels: MergeOnCIPass

#22638 AP_HAL_ChibiOS: ignore array bounds check while checking 0x0 for writes
  libraries/AP_HAL_ChibiOS/Scheduler.cpp
Labels: MergeOnCIPass

#22656 autotest: create fresh fly_mission suitable for other missions
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#22647 SITL:add SIM param metadata
  libraries/SITL/SITL.cpp
Labels: MergeOnCIPass

#22626 AP_OpenDroneID: set EMERGENCY status on crash or chute deploy
  libraries/AP_OpenDroneID/AP_OpenDroneID.cpp
  libraries/AP_OpenDroneID/AP_OpenDroneID.h
Labels: BUG, WikiNeeded, OpenDroneID

#22631 AP_BattMoniter: don't allow equal low and critical FS thresholds
  libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp
Labels: DevCallTopic

#22640 hwdef: skyviper: remove EK3 external nav and body-frame-odometry
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
Labels: DevCallTopic

#22658 Copter: allow for flight mode UI when FRAME_CLASS=0
  ArduCopter/GCS_Copter.cpp
  ArduCopter/GCS_Mavlink.cpp
Labels: Copter

#22666 AP_Compass: fixed zero compass diagonals
  libraries/AP_Compass/AP_Compass_Backend.cpp
  libraries/AP_Compass/AP_Compass_Calibration.cpp
Labels: BUG, DevCallTopic

#22669 AP_ESC_Telem: correct esc telem debug
  libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
Labels: MergeOnCIPass

#22675 autotest: test EPM gripper
  Tools/autotest/common.py
Labels: MergeOnCIPass

#22670 AP_Logger: avoid logging duplicate FMT/UNIT/FMTU/MULT messages
  libraries/AP_Logger/LoggerMessageWriter.cpp
Labels: MergeOnCIPass

#22641 Add a boolean AP::ahrs().wind_estimate
  libraries/AP_AHRS/AP_AHRS.cpp
  libraries/AP_AHRS/AP_AHRS.h
  libraries/AP_AHRS/AP_AHRS_Backend.cpp
  libraries/AP_AHRS/AP_AHRS_Backend.h
  libraries/AP_AHRS/AP_AHRS_DCM.h
  libraries/AP_AHRS/AP_AHRS_SIM.cpp
  libraries/AP_AHRS/AP_AHRS_SIM.h
  libraries/AP_AHRS/AP_AHRS_View.h
Labels: MergeOnCIPass

#22663 Cope with sensor alignment not being set in betaflight
  libraries/AP_HAL_ChibiOS/hwdef/scripts/convert_betaflight_unified.py
Labels: BUG, DevCallEU

#22677 AP_Scripting:examples - rangefinder_test.lua : Minor Spelling Correction
  libraries/AP_Scripting/examples/rangefinder_test.lua
Labels: MergeOnCIPass

#22685 AP_InertialSensor: fixed flood of log with fast fifo reset
  libraries/AP_InertialSensor/AP_InertialSensor_Invensense.cpp
Labels: BUG, MergeOnCIPass

#22684 AP_Scripting: fixed alt frame error in ship landing
  libraries/AP_Scripting/applets/plane_ship_landing.lua
Labels: BUG, VTOL-Plane, MergeOnCIPass

#22627 AP_Scripting:add error check to mission_load.lua
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: MergeOnCIPass

#22697 AP_TemperatureSensor: add driver MAX31865
  libraries/AP_TemperatureSensor/AP_TemperatureSensor.cpp
  libraries/AP_TemperatureSensor/AP_TemperatureSensor.h
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_MAX31865.cpp
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_MAX31865.h
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.cpp
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.h
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_config.h
Labels: Driver, DevCallTopic

#22688 Tools:build_options.py rename generator rpm option to reflect what it is
  Tools/scripts/build_options.py
Labels: BuildSystem, Docs, MergeOnCIPass

#22713 Tools: make size_compare_branches.py also do bootloaders
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#22378 Plane: Auto Landing Refinement
  libraries/AP_Landing/AP_Landing.cpp
  libraries/AP_Landing/AP_Landing.h
  libraries/AP_Landing/AP_Landing_Slope.cpp
  libraries/AP_TECS/AP_TECS.cpp
Labels: WikiNeeded

#22633 AP_Scripting: added custom telem msgs for EFI_Skypower driver
  libraries/AP_Scripting/drivers/EFI_SkyPower.lua
  libraries/AP_Scripting/examples/EFI_tester.lua
Labels: Scripting

#22650 Plane: tailsitter: update I reset and limit handling
  ArduPlane/tailsitter.cpp
  ArduPlane/tailsitter.h
Labels: VTOL-Plane, DevCallTopic

#22667 Plane: Quadplane: limit manual throttle tilt angle to Q_TILT_MAX
  ArduPlane/tiltrotor.cpp
Labels: VTOL-Plane

#22689 AP_Mount: servo mount yaw handling fix
  libraries/AP_Mount/AP_Mount_Servo.cpp
Labels: BUG, Driver, DevCallTopic

#22682 AP_TemperatureSensor:correct TEMP sensor metadata
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_Params.cpp
Labels: MergeOnCIPass

#22722 Aerobatics scripts updates
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/Schedules/AirShow.txt
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/Schedules/SportPlane_Airshow.txt
Labels: DevCallTopic

#22727 HAL_SITL: exit on close of port 0 on cygwin
  libraries/AP_HAL_SITL/UARTDriver.cpp
Labels: SITL, MergeOnCIPass

#22723 SITL: fixed SIM lidar for FlightAxis
  libraries/SITL/SIM_FlightAxis.cpp
Labels: SITL, MergeOnCIPass

#22733 Tools: size_compare_branches.py: skip bootloader build for skyviper-v…
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#22745 size_compare_branches.py: add test for identicality
  Tools/scripts/size_compare_branches.py
Labels: DevCallTopic, MergeOnCIPass

#22739 AP_ADSB: bug fix send mavlink status for only two types
  libraries/AP_ADSB/AP_ADSB.cpp
Labels: BUG

#22759 AC_WPNav: Fix Bug to use WPNAV_ACCEL_C
  libraries/AC_WPNav/AC_WPNav.h
Labels: BUG, Copter, DevCallTopic

#22690 AP_Scripting: fixed reverse barrel roll
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting

#22730 Plane: transition pitch limit should not apply to FBWA
  ArduPlane/quadplane.cpp
Labels: BUG, VTOL-Plane

#22762 AP_Motors: Corrected the parameters.
  libraries/AP_Motors/AP_MotorsSingle.cpp
Labels: BUG, Copter

#22750 Plane:expand yaw autotune to other modes
  ArduPlane/Attitude.cpp
  ArduPlane/Plane.h
  ArduPlane/RC_Channel.cpp
  ArduPlane/control_modes.cpp
  ArduPlane/mode.cpp
  ArduPlane/mode.h
  ArduPlane/mode_autotune.cpp
  ArduPlane/system.cpp
Labels: WikiNeeded

#22774 Move THR_G_BOOST to Multicopter only
  libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
  libraries/AC_AttitudeControl/AC_AttitudeControl.h
  libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.cpp
  libraries/AC_AttitudeControl/AC_AttitudeControl_Multi.h
Labels: BUG, Copter, TradHeli, DevCallTopic

#22696 AP_ESC_Telem: simplify AP_TemperatureSensor integration
  libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
  libraries/AP_ESC_Telem/AP_ESC_Telem.h
Labels: AllVehicles

#22732 AP_BattMonitor: reduce MPPT gcs spam
  libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_UAVCAN.h
Labels: DevCallTopic

#22742 Plane: QRTL: combine threshold radius for QRTL and RTL
  ArduPlane/mode.h
  ArduPlane/mode_qrtl.cpp
  ArduPlane/mode_rtl.cpp
Labels: VTOL-Plane, DevCallTopic, WikiNeeded

#22747 Save freq_min_ratio when saving parameters
  libraries/Filter/HarmonicNotchFilter.cpp
Labels: BUG, Copter, DevCallTopic

#22763 AP_BoardConfig: improve description of BRD_PWM_VOLT_SEL
  libraries/AP_BoardConfig/AP_BoardConfig.cpp
Labels: WikiNeeded

#22772 Learn all the power levels when using SmartAudio 2.0
  libraries/AP_VideoTX/AP_SmartAudio.cpp
Labels: BUG, AllVehicles, 4.3 Backport

#21983 AP_Logger: split MCU from POWR into new messages, POWR log nan if voltages not available
  libraries/AP_Logger/LogFile.cpp
  libraries/AP_Logger/LogStructure.h
Labels: NeedsTesting

#22748 AP_Camera: add support for Runcam 2 4k
  libraries/AP_Camera/AP_RunCam.cpp
  libraries/AP_Camera/AP_RunCam.h
Labels: AllVehicles, Driver, WikiNeeded, MergeOnCIPass

#22232 AP_Notify: Match value types
  libraries/AP_Notify/Buzzer.cpp
Labels: Library, MergeOnCIPass

#19733 AP_HAL_ESP32: Readme update
  libraries/AP_HAL_ESP32/README.md
Labels: Docs, MergeOnCIPass, esp32

#21975 RC_Channel: Add a KILL for IMU3
  libraries/RC_Channel/RC_Channel.cpp
  libraries/RC_Channel/RC_Channel.h
Labels: MergeOnCIPass

#22344 Tools: unpack_mp.sh exclude files.html and .makehtml
  Tools/scripts/unpack_mp.sh
Labels: Tools, MergeOnCIPass
