Repository ArduPilot/ardupilot, pull requests merged in 2023-06, with the labels that each got.

#23933 Allow source code to display in size_compare_branches.py elf_diff output
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#23931 autotest: poll ftp status at intervals
  Tools/autotest/common.py
Labels: MergeOnCIPass

#23930 Improve autotest mavlink connection resiliency
  Tools/autotest/common.py
Labels: MergeOnCIPass

#23887 AP_HAL_ChibiOS: minimize VRUbrain-v51
  libraries/AP_HAL_ChibiOS/hwdef/VRUBrain-v51/hwdef.dat
Labels: MergeOnCIPass

#23629 DDS: Added subscriber support
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/Idl/sensor_msgs/msg/Joy.idl
  libraries/AP_DDS/dds_xrce_profile.xml
Labels: ROS, MergeOnCIPass, For-4.5

#23952 autotest: correct duplicate-test-name problems
  Tools/autotest/common.py
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#23950 autotest: empty buffer after printing prefixed lines
  Tools/autotest/pysim/util.py
Labels: MergeOnCIPass

#23957 HAL_ChibiOS: revert recent USB changes
  Tools/scripts/board_list.py
  Tools/scripts/build_ci.sh
  libraries/AP_Filesystem/AP_Filesystem.cpp
  libraries/AP_Filesystem/AP_Filesystem.h
  libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp
  libraries/AP_Filesystem/AP_Filesystem_FATFS.h
  libraries/AP_Filesystem/AP_Filesystem_backend.h
  libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp
  libraries/AP_HAL_ChibiOS/hwdef/HerePro/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/HerePro/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/HerePro/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/HerePro/scripts/hereproled.lua
  libraries/AP_HAL_ChibiOS/hwdef/HereProAP/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/HereProAP/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/HereProAP/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/common/board.c
  libraries/AP_HAL_ChibiOS/hwdef/common/chibios_board.mk
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
  libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg.c
  libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg.h
  libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg_cdc_msd.c
  libraries/AP_HAL_ChibiOS/hwdef/common/usbcfg_dualcdc.c
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
  libraries/AP_HAL_ChibiOS/sdcard.cpp
Labels: BUG, ChibiOS

#23961 autotest: timesync roundtrip after setting parameter
  Tools/autotest/common.py
Labels: MergeOnCIPass

#23916 hwdef: added MSP support in MatekL431-GPS
  libraries/AP_HAL_ChibiOS/hwdef/MatekL431-GPS/hwdef.dat
Labels: DevCallTopic

#23962 Pixhawk1-bdshot
  libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1-bdshot/hwdef.dat
Labels: Driver, ChibiOS

#23965 AP_DDS: Fix unitialized memory
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: BUG, ROS, MergeOnCIPass, For-4.5

#23983 AP_Scripting: fixed temperatures for Halo6000 driver
  libraries/AP_Scripting/drivers/EFI_Halo6000.lua
Labels: Scripting

#23984 autotest: care not which CAN GPS is unhealthy when in maintenance mode
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#23882 AP_JSButton: add unittest
  libraries/AP_JSButton/tests/test_jsbutton.cpp
  libraries/AP_JSButton/tests/wscript
Labels: CI, DevCallEU, Non-Functional Change

#23966 AP_DDS: Improve subscriber safety
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Generic_Fn_T.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
Labels: ROS, GSoC, MergeOnCIPass, For-4.5

#23942 Fix height above ellipsoid and undulation for SBF GPS
  libraries/AP_GPS/AP_GPS_SBF.cpp
Labels: GPS, MergeOnCIPass

#23993 AP_Mount: correct compilation when HAL_MOUNT_SERVO_ENABLED is 0
  libraries/AP_Mount/AP_Mount.cpp
Labels: MergeOnCIPass

#23998 AP_NavEKF3: Fix sign error in position fix delay compensation
  libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
Labels: BUG, EKF, MergeOnCIPass

#24002 Tools: add --exclude-board=glob to size_compare_branches.py
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#24005 AP_DDS: Fix typo with pts serial port when in UDP
  libraries/AP_DDS/README.md
Labels: Docs, ROS, MergeOnCIPass, For-4.5

#23854 AP_EFI: Update EGT for Currawong ECU
  libraries/AP_EFI/AP_EFI_Currawong_ECU.cpp
Labels: MergeOnCIPass

#24012 Tools: size_compare_branches.py: blacklist build of Pixhawk1-bdshot
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#24003 Tools: board_types.txt: reserve ID for FlyingMoonH743
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#23919 AP_Mount: fix SiYi gimbal upside-down facing not working
  libraries/AP_Mount/AP_Mount_Siyi.cpp
  libraries/AP_Mount/AP_Mount_Siyi.h
Labels: BUG, Enhancement, MergeOnCIPass

#23990 AP_Notify: tidy defines
  libraries/AP_Notify/AP_Notify.cpp
  libraries/AP_Notify/AP_Notify.h
  libraries/AP_Notify/AP_Notify_config.h
Labels: DevCallTopic

#24035 AP_GPS: fixed ublox M10S auto-config
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
  libraries/AP_GPS/AP_GPS_UBLOX.h
Labels: GPS

#24055 Copter: add has_user_takeoff in ZigZag mode
  ArduCopter/mode.h
Labels: MergeOnCIPass

#23949 Fix ground speed undershoot correction bug
  ArduPlane/Plane.h
  ArduPlane/navigation.cpp
Labels: BUG, Plane

#24069 Tools: tidy solution_status_change.py
  Tools/scripts/solution_status_change.py
Labels: MergeOnCIPass

#24031 AP_DDS: Update docs for supported topics
  libraries/AP_DDS/README.md
Labels: Docs, ROS, MergeOnCIPass, For-4.5

#23959 CI: removed appveyor
  appveyor.yml
Labels: CI, MergeOnCIPass

#19092 ChibiOS: get crash dump info on main thread lockup
  libraries/AP_HAL_ChibiOS/Scheduler.cpp
Labels: ChibiOS, MergeOnCIPass

#24079 hwdef: SkyViper doesn't have two batteries; remove code based on that
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
Labels: DevCallTopic

#24058 Copter: remove has_user_takeoff from ModeAuto class (NFC)
  ArduCopter/mode.h
Labels: MergeOnCIPass

#23943 HAL_Linux: fix RPI Check
  libraries/AP_HAL_Linux/GPIO_RPI.cpp
  libraries/AP_HAL_Linux/RCInput_RPI.cpp
  libraries/AP_HAL_Linux/RCInput_RPI.h
  libraries/AP_HAL_Linux/Util_RPI.cpp
  libraries/AP_HAL_Linux/Util_RPI.h
Labels: BUG, MergeOnCIPass

#23937 AP_HAL_Linux: Modernise CLI serial options
  libraries/AP_HAL_Linux/HAL_Linux_Class.cpp
Labels: Linux, MergeOnCIPass

#19930 AP_WindVane: Enable SITL when it is selected
  libraries/AP_WindVane/AP_WindVane.cpp
  libraries/AP_WindVane/AP_WindVane.h
Labels: MergeOnCIPass

#24082 SITL: correct compilation when AP_SIM_IS31FL3195_ENABLED off
  libraries/SITL/SIM_I2C.cpp
Labels: MergeOnCIPass

#24083 AP_HAL_Linux: fix help ouput from Options to Examples
  libraries/AP_HAL_Linux/HAL_Linux_Class.cpp
Labels: MergeOnCIPass

#24084 SITL: use SIM_config for ship and adsb simulations
  libraries/SITL/SIM_ADSB.cpp
  libraries/SITL/SIM_ADSB.h
  libraries/SITL/SIM_Ship.cpp
  libraries/SITL/SIM_Ship.h
  libraries/SITL/SIM_config.h
Labels: MergeOnCIPass

#24086 AP_Scripting: examples: plane-wind-fs: fixup for luacheck
  libraries/AP_Scripting/examples/plane-wind-fs.lua
Labels: Scripting, MergeOnCIPass

#23894 AP_ESC_Telem: Raise default timeout for the RPM spin check to 210ms
  libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
Labels: Enhancement, Copter, Library

#23922 AP_Scripting: tricks-on-a-switch activation cleanup
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/RateBased/sport_aerobatics.lua
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting

#23840 Copter: Note that this process is for SOLO
  ArduCopter/mode_brake.cpp
Labels: Copter, DevCallEU, Non-Functional Change

#24099 Plane: remove SYS_NUM_RESETS, replaced by STAT_BOOTCNT
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/system.cpp
Labels: Plane

#24067 AP_Notify: correct gate on inclusion of profiled_spi enum entry
  libraries/AP_Notify/AP_Notify.h
Labels: DevCallTopic

#24103 waf: fixed dependency of ChibiOS build on compiler flags
  Tools/ardupilotwaf/chibios.py
  libraries/AP_HAL_ChibiOS/hwdef/common/chibios_common.mk
Labels: ChibiOS, DevCallEU

#24127 Rover: Lower minimum circle tracking distance
  Rover/mode_circle.cpp
Labels: Rover, MergeOnCIPass

#24134 AC_AutoTune: correct incorrect min raw rate value
  libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
Labels: BUG

#24111 HAL_SITL: fixed multicast UDP on cygwin
  libraries/AP_HAL_SITL/UARTDriver.cpp
Labels: SITL, WikiNeeded, MergeOnCIPass

#23686 AP_Motors: Heli: remove incorrect set range call
  libraries/AP_Motors/AP_MotorsHeli_RSC.cpp
Labels: TradHeli

#24046 AP_Vehicle: initialise generator before init_ardupilot
  libraries/AP_Vehicle/AP_Vehicle.cpp
Labels: DevCallTopic

#24125 AP_RCProtocol: Refactor SUMD to remove legacy cruft
  libraries/AP_RCProtocol/AP_RCProtocol_Backend.cpp
  libraries/AP_RCProtocol/AP_RCProtocol_SUMD.cpp
  libraries/AP_RCProtocol/AP_RCProtocol_SUMD.h
Labels: Enhancement, Library

#24096 Plane:remove duplication in setting servos in MANUAL
  ArduPlane/Plane.h
  ArduPlane/mode_manual.cpp
  ArduPlane/quadplane.h
  ArduPlane/servos.cpp
Labels: Plane

#24108 Pixhawk6X bdshot
  libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6X-bdshot/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6X-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6X-bdshot/param/CUAV_V6X_defaults.parm
Labels: Driver, WikiNeeded

#24080 Plane: improved fwd throttle during VTOL landing
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane

#24153 Tools:add brake mode to build options
  Tools/scripts/build_options.py
Labels: DevCallTopic

#24150 AP_ADSB: Fix spam of lost transciever message at update() rate
  libraries/AP_ADSB/AP_ADSB_uAvionix_MAVLink.cpp
Labels: BUG, MergeOnCIPass, 4.4 Backport
