Repository ArduPilot/ardupilot, pull requests merged in 2024-03, with the labels that each got.

#26187 adding IMU data in AP_DDS library for high frequency raw imu data transmission
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Frames.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/Idl/sensor_msgs/msg/Imu.idl
  libraries/AP_DDS/dds_xrce_profile.xml
Labels: ROS, MergeOnCIPass

#26354 GCS_MAVLink: allow FTP to be compiled out with build_options.py
  Tools/scripts/build_options.py
  Tools/scripts/extract_features.py
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/GCS_Common.cpp
  libraries/GCS_MAVLink/GCS_FTP.cpp
  libraries/GCS_MAVLink/GCS_config.h
Labels: DevCallTopic

#25714 Add new board PixFlamingo F7
  Tools/bootloaders/PixFlamingo-F767_bl.bin
  libraries/AP_HAL_ChibiOS/hwdef/PixFlamingo-F767/Pixflamingo-F767-pinout.jpg
  libraries/AP_HAL_ChibiOS/hwdef/PixFlamingo-F767/README.md
  libraries/AP_HAL_ChibiOS/hwdef/PixFlamingo-F767/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/PixFlamingo-F767/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/PixFlamingo-F767/hwdef.dat
Labels: WikiNeeded

#26343 AP_Motors: Heli: remove `output_armed_zero_throttle` and use identical `output_armed_stabilizing`
  libraries/AP_Motors/AP_MotorsHeli.cpp
  libraries/AP_Motors/AP_MotorsHeli.h
Labels: TradHeli

#26382 AP_ExternalAHRS: missing check for HAL_LOGGING_ENABLED in common logging
  libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
Labels: MergeOnCIPass

#26396 RC_Channel: allow customisation of position text in aux switch announcement
  libraries/RC_Channel/RC_Channel.cpp
Labels: MergeOnCIPass

#26395 Plane: allow quadplanes to scale CAN ESC throttle like normal
  ArduPlane/radio.cpp
Labels: Plane, VTOL-Plane, CAN

#26379 Copter: Payload Place: Change PLDP_RNG_MIN to PLDP_RNG_MAX
  ArduCopter/Parameters.cpp
  ArduCopter/Parameters.h
  ArduCopter/mode_auto.cpp
Labels: Copter, WikiNeeded, MergeOnCIPass

#26406 build_ci.sh: do a test build with HAL_LOGGING_ENABLED false
  Tools/scripts/build_ci.sh
Labels: DevCallEU

#26418 autotest: show map, fence and rally when map is shown
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#26419 autotest: always check altitude when going to a location
  Tools/autotest/arducopter.py
  Tools/autotest/arduplane.py
  Tools/autotest/rover.py
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#26427 SITL: fixed the vehicle type of the simulated ship
  libraries/SITL/SIM_Ship.cpp
Labels: BUG, SITL, MergeOnCIPass

#26428 SITL: name fields in loweheiser mavlink packet
  libraries/SITL/SIM_Loweheiser.cpp
Labels: MergeOnCIPass

#26421 fix logging feature extract
  Tools/scripts/extract_features.py
Labels: BUG, MergeOnCIPass

#26430 SIM_Vicon: label fields going into ODOMETRY packets
  libraries/SITL/SIM_Vicon.cpp
Labels: MergeOnCIPass

#26434 SITL: Sim_Ship: label global_position_int and attitude packet fields
  libraries/SITL/SIM_Ship.cpp
Labels: MergeOnCIPass

#26433 SIM_Vicon: label fields going into _POSITION_ESTIMATE packets
  libraries/SITL/SIM_Vicon.cpp
Labels: MergeOnCIPass

#26429 SITL: name fields when assembling vision_position_delta message
  libraries/SITL/SIM_Vicon.cpp
Labels: MergeOnCIPass

#26460 Revert "Plane: allow quadplanes to scale ESC CAN like normal"
  ArduPlane/radio.cpp
Labels: BUG, MergeOnCIPass

#26453 AP_Mount: correct compilation when GCS not available
  libraries/AP_Mount/AP_Mount_Viewpro.cpp
  libraries/AP_Mount/AP_Mount_config.h
Labels: MergeOnCIPass

#26471 autotest: set SIM_SPEEDUP=1 for log download
  Tools/autotest/vehicle_test_suite.py
Labels: CI, MergeOnCIPass

#26475 AP_Arming: OPTIONS parameter is a bitmask
  libraries/AP_Arming/AP_Arming.cpp
Labels: DevCallTopic

#26480 Tidy use of backend type in AP_GPS
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS.h
Labels: DevCallTopic

#26444 Plane: accept set_position_target_global_int with non_INT frames
  ArduPlane/GCS_Mavlink.cpp
Labels: DevCallTopic

#26441 AP_HAL_SITL: correct define around use of RC singleton
  libraries/AP_HAL_SITL/Scheduler.cpp
Labels: DevCallTopic

#26439 AP_NavEKF3: correct compilation in SITL when logging is disabled
  libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
Labels: DevCallTopic

#26391 GCS_MAVLink: Routing: forward ADSB if local ADSB parsing if disabled
  libraries/GCS_MAVLink/MAVLink_routing.cpp
Labels: AntennaTracker, DevCallTopic

#26465 AP_BattMonitor: added MAX_AMPS and SHUNT parameters for INA239
  libraries/AP_BattMonitor/AP_BattMonitor_INA239.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_INA239.h
Labels: AP_Periph, WikiNeeded

#26486 autotest: ensure latest log is timestamped, small and not growing
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#26485 autotest: re-enable Dijkstra tests
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#26385 GCS_MAVLink: dont send timesync or on active channels for high latency links
  libraries/GCS_MAVLink/GCS.cpp
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#26473 autotest: remove special-case-for-reboot for Sub
  Tools/autotest/ardusub.py
Labels: MergeOnCIPass

#26405 AP_DDS: add missing config include in client and type_conversions
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Type_Conversions.h
Labels: ROS, DevCallEU

#26384 AP_HAL_ChibiOS: CubeRedSecondary IMU orientation fix
  libraries/AP_HAL_ChibiOS/hwdef/CubeRedSecondary/hwdef.dat
Labels: BUG, DevCallEU

#26495 AP_HAL_Chibios hwdef script: remove h747 adc duplicate pin definitions
  libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32H757xx.py
Labels: BuildSystem, ChibiOS, DevCallEU

#26504 AP_Rangefinder: fix (very) out-of-range lidar causing float inf
  libraries/AP_RangeFinder/AP_RangeFinder_SITL.cpp
Labels: BUG, SITL

#26509 Plane: fixed throttle_at_zero()
  ArduPlane/radio.cpp
Labels: BUG, VTOL-Plane, MergeOnCIPass

#26518 SITL: correct compilation on g++-7.5.0
  libraries/SITL/SIM_Ship.cpp
  libraries/SITL/SIM_Vicon.cpp
Labels: MergeOnCIPass

#26513 AP_HAL_ESP32: bugfix RmtSigReader for idf - 4.4
  libraries/AP_HAL_ESP32/RmtSigReader.cpp
Labels: esp32

#25341 hwdef: Make Crazyflie2 board and JHEMCU-GSF405A board only autobuild for Copter
  libraries/AP_HAL_ChibiOS/hwdef/crazyflie2/hwdef.dat
Labels: BuildSystem, ChibiOS

#26378 AP_HAL_ESP32: esp32s3 debugger readme in .md format
  libraries/AP_HAL_ESP32/README.s3.debug.howto.md
Labels: MergeOnCIPass, esp32

#26538 HAL_ChibiOS: fixed a cache corruption issue on H7
  libraries/AP_HAL_ChibiOS/hwdef/common/bouncebuffer.c
  libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c
Labels: BUG, DevCallTopic, MergeOnCIPass

#26546 Tools: add option to test_build_options.py to emit all disable define…
  Tools/autotest/test_build_options.py
Labels: MergeOnCIPass

#26549 autotest: add script for testing parmameter upgrades
  Tools/autotest/test_param_upgrade.py
Labels: MergeOnCIPass

#26544 AP_HAL_ChibiOS: allow IOMCU to be turned off in includes
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: DevCallTopic

#26537 GCS_MAVLink: cope with AHRS not being available
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/GCS_Common.cpp
  libraries/GCS_MAVLink/ap_message.h
Labels: DevCallTopic

#26547 AP_GyroFFT: correct compilation when AP_Arming is not compiled in
  libraries/AP_GyroFFT/AP_GyroFFT.cpp
Labels: DevCallTopic

#26534 AP_CANManager: correct array bounds used for sanity check
  libraries/AP_CANManager/AP_CANManager.h
Labels: DevCallTopic

#26525 AP_VideoTX:add additional freq bands(Band X)
  libraries/AP_VideoTX/AP_VideoTX.cpp
  libraries/AP_VideoTX/AP_VideoTX.h
Labels: DevCallTopic

#26415 AP_Motors: add new PWM_TYPE_ANGLE
  libraries/AP_Motors/AP_MotorsMulticopter.cpp
  libraries/AP_Motors/AP_Motors_Class.cpp
  libraries/AP_Motors/AP_Motors_Class.h
Labels: WikiNeeded

#26526 Plane: do_RTL: don't log mode
  ArduPlane/commands_logic.cpp
Labels: Plane, DevCallTopic

#26563 HAL_ChibioOS: fixed FDCAN -> CAN labels
  libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32H730xx.py
  libraries/AP_HAL_ChibiOS/hwdef/scripts/STM32H7A3xx.py
Labels: ChibiOS

#26560 Tools: shorten labels in build options
  Tools/scripts/build_options.py
Labels: DevCallEU

#26556 AP_Mount: viewpro fix for swapped ahrs roll pitch
  libraries/AP_Mount/AP_Mount_Viewpro.cpp
  libraries/AP_Mount/AP_Mount_Viewpro.h
Labels: BUG, Driver, NeedsTesting, DevCallEU

#26565 AP_GPS: move blended-GPS functions into AP_GPS_Blended
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/AP_GPS_Blended.cpp
Labels: DevCallEU

#26533 Rename AP_CANDriver.cpp to AP_CANManager_CANDriver_Param.cpp
  libraries/AP_CANManager/AP_CANManager.cpp
  libraries/AP_CANManager/AP_CANManager_CANDriver_Params.cpp
Labels: DevCallTopic, DevCallEU

#26484 AP_Proximity: add RPLidarC1 support
  libraries/AP_Proximity/AP_Proximity_RPLidarA2.cpp
  libraries/AP_Proximity/AP_Proximity_RPLidarA2.h
Labels: Enhancement, Driver, WikiNeeded, DevCallEU

#26292 AC_PrecLand: move common code to base class
  libraries/AC_PrecLand/AC_PrecLand_Backend.h
  libraries/AC_PrecLand/AC_PrecLand_Companion.cpp
  libraries/AC_PrecLand/AC_PrecLand_Companion.h
  libraries/AC_PrecLand/AC_PrecLand_IRLock.cpp
  libraries/AC_PrecLand/AC_PrecLand_IRLock.h
  libraries/AC_PrecLand/AC_PrecLand_SITL.cpp
  libraries/AC_PrecLand/AC_PrecLand_SITL.h
  libraries/AC_PrecLand/AC_PrecLand_SITL_Gazebo.cpp
  libraries/AC_PrecLand/AC_PrecLand_SITL_Gazebo.h
Labels: Enhancement, AllVehicles, Driver, DevCallEU

#26586 Tools: size_compare_branches.py: write out some.csv less racily
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#26584 hwdef: probe external i2c compasses on MatekL431-GPS
  libraries/AP_HAL_ChibiOS/hwdef/MatekL431-GPS/hwdef.dat
Labels: AP_Periph

#26590 CI: added --force to git tags --fetch
  Tools/scripts/build_autotest.sh
Labels: CI, MergeOnCIPass

#26580 chibios_hwdef.py: correct extraction of intdefines from hwdef files
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: MergeOnCIPass

#26593 hwdef: remove unused STM32_PWM_USE_ADVANCED defines
  libraries/AP_HAL_ChibiOS/hwdef/ACNS-CM4Pilot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/ACNS-F405AIO/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/BeastF7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/BeastF7v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/BeastH7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/BeastH7v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/BlitzF745AIO/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/F35Lightning/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF745/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/HEEWING-F405/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF4Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MambaH743v4/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-CAN/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-TE/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MazzyStarDrone/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/OmnibusNanoV6-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/OmnibusNanoV6/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/RADIX2HD/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/ReaperF745/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/SPRacingH7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/SkystarsH7HD/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/SpeedyBeeF405WING/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VRBrain-v51/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VRBrain-v52/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VRBrain-v54/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VRCore-v10/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VRUBrain-v51/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/airbotf4/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/omnibusf4v6/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/sparky2/hwdef.dat
Labels: DevCallTopic

#26599 hwdef: remove save_some_flash.inc
  libraries/AP_HAL_ChibiOS/hwdef/AtomRCF405NAVI/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF745/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/HEEWING-F405/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF4Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-TE/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/ReaperF745/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VRUBrain-v51/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/include/save_some_flash.inc
  libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-i2c-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-sd/hwdef.dat
Labels: DevCallTopic

#26603 AP_HAL: Fix incorrect return type for 64 bit float pointer conversion for MicroStrain7
  libraries/AP_HAL/utility/sparse-endian.h
Labels: BUG, MergeOnCIPass, For-4.5

#26407 Copter: Guided Angle: Initialize yaw to current yaw.
  ArduCopter/mode_guided.cpp
Labels: BUG, Copter

#24719 Copter: condition yaw fix
  libraries/AC_AttitudeControl/AC_PosControl.cpp
  libraries/AC_AttitudeControl/AC_PosControl.h
Labels: BUG, Copter, DevCallTopic

#26613 autotest: add autotest for channel-6 tuning of wp speed
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#24206 AP_NavEKF3: define Yaw alignment min GPS speed per vehicle
  libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.h
Labels: BUG

#26598 AP_ExternalAHRS: Use filter data to populate EKF status report
  libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp
  libraries/AP_ExternalAHRS/MicroStrain_common.cpp
  libraries/AP_ExternalAHRS/MicroStrain_common.h
Labels: BUG, EKF, ExternalAHRS

#26604 AP_ExternalAHRS: Only use GPS data when populating GPS fields in MicroStrain7
  libraries/AP_ExternalAHRS/AP_ExternalAHRS_MicroStrain7.cpp
Labels: BUG, For-4.5, ExternalAHRS

#26609 AP_OSD: use `set_and_default` when ensuring first screen is enabled
  libraries/AP_OSD/AP_OSD.cpp
Labels: OSD

#26623 AP_InertialSensor: Improve bitmask indicating persistent parameters on bootloader flash
  libraries/AP_InertialSensor/AP_InertialSensor.cpp
Labels: MergeOnCIPass

#26626 Tools: First commit test: added name to GIT_Success.txt file
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass
