Repository ArduPilot/ardupilot, pull requests merged in 2024-04, with the labels that each got.

#26656 Tools: move items to different build options sections
  Tools/scripts/build_options.py
Labels: DevCallTopic

#24933 AP_Scripting: raise max FLTE for yaw to 8
  libraries/AP_Scripting/applets/VTOL-quicktune.lua
  libraries/AP_Scripting/applets/VTOL-quicktune.md
Labels: VTOL-Plane

#26676 AP_Scripting: examples: update servo scan
  libraries/AP_Scripting/examples/servo_scan.lua
Labels: Scripting, DevCallEU

#26671 Autobuild reverts for bds without PWM pads
  libraries/AP_HAL_ChibiOS/hwdef/BETAFPV-F405/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF405S-AIO/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/JHEMCU-GSF405A-RX2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/JHEMCU-GSF405A/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-sd/hwdef.dat
Labels: DevCallEU

#26686 AP_Logger_MAVLink: Remove code that changes behavior when in SITL
  libraries/AP_Logger/AP_Logger_MAVLink.cpp
Labels: MergeOnCIPass

#26624 AP_InertialSensor: Fix parameter name when saving persistent accel cals for Aux IMUs
  libraries/AP_InertialSensor/AP_InertialSensor_tempcal.cpp
Labels: MergeOnCIPass

#25740 Detect board class by inheritance instead of naming
  Tools/ardupilotwaf/boards.py
  wscript
Labels: MergeOnCIPass

#26566 Add board_types for holybro
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#26568 Relay: add relay output invert function
  libraries/AP_Relay/AP_Relay.cpp
  libraries/AP_Relay/AP_Relay_Params.cpp
  libraries/AP_Relay/AP_Relay_Params.h
Labels: Enhancement, Driver, WikiNeeded, MergeOnCIPass

#26717 autotest: Fix return value of `def armed()`
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#26684 hwdef: adding IMU lines for older version of board
  libraries/AP_HAL_ChibiOS/hwdef/JHEM_JHEF405/hwdef.dat
Labels: DevCallTopic

#26716 Filter:correct which vehicles can use of throttle based notches
  libraries/Filter/HarmonicNotchFilter.cpp
Labels: MergeOnCIPass

#26732 AP_HAL_ChibiOS: add missing Math.h include
  libraries/AP_HAL_ChibiOS/Scheduler.cpp
Labels: DevCallEU

#26723 AP_Periph: correct compilation when HAL_GCS_ENABLED
  Tools/AP_Periph/GCS_MAVLink.h
Labels: DevCallEU

#26736 Lint hwdef include files
  libraries/AP_HAL_ChibiOS/hwdef/BeastF7v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CSKY405/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/F35Lightning/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/HEEWING-F405/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini-Nand/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-CAN/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-TE/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-Wing/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF405/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/OmnibusNanoV6/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Pixhawk1-1M/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/SuccexF4/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/include/minimize_features.inc
  libraries/AP_HAL_ChibiOS/hwdef/include/minimize_fpv_osd.inc
  libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro-bdshot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/omnibusf4pro/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-i2c/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
Labels: DevCallEU

#26740 AP_GPS: copy GPS metadata in for pre-per-instance-parameters
  libraries/AP_GPS/AP_GPS.cpp
Labels: MergeOnCIPass

#26739 mRo Control Zero Classic: Added ADC input for servo rail
  libraries/AP_HAL_ChibiOS/hwdef/mRoControlZeroClassic/hwdef.dat
Labels: MergeOnCIPass

#26742 Tools: reserve ID for PixPilot-V6PRO
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#26733 AP_VisualOdom: correct unused variable in visualodom
  libraries/AP_VisualOdom/AP_VisualOdom_Backend.cpp
Labels: MergeOnCIPass

#26729 Tools : add a script to make an OEM setup
  Tools/scripts/create_OEM_board.py
Labels: MergeOnCIPass

#26638 Some corrections regarding MicoAir405v2
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405v2/README.md
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405v2/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405v2/hwdef.dat
Labels: MergeOnCIPass

#26389 Added board IDs for Eagle Eye Drones
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#26578 Plane: drop min Q_TRANSITION_MS to 500ms
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, MergeOnCIPass

#26743 Tools: locations.txt gets Kaga athletic stadium
  Tools/autotest/locations.txt
Labels: DevEnv, Tools, MergeOnCIPass

#26744 hwdef: add MatekH7A3 readme.md
  libraries/AP_HAL_ChibiOS/hwdef/MatekH7A3/H7A3-SLIM.jpg
  libraries/AP_HAL_ChibiOS/hwdef/MatekH7A3/Readme.md
Labels: MergeOnCIPass

#26754 hwdef:add BIDIR to MatekH7A3
  libraries/AP_HAL_ChibiOS/hwdef/MatekH7A3/hwdef.dat
Labels: MergeOnCIPass

#26726 Copter: autoyaw: correct units returned by look_ahead_yaw
  ArduCopter/autoyaw.cpp
  ArduCopter/mode.h
Labels: MergeOnCIPass

#26746 Reserve an ID for NxtPX4v2
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#24818 AP_Mount: Do not perform unnecessary processing
  libraries/AP_Mount/AP_Mount_Siyi.cpp
  libraries/AP_Mount/AP_Mount_Viewpro.cpp
Labels: MergeOnCIPass

#26628 AP_GPS: SBF report correct satellite count on NrSV DNU value
  libraries/AP_GPS/AP_GPS_SBF.cpp
Labels: MergeOnCIPass

#26752 Copter: move #ifs to outside case statements in do_aux_function
  ArduCopter/RC_Channel.cpp
Labels: MergeOnCIPass

#26755 Reserve ID for MicoAir405Mini
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#26756 Reserving board id for sakurarc h743
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#26721 AP_HAL_ChibiOS: fixups for FoxeerF405v2
  libraries/AP_HAL_ChibiOS/hwdef/FoxeerF405v2/README.md
  libraries/AP_HAL_ChibiOS/hwdef/FoxeerF405v2/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/FoxeerF405v2/hwdef.dat
Labels: BUG, MergeOnCIPass

#26741 Add more AUX_FUNC options to RC_Channel transition-required list
  libraries/RC_Channel/RC_Channel.cpp
Labels: MergeOnCIPass

#26738 AP_Mount: Do not override default mode when first connecting to RC
  libraries/AP_Mount/AP_Mount_Backend.cpp
  libraries/AP_Mount/AP_Mount_Backend.h
Labels: BUG

#26778 AP_Scripting: improve INF inject driver
  libraries/AP_Scripting/drivers/INF_Inject.lua
Labels: Scripting, MergeOnCIPass

#26782 autotest: add test for GuidedModeThrust
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#26768 AP_Follow: use Location.change_alt_frame for what it is good for
  libraries/AP_Follow/AP_Follow.cpp
Labels: MergeOnCIPass

#26781 AP_Camera: correct compilation when HAL_MOUNT_SET_CAMERA_SOURCE_ENABL…
  libraries/AP_Camera/AP_Camera_Backend.h
  libraries/AP_Camera/AP_Camera_Mount.cpp
  libraries/AP_Camera/AP_Camera_Mount.h
Labels: DevCallTopic

#26795 autotest: allow frame to be specified when creating simple missions
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#25273 hwdef: bdshot version of the MatekF765-SE
  Tools/bootloaders/MatekF765-SE-bdshot_bl.bin
  Tools/bootloaders/MatekF765-SE-bdshot_bl.hex
  libraries/AP_HAL_ChibiOS/hwdef/MatekF765-SE-bdshot/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/MatekF765-SE-bdshot/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/MatekF765-SE-bdshot/hwdef.dat
Labels: WikiNeeded, hwdef

#26796 Plane: Fix FBWB/CRUISE missing zero crossing of elevator input
  ArduPlane/navigation.cpp
Labels: DevCallTopic

#26820 Tools: stop emitting debug as part of test_build_options.py
  Tools/autotest/test_build_options.py
Labels: MergeOnCIPass

#26813 AP_DAL: visual odom get_delay_ms return fix
  libraries/AP_DAL/AP_DAL_VisualOdom.h
Labels: BUG, DevCallEU

#26817 waf: factor out a vehicles array
  wscript
Labels: DevCallEU

#26823 AP_Arming: exclude body of AP_Arming.cpp based on AP_ARMING_ENABLED
  libraries/AP_Arming/AP_Arming.cpp
Labels: DevCallEU

#26822 AP_RCMapper: exclude body of AP_RCMapper based on AP_RCMAPPER_ENABLED
  libraries/AP_RCMapper/AP_RCMapper.cpp
  libraries/AP_RCMapper/AP_RCMapper_config.h
Labels: DevCallEU

#26838 autotest: correct command-line for sitl in FlyEachFrame
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#26834 AC_AttitudeControl: fix ATC_SLEW_YAW description (NFC)
  libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
Labels: MergeOnCIPass

#26810 Add Heli Autotune Autotest
  Tools/autotest/helicopter.py
Labels: TradHeli, MergeOnCIPass

#26845 autotest: correct parameters used for Callisto
  Tools/autotest/pysim/vehicleinfo.py
Labels: MergeOnCIPass

#26844 autotest: stop passing defaults in via --defaults to custom_sitl_comm…
  Tools/autotest/arducopter.py
  Tools/autotest/arduplane.py
  Tools/autotest/helicopter.py
  Tools/autotest/pysim/util.py
Labels: MergeOnCIPass

#26783 AP_Baro: Do not cache EAS2TAS conversions
  libraries/AP_Baro/AP_Baro.cpp
  libraries/AP_Baro/AP_Baro.h
Labels: Enhancement, Library

#26856 Plane: Limit possible climb/sink rate in FBWB/CRUISE to TECS limits
  ArduPlane/navigation.cpp
Labels: Plane

#26762 AP_NavEKF3: don't look at compass learning with GPS yaw
  libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.h
Labels: BUG, EKF, WikiNeeded, MergeOnCIPass

#25156 solved the logical error in grouping of escs into 4
  libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
Labels: BUG, DevCallEU, MergeOnCIPass

#26874 Periph: Add probe continuous checks to airspeed and compass
  Tools/AP_Periph/airspeed.cpp
  Tools/AP_Periph/compass.cpp
Labels: AP_Periph, DevCallEU

#26869 Filter: NotchFilter: return NaN for `logging_frequency` if not initialised
  libraries/Filter/NotchFilter.cpp
  libraries/Filter/NotchFilter.h
Labels: DevCallEU

#26848 AP_Baro: correct placement of field elevation #endif
  libraries/AP_Baro/AP_Baro.cpp
Labels: MergeOnCIPass

#26906 hwdef: Fix MicoAir743 internal compass rotation
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir743/hwdef.dat
Labels: MergeOnCIPass

#26883 GCS_MAVLink: Avoid serial passthrough buffer exhausted/lost data
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: DevCallTopic

#26899 AP_HAL: make NeoPixel high-low proportions match for 0 and 1
  libraries/AP_HAL/RCOutput.h
Labels: BUG

#26929 AP_Compass: workaround hardware bug in IST8310 whoami
  libraries/AP_Compass/AP_Compass_IST8310.cpp
Labels: DevCallEU
