Repository ArduPilot/ardupilot, pull requests merged in 2024-01, with the labels that each got.

#25854 Tools: Scripts: decode_ICSR: use `decoder_m4_pendsvset` function
  Tools/scripts/decode_ICSR.py
Labels: DevCallTopic

#25819 AP_Scripting: examples: update examples for fixed io.open behaviour
  libraries/AP_Scripting/examples/SN-GCJA5-particle-sensor.lua
  libraries/AP_Scripting/examples/mission-save.lua
Labels: DevCallTopic, Scripting

#25707 Don't Switch to DCM to get Better GPS if DCM Isn't Using GPS
  libraries/AP_AHRS/AP_AHRS.cpp
Labels: DevCallTopic, MergeOnCIPass

#25836 hwdef: ARKV6X add USART6 to serial list
  libraries/AP_HAL_ChibiOS/hwdef/ARKV6X/hwdef.dat
Labels: DevCallTopic, WikiNeeded

#25828 AP_ExternalAHRS: add InertialLabs to type parameter
  libraries/AP_ExternalAHRS/AP_ExternalAHRS.cpp
Labels: DevCallTopic

#25815 AC_Fence:expand FENCE_AUTOENABLE description
  libraries/AC_Fence/AC_Fence.cpp
Labels: DevCallTopic

#25856 AR_Motors: fix support for omni vehicles
  libraries/AR_Motors/AP_MotorsUGV.cpp
Labels: BUG, Rover, DevCallTopic

#25857 autotest: fixed flapping sub log download test
  Tools/autotest/vehicle_test_suite.py
Labels: DevCallTopic, CI

#25843 AP_Parachute:upate metadata in line with new relay functions
  libraries/AP_Parachute/AP_Parachute.cpp
Labels: DevCallTopic

#25810 hwdef: ARK_CANNODE add rangefinder
  libraries/AP_HAL_ChibiOS/hwdef/ARK_CANNODE/hwdef.dat
Labels: DevCallTopic

#25691 Restore use of the VTX_MAX_POWER parameter
  libraries/AP_VideoTX/AP_VideoTX.cpp
Labels: BUG, DevCallTopic

#25830 add note about Qmode FS switches to FS actions
  ArduPlane/Parameters.cpp
Labels: MergeOnCIPass

#25864 hwdef: tidy checking of is-bootloader-build
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: MergeOnCIPass

#25796 AP_HAL_SITL: ensure stdint include
  libraries/AP_HAL_SITL/CANSocketIface.cpp
Labels: SITL, MergeOnCIPass

#25845 AP_NMEA_Output: fix time format
  libraries/AP_NMEA_Output/AP_NMEA_Output.cpp
Labels: NeedsTesting

#25869 AP_Periph: rename rx-protocol-stats ins local to avoid conflict with ins singleton
  Tools/AP_Periph/can.cpp
Labels: DevCallEU

#25863 Tools: don't check all files if not files-to-check supplied
  Tools/scripts/run_flake8.py
Labels: MergeOnCIPass

#25879 autotest: Use contexts to control script lifetimes in networking tests
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#25878 chibios_hwdef.py: add quiet option to remove parsing debug output
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
  libraries/AP_HAL_ChibiOS/hwdef/scripts/dma_resolver.py
Labels: DevCallEU

#25877 AP_Camera: correct compilation when AP_CAMERA_RELAY_ENABLED is 0
  libraries/AP_Camera/AP_Camera.cpp
Labels: DevCallEU

#25866 AP_InertialSensor: SITL: call logging singleton methods only if avail…
  libraries/AP_InertialSensor/AP_InertialSensor_SITL.cpp
Labels: DevCallEU

#25884 AP_Relay: allow hwdef to provide more then 6 relays
  libraries/AP_Relay/AP_Relay.cpp
  libraries/AP_Relay/AP_Relay.h
Labels: Enhancement, Library, AllVehicles, DevCallTopic, MergeOnCIPass

#25883 AP_Camera:fix OPTIONS bitmask
  libraries/AP_Camera/AP_Camera_Backend.h
  libraries/AP_Camera/AP_Camera_Params.cpp
Labels: BUG

#25885 AP_Networking: don't build lwip code if not needed
  libraries/AP_Networking/AP_Networking_Config.h
  libraries/AP_Networking/lwip_hal/arch/sys_arch.cpp
Labels: MergeOnCIPass, Networking

#25886 chibios_hwdef.py: populate intdefines as part of parsing, not output
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: DevCallTopic

#25899 autotest: fixed missing Blimp for enum parsing
  Tools/autotest/logger_metadata/enum_parse.py
Labels: BUG, BuildSystem

#25887 Tools: improve diagnostics from failed check_replay
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#25897 Tools: added name to GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#25903 AP_Networking: fixed build of evtimer.c on firmware server
  libraries/AP_Networking/lwip_hal/arch/evtimer.c
Labels: BuildSystem

#25908 Tools: on esp32 force constants to single-precision like chibios port…
  Tools/ardupilotwaf/boards.py
Labels: esp32

#25915 Tools: allow CPUInfo to build on systems without ESC telem
  Tools/CPUInfo/CPUInfo.cpp
Labels: BuildSystem

#24527 Update the WiFi init code to the newer ESP-IDF (4.2+) and add WiFi station mode for both TCP and UDP.
  libraries/AP_HAL_ESP32/WiFiDriver.cpp
  libraries/AP_HAL_ESP32/WiFiUdpDriver.cpp
  libraries/AP_HAL_ESP32/WiFiUdpDriver.h
Labels: Enhancement, esp32

#25865 HAL_ESP32: bring S3's sdkconfig closer to classic , and optimise wifi…
  libraries/AP_HAL_ESP32/targets/esp32/esp-idf/sdkconfig
  libraries/AP_HAL_ESP32/targets/esp32s3/esp-idf/sdkconfig
Labels: esp32

#25919 HAL_ChibiOS: fixed DMA on SPI on H743
  libraries/AP_HAL_ChibiOS/hwdef/common/malloc.c
Labels: BUG, ChibiOS

#25904 AP_Network:add reboot req'd metadata to params missing it
  libraries/AP_Networking/AP_Networking_port.cpp
Labels: Docs, MergeOnCIPass, Non-Functional Change, Networking

#25921 AP_HAL_ESP32 : this was an attempt at resolving watchdog issues , now just needs to go
  libraries/AP_HAL_ESP32/Scheduler.cpp
  libraries/AP_HAL_ESP32/SdCard.cpp
  libraries/AP_HAL_ESP32/WiFiUdpDriver.cpp
Labels: MergeOnCIPass

#25893 AP_Networking: auto-restart PPP on error
  libraries/AP_Networking/AP_Networking_PPP.cpp
  libraries/AP_Networking/AP_Networking_PPP.h
Labels: Networking

#25888 AP_Scripting: fixed memory leak in sendfile()
  libraries/AP_Scripting/AP_Scripting.cpp
  libraries/AP_Scripting/AP_Scripting.h
  libraries/AP_Scripting/lua_bindings.cpp
Labels: Networking

#25411 AP_TECS: scale velRateMin correctly with airspeed
  libraries/AP_TECS/AP_TECS.cpp
  libraries/AP_TECS/AP_TECS.h
Labels: Plane, DevCallTopic

#25906 AP_Scripting: Add bindings for jump to landing and abort in the mission
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: Scripting

#25876 Copter: Throw mode check altitude params
  ArduCopter/Parameters.cpp
  ArduCopter/Parameters.h
  ArduCopter/mode_throw.cpp
Labels: WikiNeeded, MergeOnCIPass

#25936 Tools: uploader.py: set write_timeout
  Tools/scripts/uploader.py
Labels: Tools

#25939 AR_Motors: fix prearm for omni outputs
  libraries/AR_Motors/AP_MotorsUGV.cpp
Labels: BUG, Rover

#25927 AP_Mount: switch to RC_TARGETING on RC input
  libraries/AP_Mount/AP_Mount_Backend.cpp
  libraries/AP_Mount/AP_Mount_Backend.h
  libraries/AP_Mount/AP_Mount_Gremsy.cpp
  libraries/AP_Mount/AP_Mount_SToRM32.cpp
  libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
  libraries/AP_Mount/AP_Mount_Scripting.cpp
  libraries/AP_Mount/AP_Mount_Servo.cpp
  libraries/AP_Mount/AP_Mount_Siyi.cpp
  libraries/AP_Mount/AP_Mount_SoloGimbal.cpp
  libraries/AP_Mount/AP_Mount_Viewpro.cpp
  libraries/AP_Mount/AP_Mount_Xacti.cpp
Labels: Enhancement, WikiNeeded

#25932 AP_HAL_ChibiOS: Only test SPI clock if SPI is enabled
  libraries/AP_HAL_ChibiOS/HAL_ChibiOS_Class.cpp
Labels: DevCallEU

#25706 TradHeli: script for idle control
  libraries/AP_Scripting/applets/Heli_idle_control.lua
  libraries/AP_Scripting/applets/Heli_idle_control.md
Labels: TradHeli, Scripting

#25937 AP_Mount.cpp: send gimbal_manager_status msg when control changes
  libraries/AP_Mount/AP_Mount_Backend.cpp
  libraries/AP_Mount/AP_Mount_Backend.h
Labels: Enhancement, Driver, DevCallEU

#25926 BattMonitor: DroneCAN batteries report and log state-of-health percentage
  libraries/AP_BattMonitor/AP_BattMonitor.cpp
  libraries/AP_BattMonitor/AP_BattMonitor.h
  libraries/AP_BattMonitor/AP_BattMonitor_Backend.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_Backend.h
  libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.h
  libraries/AP_BattMonitor/AP_BattMonitor_Logging.cpp
  libraries/AP_BattMonitor/LogStructure.h
Labels: Enhancement, DevCallEU

#25957 Tools: added Alia xplane parameters
  Tools/Frame_params/QuadPlanes/XPlane-Alia.parm
Labels: SITL

#25955 AP_HAL_ChibiOS: Update defaults.parm of luminousbee5 board
  libraries/AP_HAL_ChibiOS/hwdef/luminousbee5/defaults.parm
Labels: DevCallTopic

#25973 Tools: add bin file when building binaries for Here4FC
  Tools/scripts/build_binaries.py
Labels: MergeOnCIPass

#25930 Tools: ros2: pass verbose flag to micro-ROS agent.
  Tools/ros2/ardupilot_sitl/src/ardupilot_sitl/launch.py
Labels: ROS, MergeOnCIPass

#25267 Update sitl-on-hardware README.md to match new file paths.
  Tools/scripts/sitl-on-hardware/README.md
Labels: SITL, Docs, MergeOnCIPass, Non-Functional Change

#25965 Tools: Reserve board IDs for Sierra
  Tools/AP_Bootloader/board_types.txt
Labels: DevCallTopic

#25980 hwdef: correct compilation of revo-mini-sd
  libraries/AP_HAL_ChibiOS/hwdef/revo-mini-sd/hwdef.dat
Labels: DevCallTopic

#25966 AP_ADSB: de-duplicate packing of operating message
  libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.cpp
  libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.h
Labels: DevCallTopic

#25984 AP_ADSB: send absolute height in GPS packet to MXS device
  libraries/AP_ADSB/AP_ADSB_Sagetech_MXS.cpp
Labels: BUG, Library

#25935 github actions problem solvers , annotations and summary
  .github/problem-matchers/autotestfail.json
  .github/problem-matchers/autotestwarn.json
  .github/problem-matchers/gcc.json
  .github/problem-matchers/python.json
  .github/workflows/esp32_build.yml
Labels: BuildSystem, CI, MergeOnCIPass

#26005 bootloaders: add mRoControlZeroClassic bootloader
  Tools/bootloaders/mRoControlZeroClassic_bl.bin
  Tools/bootloaders/mRoControlZeroClassic_bl.hex
Labels: DevCallEU

#26006 AP_HAL_SITL: allow sim_vehicle.py -I to work again
  libraries/AP_HAL_SITL/SITL_State.cpp
Labels: DevCallEU

#25995 GCS_MAVLink: exclude entire case statement for can filter modify
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: DevCallEU

#26009 AP_Relay: pre-arm check for pin conflicts between relays.
  libraries/AP_Relay/AP_Relay.cpp
Labels: DevCallTopic

#26015 Plane: ask mode if battery voltage compensation should be done
  ArduPlane/mode.cpp
  ArduPlane/mode.h
  ArduPlane/servos.cpp
Labels: Plane

#26017 hwdef: enable ROMFS if we have a defaults filepath to embed
  libraries/AP_Param/AP_Param.cpp
  libraries/AP_Param/AP_Param.h
Labels: MergeOnCIPass

#26029 Tools: added linux boards to build sizes web page
  Tools/scripts/build_sizes/build_sizes.py
Labels: BuildSystem

#25777 AP_ExternalAHRS: Reserve Aeron ID
  libraries/AP_ExternalAHRS/AP_ExternalAHRS.h
Labels: MergeOnCIPass, ExternalAHRS

#25959 Plane:expand description of AUTOTUNE_OPTIONS
  ArduPlane/Parameters.cpp
Labels: DevCallTopic

#26023 Added board id for Anyleaf H7
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass, hwdef

#25325 SITL: add support for simulated QMC5883L compass
  libraries/SITL/SIM_I2C.cpp
  libraries/SITL/SIM_QMC5883L.cpp
  libraries/SITL/SIM_QMC5883L.h
  libraries/SITL/SIM_config.h
Labels: MergeOnCIPass

#25979 Fix Riscv64 compiler error issue #25974
  libraries/AR_Motors/AP_MotorsUGV.cpp
Labels: Rover, DevCallTopic

#26055 AP_HAL_ChibiOS: allow dshot beeps to play on all dshot ESC types
  libraries/AP_HAL_ChibiOS/Util.cpp
Labels: BUG

#26056 AP_HAL_ChibiOS: Update Sierra TrueNav hwdef
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-TrueNavIC/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-TrueNavIC/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-TrueNavPro-G4/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-TrueNavPro-G4/hwdef.dat
Labels: DevCallEU

#26065 AP_HAL_ChibiOS: Use correct pin config for ADC2 and ADC3
  libraries/AP_HAL_ChibiOS/AnalogIn.cpp
Labels: MergeOnCIPass

#26063 AP_Mission: fix use of uninitialised stack data
  libraries/AP_Mission/AP_Mission.cpp
Labels: DevCallEU

#26076 autotest: tidy setting of board type
  Tools/autotest/autotest.py
Labels: DevCallEU

#26072 Plane: factor handle_message
  ArduPlane/GCS_Mavlink.cpp
  ArduPlane/GCS_Mavlink.h
Labels: DevCallEU

#26087 AP_Param: don't enable param backup on all boards
  libraries/AP_Param/AP_Param.cpp
Labels: BUG

#26090 HAL_ChibiOS: raise SDMMC clock limit on H7
  libraries/AP_HAL_ChibiOS/hwdef/common/stm32h7_mcuconf.h
Labels: ChibiOS, Networking

#26028 Plane: move forward throttle output in VTOL modes to QuadPlane update
  ArduPlane/quadplane.cpp
  ArduPlane/servos.cpp
Labels: Plane, DelayMerge

#26100 Plane: move guided throttle passthrough to mode_guided
  ArduPlane/mode_guided.cpp
  ArduPlane/servos.cpp
Labels: Plane, DevCallEU
