Repository ArduPilot/ardupilot, pull requests merged in 2024-10, with the labels that each got.

#28227 AP_BattMonitor: add option minimum volt option
  libraries/AP_BattMonitor/AP_BattMonitor_Params.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_Params.h
  libraries/AP_BattMonitor/AP_BattMonitor_Sum.cpp
Labels: WikiNeeded

#28272 SITL: remove stale parameter metadata
  libraries/SITL/SITL.cpp
Labels: MergeOnCIPass

#28271 Copter: add turtle mode to flight modes metadata
  ArduCopter/Parameters.cpp
Labels: Copter, MergeOnCIPass, Non-Functional Change

#28145 AP_DDS: Joystick Support 2
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_joy_msg_received.py
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/README.md
Labels: ROS, MergeOnCIPass

#28273 Tools: Do not use system packages on openSUSE
  Tools/environment_install/install-prereqs-openSUSE-Tumbleweed.sh
Labels: DevEnv, MergeOnCIPass

#28275 autotest: correct frame in reposition command
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#28215 Plane: avoid calling quadplane methods if quadplane not available
  ArduPlane/ArduPlane.cpp
Labels: DevCallEU

#28281 Tools: use /usr/bin/env to find python3
  Tools/autotest/run_mission.py
  Tools/autotest/test_param_upgrade.py
  Tools/autotest/unittest/annotate_params_unittest.py
  Tools/autotest/unittest/extract_param_defaults_unittest.py
  Tools/scripts/annotate_params.py
  Tools/scripts/extract_param_defaults.py
  Tools/scripts/generate_pdef.xml_metadata.py
Labels: MergeOnCIPass

#28302 Copter: add comment to loc_from_cmd
  ArduCopter/mode.h
  ArduCopter/mode_auto.cpp
Labels: Copter, MergeOnCIPass, Non-Functional Change

#28235 Copter: Keep FIXED mode when WP_YAW_BEHAVIOR is NONE
  ArduCopter/mode_auto.cpp
Labels: BUG, Copter

#28177 AP_DDS: Wrap all topics in ifdefs
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/AP_DDS_config.h
Labels: ROS

#28305 AP_HAL_ESP32: ADC ported to new idf 5.x driver and debugged
  libraries/AP_HAL_ESP32/AnalogIn.cpp
  libraries/AP_HAL_ESP32/AnalogIn.h
Labels: esp32

#28308 AP_DroneCAN: properly convert timeout to deadline for aux frames
  libraries/AP_DroneCAN/AP_Canard_iface.cpp
Labels: BUG, CAN

#28336 Plane: stop using bit-packing for quadplane state
  ArduPlane/quadplane.h
Labels: MergeOnCIPass

#28322 AP_Logger: Align the order of definitions
  libraries/AP_Logger/AP_Logger.h
Labels: MergeOnCIPass

#28335 AP_AHRS: DCM: tidy variable creation
  libraries/AP_AHRS/AP_AHRS_DCM.cpp
Labels: MergeOnCIPass

#28318 AP_BLHeli:correct RVMASK metadata
  libraries/AP_BLHeli/AP_BLHeli.cpp
Labels: MergeOnCIPass, Non-Functional Change

#28124 Tools: Expose arbitrary waf configure and build args
  Tools/ros2/ardupilot_sitl/CMakeLists.txt
Labels: ROS, MergeOnCIPass

#28326 hwdef: GEPRCF745BTHD: remove parachute and bl-flashing support (flash…
  libraries/AP_HAL_ChibiOS/hwdef/GEPRCF745BTHD/hwdef.dat
Labels: DevCallEU

#28319 AP_DDS: publish relative true airspeed to /ap/airspeed
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/AP_DDS_config.h
  libraries/AP_DDS/Idl/geometry_msgs/msg/Vector3Stamped.idl
  libraries/AP_DDS/README.md
Labels: ROS, MergeOnCIPass

#28345 autotest: add simple test that wind estimates from DCM and EKF3 converge
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#28309 Cope with negative ESC rpms in notch filter
  libraries/AP_InertialSensor/AP_InertialSensor.cpp
Labels: DevCallEU

#28368 SITL: avoid floating point exception around rangefinder distance
  libraries/SITL/SIM_Aircraft.cpp
Labels: MergeOnCIPass

#28361 defaults_periph.h: Removed duplication for AP_STATS_ENABLED
  libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h
Labels: MergeOnCIPass

#28360 AP_KDECAN: standardize on 32 bit microsecond CAN timeouts
  libraries/AP_KDECAN/AP_KDECAN.cpp
  libraries/AP_KDECAN/AP_KDECAN.h
Labels: MergeOnCIPass, Non-Functional Change

#28358 AP_TemperatureSensor: compile all of TemperatureSensor in on boards with >2048 flash
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_config.h
Labels: MergeOnCIPass

#28357 autotest: restart MAVProxy if it exits when running under gdb
  Tools/autotest/sim_vehicle.py
Labels: MergeOnCIPass

#28291 AP_DDS: battery topic to report all the available batteries
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_battery_msg_received.py
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/README.md
Labels: ROS, MergeOnCIPass

#28386 AP_Scripting: use cached in AHRS_switch example
  libraries/AP_Scripting/examples/AHRS_switch.lua
Labels: Scripting

#28402 AP_Temperature: fix MCP9600 i2c address and TEMP9 index
  libraries/AP_TemperatureSensor/AP_TemperatureSensor.cpp
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_MCP9600.cpp
Labels: BUG, DevCallTopic

#28404 AP_Logger: mark CSRV non-streaming
  libraries/AP_Logger/LogStructure.h
Labels: DevCallTopic, CAN

#28397 AP_DroneCAN: force DroneCAN zero throttle when disarmed
  libraries/AP_DroneCAN/AP_DroneCAN.cpp
Labels: BUG, CAN

#28343 GCS_MAVLink: raise number of MAVLink ports
  libraries/GCS_MAVLink/GCS_MAVLink.h
Labels: MergeOnCIPass

#28408 Tools: remove curl from installation as its not needed
  Tools/environment_install/install-prereqs-mac.sh
Labels: CI

#27827 Plane: Reset TECS along with the rest of the controllers
  ArduPlane/mode.cpp
  ArduPlane/mode.h
Labels: DevCallEU

#28380 Plane: Refactored quadplane's SLT_Transition::active_frwd()
  ArduPlane/quadplane.cpp
Labels: DevCallEU

#28338 AP_Scripting: Add mcu_voltage
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: DevCallEU

#28412 Tools: added name to GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#28437 Tools: add --core to solution_status_change.py
  Tools/scripts/solution_status_change.py
Labels: MergeOnCIPass

#28424 Tools: added name to GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#28434 AP_DDS: Support compile-time configurable rates for each publisher
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_config.h
Labels: ROS, WikiNeeded

#28461 Frame_params: Added Starling 2 Max params file
  Tools/Frame_params/ModalAI/Starling2Max.parm
Labels: MergeOnCIPass

#28392 AP_AHRS: Change the order in which you make judgments
  libraries/AP_AHRS/AP_AHRS_DCM.cpp
Labels: MergeOnCIPass

#28409 AP_HAL_ChibiOS: do not run through SPI_RX and TX as well
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: ChibiOS, MergeOnCIPass

#28454 waf: Fail if custom hwdef file doesn't exist
  wscript
Labels: MergeOnCIPass

#28422 Change the X6 picture
  libraries/AP_HAL_ChibiOS/hwdef/ZeroOneX6/README.md
  libraries/AP_HAL_ChibiOS/hwdef/ZeroOneX6/ZeroOneX6.jpg
Labels: MergeOnCIPass

#28439 AP_DDS: Wrap services in defines
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Service_Table.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/AP_DDS_config.h
Labels: ROS, MergeOnCIPass

#28460 AP_HAL_ESP32: Switch WIFI task from FASTCPU to SLOWCPU
  libraries/AP_HAL_ESP32/WiFiDriver.cpp
  libraries/AP_HAL_ESP32/WiFiUdpDriver.cpp
Labels: esp32

#28370 AP_HAL_ESP32: RCOutput ported to new mcpwm driver
  libraries/AP_HAL_ESP32/RCOutput.cpp
  libraries/AP_HAL_ESP32/RCOutput.h
Labels: esp32
