Repository ArduPilot/ardupilot, pull requests merged in 2024-07, with the labels that each got.

#27415 AP_NavEKF2: remove unused initFailureReason
  libraries/AP_NavEKF2/AP_NavEKF2.h
Labels: DevCallTopic

#27419 AP_Temperature:expand metadata for analog sensors
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_Analog.cpp
Labels: DevCallTopic, Non-Functional Change

#27407 autotest: correct places using print rather than progress
  Tools/autotest/rover.py
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#27431 Rover: fix ModeReason on fence breaches
  Rover/failsafe.cpp
  Rover/fence.cpp
Labels: Rover

#27399 Plane: Quadplane: update Q_OPTION bit 22 description
  ArduPlane/quadplane.cpp
Labels: VTOL-Plane, WikiNeeded

#27425 AP_Scripting: ignore hidden Lua files
  libraries/AP_Scripting/lua_scripts.cpp
Labels: Scripting

#25666 EKF3: allow earth-frame fields to be estimated with an origin but no GPS
  libraries/AP_NavEKF3/AP_NavEKF3_Control.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_Measurements.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.h
Labels: EKF

#27350 SITL: Documented SIM_WIND_DIR_Z
  Tools/autotest/vehicle_test_suite.py
  libraries/SITL/SITL.cpp
Labels: SITL, Docs, DevCallEU

#27402 Lua Script for copter CoM compensation
  libraries/AP_Scripting/applets/x-quad-cg-allocation.lua
  libraries/AP_Scripting/applets/x-quad-cg-allocation.md
Labels: DevCallEU

#27440 Update Pixhawk6C hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6C/hwdef.dat
Labels: MergeOnCIPass

#27454 AC_Sprayer: create and use an AP_Sprayer_config.h
  libraries/AC_Sprayer/AC_Sprayer.cpp
  libraries/AC_Sprayer/AC_Sprayer.h
  libraries/AC_Sprayer/AC_Sprayer_config.h
Labels: MergeOnCIPass

#27455 AP_Logger: remove unused _log_file_size_bytes variable
  libraries/AP_Logger/AP_Logger_Backend.cpp
  libraries/AP_Logger/AP_Logger_Backend.h
  libraries/AP_Logger/AP_Logger_Block.cpp
Labels: MergeOnCIPass

#27456 SITL: remove duplicated crc code
  libraries/SITL/SIM_GPS_NOVA.cpp
  libraries/SITL/SIM_GPS_NOVA.h
Labels: MergeOnCIPass

#27433 AP_Scripting: added NMEA 2000 EFI driver
  libraries/AP_Scripting/drivers/EFI_NMEA2k.lua
  libraries/AP_Scripting/drivers/EFI_NMEA2k.md
  libraries/AP_Scripting/modules/NMEA_2000.lua
Labels: Scripting, WikiNeeded, DevCallEU

#27479 Copter: remove unused #if around rangefinder
  ArduCopter/surface_tracking.cpp
Labels: DevCallTopic

#27492 hwdef: fixed pin definition for C-RTK2-HP
  libraries/AP_HAL_ChibiOS/hwdef/C-RTK2-HP/hwdef.dat
Labels: BUG, DevCallTopic

#27489 autotest: param_metadata: add jerk as a known unit
  Tools/autotest/param_metadata/param.py
Labels: MergeOnCIPass

#27490 autotest: fix race condition in DataFlashOverMAVLink test
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#27493 AP_Scripting: add missing scheduler include
  libraries/AP_Scripting/lua_bindings.cpp
Labels: Scripting

#27480 GCS_MAVLink: correct a debugging message
  libraries/GCS_MAVLink/MAVLink_routing.cpp
Labels: MAVLink, MergeOnCIPass

#27494 AP_HAL_ChibiOS: chibios_hwdef.py: correct flake8 issues
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: MergeOnCIPass

#27457 AP_Mount: added sending of position data to Siyi gimbal
  libraries/AP_Mount/AP_Mount_Siyi.cpp
  libraries/AP_Mount/AP_Mount_Siyi.h
Labels: Enhancement

#27460 AC_PID: correct error calculation to use latest target
  libraries/AC_PID/AC_PID.cpp
Labels: BUG

#27487 AP_NavEKF: option to align extnav to optflow pos estimate
  libraries/AP_NavEKF/AP_NavEKF_Source.cpp
  libraries/AP_NavEKF/AP_NavEKF_Source.h
Labels: Enhancement, WikiNeeded

#27495 hwdef: H757_EVAL: make it not-AP_Periph
  libraries/AP_HAL_ChibiOS/hwdef/H757I_EVAL/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/H757I_EVAL/hwdef.dat
Labels: DevCallTopic

#27486 autotest: reboot after any context in which a reboot was done
  Tools/autotest/arducopter.py
  Tools/autotest/helicopter.py
  Tools/autotest/rover.py
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#27444 AP_Periph: ensure the dshot type gets set
  Tools/AP_Periph/rc_out.cpp
Labels: MergeOnCIPass

#27476 SITL: fix json airspeed
  libraries/SITL/SIM_JSON.cpp
Labels: DevCallEU

#27501 AP_Mount: Increment the serial instance
  libraries/AP_Mount/AP_Mount.cpp
Labels: BUG, Driver

#27297 board_types.txt: PMU And GNSS ID Reserve for ZeroOne.
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#27424 AP_InertialSensor: Clearly state the maximum G-force
  libraries/AP_InertialSensor/AP_InertialSensor_ADIS1647x.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
  libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
Labels: MergeOnCIPass

#27499 AP_Math: Remove template parameter from constructor
  libraries/AP_Math/matrix3.h
  libraries/AP_Math/vector2.h
  libraries/AP_Math/vector3.h
  libraries/AP_Math/vectorN.h
Labels: Enhancement, MergeOnCIPass

#27306 AP_RPM: Demystifying RPM sensors
  libraries/AP_RPM/AP_RPM.cpp
  libraries/AP_RPM/LogStructure.h
Labels: Library, DevCallEU, MergeOnCIPass

#27496 AP_Proximity: avoid use of int16_t-read call
  libraries/AP_Proximity/AP_Proximity_LightWareSF45B.cpp
  libraries/AP_Proximity/AP_Proximity_TeraRangerTower.cpp
Labels: DevCallEU

#27352 MOUNT: Add a mount2 retract
  libraries/RC_Channel/RC_Channel.cpp
  libraries/RC_Channel/RC_Channel.h
Labels: WikiNeeded, DevCallEU

#27498 AP_InertialSensor: tidy IMU killing
  libraries/AP_InertialSensor/AP_InertialSensor.h
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
Labels: DevCallEU

#27406 AP_Periph: add ESC_RATE parameter to RC_OUT peripherals
  Tools/AP_Periph/Parameters.cpp
  Tools/AP_Periph/Parameters.h
  Tools/AP_Periph/rc_out.cpp
Labels: NeedsTesting, WikiNeeded, DevCallEU

#25351 hwdef: remove bogus EK2_RPRIMARY from Cube defaults files
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-ODID/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-SimOnHardWare/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange-joey/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/CubeRedPrimary/defaults.parm
Labels: hwdef

#27520 AP_DDS: fixed cell voltages
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: BUG, ROS, MergeOnCIPass

#27514 AP_Scripting: fixed remove call
  libraries/AP_Scripting/lua_bindings.cpp
Labels: MergeOnCIPass

#27518 AP_GPS: resolve compilation problem with timeval
  libraries/AP_GPS/AP_GPS_SITL.cpp
Labels: MergeOnCIPass

#27516 Tools: build_options.py: add AP_BARO_PROBE_EXTERNAL_COMPASSES
  Tools/scripts/build_options.py
  Tools/scripts/extract_features.py
Labels: MergeOnCIPass

#27513 AP_Filesystem: make fgets() much more efficient
  libraries/AP_Filesystem/AP_Filesystem.cpp
Labels: MergeOnCIPass

#27509 AP_Baro: avoid i2c errors with ICP101XX
  libraries/AP_Baro/AP_Baro_ICP101XX.cpp
Labels: MergeOnCIPass

#27522 waf: Revert "waf: use debug option 3 which records defines as well"
  Tools/ardupilotwaf/boards.py
Labels: MergeOnCIPass

#27430 AP_NavEKF3: log mag fusion selection to XKFS
  libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.h
  libraries/AP_NavEKF3/LogStructure.h
Labels: EKF, Logging, MergeOnCIPass

#27524 Sub: tell ahrs we can fly in multiple directions
  ArduSub/system.cpp
Labels: EKF, Sub

#27401 set the last_updated_ms field of efi_state
  libraries/AP_EFI/AP_EFI_DroneCAN.cpp
Labels: MergeOnCIPass

#27548 Copter: Payload Place: Fix first run abort
  ArduCopter/mode_auto.cpp
Labels: BUG, Copter

#27541 AP_HAL_SITL: improve periph simulation efficiency
  libraries/AP_HAL_SITL/SITL_Periph_State.cpp
Labels: MergeOnCIPass

#27540 AP_HAL_ESP32: use correct unformatted system ID length
  libraries/AP_HAL_ESP32/Util.cpp
Labels: MergeOnCIPass

#27564 Tools: fixed typo in HAGL feature
  Tools/scripts/build_options.py
  Tools/scripts/extract_features.py
Labels: MergeOnCIPass

#27562 AP_Camera: proper string formatting
  libraries/AP_Camera/AP_Camera_MAVLinkCamV2.cpp
Labels: BUG, DevCallEU

#27567 AP_Notify: remove unused BUZZER_ON/OFF defines
  libraries/AP_Notify/AP_Notify.h
Labels: DevCallEU

#27566 hwdef: prune out redundant lines
  libraries/AP_HAL_ChibiOS/hwdef/ACNS-CM4Pilot/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/ACNS-F405AIO/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/CSKY405/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir743/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/NxtPX4v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/PixFlamingo-F767/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/PixPilot-C3/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/QioTekAdeptF407/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/RadiolinkPIX6/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6SE_H743/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/YJUAV_A6Ultra/hwdef.dat
Labels: DevCallEU

#27569 Copter: add and use private ModeAuto::option_is_enabled method
  ArduCopter/mode.h
  ArduCopter/mode_auto.cpp
Labels: DevCallEU

#27575 AP_Networking: allow reconnection to TCP server or client
  libraries/AP_Networking/AP_Networking_port.cpp
Labels: DevCallEU, Networking

#27586 Add new default parameters file for ModalAI D0013 drone
  Tools/Frame_params/ModalAI/D0013.parm
Labels: QURT

#27570 Tools: add test for final-yaw behaviour in Auto mode RTL
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#27258 AP_DDS: add param DDS_DOMAIN_ID
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
Labels: ROS, MergeOnCIPass

#27349 Update README.md
  Tools/ros2/README.md
Labels: Docs, ROS, MergeOnCIPass

#27600 AP_Scripting: add Readme.md for generating message definitions
  libraries/AP_Scripting/modules/MAVLink/Readme.md
Labels: Scripting

#27601 autotest: add Mount test for relative yaw
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#27426 AP_Scripting: reduce Lua state memory usage
  libraries/AP_Scripting/generator/src/main.c
Labels: Scripting

#27568 AP_Mount: Topotek image tracking fix
  libraries/AP_Mount/AP_Mount_Topotek.cpp
  libraries/AP_Mount/AP_Mount_Topotek.h
Labels: Enhancement, Driver

#27579 AP_InertialSensor: Fix persistent storage of parameter INSn_ACCSCAL_Z
  libraries/AP_InertialSensor/AP_InertialSensor_tempcal.cpp
Labels: DevCallTopic

#27583 AP_HAL_ChibiOS: Capture the case where the persistent parameter is the newer format INSn_ACC_ID
  libraries/AP_HAL_ChibiOS/Util.cpp
Labels: DevCallTopic

#27613 hwdef: enable relay support in MatekL431-DShot fw
  libraries/AP_HAL_ChibiOS/hwdef/MatekL431-DShot/hwdef.dat
Labels: DevCallEU

#27614 Clean various autotests
  Tools/autotest/arducopter.py
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#27535 Filter: add "source" to option 5
  libraries/Filter/HarmonicNotchFilter.cpp
Labels: DevCallEU, Non-Functional Change

#27616 AP_Mount: Topotek safely parses version packet
  libraries/AP_Mount/AP_Mount_Topotek.cpp
Labels: BUG, Driver, DevCallEU

#27627 AP_Bootloader: fix build for STM32H7 without heap
  Tools/AP_Bootloader/AP_Bootloader.cpp
  Tools/AP_Bootloader/support.cpp
  Tools/AP_Bootloader/support.h
Labels: DevCallEU

#27221 Copter: Change the description(NFC)
  ArduCopter/Copter.cpp
Labels: MergeOnCIPass

#27636 AP_NavEKF3: Fix yaw alignment bug preventing copter wind estimation
  libraries/AP_NavEKF3/AP_NavEKF3_MagFusion.cpp
Labels: BUG, EKF, MergeOnCIPass

#27607 AP_Mount: Conditionally define `serial_instance` to fix unused variable compile error
  libraries/AP_Mount/AP_Mount.cpp
Labels: MergeOnCIPass

#27477 Plane: option to immediately climb in AUTO mode (not doing glide slope)
  ArduPlane/Parameters.cpp
  ArduPlane/altitude.cpp
  ArduPlane/defines.h
Labels: WikiNeeded, MergeOnCIPass

#27584 AP_InertialSensor: Check the gyro/accel id has not been previously registered
  libraries/AP_InertialSensor/AP_InertialSensor.cpp
Labels: BUG, MergeOnCIPass

#27394 AP_Notify: Perform common checks first
  libraries/AP_Notify/RGBLed.cpp
Labels: MergeOnCIPass

#27621 AP_Periph: Fix compiling issues with AP_PERIPH_PROBE_CONTIONUS enabled
  Tools/AP_Periph/compass.cpp
Labels: BUG, AP_Periph

#27231 AP_CANManager: use a switch statement to tidy driver allocation
  libraries/AP_CANManager/AP_CANManager.cpp
Labels: CAN

#26956 Rover: Change the IF statement to a SWITCH statement
  Rover/GCS_Mavlink.cpp
Labels: Rover, DevCallTopic

#25159 Added AP_WINCH options to Custom-Build server
  Tools/scripts/build_options.py
  Tools/scripts/extract_features.py
Labels: MergeOnCIPass

#27640 AP_Camera: TYPE param description get Topotek, Viewpro, Xacti
  libraries/AP_Camera/AP_Camera_Params.cpp
Labels: Driver, Non-Functional Change

#27657 autotest: tidy various tests to take advantage of new infrastructure
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#27656 autotest: add SmartRTL test for rapid switch between smartrtl and alt…
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#26853 AP_Filesystem: BOOL for binary types
  libraries/AP_Filesystem/AP_Filesystem_FATFS.cpp
Labels: MergeOnCIPass

#23182 Tools: Reserve ID for CBUnmanned CM405 Flight Controller
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass, hwdef

#27664 autotest: tidy various Rover autotests
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#27665 autotest: tidy Helicopter missions to use new infrastructure
  Tools/autotest/helicopter.py
Labels: MergeOnCIPass

#27673 autotest: tidy various ArduPlane autotests
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#27677 CI: only run qurt build on ArduPilot main repo
  .github/workflows/qurt_build.yml
Labels: MergeOnCIPass, QURT

#27679 hwdef: remove EKF opinion from FlywooF745
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF745/hwdef.dat
Labels: DevCallTopic

#27654 AP_Mission: add and use an option_is_set method
  libraries/AP_Mission/AP_Mission.cpp
  libraries/AP_Mission/AP_Mission.h
Labels: DevCallTopic

#27689 Tools: environment_install: fix focal install
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: MergeOnCIPass

#27692 autotest: correct Rover RangeFinder test
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#27687 AP_Param: Fix `ENABLE_DEBUG` enabled error with no embedded param
  libraries/AP_Param/AP_Param.cpp
Labels: DevCallTopic

#26902 Copter: Make multiple decisions into a SWITCH statement
  ArduCopter/AP_Arming.cpp
Labels: Copter

#27638 Plane: move `have_autoenabled_fences` to be private in `ModeTakeoff`
  ArduPlane/Plane.h
  ArduPlane/mode.h
  ArduPlane/mode_takeoff.cpp
Labels: Plane

#27647 Copter: correct skyviper-v2450 compilation
  ArduCopter/toy_mode.cpp
Labels: Copter

#27666 AP_Scripting: adjust string metatable setup to fix sandbox integrity
  libraries/AP_Scripting/lua/src/lstrlib.c
  libraries/AP_Scripting/lua_scripts.cpp
Labels: Scripting

#27623 board_types.txt: Reserving board IDs for Easy Aerial
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#27690 autotest: correct applet-testing scripts to use contexts for scripts
  Tools/autotest/arduplane.py
  Tools/autotest/quadplane.py
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#27697 autotest: add tests for iBus telemetry
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#27699 AP_Scripting: Change serial depends HAL_GCS to AP_SERIALMANAGER
  libraries/AP_Scripting/generator/description/bindings.desc
  libraries/AP_Scripting/lua_bindings.cpp
Labels: MergeOnCIPass

#27698 AP_DroneCAN: DNA_Server: fix handling of empty entry
  libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
Labels: MergeOnCIPass

#27691 HWDEF:fix CUAV-7-Nano default batt monitor
  libraries/AP_HAL_ChibiOS/hwdef/CUAV-7-Nano/hwdef.dat
Labels: DevCallEU

#27702 AP_NavEKF2: zero H_MAG to prevent compiler error
  libraries/AP_NavEKF2/AP_NavEKF2_MagFusion.cpp
Labels: DevCallEU

#27701 AP_NavEKF2: zero H_MAG to prevent compiler error
  libraries/AP_NavEKF2/AP_NavEKF2_MagFusion.cpp
Labels: DevCallEU

#27700 AP_NavEKF2: zero H_MAG to prevent compiler error
  libraries/AP_NavEKF2/AP_NavEKF2_MagFusion.cpp
Labels: DevCallEU

#27715 Tools: ROS2: Add missing dependencies with docs
  Tools/ros2/README.md
  Tools/ros2/ardupilot_dds_tests/package.xml
  Tools/ros2/ardupilot_sitl/package.xml
Labels: MergeOnCIPass

#27628 AC_FENCE:Add AUTOENABLE deprecation warning
  libraries/AC_Fence/AC_Fence.cpp
Labels: MergeOnCIPass

#27503 Sub: make gcs failsafe timeout a parameter
  ArduSub/Parameters.cpp
  ArduSub/Parameters.h
  ArduSub/defines.h
  ArduSub/failsafe.cpp
Labels: Sub, MergeOnCIPass
