Repository ArduPilot/ardupilot, pull requests merged in 2024-08, with the labels that each got.

#27719 Feature/vehicle compile
  libraries/AP_Vehicle/AP_Vehicle.h
Labels: Library

#27738 Tracker: remove ENABLED/DISABLED defines
  AntennaTracker/config.h
Labels: MergeOnCIPass

#27735 HAL_ChibiOS: fixed AP_FILESYSTEM_ROMFS_ENABLED for peripherals with d…
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: BUG, AP_Periph, MergeOnCIPass

#27739 Blimp: remove ENABLED/DISABLED defines
  Blimp/defines.h
Labels: Blimp

#27722 AP_SerialManager: add warning iffrsky already configured
  libraries/AP_SerialManager/AP_SerialManager.cpp
Labels: DevCallTopic

#27730 AP_ICEngine: stop engine in E-Stop
  libraries/AP_ICEngine/AP_ICEngine.cpp
Labels: Plane

#27760 AP_SerialManager: tweak error message
  libraries/AP_SerialManager/AP_SerialManager.cpp
Labels: MergeOnCIPass

#27720 AP_Camera: rely on AHRS for position, not GPS
  libraries/AP_Camera/AP_Camera.cpp
  libraries/AP_Camera/AP_Camera_Backend.cpp
Labels: MergeOnCIPass

#27762 AC_Autotune: Fix bug introduced in #27370
  libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
  libraries/AC_AutoTune/AC_AutoTune_Multi.h
Labels: MergeOnCIPass

#27761 Plane: move braces to be around entire case in do_aux_function
  ArduPlane/RC_Channel.cpp
Labels: DevCallEU

#27711 AP_NavEKF3: Corrected logged test ratios
  libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp
  libraries/AP_NavEKF3/LogStructure.h
Labels: DevCallEU

#27742 AP_HAL_SITL: work around bug in dash
  libraries/AP_HAL_SITL/system.cpp
Labels: DevCallEU

#27753 CAMERA_FOV_STATUS altitude unit fix
  libraries/AP_Camera/AP_Camera_Backend.cpp
Labels: DevCallEU

#27764 Copter: use mavlink enumeration to clarify do_change_speed implementa…
  ArduCopter/mode_auto.cpp
Labels: Copter, DevCallEU

#27774 Plane: use enum class for VTOL approach stage
  ArduPlane/Plane.h
  ArduPlane/commands_logic.cpp
  ArduPlane/mode_rtl.cpp
  ArduPlane/navigation.cpp
  ArduPlane/quadplane.cpp
Labels: DevCallEU

#27793 Copter: Fix payload place bug
  ArduCopter/mode_auto.cpp
Labels: BUG, Copter, Safety, DevCallTopic

#27797 AP_Baro: replace gcs().send_text with GCS_SEND_TEXT
  libraries/AP_Baro/AP_Baro.cpp
Labels: DevCallTopic

#27801 Tidy autotests
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#24645 AP_RPM: Allow more instances
  libraries/AP_RPM/AP_RPM.cpp
Labels: WikiNeeded, MergeOnCIPass

#27807 AP_MSP: cut more code out based on defines
  libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
Labels: DevCallTopic

#27810 AP_Compass: correct compilation when logging disabled
  libraries/AP_Compass/AP_Compass_DroneCAN.cpp
Labels: MergeOnCIPass

#27808 AP_Winch: correct compilation when backends compiled out
  libraries/AP_Winch/AP_Winch.cpp
Labels: MergeOnCIPass

#27791 AP_InertialSensor: correct warnings on static_assert requiring a message
  libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
Labels: DevCallTopic

#27789 AP_ExternalAHRS: correct VectorNAV handling of error term
  libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp
Labels: DevCallTopic

#27750 AP_DroneCAN: DNA_Server: lock all high level database operations
  libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
  libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.h
Labels: CAN

#27815 AP_Logger: correctly read file header for block logger
  libraries/AP_Logger/AP_Logger_Block.cpp
Labels: BUG

#27805 AP_GPS: fixed unconfigured uBlox pre-arm
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
Labels: BUG, GPS

#27784 AP_VideoTX:add additional freq bands(RushFPV 3.3GHz)
  libraries/AP_VideoTX/AP_VideoTX.cpp
  libraries/AP_VideoTX/AP_VideoTX.h
Labels: MergeOnCIPass

#27826 AP_Notify: tidy defaulting of DEFAULT_NTF_LED_TYPES
  libraries/AP_Notify/AP_Notify.cpp
Labels: DevCallEU

#27824 AP_Terrain: gate mavlink includes on HAL_GCS_ENABLED
  libraries/AP_Terrain/AP_Terrain.h
  libraries/AP_Terrain/TerrainGCS.cpp
Labels: DevCallEU

#27823 AP_Compass: avoid use of MAV_RESULT if mavlink bindings not used
  libraries/AP_Compass/AP_Compass.h
Labels: DevCallEU

#27837 AP_Camera: move defintiion of HAL_RUNCAM_ENABLED into AP_Camera_config.h
  libraries/AP_Camera/AP_Camera_config.h
  libraries/AP_Camera/AP_RunCam.h
Labels: MergeOnCIPass

#27853 QURT: allow for external compasses
  libraries/AP_HAL/board/qurt.h
Labels: QURT

#27077 Adding ThM (modified throttle send to engine) to EFIS log
  libraries/AP_EFI/AP_EFI_Serial_Hirth.cpp
  libraries/AP_EFI/AP_EFI_Serial_Hirth.h
Labels: MergeOnCIPass

#27076 AP_ICEngine: Add CRANK_DIR for direction control of TCA9554 Engine
  libraries/AP_ICEngine/AP_ICEngine.cpp
  libraries/AP_ICEngine/AP_ICEngine.h
  libraries/AP_ICEngine/AP_ICEngine_TCA9554.cpp
  libraries/AP_ICEngine/AP_ICEngine_TCA9554.h
Labels: WikiNeeded, MergeOnCIPass

#27821 Copter: Disarm: move autotune disarm call after setting soft arm false
  ArduCopter/AP_Arming.cpp
Labels: Copter, DevCallTopic

#27849 SRV_Channels: find_channel: use channel mask remove need for search over all channels
  libraries/SRV_Channel/SRV_Channel_aux.cpp
Labels: Enhancement

#27863 AP_DroneCAN: DNA_Server: polish db comments and organize
  libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
  libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.h
Labels: CAN, Non-Functional Change

#27864 AP_GPS: allow for EAHRS_SENSORS to not include GPS
  libraries/AP_GPS/AP_GPS.cpp
Labels: ExternalAHRS

#27781 AP_Camera: create and use an option_is_enabled
  libraries/AP_Camera/AP_Camera_Backend.cpp
  libraries/AP_Camera/AP_Camera_Backend.h
Labels: MergeOnCIPass

#27840 AP_GPS: change GPS_TYPE value 10 from SBF to Septentrio
  libraries/AP_GPS/AP_GPS_Params.cpp
Labels: WikiNeeded, MergeOnCIPass

#27852 AP_NavEKF2: added EK2_OPTIONS
  libraries/AP_NavEKF2/AP_NavEKF2.cpp
  libraries/AP_NavEKF2/AP_NavEKF2.h
Labels: EKF, WikiNeeded, MergeOnCIPass

#27860 AP_Scripting: added TECS tuning to revert param script
  libraries/AP_Scripting/applets/revert_param.lua
  libraries/AP_Scripting/applets/revert_param.md
Labels: Scripting, WikiNeeded

#27858 autotest: fix FenceFloorEnabledLanding test
  Tools/autotest/arducopter.py
Labels: DevCallEU

#27873 AP_Scripting: message_interval example handles 0hz
  libraries/AP_Scripting/examples/message_interval.lua
Labels: Scripting, MergeOnCIPass

#27845 AP_HAL_ChibiOS: do not include NeoPixel in minimum pulse separation
  libraries/AP_HAL_ChibiOS/RCOutput.cpp
Labels: BUG, DevCallEU

#27874 Add support for deca frame in QuadPlane::setup
  ArduPlane/quadplane.cpp
Labels: MergeOnCIPass

#27880 Tools: fixed SpringValley alt
  Tools/autotest/locations.txt
Labels: MergeOnCIPass

#27879 autotest: added SpringValley4
  Tools/autotest/locations.txt
Labels: MergeOnCIPass

#27878 hwdef: Add IST8310 and RM3100 Compass support for HolybroG4_GPS
  libraries/AP_HAL_ChibiOS/hwdef/HolybroG4_GPS/hwdef.dat
Labels: MergeOnCIPass

#27900 AC_AttitudeControl: update comment in is_active_xy() (NFC)
  libraries/AC_AttitudeControl/AC_PosControl.cpp
Labels: MergeOnCIPass

#27904 Copter: 4.5.6-beta1 version label fix
  ArduCopter/version.h
Labels: MergeOnCIPass, ReleaseAdmin

#27842 AP_InertialSensor: allow backend filters to be updated independently
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.cpp
  libraries/AP_InertialSensor/AP_InertialSensor_Backend.h
Labels: DevCallEU, MergeOnCIPass

#27887 AP_GSOF: Use sparse endian instead of custom code
  libraries/AP_GSOF/AP_GSOF.cpp
  libraries/AP_GSOF/AP_GSOF.h
Labels: GPS, Non-Functional Change

#27923 AP_Beacon: allow hwdefs to override number of beacons
  libraries/AP_Beacon/AP_Beacon.cpp
  libraries/AP_Beacon/AP_Beacon.h
  libraries/AP_Beacon/AP_Beacon_config.h
Labels: DevCallTopic

#27890 AP_Mount: Siyi ZT6 hardware id and set-lens fix
  libraries/AP_Mount/AP_Mount_Siyi.cpp
Labels: BUG, Driver

#27914 AP_RangeFinder: number enum entries
  libraries/AP_RangeFinder/AP_RangeFinder.h
Labels: DevCallTopic

#27938 Tools: Translate Linux Mint Wilma to Noble
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: MergeOnCIPass

#27933 AP_GPS:add note to old param names to avoid confusion
  libraries/AP_GPS/AP_GPS.cpp
  libraries/AP_GPS/MovingBase.cpp
Labels: MergeOnCIPass

#27943 AP_GPS:fix metadata typo
  libraries/AP_GPS/AP_GPS.cpp
Labels: DevCallEU

#27944 Drone build adding new board
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass, NewBoardSupport

#27931 AP_Notify:correct and expand 1 led flash sequences
  libraries/AP_Notify/GPIO_LED_1.cpp
  libraries/AP_Notify/GPIO_LED_1.h
Labels: DevCallEU

#27946 board-types.txt:reserve IDs for VIEWPRO
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#27954 autotest: test the simulated rangefinder driver
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#27956 autotest: improve diagnostics when receiving unexpected mission ack
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass
