Repository ArduPilot/ardupilot, pull requests merged in 2024-11, with the labels that each got.

#28442 APM_Control: Use deceleration for stopping distance
  libraries/APM_Control/AR_AttitudeControl.cpp
Labels: Rover, DevCallTopic

#28447 Plane: Adjust the grouping of functions to match the style
  ArduPlane/quadplane.cpp
Labels: Plane

#28479 Plane Guided Alt Command: Use frame instead of bools for setting alt frame
  ArduPlane/GCS_Mavlink.cpp
Labels: MAVLink, Non-Functional Change

#28522 [Backport] AP_HAL: add BMP390 option for navigator
  libraries/AP_HAL/board/linux.h
Labels: DevCallTopic

#28520 AP_Scripting: Applets: MissionSelector: fix error on file open and checker errors
  libraries/AP_Scripting/applets/MissionSelector.lua
Labels: Scripting, DevCallEU

#28096 AP_Camera: RunCam: get rpty channels directly using convenience functions
  libraries/AP_Camera/AP_RunCam.cpp
  libraries/AP_Camera/AP_RunCam.h
Labels: NeedsTesting, DevCallEU

#28540 AP_Boootloader: board_types.txt: correct company name for V-UAV reser…
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#28512 AP_Scripting: mount-djirs2: freshen driver
  libraries/AP_Scripting/drivers/mount-djirs2-driver.lua
  libraries/AP_Scripting/drivers/mount-djirs2-driver.md
Labels: MergeOnCIPass

#28510 Copter: Correct the typo
  ArduCopter/ReleaseNotes.txt
Labels: MergeOnCIPass

#28502 .github: update actions/cache to v4 to remove node version warning
  .github/workflows/colcon.yml
  .github/workflows/cygwin_build.yml
  .github/workflows/macos_build.yml
  .github/workflows/test_chibios.yml
  .github/workflows/test_coverage.yml
  .github/workflows/test_dds.yml
  .github/workflows/test_linux_sbc.yml
  .github/workflows/test_replay.yml
  .github/workflows/test_sitl_blimp.yml
  .github/workflows/test_sitl_copter.yml
  .github/workflows/test_sitl_periph.yml
  .github/workflows/test_sitl_plane.yml
  .github/workflows/test_sitl_rover.yml
  .github/workflows/test_sitl_sub.yml
  .github/workflows/test_sitl_tracker.yml
  .github/workflows/test_size.yml
  .github/workflows/test_unit_tests.yml
Labels: CI, MergeOnCIPass

#28465 AP_DDS: Change the comparison of float value zero to IS_XXXX
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: ROS, MergeOnCIPass

#28349 AP_DDS: Added Micro-XRCE-DDS-GEN instal to Dockerfile.
  Dockerfile
Labels: DevEnv, ROS, WikiNeeded, MergeOnCIPass

#28094 SkySakura H743 fc Support
  Tools/bootloaders/SkySakuraH743_bl.bin
  libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/README.md
  libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/SkySakuraH743-bottom.png
  libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/SkySakuraH743_top.png
  libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/Wiring diagram.pdf
  libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/SkySakuraH743/hwdef.dat
Labels: WikiNeeded, MergeOnCIPass, NewBoardSupport

#28446 HAL_QURT: added install script
  libraries/AP_HAL_QURT/install.sh
Labels: QURT

#28551 Tools: strip python2 support from size_compare_branches.py
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#28553 Tools: add bebop to Python all-boards list
  Tools/scripts/board_list.py
Labels: MergeOnCIPass

#28518 AP_Bootloader: reserve board ids and range for Karshak Drones
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#28560 Tools: Add wsproto to ubuntu python deps
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: DevEnv, Networking

#28559 Fix incorrect astyle option that breaks in astyle 3.6.4
  Tools/CodeStyle/astylerc
Labels: DevEnv, DevCallTopic

#28558 Tools: Remove format.sh
  Tools/scripts/format.sh
Labels: DevEnv, DevCallTopic

#28568 QuadPlane: Fix QLand getting stuck in pilot repositioning
  ArduPlane/mode_qland.cpp
  ArduPlane/quadplane.cpp
Labels: BUG, VTOL-Plane, DevCallTopic

#28575 Plane: remove unused `ChannelMixing` enum
  ArduPlane/defines.h
Labels: Plane, DevCallTopic

#28313 Copter: Consolidate processing
  ArduCopter/mode_poshold.cpp
Labels: Copter, DevCallTopic

#28314 Copter: Use GRAVITY_MSS
  ArduCopter/mode_poshold.cpp
Labels: Copter, DevCallTopic

#26501 Foxeer H743v2
  libraries/AP_HAL_ChibiOS/hwdef/FoxeerH743v1/hwdef.dat
Labels: WIP, WikiNeeded, NewBoardSupport

#28201 Direct DMA transfer on Invensense v3
  libraries/AP_InertialSensor/AP_InertialSensor_Invensensev3.cpp
Labels: BUG

#28298 AP_DDS: Parameters service
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_parameter_service.py
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Service_Table.h
  libraries/AP_DDS/AP_DDS_config.h
  libraries/AP_DDS/Idl/rcl_interfaces/msg/Parameter.idl
  libraries/AP_DDS/Idl/rcl_interfaces/msg/ParameterType.idl
  libraries/AP_DDS/Idl/rcl_interfaces/msg/ParameterValue.idl
  libraries/AP_DDS/Idl/rcl_interfaces/msg/SetParametersResult.idl
  libraries/AP_DDS/Idl/rcl_interfaces/srv/GetParameters.idl
  libraries/AP_DDS/Idl/rcl_interfaces/srv/SetParameters.idl
Labels: ROS, WikiNeeded

#28337 AP_DDS: Status Message
  Tools/ros2/ardupilot_msgs/CMakeLists.txt
  Tools/ros2/ardupilot_msgs/msg/Status.msg
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/AP_DDS_config.h
  libraries/AP_DDS/Idl/ardupilot_msgs/msg/Status.idl
Labels: ROS

#28490 Update clang pragma that is causing trouble
  ArduCopter/AP_Arming.cpp
  libraries/AP_Arming/AP_Arming.cpp
Labels: Copter

#28561 Tools: Add astyle dependency
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: DevEnv, MergeOnCIPass

#28594 Tools: correct powr_change.py output for accumulated flags
  Tools/scripts/powr_change.py
Labels: MergeOnCIPass

#28555 Tools: Add mavcesium option to sim_vehicle.py
  Tools/autotest/sim_vehicle.py
Labels: Enhancement, SITL, MergeOnCIPass

#28597 AP_DDS: move closing #endif for status publisher
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: BUG, ROS

#28596 AP_DDS: use memset to initialise variable size array
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: BUG, ROS

#28595 AP_Scripting: copter-slung-payload minor format fix
  libraries/AP_Scripting/applets/copter-slung-payload.md
Labels: Docs, Scripting

#28584 AP_VideoTX: Fix _configuration_finished indication for Tramp VTX
  libraries/AP_VideoTX/AP_Tramp.cpp
Labels: DevCallEU

#28588 AP_AHRS: correct get_accel() to use primary accel rather than first usable for scripting
  libraries/AP_AHRS/AP_AHRS.h
Labels: BUG, DevCallEU

#28601 RC_Channel: remove unused method get_channel_pos
  libraries/RC_Channel/RC_Channel.cpp
  libraries/RC_Channel/RC_Channel.h
Labels: DevCallEU

#28569 HAL_ChibiOS: cleanup cube IMUs and compasses
  libraries/AP_HAL_ChibiOS/hwdef/CubeOrange/hwdef.inc
  libraries/AP_HAL_ChibiOS/hwdef/CubeYellow/hwdef.dat
Labels: DevCallEU

#28607 AP_DDS: status topic to report RC failsafe with callback function
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: ROS, Non-Functional Change

#28611 autotest: tidy GpsForYaw using new infrastructure
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#28287 AP_HAL_ChibiOS: support BMP280 on FoxeerF405v2
  libraries/AP_HAL_ChibiOS/hwdef/FoxeerF405v2/hwdef.dat
Labels: BUG, DevCallTopic

#28613 AP_HAL_QURT: Fix SPI transfer special case
  libraries/AP_HAL_QURT/SPIDevice.cpp
Labels: DevCallTopic

#28621 AP_Rely: allow RELAYn_DEFAULT values on DroneCAN Periphs
  libraries/AP_Relay/AP_Relay.cpp
Labels: AP_Periph

#28617 AP_HAL_ChibiOS: CubeRedPrimary: update config for icm45686
  libraries/AP_HAL_ChibiOS/hwdef/CubeRedPrimary/hwdef.dat
Labels: DevCallTopic

#28618 AP_HAL_ChibiOS: correct logging of MAV_POWER_STATUS_CHANGED
  libraries/AP_HAL_ChibiOS/AnalogIn.cpp
Labels: DevCallTopic

#28654 Plane: tailsitter: tidy tilt left and right handling
  ArduPlane/tailsitter.cpp
Labels: VTOL-Plane, DevCallTopic

#28670 AP_Arming: typo fix in magnetic model check
  libraries/AP_Arming/AP_Arming.cpp
Labels: BUG

#28653 Plane: slew limit all throttles in one place
  ArduPlane/Plane.h
  ArduPlane/servos.cpp
Labels: Plane, DevCallTopic

#28650 AP_HAL_ESP32: enable uart rc
  libraries/AP_HAL_ESP32/RCInput.cpp
  libraries/AP_HAL_ESP32/RCInput.h
Labels: esp32

#28639 Removed unused private members to fix Qurt compiler warnings
  libraries/AP_GSOF/AP_GSOF.h
Labels: MergeOnCIPass

#28668 autotest: augment blended test to ensure three GPSs seen
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#28660 feat:New board id added for CrazyF405 FC
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#28628 AP_Bootloader: reserve a board ID for CSKY-PMU
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#28410 AP_Networking: make connector loopback test priority to be PRIORITY_IO-1
  libraries/AP_Networking/AP_Networking_tests.cpp
Labels: DevCallEU

#28689 AP_Airspeed:correct metadata ref to old param
  libraries/AP_Airspeed/AP_Airspeed.cpp
Labels: MergeOnCIPass, Non-Functional Change

#28372 AP_DDS: Goal topic publisher
  Tools/ros2/ardupilot_dds_tests/ardupilot_dds_tests/plane_waypoint_follower.py
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/AP_DDS_config.h
Labels: Enhancement, ROS

#28401 AP_DDS: Service to check if vehicle is armable
  Tools/ros2/ardupilot_dds_tests/ardupilot_dds_tests/pre_arm_check_service.py
  Tools/ros2/ardupilot_dds_tests/setup.py
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_prearm_service.py
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Service_Table.h
  libraries/AP_DDS/AP_DDS_config.h
  libraries/AP_DDS/Idl/std_srvs/srv/Trigger.idl
  libraries/AP_DDS/README.md
Labels: Enhancement, ROS

#28698 SITL: precland alt and dist limit doc fix
  libraries/SITL/SIM_Precland.cpp
Labels: Docs, Non-Functional Change

#28701 add SPA06 support to Kakute hwdef
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF4/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7-Wing/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/KakuteH7Mini/hwdef.dat
Labels: MergeOnCIPass

#28708 AP_HAL_ESP32: reduce scheduler stack sizes
  libraries/AP_HAL_ESP32/Scheduler.h
Labels: esp32

#28709 AP_Soaring: Use constexpr instead of define for constants
  libraries/AP_Soaring/AP_Soaring.h
Labels: MergeOnCIPass, Non-Functional Change

#28716 AP_HAL_ESP32: disable define of HAL_ESP32_RCIN on esp32empty
  libraries/AP_HAL_ESP32/boards/esp32empty.h
Labels: esp32

#28711 AP_RangeFinder: alphabetise type parm docs
  libraries/AP_RangeFinder/AP_RangeFinder_Params.cpp
Labels: Docs, DevCallTopic

#28719 AP_Logger: correct typo in MAV documentation
  libraries/AP_Logger/LogStructure.h
Labels: MergeOnCIPass

#28693 AP_NavEKF3: pos and vel resets default to user defined source
  libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
Labels: BUG, EKF

#28734 AP_Terrain: Add const to locals
  libraries/AP_Terrain/AP_Terrain.cpp
Labels: MergeOnCIPass, Non-Functional Change

#28733 Tools: Add new board ids for UAV-DEV GmbH
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#28735 Add tabulate dependency
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: MergeOnCIPass
