Repository ArduPilot/ardupilot, pull requests merged in 2024-05, with the labels that each got.

#26934 AP_Motors:explain PMWRange/Angle PWM types in metadata
  libraries/AP_Motors/AP_MotorsMulticopter.cpp
Labels: MergeOnCIPass, Non-Functional Change

#26957 AP_Scripting: allow for 0x00 for 2nd checksum byte in INF_Inject driver
  libraries/AP_Scripting/drivers/INF_Inject.lua
Labels: Scripting

#26606 Heli: Add blade pitch angle logging
  libraries/AP_Motors/AP_MotorsHeli.cpp
  libraries/AP_Motors/AP_MotorsHeli.h
  libraries/AP_Motors/AP_MotorsHeli_Dual.cpp
  libraries/AP_Motors/AP_MotorsHeli_Dual.h
  libraries/AP_Motors/AP_MotorsHeli_Single.cpp
  libraries/AP_Motors/AP_MotorsHeli_Single.h
  libraries/AP_Motors/AP_MotorsHeli_Swash.cpp
  libraries/AP_Motors/AP_MotorsHeli_Swash.h
Labels: TradHeli

#26974 Tools: add blended GPS build option
  Tools/scripts/build_options.py
  Tools/scripts/extract_features.py
Labels: DevCallTopic

#26961 Rover: Change division to multiplication
  Rover/GCS_Mavlink.cpp
  Rover/Rover.cpp
  Rover/mode.cpp
  Rover/mode_guided.cpp
Labels: DevCallTopic

#26978 Plane: Tiltrotor: add logging of tilt angles.
  ArduPlane/Log.cpp
  ArduPlane/defines.h
  ArduPlane/quadplane.cpp
  ArduPlane/tiltrotor.cpp
  ArduPlane/tiltrotor.h
Labels: VTOL-Plane

#26981 hwdef: enable can port on Blitz743Pro
  libraries/AP_HAL_ChibiOS/hwdef/BlitzH743Pro/defaults.parm
Labels: DevCallTopic

#26988 Plane: remove altitude_error_cm variable
  ArduPlane/GCS_Mavlink.cpp
  ArduPlane/Log.cpp
  ArduPlane/Plane.h
  ArduPlane/commands_logic.cpp
  ArduPlane/mode.cpp
  ArduPlane/mode_guided.cpp
  ArduPlane/mode_qrtl.cpp
  ArduPlane/mode_rtl.cpp
  ArduPlane/navigation.cpp
  ArduPlane/quadplane.cpp
Labels: Plane

#26982 hwdef:preconfig MicoAir bds shipping with BF for BF migration
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405Mini/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405v2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir743/hwdef.dat
Labels: WikiNeeded, MergeOnCIPass

#26971 AP_Scripting: added copter_loiter_brake script
  libraries/AP_Scripting/applets/copter_terrain_brake.lua
  libraries/AP_Scripting/applets/copter_terrain_brake.md
Labels: Scripting, WikiNeeded, MergeOnCIPass

#26830 Copter: Change from enum to class
  ArduCopter/mode.cpp
  ArduCopter/mode.h
  ArduCopter/mode_althold.cpp
  ArduCopter/mode_flowhold.cpp
  ArduCopter/mode_loiter.cpp
  ArduCopter/mode_poshold.cpp
  ArduCopter/mode_sport.cpp
  ArduCopter/mode_zigzag.cpp
Labels: MergeOnCIPass

#27008 Tools: add comment at end of file restricting range to be allocated from
  Tools/AP_Bootloader/board_types.txt
Labels: DevCallEU

#27014 Tools: added LongBowF405WING to board_types.txt
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#26997 AP_HAL_Linux: fix SPIUARTDriver to work with GPS autodetection
  libraries/AP_HAL_Linux/SPIUARTDriver.cpp
  libraries/AP_HAL_Linux/SPIUARTDriver.h
  libraries/AP_HAL_Linux/UARTDriver.h
Labels: DevCallEU

#26983 AP_Periph: allow airspeed without I2C
  Tools/AP_Periph/AP_Periph.cpp
Labels: AP_Periph, DevCallEU

#26994 AP_Periph: always limit rangefinder update rate to given max rate
  Tools/AP_Periph/rangefinder.cpp
Labels: BUG, AP_Periph, DevCallEU

#26909 Filter: Get common processes out of the way
  libraries/Filter/NotchFilter.cpp
Labels: DevCallEU

#26881 AP_Scripting: allow revert of angular rate limits
  libraries/AP_Scripting/applets/revert_param.lua
  libraries/AP_Scripting/applets/revert_param.md
Labels: DevCallEU

#27003 AP_Mission: emit jump count even if no limit
  libraries/AP_Mission/AP_Mission.cpp
Labels: DevCallEU

#26793 AP_HAL_ChibiOS: correct GPS output on MambaH743v4
  libraries/AP_HAL_ChibiOS/hwdef/MambaH743v4/hwdef.dat
Labels: BUG, WikiNeeded, DevCallEU

#27019 Tools: install-prereqs-ubuntu.sh: add support for Ubuntu Noble (24.04)
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: MergeOnCIPass

#27012 Heli Swashplate: Make motor numbers const
  libraries/AP_Motors/AP_MotorsHeli_Swash.cpp
  libraries/AP_Motors/AP_MotorsHeli_Swash.h
Labels: TradHeli

#27032 github: test_environment: test Ubuntu noble and not Ubuntu mantic
  .github/workflows/test_environment.yml
Labels: MergeOnCIPass

#27034 Tools: use previous release of pymonocypher
  Tools/scripts/build_ci.sh
Labels: MergeOnCIPass

#27046 board_types.txt: reserve board ID for MountainEagle H743
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#27010 Tools: Expose map/console mavproxy args
  Tools/ros2/README.md
  Tools/ros2/ardupilot_sitl/src/ardupilot_sitl/launch.py
Labels: ROS

#27030 AP_BattMonitor: ESC: add mask parameter
  libraries/AP_BattMonitor/AP_BattMonitor.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_DroneCAN.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_ESC.cpp
  libraries/AP_BattMonitor/AP_BattMonitor_ESC.h
Labels: DevCallTopic, WikiNeeded

#27025 AC_AutoTune: zero out D_FF during twitching
  libraries/AC_AutoTune/AC_AutoTune.h
  libraries/AC_AutoTune/AC_AutoTune_Multi.cpp
Labels: BUG

#23658 Plane: fix rangefinder correction when terrain follow is off
  ArduPlane/altitude.cpp
Labels: Plane

#27114 autotest: add test showing throttle satuation problem
  Tools/autotest/arduplane.py
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#27113 autotest: neaten Copter Loiter test
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#27075 AP_Mount: Clarify angle frames of set_angle_target()
  libraries/AP_Mount/AP_Mount.cpp
  libraries/AP_Mount/AP_Mount.h
  libraries/AP_Mount/AP_Mount_Backend.cpp
  libraries/AP_Mount/AP_Mount_Backend.h
Labels: MergeOnCIPass

#27037 AP_Bootloader: ID reserve for FlywooF405HD_AIOv2
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#25670 AP_Motors_test: add tri frames to json output
  libraries/AP_Motors/AP_MotorsTri.cpp
  libraries/AP_Motors/AP_MotorsTri.h
  libraries/AP_Motors/examples/AP_Motors_test/AP_Motors_test.cpp
Labels: DevCallEU

#27108 AC_WPNav: remove un-needed initialisation
  libraries/AC_WPNav/AC_Circle.cpp
Labels: MergeOnCIPass

#27117 autotest: add polygon pre-arm tests
  Tools/autotest/rover.py
Labels: MergeOnCIPass

#26921 Update run_in_terminal_window.sh
  Tools/autotest/run_in_terminal_window.sh
Labels: MergeOnCIPass

#27105 AP_Bootloader: Reserve ID range for UAV-DEV GmbH
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#27127 AP_Compass: removed IST8310 overrun message
  libraries/AP_Compass/AP_Compass_IST8308.cpp
Labels: DevCallEU

#27109 AP_Mount: Only save converted mount parameter if mount was previously set in the first place
  libraries/AP_Mount/AP_Mount.cpp
Labels: Library, DevCallEU

#27116 hwdef: fold minimal_GPS.inc into sole user
  libraries/AP_HAL_ChibiOS/hwdef/Sierra-TrueNavPro/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/include/minimal_GPS.inc
Labels: DevCallEU

#27111 AP_Scripting: docs: document all functions currently documented on the wiki
  libraries/AP_Scripting/docs/docs.lua
Labels: Scripting, DevCallEU

#27093 Plane: ensure the dshot type gets set
  ArduPlane/system.cpp
Labels: BUG, DevCallEU

#27131 Tools: ros2: Improve ability to launch plane in headless mode
  Tools/ros2/ardupilot_sitl/CMakeLists.txt
  Tools/ros2/ardupilot_sitl/src/ardupilot_sitl/launch.py
Labels: ROS, MergeOnCIPass

#27140 AP_DDS: ensure zero rotation quaternions are normalised
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: BUG, ROS, MergeOnCIPass

#27168 Update board_types.txt
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#27112 Tools: Scripts: run_lua_language_check: give hint about github-release-downloader
  Tools/scripts/run_lua_language_check.py
Labels: Scripting

#27146 AP_Scripting: remove support for REPL
  libraries/AP_Scripting/AP_Scripting.cpp
  libraries/AP_Scripting/AP_Scripting.h
  libraries/AP_Scripting/lua_common_defs.h
  libraries/AP_Scripting/lua_repl.cpp
  libraries/AP_Scripting/lua_scripts.cpp
  libraries/AP_Scripting/lua_scripts.h
Labels: Scripting

#27160 AP_DroneCAN: Serial: map baudrates so param works as expected
  libraries/AP_DroneCAN/AP_DroneCAN_serial.cpp
Labels: CAN

#27170 SITL: update to work on newer cygwin versions
  libraries/SITL/SIM_Aircraft.cpp
Labels: BuildSystem

#27061 Scripting: backport of pcall fault fix for 4.4.x
  libraries/AP_Scripting/lua/src/ldo.c
Labels: BUG

#27186 Scripting: backport of pcall fault fix for 4.3.x
  libraries/AP_Scripting/lua/src/ldo.c
Labels: BUG, 4.3 Backport

#27176 AP_HAL_ChibiOS:Improve SDMODELH7V2 definition
  libraries/AP_HAL_ChibiOS/hwdef/SDMODELH7V2/README.md
  libraries/AP_HAL_ChibiOS/hwdef/SDMODELH7V2/SDMODEL_H7V2.jpg
  libraries/AP_HAL_ChibiOS/hwdef/SDMODELH7V2/defaults.parm
Labels: DevCallTopic

#27178 AP_Scripting: added GPS yaw binding
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: Scripting, MergeOnCIPass

#27143 AP_HAL_SITL: Give tcp client 3 attempts to connect
  libraries/AP_HAL_SITL/UARTDriver.cpp
Labels: SITL, MergeOnCIPass

#27183 AP_Motor: Fix a typo
  libraries/AP_Motors/AP_MotorsMatrix.cpp
Labels: MergeOnCIPass

#27185 AP_Networking: enable Socket SO_REUSEADDR on LwIP
  libraries/AP_Networking/config/lwipopts.h
Labels: ChibiOS, MergeOnCIPass, Networking

#27161 AP_DDS: Use common quaternion initialization function
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: ROS, MergeOnCIPass

#27202 Tools: Do not emit __field_text in JSON parameter documentation
  Tools/autotest/param_metadata/jsonemit.py
Labels: Enhancement, Tools, Docs
