Repository ArduPilot/ardupilot, pull requests merged in 2024-09, with the labels that each got.

#27969 autotest: test_build_options.py: add --resume option
  Tools/autotest/test_build_options.py
Labels: MergeOnCIPass

#27971 AP_Motors: fix DDVP tail servo initialization
  libraries/AP_Motors/AP_MotorsHeli_Single.cpp
Labels: BUG, TradHeli

#27974 autotest: AutoContinueOnRCFailsafe extend auto leg to avoid race
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#27968 Pr/esp loop rate buzz redo
  libraries/AP_HAL_ESP32/Scheduler.h
Labels: DevCallTopic, esp32

#27972 AP_DroneCAN: DNA_Server: polish db methods
  libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
Labels: MergeOnCIPass

#27958 AP_NavEKF3: use reference for dal in frontend in place of method calls
  libraries/AP_NavEKF3/AP_NavEKF3.cpp
  libraries/AP_NavEKF3/AP_NavEKF3.h
  libraries/AP_NavEKF3/AP_NavEKF3_OptFlowFusion.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_RngBcnFusion.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.cpp
  libraries/AP_NavEKF3/AP_NavEKF3_core.h
Labels: DevCallTopic

#24159 Tools: fixed airport parameters in Flight Gear shell scripts
  Tools/autotest/fg_plane_view.sh
  Tools/autotest/fg_quad_view.sh
Labels: SITL, MergeOnCIPass

#27980 HWDEF: update default parameters for MicoAir405v2 and MicoAir405mini
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405Mini/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405v2/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405v2/hwdef.dat
Labels: WikiNeeded, MergeOnCIPass

#27988 Avoid using global "args" object within ChibiOSHWdef object
  libraries/AP_HAL_ChibiOS/hwdef/scripts/chibios_hwdef.py
Labels: MergeOnCIPass

#27987 AP_Common: fixed cygwin for non-SITL builds
  libraries/AP_Common/c++.cpp
Labels: DevCallEU

#27995 Tools: added name to GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#27981 AP_Baro: remove unnecessary "#ifdef HAL_BUILD_AP_PERIPH"
  libraries/AP_Baro/AP_Baro.h
Labels: MergeOnCIPass

#27356 AP_Proximity: Include database push in MR72 driver
  libraries/AP_Proximity/AP_Proximity_MR72_CAN.cpp
Labels: BUG, Copter

#27994 hwdef: enable flash-from-SD on Pixhawk6C
  libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6C/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/Pixhawk6C/hwdef.dat
Labels: DevCallEU

#27443 default to MavLinkV1 on CubeSolo
  libraries/AP_HAL_ChibiOS/hwdef/CubeSolo/defaults.parm
Labels: Solo, DevCallEU

#28016 Copter: rename RTLAltType enumeration entries
  ArduCopter/AP_Arming.cpp
  ArduCopter/mode.h
  ArduCopter/mode_rtl.cpp
Labels: MergeOnCIPass

#28015 hwdef: ARKV6x: fix RC input
  libraries/AP_HAL_ChibiOS/hwdef/ARKV6X/hwdef.dat
Labels: WikiNeeded, MergeOnCIPass

#28007 Revert "AP_NavEKF3: Corrected logged units"
  libraries/AP_NavEKF3/AP_NavEKF3_Logging.cpp
  libraries/AP_NavEKF3/LogStructure.h
Labels: MergeOnCIPass

#28003 AP_Mission: do not adjust ret_packet on get_item failure
  libraries/AP_Mission/AP_Mission.cpp
Labels: MergeOnCIPass

#28001 Tools: size_compare_branches.py: blacklist build of Pixhack-V3 bootlo…
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#28000 hwdef: remove SMBus battery support from all minimize-fpv boards
  libraries/AP_HAL_ChibiOS/hwdef/KakuteF7/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/OMNIBUSF7V2/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/include/minimize_fpv_osd.inc
Labels: MergeOnCIPass

#27999 hwdef: GEPRCF745BTHD: rely on custom builds for non-BMP280 baros
  libraries/AP_HAL_ChibiOS/hwdef/GEPRCF745BTHD/hwdef.dat
Labels: MergeOnCIPass

#27941 AP_DDS: remove instance check for DDS Client
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: ROS, MergeOnCIPass

#28023 AP_HAL_ESP32: bigger instruction cache on s3 helps performance
  libraries/AP_HAL_ESP32/targets/esp32s3/esp-idf/sdkconfig
Labels: esp32

#28004 Copter: remove ENABLE/ENABLED/DISABLE/DISABLED defines
  ArduCopter/APM_Config.h
  ArduCopter/AP_Arming.cpp
  ArduCopter/Attitude.cpp
  ArduCopter/Copter.cpp
  ArduCopter/Copter.h
  ArduCopter/GCS_Mavlink.cpp
  ArduCopter/Log.cpp
  ArduCopter/Parameters.cpp
  ArduCopter/Parameters.h
  ArduCopter/RC_Channel.cpp
  ArduCopter/UserParameters.cpp
  ArduCopter/afs_copter.cpp
  ArduCopter/afs_copter.h
  ArduCopter/autoyaw.cpp
  ArduCopter/avoidance_adsb.cpp
  ArduCopter/commands.cpp
  ArduCopter/config.h
  ArduCopter/crash_check.cpp
  ArduCopter/defines.h
  ArduCopter/events.cpp
  ArduCopter/failsafe.cpp
  ArduCopter/heli.cpp
  ArduCopter/land_detector.cpp
  ArduCopter/mode.cpp
  ArduCopter/mode.h
  ArduCopter/mode_acro.cpp
  ArduCopter/mode_acro_heli.cpp
  ArduCopter/mode_auto.cpp
  ArduCopter/mode_autorotate.cpp
  ArduCopter/mode_autotune.cpp
  ArduCopter/mode_brake.cpp
  ArduCopter/mode_circle.cpp
  ArduCopter/mode_drift.cpp
  ArduCopter/mode_flip.cpp
  ArduCopter/mode_flowhold.cpp
  ArduCopter/mode_follow.cpp
  ArduCopter/mode_guided.cpp
  ArduCopter/mode_guided_nogps.cpp
  ArduCopter/mode_loiter.cpp
  ArduCopter/mode_poshold.cpp
  ArduCopter/mode_rtl.cpp
  ArduCopter/mode_smart_rtl.cpp
  ArduCopter/mode_sport.cpp
  ArduCopter/mode_systemid.cpp
  ArduCopter/mode_throw.cpp
  ArduCopter/mode_turtle.cpp
  ArduCopter/mode_zigzag.cpp
  ArduCopter/motors.cpp
  ArduCopter/radio.cpp
  ArduCopter/system.cpp
  ArduCopter/toy_mode.cpp
  ArduCopter/tuning.cpp
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-f412-rev1/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-journey/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/skyviper-v2450/hwdef.dat
Labels: MergeOnCIPass

#28022 AP_HAL_ESP32: fix RMT on s3 by using channel thats compatible with both .
  libraries/AP_HAL_ESP32/RmtSigReader.cpp
Labels: esp32

#28025 Tools: raise build time limit
  Tools/scripts/build_autotest.sh
Labels: MergeOnCIPass

#27686 Add MPU6000 to hwdef for ReaperF745 to Support V4 FC
  libraries/AP_HAL_ChibiOS/hwdef/ReaperF745/hwdef.dat
Labels: NeedAnswer, WikiNeeded, MergeOnCIPass, hwdef

#28029 autotest: tweak takeoff test names to avoid poor summary output
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#28032 GCS_MAVLink: zero signing key structure for valgrind
  libraries/GCS_MAVLink/GCS_Signing.cpp
Labels: MergeOnCIPass

#28026 AP_AHRS: log DCM errrp and erryaw into DCM message
  libraries/AP_AHRS/AP_AHRS_DCM.cpp
  libraries/AP_AHRS/AP_AHRS_Logging.cpp
  libraries/AP_AHRS/LogStructure.h
Labels: DevCallTopic

#28048 waf: fixed app signature in elf files
  Tools/ardupilotwaf/chibios.py
Labels: ChibiOS

#28035 Tools: Use apt for pexpect and allow system packages in the virtual environment
  Tools/environment_install/install-prereqs-arch.sh
  Tools/environment_install/install-prereqs-openSUSE-Tumbleweed.sh
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: CI, Experiment

#28061 Copter: auto mode takeoff complete pos fix
  ArduCopter/mode.h
  ArduCopter/mode_auto.cpp
  ArduCopter/takeoff.cpp
Labels: BUG, Copter, MergeOnCIPass

#28058 GCS_MAVLink: fix includes to ap_message
  libraries/GCS_MAVLink/ap_message.h
Labels: MergeOnCIPass

#27983 Rover: Circle mode enhancements
  Rover/mode.h
  Rover/mode_circle.cpp
Labels: Rover, WikiNeeded, MergeOnCIPass

#28054 AP_ESC_Telem: tidy old calls to _telem_data
  libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
Labels: MergeOnCIPass

#28057 Tools: Hotfix missing 3 in python-scripy
  Tools/ros2/ardupilot_dds_tests/package.xml
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_geopose_msg_received.py
Labels: ROS, MergeOnCIPass

#27277 AP_Scripting: add handle_external_position_estimate binding
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: Scripting, MergeOnCIPass

#28074 AP_EFI: fix ECYL log message
  libraries/AP_EFI/AP_EFI.cpp
Labels: MergeOnCIPass

#28069 VectorNav: rename dataflash log message names
  libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.cpp
  libraries/AP_ExternalAHRS/AP_ExternalAHRS_VectorNav.h
Labels: MergeOnCIPass

#26914 AP_Scripting: add advance-wp.lua
  libraries/AP_Scripting/applets/advance-wp.lua
  libraries/AP_Scripting/applets/advance-wp.md
Labels: MergeOnCIPass

#28072 Plane: added Q_APPROACH_DIST
  ArduPlane/quadplane.cpp
  ArduPlane/quadplane.h
Labels: VTOL-Plane, WikiNeeded, MergeOnCIPass

#28090 AP_MSP: MSP_RAW_GPS cog should be decidegrees not centidegrees
  libraries/AP_MSP/AP_MSP_Telem_Backend.cpp
  libraries/AP_MSP/AP_MSP_Telem_Backend.h
Labels: DevCallTopic

#26600 AP_ExternalAHRS: Remove incorrect 0xFFFF default comment
  libraries/AP_ExternalAHRS/AP_ExternalAHRS.h
Labels: ExternalAHRS

#26467 AP_Scripting: added 2nd supply voltage to SkyPower EFI driver
  libraries/AP_Scripting/drivers/EFI_SkyPower.lua
Labels: DevCallTopic, Scripting

#28109 Copter: The failsafe enable flag should be cleared on cold reset
  ArduCopter/failsafe.cpp
Labels: Copter, DevCallTopic

#28091 Add test for geopose heading
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_geopose_msg_received.py
Labels: ROS

#28098 Add defines for experimental topics such as IMU to allow saving flash for unused topics
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/AP_DDS_config.h
Labels: ROS, WikiNeeded, Experiment

#28100 AP_DroneCAN: DNAServer: remove preferred allocation support
  libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.cpp
  libraries/AP_DroneCAN/AP_DroneCAN_DNA_Server.h
Labels: MergeOnCIPass

#28125 AP_HAL_ChibiOS: check nullptr 'name' variable
  libraries/AP_HAL_ChibiOS/Device.cpp
Labels: MergeOnCIPass

#28095 AP_OSD: don't go via RCMap singleton to get RPTY RC channels
  libraries/AP_OSD/AP_OSD.h
  libraries/AP_OSD/AP_OSD_ParamScreen.cpp
Labels: MergeOnCIPass

#28121 GCS_MAVLink: Fix Airspeed without AHRS
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#28122 Tools: Remove bionic support for ubuntu setup
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: WikiNeeded, MergeOnCIPass

#28130 Tools: added name to GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#22513 AP_Scripting:Add parameter controller applet
  libraries/AP_Scripting/applets/Param_Controller.lua
  libraries/AP_Scripting/applets/Param_Controller.md
Labels: WikiNeeded, MergeOnCIPass

#28137 hwdef: add bdshot to SpeedyBeeF405Wing
  libraries/AP_HAL_ChibiOS/hwdef/SpeedyBeeF405WING/hwdef.dat
Labels: DevCallEU, NewBoardSupport

#28128 CI: build CubeRed-EKF2 not CubeOrange-EKF2 in CI
  .github/workflows/test_chibios.yml
  Tools/scripts/build_ci.sh
Labels: MergeOnCIPass

#28139 Tools: stop invoking setup.py directly
  Tools/scripts/build_autotest.sh
  Tools/scripts/build_ci.sh
Labels: MergeOnCIPass

#28135 AntennaTracker: refuse to track (0;0)
  AntennaTracker/tracking.cpp
Labels: MergeOnCIPass

#28138 GCS_MAVLink: Add conditions and delete the same processing
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#28078 Blimp: Remove previous flight mode
  Blimp/Blimp.h
  Blimp/mode.cpp
Labels: DevCallEU, Blimp

#28151 AP_TemperatureSensor: new MLX90614 sensor backend driver conversion fix
  libraries/AP_TemperatureSensor/AP_TemperatureSensor_MLX90614.cpp
Labels: MergeOnCIPass

#28156 Replay: Change NULL to nullptr
  Tools/Replay/MsgHandler.cpp
Labels: MergeOnCIPass

#28140 AP_Scripting: add bindings get/set full mode for GPIO
  libraries/AP_Scripting/docs/docs.lua
  libraries/AP_Scripting/generator/description/bindings.desc
Labels: MergeOnCIPass

#28173 Tools: added name to GIT_Success.txt
  Tools/GIT_Test/GIT_Success.txt
Labels: MergeOnCIPass

#28168 Replay: Declare the type of the loop variable and consolidate the processing
  Tools/Replay/MsgHandler.cpp
Labels: MergeOnCIPass

#28155 Copter: don't pass `channel_yaw->norm_input_dz()` into `get_pilot_desired_yaw_rate`
  ArduCopter/autoyaw.cpp
  ArduCopter/mode.cpp
  ArduCopter/mode.h
  ArduCopter/mode_acro_heli.cpp
  ArduCopter/mode_althold.cpp
  ArduCopter/mode_autorotate.cpp
  ArduCopter/mode_autotune.cpp
  ArduCopter/mode_flowhold.cpp
  ArduCopter/mode_loiter.cpp
  ArduCopter/mode_poshold.cpp
  ArduCopter/mode_sport.cpp
  ArduCopter/mode_stabilize.cpp
  ArduCopter/mode_stabilize_heli.cpp
  ArduCopter/mode_systemid.cpp
  ArduCopter/mode_zigzag.cpp
Labels: Copter, DevCallTopic

#28181 AP_Compass: Add existing devices
  libraries/AP_Compass/AP_Compass.cpp
Labels: MergeOnCIPass

#27684 autotest: large outliers in sub terrain test have low sq
  Tools/autotest/ardusub.py
  libraries/AP_Scripting/examples/sub_test_synthetic_seafloor.lua
Labels: DevCallTopic

#28182 AP_CANManager: fixed de-registering CAN forwarding
  libraries/AP_CANManager/AP_CANManager.cpp
  libraries/AP_CANManager/AP_CANManager.h
Labels: BUG, DevCallTopic, CAN

#28184 Copter: mode_auto: remove more code based on defines
  ArduCopter/mode_auto.cpp
Labels: DevCallTopic

#28167 AP_GPS: move initialisation of some members into header
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
  libraries/AP_GPS/AP_GPS_UBLOX.h
Labels: DevCallTopic

#28132 Copter: add and use new `afs_mode` mode method
  ArduCopter/afs_copter.cpp
  ArduCopter/mode.h
Labels: Copter

#28157 AP_DroneCAN: Fix constructor initialization order
  libraries/AP_DroneCAN/AP_DroneCAN.h
Labels: BUG

#28161 AC_AttitudeControl: use AC_PID defaults to tidy rate Sub PID initialisation
  libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.cpp
  libraries/AC_AttitudeControl/AC_AttitudeControl_Sub.h
Labels: Sub

#28172 AP_Bootloader: add request to fill gaps rather than add to end
  Tools/AP_Bootloader/board_types.txt
Labels: DevCallTopic

#28207 AP_Bootloader: Reserve a board ID for 3DR R0011
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#28203 AP_DDS: add params for ping timeout and max retries
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
Labels: ROS, WikiNeeded, MergeOnCIPass

#28129 Copter: guided: `set_angle` call `init_z_controller` when changing from thrust to climb rate control to avoid flow of control error
  ArduCopter/mode_guided.cpp
Labels: Copter, MergeOnCIPass

#24246 AP_Motors: Change to pass-through
  libraries/AP_Motors/AP_MotorsCoax.cpp
Labels: MergeOnCIPass

#28169 Replay: The number of elements in a char array can be obtained using SIZEOF
  Tools/Replay/MsgHandler.cpp
Labels: MergeOnCIPass

#28133 Copter: add and use new `allows_GCS_arming_with_throttle_high` mode method
  ArduCopter/AP_Arming.cpp
  ArduCopter/mode.h
Labels: Copter, MergeOnCIPass

#28224 hwdef: JHEMCU-GSF405A becomes minimize-fpv-osd
  libraries/AP_HAL_ChibiOS/hwdef/JHEMCU-GSF405A/hwdef.dat
Labels: DevCallEU

#28226 hwdef: correct compilation for MFT-SEMA100
  libraries/AP_HAL_ChibiOS/hwdef/MFT-SEMA100/hwdef.dat
Labels: MergeOnCIPass

#28216 autotest: param_metadata.py: emit bitmask as XML sub-element
  Tools/autotest/param_metadata/xmlemit.py
Labels: MergeOnCIPass

#28208 Tools:clean up displayed build options
  Tools/scripts/build_options.py
Labels: MergeOnCIPass, Non-Functional Change

#28200 AP_ICEngine: don't run engine with safety engaged
  libraries/AP_ICEngine/AP_ICEngine.cpp
Labels: MergeOnCIPass

#28183 AP_Camera: add Python examples for GStreamer UDP and RTSP video streams
  libraries/AP_Camera/examples/README.md
  libraries/AP_Camera/examples/gst_rtsp_server.py
  libraries/AP_Camera/examples/gst_rtsp_to_wx.py
  libraries/AP_Camera/examples/gst_udp_to_rtsp.py
  libraries/AP_Camera/examples/gst_udp_to_wx.py
Labels: GSoC

#28233 Scripting: added Lat,Lon to aerobatics POSM/POST
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
Labels: Scripting, MergeOnCIPass

#28234 Plane: add test for MAV_CMD_NAV_LOITER_TO_ALT
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#28243 AP_RobotisServo: Send register write values as little-endian
  libraries/AP_RobotisServo/AP_RobotisServo.cpp
Labels: MergeOnCIPass

#28245 SITL: Change division to multiplication
  libraries/SITL/SIM_Gripper_EPM.cpp
  libraries/SITL/SIM_Gripper_Servo.cpp
  libraries/SITL/SIM_RF_LightWareSerial.cpp
  libraries/SITL/SIM_RF_NMEA.cpp
  libraries/SITL/SIM_RF_Wasp.cpp
  libraries/SITL/SIM_Sprayer.cpp
  libraries/SITL/SITL.cpp
Labels: MergeOnCIPass

#28253 AP_Bootloader:reserve bd id for X-MAV-AP-H743v2
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#26595 AP_RangeFinder: Move the flag setting location of has_data
  libraries/AP_RangeFinder/AP_RangeFinder_Ainstein_LR_D1.cpp
Labels: MergeOnCIPass

#24786 AP_Baro: fix example: fixing missing objects
  libraries/AP_Baro/examples/BARO_generic/BARO_generic.cpp
Labels: MergeOnCIPass

#28261 github: move to actions/upload-artifact@v4
  .github/workflows/cygwin_build.yml
  .github/workflows/esp32_build.yml
  .github/workflows/qurt_build.yml
  .github/workflows/test_dds.yml
  .github/workflows/test_replay.yml
  .github/workflows/test_scripting.yml
  .github/workflows/test_sitl_blimp.yml
  .github/workflows/test_sitl_copter.yml
  .github/workflows/test_sitl_plane.yml
  .github/workflows/test_sitl_rover.yml
  .github/workflows/test_sitl_sub.yml
  .github/workflows/test_sitl_tracker.yml
  .github/workflows/test_unit_tests.yml
Labels: DevCallTopic

#23116 Fix wrong baro for FlywooF745
  libraries/AP_HAL_ChibiOS/hwdef/FlywooF745/hwdef.dat
Labels: DevCallTopic, hwdef

#28190 Rover: remove handling of prearm empty-string case
  Rover/AP_Arming.cpp
Labels: Rover

#28218 DroneCAN: fixed deadlock and saturation of CAN bus
  libraries/AP_HAL_ChibiOS/UARTDriver.cpp
  libraries/AP_HAL_ChibiOS/UARTDriver.h
Labels: BUG
