Repository ArduPilot/ardupilot, pull requests merged in 2025-10, with the labels that each got.

#31205 autotest: Fix Autotune Tests
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#28627 AP_Scripting: Added VSPeak Modell flow meter driver
  libraries/AP_Scripting/drivers/VSPeak_flow_meter.lua
  libraries/AP_Scripting/drivers/VSPeak_flow_meter.md
Labels: WikiNeeded, MergeOnCIPass

#31191 autotest: Ensure log message fields are in the correct order
  Tools/autotest/logger_metadata/parse.py
Labels: MergeOnCIPass

#31226 AC_AttitudeControl: yaw I scaling should use Z-axis
  libraries/AC_AttitudeControl/AC_AttitudeControl.cpp
Labels: BUG

#31202 AP_GPS: Add support for NAVIC constellation in UBLOX driver
  libraries/AP_GPS/AP_GPS_Params.cpp
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
  libraries/AP_GPS/AP_GPS_UBLOX.h
Labels: WikiNeeded, MergeOnCIPass

#31227 AP_HAL_ChibiOS: BlitzF745 gets littlefs
  libraries/AP_HAL_ChibiOS/hwdef/BlitzF745/hwdef.dat
Labels: Enhancement

#31235 hwdef: rename BATT_CURR_SCALE to BATT_AMP_PERVLT in board READMEs
  libraries/AP_HAL_ChibiOS/hwdef/3DRControlZeroG/README.md
  libraries/AP_HAL_ChibiOS/hwdef/ACNS-CM4Pilot/README.md
  libraries/AP_HAL_ChibiOS/hwdef/ACNS-F405AIO/README.md
  libraries/AP_HAL_ChibiOS/hwdef/AET-H743-Basic/README.md
  libraries/AP_HAL_ChibiOS/hwdef/ARK_FPV/README.md
  libraries/AP_HAL_ChibiOS/hwdef/BROTHERHOBBYF405v3/README.md
  libraries/AP_HAL_ChibiOS/hwdef/GEPRCF745BTHD/README.md
  libraries/AP_HAL_ChibiOS/hwdef/GEPRC_TAKER_H743/README.md
  libraries/AP_HAL_ChibiOS/hwdef/MFT-SEMA100/README.md
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405Mini/README.md
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir405v2/README.md
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir743-AIO/README.md
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir743/README.md
  libraries/AP_HAL_ChibiOS/hwdef/MicoAir743v2/README.md
  libraries/AP_HAL_ChibiOS/hwdef/NxtPX4v2/README.md
  libraries/AP_HAL_ChibiOS/hwdef/X-MAV-AP-H743v2/README.md
Labels: Docs, Non-Functional Change

#31224 AP_Networking: correct starting of CAN multicast server
  libraries/AP_Networking/AP_Networking.cpp
Labels: BUG

#30899 DDS: Fix initialisation on UDP transport
  libraries/AP_DDS/AP_DDS_Client.cpp
Labels: ROS, MergeOnCIPass
