Repository ArduPilot/ardupilot, pull requests merged in 2025-07, with the labels that each got.

#30450 AP_Motors: move defaulting of defines info AP_Motors_config.h
  libraries/AP_Motors/AP_Motors_Class.h
  libraries/AP_Motors/AP_Motors_config.h
Labels: DevCallTopic

#30380 Plane: reduce speed scaler in assisted flight at low airspeed
  ArduPlane/Attitude.cpp
Labels: VTOL-Plane

#30497 AP_HAL_Linux: Move AnalogIn_IIO scaling constants into hwdef
  libraries/AP_HAL_Linux/AnalogIn_IIO.cpp
  libraries/AP_HAL_Linux/AnalogIn_IIO.h
  libraries/AP_HAL_Linux/hwdef/bbbmini/hwdef.dat
  libraries/AP_HAL_Linux/hwdef/blue/hwdef.dat
  libraries/AP_HAL_Linux/hwdef/pocket/hwdef.dat
  libraries/AP_HAL_Linux/hwdef/pxf/hwdef.dat
Labels: DevCallTopic

#30501 AP_Mount: SToRM32 search continues while disarmed
  libraries/AP_Mount/AP_Mount_SToRM32.cpp
Labels: Enhancement, NeedsTesting, MergeOnCIPass, Gimbal

#30522 AP_Airspeed:add I2C3 to metadata
  libraries/AP_Airspeed/AP_Airspeed_Params.cpp
Labels: Docs, MergeOnCIPass, Non-Functional Change

#30459 Plane: make RNGFND_LANDING a bitmask (4.6 backport)
  ArduPlane/GCS_Plane.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/Plane.h
  ArduPlane/VTOL_Assist.cpp
  ArduPlane/altitude.cpp
  ArduPlane/defines.h
  ArduPlane/mode_qland.cpp
  ArduPlane/mode_qloiter.cpp
  ArduPlane/mode_qrtl.cpp
  ArduPlane/mode_takeoff.cpp
  ArduPlane/parachute.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/takeoff.cpp
Labels: Plane, VTOL-Plane

#30517 AP_Camera: mavlink commands use target sysid and compid
  libraries/AP_Camera/AP_Camera_MAVLinkCamV2.cpp
Labels: BUG, Enhancement, DevCallEU, Camera

#30521 .github: add test that there are no Merge commits in the branch
  .github/workflows/test_branch_conventions.yml
Labels: WikiNeeded, MergeOnCIPass

#30505 AP_HAL: reserve HAL_BOARD_SUBTYPE_LINUX_POCKET2
  libraries/AP_HAL/AP_HAL_Boards.h
Labels: MergeOnCIPass

#30534 SITL: Since it is a pointer variable, it is compared with nullptr
  libraries/SITL/SIM_GPS_SBP_Common.cpp
Labels: MergeOnCIPass

#30540 AP_Scripting: added docs for plane_ship_landing.lua
  libraries/AP_Scripting/applets/plane_ship_landing.md
Labels: Scripting

#30558 hwdef: SkystarsHD: remove pin defaults which are inherited
  libraries/AP_HAL_ChibiOS/hwdef/SkystarsH7HDv2/hwdef.dat
Labels: MergeOnCIPass

#30559 hwdef: CubeNode-ETH: remove duplicated define
  libraries/AP_HAL_ChibiOS/hwdef/CubeNode-ETH/hwdef.dat
Labels: MergeOnCIPass

#30564 .github: test_branch_conventions.py: test for fixup commits and commits lacking a :
  .github/workflows/test_branch_conventions.yml
Labels: MergeOnCIPass

#30563 Tools: Fix pytest DeprecationWarning: 'maxsplit' is passed as positional
  Tools/scripts/param_check.py
Labels: MergeOnCIPass

#30576 AP_Servo_Telem: correct update of STATUS
  libraries/AP_Servo_Telem/AP_Servo_Telem.cpp
Labels: MergeOnCIPass

#30577 Tools: First argument of a method should be named 'self'
  Tools/Replay/examples/rewrite-RFND-values-to-floats.py
Labels: MergeOnCIPass

#30557 Copter: Convert Sports Mode to radians and finish Acro Mode
  ArduCopter/config.h
  ArduCopter/mode_acro.cpp
  ArduCopter/mode_sport.cpp
Labels: Copter

#30532 Plane: rework `allow_reverse_thrust` to allow reverse thrust in manual modes with `USE_REV_THRUST` 0
  ArduPlane/Parameters.cpp
  ArduPlane/Plane.h
  ArduPlane/defines.h
  ArduPlane/reverse_thrust.cpp
Labels: Plane, WikiNeeded

#30586 Copter: heli: remove unused rotor speed deglitch filter
  ArduCopter/Copter.h
Labels: TradHeli

#30073 Copter: rename radio_tuning to rc_tuning_param
  ArduCopter/Parameters.cpp
  ArduCopter/Parameters.h
  ArduCopter/mode_circle.cpp
  ArduCopter/tuning.cpp
Labels: Copter, DevCallEU

#30518 Plane: quantise the airspeed target from MIN_GROUNDSPEED
  ArduPlane/Plane.h
  ArduPlane/navigation.cpp
Labels: Plane, DevCallEU

#30601 AP_Scripting: changed LTE_BAND and LTE_MCCMNC to no-change by default
  libraries/AP_Scripting/drivers/LTE_modem.lua
Labels: Scripting

#30621 Tools: add AP_PERIPH_BATTERY_BALANCE_ENABLED as a build option
  Tools/scripts/build_options.py
  Tools/scripts/extract_features.py
Labels: MergeOnCIPass

#26462 GCS_MAVLink: ftp receiving messages where size takes into account terminating null
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/GCS_FTP.cpp
Labels: MAVLink, MergeOnCIPass

#30476 Plane: added an option to enable flaps by actual speed
  ArduPlane/Parameters.cpp
  ArduPlane/defines.h
  ArduPlane/servos.cpp
Labels: Plane, DevCallTopic, WikiNeeded

#30458 Plane: make RNGFND_LANDING a bitmask
  ArduPlane/GCS_Plane.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/Plane.h
  ArduPlane/VTOL_Assist.cpp
  ArduPlane/altitude.cpp
  ArduPlane/defines.h
  ArduPlane/mode_autoland.cpp
  ArduPlane/mode_qland.cpp
  ArduPlane/mode_qloiter.cpp
  ArduPlane/mode_qrtl.cpp
  ArduPlane/mode_takeoff.cpp
  ArduPlane/parachute.cpp
  ArduPlane/quadplane.cpp
  ArduPlane/takeoff.cpp
Labels: Plane, VTOL-Plane, DevCallTopic, WikiNeeded

#30624 AP_Scripting: use native implementation of luaO_ceillog2
  libraries/AP_Scripting/lua/src/lobject.c
Labels: Scripting, MergeOnCIPass

#29916 fix enum format
  libraries/AP_HAL_Linux/RCInput_RPI.cpp
Labels: MergeOnCIPass

#30656 AP_BattMonitor: remove param conversion to dynamic tables required for update from 4.1 to 4.2
  libraries/AP_BattMonitor/AP_BattMonitor.cpp
  libraries/AP_BattMonitor/AP_BattMonitor.h
Labels: DevCallEU

#30667 Plane:correct description of FBWB_ELEV_REV parameter
  ArduPlane/Parameters.cpp
Labels: BUG, Docs

#30659 AP_Param: fixed find_by_name()
  libraries/AP_Param/AP_Param.cpp
Labels: MergeOnCIPass

#30686 AP_GPS: make 115K drvr option clear that it is for Ublox only
  libraries/AP_GPS/AP_GPS.cpp
Labels: Docs, Non-Functional Change

#30655 AP_Param: add a gtest for find_by_name
  libraries/AP_Param/tests/test_find_by_name.cpp
  libraries/AP_Param/tests/wscript
Labels: MergeOnCIPass

#30703 autotest: improve `test.Plane.CompassLearnInFlight` robustness
  Tools/autotest/arduplane.py
Labels: MergeOnCIPass

#30708 hwdef: update baro on BlitzH743 pro and wing
  libraries/AP_HAL_ChibiOS/hwdef/BlitzH743Pro/README.md
  libraries/AP_HAL_ChibiOS/hwdef/BlitzH743Pro/hwdef.dat
Labels: BUG, DevCallTopic

#30662 Copter: `WP_NAVALT_MIN` only apply to takeoff
  ArduCopter/Parameters.cpp
  ArduCopter/mode.cpp
Labels: Copter

#30690 hwdef: SIYI_N7: add support for ICM45686 and correct LED setup
  libraries/AP_HAL_ChibiOS/hwdef/SIYI_N7/hwdef.dat
Labels: MergeOnCIPass

#30691 AP_Scripting: add example which prints checksum of @SYS/flash.bin
  libraries/AP_Scripting/examples/checksum_firmware.lua
Labels: DevCallEU

#30717 AP_Mount: fix accels sent to XFRobot camera gimbal
  libraries/AP_Mount/AP_Mount_XFRobot.cpp
Labels: BUG, DevCallEU, Gimbal

#30729 AP_NavEKF3: rename EK3_MAX_FLOW to EK3_FLOW_MAX
  libraries/AP_NavEKF3/AP_NavEKF3.cpp
Labels: EKF, MergeOnCIPass

#30736 ArduSub: Attitude.cpp: limit throttle deadzone before use
  ArduSub/Attitude.cpp
Labels: Sub

#30735 Tools: add AP_PERIPH_RCIN_ENABLED as a build option
  Tools/scripts/build_options.py
  Tools/scripts/extract_features.py
Labels: MergeOnCIPass

#30728 board_types.txt : add board ID for AP_HW_NarinX3.
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#30670 Copter: Brake mode is a autopilot mode as there is no pilot input
  ArduCopter/mode.h
Labels: Copter

#30764 AP_HAL_ChibiOS: replace CubeNode PDF with reference to CubeNode wiki
  libraries/AP_HAL_ChibiOS/hwdef/CubeNode/CubeNode_PinOut.pdf
  libraries/AP_HAL_ChibiOS/hwdef/CubeNode/hwdef.dat
Labels: MergeOnCIPass

#30012 Rover: Better handling of stopped leader in Follow mode
  Rover/mode_follow.cpp
Labels: Rover

#30761 SITL: SIM_Vicon: add usage information
  libraries/SITL/SIM_Vicon.h
Labels: DevCallEU

#29390 Plane: Fix crash detection false positive on "shake to launch"
  ArduPlane/is_flying.cpp
Labels: WikiNeeded, MergeOnCIPass

#29077 Plane: Add climb slope minimum height parameter
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/altitude.cpp
Labels: WikiNeeded, MergeOnCIPass

#30771 Plane: use parameterised trim_throttle in place of constant value of TRIM_THROTTLE
  ArduPlane/Attitude.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/config.h
Labels: MergeOnCIPass
