Repository ArduPilot/ardupilot, pull requests merged in 2025-05, with the labels that each got.

#29831 Tools: ros2: Remove unused imports (and fix format issues)
  Tools/ros2/ardupilot_dds_tests/ardupilot_dds_tests/plane_waypoint_follower.py
  Tools/ros2/ardupilot_dds_tests/ardupilot_dds_tests/pre_arm_check_service.py
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/conftest.py
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_prearm_service.py
Labels: ROS, Non-Functional Change

#29522 AP_DDS: airspeed message to include eas_2_tas factor
  Tools/ros2/ardupilot_msgs/CMakeLists.txt
  Tools/ros2/ardupilot_msgs/msg/Airspeed.msg
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/Idl/ardupilot_msgs/msg/Airspeed.idl
  libraries/AP_DDS/README.md
Labels: Enhancement, ROS

#28967 ArduPlane: Clarify behavior with small WP_LOITER_RAD
  ArduPlane/Parameters.cpp
Labels: Docs, Non-Functional Change

#29947 Tools: reserve Board IDs for ViaDrone
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#29946 AP_DroneCAN: ESC bitmask description clarification
  libraries/AP_DroneCAN/AP_DroneCAN.cpp
Labels: MergeOnCIPass

#29941 AC_Autorotation: correct logging of reason into AROT
  libraries/AC_Autorotation/AC_Autorotation.cpp
Labels: MergeOnCIPass

#29936 autotest: param_metadata: fix warnings about regex strings
  Tools/autotest/param_metadata/mdemit.py
Labels: MergeOnCIPass

#29929 GCS_MAVLink: add comment to ensure 16-bit maths is preserved
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#29926 Plane: fix Q_OPTION bit 18 docstring
  ArduPlane/quadplane.cpp
Labels: MergeOnCIPass

#29905 AP_GPS: DroneCAN: only trust ellipsoid height if different from MSL
  libraries/AP_GPS/AP_GPS_DroneCAN.cpp
  libraries/AP_GPS/AP_GPS_DroneCAN.h
Labels: MergeOnCIPass

#28885 AP_HAL_ESP32: add AP_MOTORS_FRAME_xxx_ENABLED guards
  libraries/AP_HAL_ESP32/boards/esp32empty.h
  libraries/AP_HAL_ESP32/boards/esp32s3empty.h
Labels: SITL, MergeOnCIPass, esp32

#28076 Rover: reject position targets if acceleration supplied
  Rover/GCS_MAVLink_Rover.cpp
  Rover/GCS_MAVLink_Rover.h
Labels: Rover, MergeOnCIPass

#28907 AP_DDS: RC channels message
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_rc_msg_received.py
  Tools/ros2/ardupilot_msgs/CMakeLists.txt
  Tools/ros2/ardupilot_msgs/msg/Rc.msg
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_Client.h
  libraries/AP_DDS/AP_DDS_Topic_Table.h
  libraries/AP_DDS/AP_DDS_config.h
  libraries/AP_DDS/Idl/ardupilot_msgs/msg/Rc.idl
  libraries/AP_DDS/README.md
Labels: Enhancement, ROS, MergeOnCIPass

#29931 AP_RCTelemetry, CRSF ground speed incorrect by some 20%
  libraries/AP_RCTelemetry/AP_CRSF_Telem.cpp
Labels: DevCallTopic, MergeOnCIPass

#29877 AP_TECS: stop setting badDescent during transition
  libraries/AP_TECS/AP_TECS.cpp
Labels: Plane, NeedsTesting

#29956 AP_Logger: correct extraction of DMS message metadata
  libraries/AP_Logger/AP_Logger_MAVLink.cpp
  libraries/AP_Logger/LogStructure.h
Labels: MergeOnCIPass

#29978 Sub:remove SITL dependancies
  ArduSub/AP_Arming_Sub.cpp
  ArduSub/Sub.cpp
  ArduSub/failsafe.cpp
  ArduSub/radio.cpp
Labels: Sub, DevCallTopic

#29955 waf: allow --embed-XXX on configure
  Tools/ardupilotwaf/boards.py
  wscript
Labels: Scripting, WikiNeeded

#29977 AP_CANManager: create a new class for MAVLink CAN
  libraries/AP_CANManager/AP_CANManager.cpp
  libraries/AP_CANManager/AP_CANManager.h
  libraries/AP_CANManager/AP_MAVLinkCAN.cpp
  libraries/AP_CANManager/AP_MAVLinkCAN.h
Labels: CAN

#29992 Tools: correct size_compare_branches elf_diff
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#29987 AP_Mount: Siyi ZT6 min cam version is 0.1.9
  libraries/AP_Mount/AP_Mount_Siyi.cpp
Labels: Enhancement, Driver, MergeOnCIPass, Gimbal

#29993 Tools: Update locations.txt
  Tools/autotest/locations.txt
Labels: MergeOnCIPass

#29933 AP_TECS: avoid use of cosphi_squared dcm matrix trick
  libraries/AP_TECS/AP_TECS.cpp
Labels: DevCallEU

#30002 Tools: Add airspeed test and SITL plane fixtures
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/conftest.py
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_plane_airspeed.py
Labels: ROS, CI

#29999 hwdef: remove unused lines from JFB110 hwdef
  libraries/AP_HAL_ChibiOS/hwdef/JFB110/hwdef.dat
Labels: MergeOnCIPass

#30004 AP_HAL_ChibiOS: wrap `define AP_XX_ENABLED AP_PERIPH_YY_ENABLED` inside ifndef-endif
  libraries/AP_HAL_ChibiOS/hwdef/scripts/defaults_periph.h
Labels: MergeOnCIPass

#30020 Plane:remove unused declaration
  ArduPlane/Plane.h
Labels: Plane

#30014 RC_Channel:add Lowheiser metadata to aux functions
  libraries/RC_Channel/RC_Channel.cpp
Labels: DevCallTopic

#29818 AP_HAL_ChibiOS:add vimdrones ap_periph pico and servo hub 4chp
  Tools/bootloaders/VM-L431-Periph-Pico_bl.bin
  Tools/bootloaders/VM-L431-Periph-Pico_bl.hex
  Tools/bootloaders/VM-L431-SRV-Hub-4CHP_bl.bin
  Tools/bootloaders/VM-L431-SRV-Hub-4CHP_bl.hex
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431-Periph-Pico/README.md
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431-Periph-Pico/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431-Periph-Pico/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431-Periph-Pico/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431-Periph-Pico/vimdrones_ap_periph_pico_wiring.png
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431-SRV-Hub-4CHP/README.md
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431-SRV-Hub-4CHP/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431-SRV-Hub-4CHP/hwdef-bl.dat
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431-SRV-Hub-4CHP/hwdef.dat
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431-SRV-Hub-4CHP/vimdrones_can_servo_hub_4chp_wiring.png
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431/hwdef-bl.inc
  libraries/AP_HAL_ChibiOS/hwdef/VM-L431/hwdef.inc
Labels: WikiNeeded, NewBoardSupport

#29979 Sub:add aux func disarm/estop to pre-arm check for disarm function
  ArduSub/AP_Arming_Sub.cpp
Labels: Sub

#30035 autotest: add ratchet for log message documentation
  Tools/autotest/vehicle_test_suite.py
Labels: DevCallTopic

#30006 AP_Mount: Adjust the version setting to match ZT6
  libraries/AP_Mount/AP_Mount_Siyi.cpp
Labels: MergeOnCIPass

#30008 RC_Channel:add sub to additional aux sw metadata
  libraries/RC_Channel/RC_Channel.cpp
Labels: Sub, DevCallTopic

#30003 Tools: ros2: Reduce test code duplication with fixture reuse
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/launch_fixtures.py
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_battery_msg_received.py
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_geopose_msg_received.py
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_joy_msg_received.py
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_navsat_msg_received.py
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_prearm_service.py
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_rc_msg_received.py
  Tools/ros2/ardupilot_dds_tests/test/ardupilot_dds_tests/test_time_msg_received.py
Labels: ROS, DevCallTopic, CI, Non-Functional Change

#30041 AP_Landing: fixed assumption of AMSL WPs
  libraries/AP_Landing/AP_Landing.cpp
  libraries/AP_Landing/AP_Landing.h
  libraries/AP_Landing/AP_Landing_Slope.cpp
Labels: BUG, Plane, DevCallTopic

#29886 AP_Scripting: plane_ship_landing.lua: add pos/vel sanity check
  libraries/AP_Scripting/applets/plane_ship_landing.lua
Labels: NeedsTesting

#30010 AP_Generator: remove Python3 suppor from test-loweheiser.py
  libraries/AP_Generator/scripts/test-loweheiser.py
Labels: MergeOnCIPass

#29653 AP_Terrain: Protect against division by 0 when TERRAIN_SPACING is less then 1
  libraries/AP_Terrain/AP_Terrain.cpp
Labels: MergeOnCIPass

#30045 Plane: backport of terrain landing fix
  libraries/AP_Landing/AP_Landing.cpp
  libraries/AP_Landing/AP_Landing.h
  libraries/AP_Landing/AP_Landing_Slope.cpp
Labels: BUG, Plane

#30071 Copter: avoid updating simple-mode values when RC input is invalid
  ArduCopter/Copter.cpp
Labels: BUG, Copter

#30067 AP_BattMonitor: add null check to mppt power state
  libraries/AP_BattMonitor/AP_BattMonitor.cpp
Labels: BUG, MergeOnCIPass

#30070 Copter: Trust get-pilot-desired methods check RC input for validity
  ArduCopter/mode_loiter.cpp
  ArduCopter/mode_zigzag.cpp
Labels: Copter, NeedsTesting

#28341 AP_DDS: Make GPS DDS features depend on GPS
  libraries/AP_DDS/AP_DDS_Client.cpp
  libraries/AP_DDS/AP_DDS_config.h
Labels: MergeOnCIPass

#30077 AP_HAL_SITL: remove redundant sitl nullptr checks
  libraries/AP_HAL_SITL/SITL_State.cpp
Labels: MergeOnCIPass

#30081 AP_Scripting: correct use of pcall in examples and applets
  libraries/AP_Scripting/applets/VTOL-quicktune.lua
  libraries/AP_Scripting/applets/revert_param.lua
  libraries/AP_Scripting/applets/rover-quicktune.lua
  libraries/AP_Scripting/examples/gen_control.lua
Labels: DevCallTopic

#30085 AP_HAL_ChibiOS: correctly verify flash on H7
  libraries/AP_HAL_ChibiOS/hwdef/common/flash.c
Labels: MergeOnCIPass

#30106 AP_TECS: Fix spelling
  libraries/AP_TECS/AP_TECS.cpp
Labels: MergeOnCIPass

#30062 AP_ExternalAHRS: include only on boards with more than 2MB of flash
  libraries/AP_ExternalAHRS/AP_ExternalAHRS_config.h
Labels: WikiNeeded

#30089 Add terrain comparison to rangefinder Jupyter notebook
  Tools/terrain-tools/.gitignore
  Tools/terrain-tools/README.md
  Tools/terrain-tools/terrain_rangefinder_postprocess.ipynb
Labels: Non-Functional Change

#30116 AP_Scripting: param-set.lua: trim out unused MAV_SYSID parameter reference
  libraries/AP_Scripting/applets/param-set.lua
Labels: MergeOnCIPass

#30124 GCS_MAVLink: set message interval fail msg only sent on SITL
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#30039 Blimp: remove pointless set of CH_6 RC deadzone
  Blimp/radio.cpp
Labels: Blimp

#30111 GCS_MAVLink: check airspeed is enabled before trying to calibrate
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#30138 hwdef:adjust current scaler on NAVI-Deluxe
  libraries/AP_HAL_ChibiOS/hwdef/ATOMRCF405NAVI-Deluxe/hwdef.dat
Labels: MergeOnCIPass, hwdef

#30021 (BUG Fix) AP_VideoTX: fix VTX hang when setting LowRace band (Analog 5.8 GHz)
  libraries/AP_VideoTX/AP_VideoTX.cpp
Labels: BUG

#30146 AP_TECS: Convert option to enum class
  libraries/AP_TECS/AP_TECS.cpp
  libraries/AP_TECS/AP_TECS.h
Labels: Plane, Non-Functional Change

#30149 Refactor AC_PID comments and internal naming for clarity and consistency
  libraries/AC_PID/AC_P.cpp
  libraries/AC_PID/AC_P.h
  libraries/AC_PID/AC_PID.cpp
  libraries/AC_PID/AC_PID.h
  libraries/AC_PID/AC_PID_2D.cpp
  libraries/AC_PID/AC_PID_2D.h
  libraries/AC_PID/AC_PID_Basic.cpp
  libraries/AC_PID/AC_PID_Basic.h
  libraries/AC_PID/AC_PI_2D.cpp
  libraries/AC_PID/AC_PI_2D.h
  libraries/AC_PID/AC_P_1D.cpp
  libraries/AC_PID/AC_P_1D.h
  libraries/AC_PID/AC_P_2D.cpp
  libraries/AC_PID/AC_P_2D.h
Labels: AllVehicles, DevCallTopic

#30054 AP_Scripting: Add wind decoder for Trisonica LI-550
  libraries/AP_Scripting/examples/trisonica-mini.lua
  libraries/AP_Scripting/examples/trisonicia-mini.md
Labels: Driver, Scripting, WikiNeeded

#30178 autotest: Flake8 clean all logger metadata scripts
  Tools/autotest/logger_metadata/emit_html.py
  Tools/autotest/logger_metadata/emit_md.py
  Tools/autotest/logger_metadata/emit_rst.py
  Tools/autotest/logger_metadata/emit_xml.py
  Tools/autotest/logger_metadata/emitter.py
Labels: MergeOnCIPass

#30179 autotest: Create README file about the logmessage parser
  Tools/autotest/logger_metadata/README.md
  Tools/autotest/logger_metadata/enum_parse.py
Labels: WikiNeeded, MergeOnCIPass

#30128 AP_Arming:expand metadata on ARMING_REQUIRE
  libraries/AP_Arming/AP_Arming.cpp
Labels: Docs, Non-Functional Change

#29112 Copter: fix threading issues with motor test and the fast rate thread
  ArduCopter/motor_test.cpp
  ArduCopter/rate_thread.cpp
Labels: BUG, DevCallEU

#29546 New MAVx_OPTIONS parameter to enable channel-specific signing
  libraries/GCS_MAVLink/GCS.h
  libraries/GCS_MAVLink/GCS_MAVLink_Parameters.cpp
  libraries/GCS_MAVLink/GCS_Signing.cpp
Labels: NeedsTesting, DevCallEU

#30188 AR_Motors: added MOT_REV_DELAY
  libraries/AR_Motors/AP_MotorsUGV.cpp
  libraries/AR_Motors/AP_MotorsUGV.h
Labels: Rover, WikiNeeded

#30200 Tools: build_options.py: correct feature name for externalahrs-baro s…
  Tools/scripts/build_options.py
Labels: MergeOnCIPass
