Repository ArduPilot/ardupilot, pull requests merged in 2025-09, with the labels that each got.

#31028 Tools/environment_install: drop pymavlink from cygwin
  Tools/environment_install/install-prereqs-windows-andAPMSource.ps1
  Tools/environment_install/install-prereqs-windows.ps1
Labels: MergeOnCIPass

#31037 GCS_MAVLink: fix MAVn_OPTIONS doc
  libraries/GCS_MAVLink/GCS_MAVLink_Parameters.cpp
Labels: MergeOnCIPass

#31034 autotest: relax TetherStuck test constraints
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#30669 Tools: improve venv install and add wxpython wheel for ubuntu
  Tools/environment_install/install-prereqs-ubuntu.sh
Labels: MergeOnCIPass

#31123 AP_DAL: add comment as to what the DAL is
  libraries/AP_DAL/AP_DAL.h
Labels: MergeOnCIPass

#30823 Sub: DON'T interpret zero altitude waypoints as 'current altitude'
  ArduSub/commands_logic.cpp
  Tools/autotest/ArduSub_Tests/TerrainMission/terrain_mission.txt
Labels: WikiNeeded, MergeOnCIPass

#30737 AP_Proximity: Add support for RPLidar A2M12
  libraries/AP_Proximity/AP_Proximity_RPLidarA2.cpp
  libraries/AP_Proximity/AP_Proximity_RPLidarA2.h
Labels: Driver, WikiNeeded, MergeOnCIPass

#29961 AP_AdvancedFailsafe: option to not go back to the loss comm mission item if we are already in the return path
  libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.cpp
  libraries/AP_AdvancedFailsafe/AP_AdvancedFailsafe.h
Labels: WikiNeeded, MergeOnCIPass

#31160 AP_HAL_ChibiOS: enable analog VTX on Spedix H743
  libraries/AP_HAL_ChibiOS/hwdef/SPEDIXH743/defaults.parm
  libraries/AP_HAL_ChibiOS/hwdef/SPEDIXH743/hwdef.dat
Labels: BUG, MergeOnCIPass

#30915 Fix typo in MavLink command used in message
  ArduPlane/GCS_MAVLink_Plane.cpp
Labels: MergeOnCIPass

#31179 AP_Compass: add a MSP probe method which can fail
  libraries/AP_Compass/AP_Compass.cpp
  libraries/AP_Compass/AP_Compass_MSP.cpp
  libraries/AP_Compass/AP_Compass_MSP.h
Labels: NeedsTesting

#31209 AC_AttitudeControl: Removed old reference to PSC_ACC_XY_FILT
  libraries/AC_AttitudeControl/AC_PosControl.cpp
Labels: MergeOnCIPass
