Repository ArduPilot/ardupilot, pull requests merged in 2025-02, with the labels that each got.

#29201 AP_Filesystem: ROMFS: fix open race conditions
  libraries/AP_Filesystem/AP_Filesystem_ROMFS.cpp
  libraries/AP_Filesystem/AP_Filesystem_ROMFS.h
Labels: BUG, MergeOnCIPass

#29175 SITL: fix array-bounds warning in tsys01 simulation
  libraries/SITL/SIM_Temperature_TSYS01.cpp
  libraries/SITL/SIM_Temperature_TSYS01.h
Labels: MergeOnCIPass

#29194 Copter: SystemID: Fix unutilized variables
  ArduCopter/mode_systemid.cpp
Labels: BUG, Copter

#29195 AP_AIS: fix multi part message decoding
  libraries/AP_AIS/AP_AIS.cpp
Labels: DevCallTopic

#29211 add SULILGH7-P1-P2 Board ID
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#29143 gitignore: ignore .python-version file used by pyenv
  .gitignore
Labels: DevEnv

#29152 Plane:adjust CTUN.Pitch to remove PITCH_TRIM
  ArduPlane/Log.cpp
Labels: WikiNeeded

#29162 Clarification for timestamp in JSON interface
  libraries/SITL/examples/JSON/readme.md
Labels: SITL, Docs, MergeOnCIPass

#29180 .github: exclude QURT changes when running various workflows
  .github/workflows/cygwin_build.yml
  .github/workflows/qurt_build.yml
  .github/workflows/test_replay.yml
  .github/workflows/test_sitl_blimp.yml
  .github/workflows/test_sitl_copter.yml
  .github/workflows/test_sitl_periph.yml
  .github/workflows/test_sitl_plane.yml
  .github/workflows/test_sitl_rover.yml
  .github/workflows/test_sitl_sub.yml
  .github/workflows/test_sitl_tracker.yml
  .github/workflows/test_unit_tests.yml
Labels: DevCallEU

#29224 waf: stop clang complaining about variable-length stack arrays
  Tools/ardupilotwaf/boards.py
Labels: DevCallEU

#29028 AP_ESC_Telem: fix other timeout race
  libraries/AP_ESC_Telem/AP_ESC_Telem.cpp
  libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.cpp
  libraries/AP_ESC_Telem/AP_ESC_Telem_Backend.h
Labels: DevCallEU

#29229 waf: correct clang++ extension name
  Tools/ardupilotwaf/boards.py
Labels: MergeOnCIPass

#29164 Tools: uploader.py: verify correct install
  Tools/scripts/uploader.py
Labels: MergeOnCIPass

#29192 Scripting: Update Rockblock and MAVLinkHL scripts
  libraries/AP_Scripting/applets/RockBlock.lua
  libraries/AP_Scripting/applets/RockBlock.md
  libraries/AP_Scripting/examples/MAVLinkHL.lua
Labels: Scripting

#29228 AP_Mount: fix object tracking command for ViewPro
  libraries/AP_Mount/AP_Mount_Viewpro.cpp
  libraries/AP_Mount/AP_Mount_Viewpro.h
Labels: BUG

#29248 AP_Baro: Fix BMP581 initialization error
  libraries/AP_Baro/AP_Baro_BMP581.cpp
Labels: MergeOnCIPass

#29249 Tools: explicitly set AP_PERIPH_XX_ENABLED defines to 0 for sitl_periph_gps and sitl_periph_battmon
  Tools/ardupilotwaf/boards.py
Labels: MergeOnCIPass

#29246 AP_Scripting: Docs: correct argument order on `mavlink:init`
  libraries/AP_Scripting/docs/docs.lua
Labels: Scripting

#29254 AP_Scripting: update so mavlink init intent matches behavior
  libraries/AP_Scripting/applets/Aerobatics/FixedWing/plane_aerobatics.lua
  libraries/AP_Scripting/applets/copter-slung-payload.lua
  libraries/AP_Scripting/applets/follow-target-send.lua
  libraries/AP_Scripting/applets/mount-poi.lua
  libraries/AP_Scripting/examples/BQ40Z_bms_shutdown.lua
  libraries/AP_Scripting/examples/MAVLink_Commands.lua
  libraries/AP_Scripting/modules/mavport.lua
  libraries/AP_Scripting/tests/mavlink_test.lua
Labels: Scripting

#29253 AP_Logger: clarify behavior of log_file_content
  libraries/AP_Logger/AP_Logger.h
Labels: Non-Functional Change

#29261 ArduPlane:add missing flight mode metadata
  ArduPlane/Parameters.cpp
Labels: MergeOnCIPass

#29245 Plane: Quadplane: only log `TILT` on tilt-rotors
  ArduPlane/tiltrotor.cpp
Labels: VTOL-Plane

#29257 AP_Scripting: mavlink: fix potential deadlock and clean up
  libraries/AP_Scripting/lua_bindings.cpp
Labels: DevCallTopic, Scripting

#29080 Plane: Add fwd. throttle cutoff voltage parameter
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/servos.cpp
Labels: WikiNeeded

#29187 AR_Motors: fix brushed motor support for omni vehicles
  libraries/AR_Motors/AP_MotorsUGV.cpp
Labels: Rover

#29268 TECS:correct metadata
  libraries/AP_TECS/AP_TECS.cpp
Labels: Docs, Non-Functional Change

#29222 AP_Airspeed: disable airspeed auto calibration in specific cases
  libraries/AP_Airspeed/Airspeed_Calibration.cpp
Labels: MergeOnCIPass

#29276 ArduPlane:add AUTOLAND metadata to FS_LONG_ATCN
  ArduPlane/Parameters.cpp
Labels: Non-Functional Change

#29275 Filter: SlewCalculator2D typo fix
  libraries/Filter/SlewCalculator2D.cpp
Labels: BUG, Copter, Rover, DevCallEU, Blimp

#29286 AP_BLHeli: fixed documentation for SERVO_BLH_3DMASK and SERVO_BLH_RVMASK
  libraries/AP_BLHeli/AP_BLHeli.cpp
Labels: WikiNeeded

#29288 AP_Bootloader: SpeedyBee board ids
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#29270 [backport 4.6] AP_Filesystem: ROMFS: fix open race conditions
  libraries/AP_Filesystem/AP_Filesystem_ROMFS.cpp
  libraries/AP_Filesystem/AP_Filesystem_ROMFS.h
Labels: Scripting

#29271 [backport 4.6] AP_Scripting: mavlink: fix potential deadlock and clean up
  libraries/AP_Scripting/lua_bindings.cpp
Labels: Scripting

#29309 AP_Mount: CADDX RC rate control fix
  libraries/AP_Mount/AP_Mount_CADDX.cpp
Labels: BUG, Driver, DevCallTopic, MergeOnCIPass

#29302 RC_Channel: add docs for copter inflight ahrs trim
  libraries/RC_Channel/RC_Channel.cpp
Labels: DevCallTopic, Non-Functional Change

#29301 RC_Channel: Document EKF lane switch and yaw reset aux functions.
  libraries/RC_Channel/RC_Channel.cpp
Labels: WikiNeeded, MergeOnCIPass, Non-Functional Change

#29322 Tools: Add Jervis_Bay to locations
  Tools/autotest/locations.txt
Labels: MergeOnCIPass

#28620 Copter: save a few bytes in variance check
  ArduCopter/AP_Arming_Copter.cpp
Labels: DevCallEU

#29339 GCS_Common: fix missing #if for CAMERA_FOV_STATUS
  libraries/GCS_MAVLink/GCS_Common.cpp
Labels: MergeOnCIPass

#29360 autotest: add a test for brake/land failsafe
  Tools/autotest/arducopter.py
Labels: MergeOnCIPass

#29362 AP_Airspeed: inline get_pressure
  libraries/AP_Airspeed/AP_Airspeed.cpp
  libraries/AP_Airspeed/AP_Airspeed.h
Labels: DevCallTopic

#29364 AP_NavEKF3: remove unused assignments of posCheckPassed
  libraries/AP_NavEKF3/AP_NavEKF3_PosVelFusion.cpp
Labels: MergeOnCIPass

#29380 Tools: size_compare_branches.py: improve process failure output file …
  Tools/scripts/size_compare_branches.py
Labels: MergeOnCIPass

#29374 AP_GPS: UBLOX: fix memory leak when "F9" GNSS configuration is used
  libraries/AP_GPS/AP_GPS_UBLOX.cpp
Labels: NeedsTesting, DevCallEU

#29365 AP_HAL: Socket: check return value of getsockname
  libraries/AP_HAL/utility/Socket.cpp
Labels: NeedsTesting, DevCallEU

#29382 Tools: generate_manifest.py: make flake8 clean
  Tools/scripts/generate_manifest.py
Labels: MergeOnCIPass

#29375 AP_Proximity: LD19/LD06 data length sanity check fix
  libraries/AP_Proximity/AP_Proximity_LD06.cpp
Labels: MergeOnCIPass

#29314 AP_Scripting: Better mavlink parsing for MAVLinkHL and Rockblock
  libraries/AP_Scripting/applets/RockBlock.lua
  libraries/AP_Scripting/applets/RockBlock.md
  libraries/AP_Scripting/examples/MAVLinkHL.lua
Labels: Scripting

#29372 AP_GPS: correct GNSS_MODE parameter description
  libraries/AP_GPS/AP_GPS_Params.cpp
Labels: MergeOnCIPass

#29401 AP_Bootloader: reserve board id for X-MAV-AP-F405Mini
  Tools/AP_Bootloader/board_types.txt
Labels: MergeOnCIPass

#28906 Plane: log whether throttle is suppressed or not
  ArduPlane/Log.cpp
Labels: DevCallTopic

#29398 AP_AccelCal:Remove an unusable return
  libraries/AP_AccelCal/AP_AccelCal.cpp
Labels: MergeOnCIPass
