Repository ArduPilot/ardupilot, pull requests merged in 2025-08, with the labels that each got.

#30791 AP_Camera_Servo: report back zoom and focus levels
  libraries/AP_Camera/AP_Camera_Servo.cpp
  libraries/AP_Camera/AP_Camera_Servo.h
Labels: MergeOnCIPass

#30807 AP_Param: ensure flags is filled in for find()
  libraries/AP_Param/AP_Param.cpp
Labels: BUG

#30793 Convert Copter to meters (0-Static): No Compiler name, axis and units
  ArduCopter/mode_guided.cpp
Labels: Copter, MergeOnCIPass

#30828 AP_Networking: cache port type in init
  libraries/AP_Networking/AP_Networking.h
  libraries/AP_Networking/AP_Networking_port.cpp
Labels: BUG, Networking

#30815 AP_Scripting: added MOT slew rates to revert_params.lua
  libraries/AP_Scripting/applets/revert_param.lua
Labels: Scripting

#30810 AP_Mount: retract servo(s) operation for all backends
  libraries/AP_Mount/AP_Mount_Alexmos.cpp
  libraries/AP_Mount/AP_Mount_Backend.cpp
  libraries/AP_Mount/AP_Mount_Backend.h
  libraries/AP_Mount/AP_Mount_CADDX.cpp
  libraries/AP_Mount/AP_Mount_Gremsy.cpp
  libraries/AP_Mount/AP_Mount_SToRM32.cpp
  libraries/AP_Mount/AP_Mount_SToRM32_serial.cpp
  libraries/AP_Mount/AP_Mount_Scripting.cpp
  libraries/AP_Mount/AP_Mount_Servo.cpp
  libraries/AP_Mount/AP_Mount_Servo.h
  libraries/AP_Mount/AP_Mount_Siyi.cpp
  libraries/AP_Mount/AP_Mount_SoloGimbal.cpp
  libraries/AP_Mount/AP_Mount_Topotek.cpp
  libraries/AP_Mount/AP_Mount_Viewpro.cpp
Labels: Enhancement, MergeOnCIPass, Gimbal

#30836 AP_Arming: added option to disable IMU check with ICE running
  libraries/AP_Arming/AP_Arming.cpp
  libraries/AP_Arming/AP_Arming.h
Labels: Plane

#30858 GCS_MAVLink: avoid stringop warning
  libraries/GCS_MAVLink/GCS_MAVLink.h
Labels: MergeOnCIPass

#30869 autotest: added ANUSC location
  Tools/autotest/locations.txt
Labels: MergeOnCIPass

#30853 SITL: fix import in libAP_JSON
  libraries/SITL/examples/JSON/C++/libAP_JSON.h
Labels: MergeOnCIPass

#30350 Plane: fix short failsafe
  ArduPlane/AP_Arming_Plane.cpp
  ArduPlane/Parameters.cpp
  ArduPlane/Parameters.h
  ArduPlane/Plane.cpp
  ArduPlane/Plane.h
  ArduPlane/events.cpp
  ArduPlane/radio.cpp
  ArduPlane/system.cpp
Labels: BUG, DevCallTopic, WikiNeeded

#30844 AP_HAL_SITL: Blimp: stop initialising pwm_output to 1000
  libraries/AP_HAL_SITL/SITL_State.cpp
Labels: MergeOnCIPass, Blimp

#30888 AP_AHRS: remove duplicate dependency
  libraries/AP_AHRS/AP_AHRS.h
Labels: MergeOnCIPass

#30898 AP_Param: fixed data race in param creation
  libraries/AP_Param/AP_Param.cpp
Labels: Scripting, MergeOnCIPass

#30892 autotest: do not move failed-test logs if not running on autotest server
  Tools/autotest/autotest.py
  Tools/autotest/vehicle_test_suite.py
Labels: MergeOnCIPass

#30936 autotest: make error on quadplane ship landing larger
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#30882 autotest: tweak qassist test servo output to more closely match scenario
  Tools/autotest/quadplane.py
Labels: MergeOnCIPass

#30904 AP_MotorsHeli: Add clarifying comments to yaw trim parameter metadata.
  libraries/AP_Motors/AP_MotorsHeli_Single.cpp
Labels: TradHeli, WikiNeeded

#30926 Plane: added BBX messages for blackbox logging
  ArduPlane/Log.cpp
  ArduPlane/Plane.cpp
  ArduPlane/Plane.h
Labels: Plane, DevCallEU

#30945 AP_Networking: increase stack for network ports
  libraries/AP_Networking/AP_Networking_port.cpp
Labels: BUG, MergeOnCIPass, Networking

#30946 AP_GPS: do not zero blended weights if no-fix from a GPS
  libraries/AP_GPS/AP_GPS_Blended.cpp
Labels: MergeOnCIPass

#30938 autotest: allow running multiple tests in one runner
  Tools/autotest/autotest.py
Labels: MergeOnCIPass

#30952 AP_Motors: add governor engage condition to rotor runup complete check
  libraries/AP_Motors/AP_MotorsHeli_RSC.cpp
Labels: TradHeli

#30867 AP_Scripting: added LTE BG95 and EG800Q support
  libraries/AP_Scripting/drivers/LTE_modem.lua
Labels: Scripting
